AVR LGPL Assembler and Disassembler + tests
rizinorg/rizin pull request #1028
Opened 2021-04-15 09:23 UTC by wargio

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Removes the GPL code to replace it with a rewritten version of it with LGPL license

...

**Test plan**

Tests have been included into the PR

...

**Closing issues**

Resolves one of the points regarding the GPL issue

...

2021-04-15 09:56 UTC, XVilka requested changes

2021-04-15 09:56 UTC, XVilka commented on librz/asm/arch/avr/assembler.c
> +#include "assembler.h"
Missing SPDX

2021-04-15 09:56 UTC, XVilka commented on librz/asm/arch/avr/disassembler.c
> +#include "disassembler.h"
Missing SPDX

2021-04-15 12:31 UTC, thestr4ng3r approved these changes

2021-04-15 17:55 UTC, XVilka approved these changes

2021-04-16 02:01 UTC, merged

2021-04-16 04:09 UTC, XVilka commented
@wargio there is one broken test on Travis ARMv8 build:
```
[XX] db/asm/avr <asm> invalid
-- disassembly
@@ -1 +1,2 @@
+WARNING: avr_disassembler: assertion 'buffer && size > 1 && sb' failed (line 593)
 invalid
\ No newline at end of file
```

If you will use branch named started from `import-` it will run Travis. Probably we should enable it for all PRs.