WIP: Refactoring Hash
rizinorg/rizin pull request #1082
Opened 2021-04-27 15:02 UTC by wargio

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This PR tries to fix so many issues with message digest.

**TODO - ADD ALL DETAILS HERE**

This PR has removed the following algorithms:

- hamming distance
- luhn
- pcprint
- deviation

2021-04-29 04:37 UTC, XVilka requested changes
Is it possible to restore Luhn algorithm? It's very basic but somewhat common for simple number checking. It's not exactly the hash, more like a correctness check, but we have various CRCs here too.

2021-04-29 04:37 UTC, XVilka commented on test/unit/legacy_unit/hash/hello.c
>  #include <stdio.h>
Could  you please convert these two into the new unit tests and move into the `test/unit` instead? See https://github.com/rizinorg/rizin/issues/923

2021-05-01 14:02 UTC, wargio commented
i have decided to write the unit tests directly instead of porting the legacy one. but i have updated them to be sure that they do work and compile

2021-05-02 03:06 UTC, XVilka approved these changes

2021-05-02 09:55 UTC, thestr4ng3r approved these changes

2021-05-02 12:47 UTC, merged