RzJson: support simple JSON paths
rizinorg/rizin pull request #1115
Opened 2021-05-08 21:03 UTC by 0xfd000000

add rz_json_get_path, which allows querying by paths like
'[0].sub.children[0].thing'

 

**Your checklist for this pull request**
- [*] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [*] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [*] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2021-05-08 21:08 UTC, 0xfd000000 commented on librz/util/json_parser.c
> +	// unreachable code
Would `rz_warn_if_reached` be the proper thing to use here?

2021-05-08 21:34 UTC, 0xfd000000 commented on librz/util/json_parser.c
> +	// unreachable code
Nevermind, I changed the control flow to be more obvious, removing this dead code completely

2021-05-08 21:57 UTC, wargio commented
what if we want to iterate all arrays ?

2021-05-08 22:27 UTC, 0xfd000000 commented
> what if we want to iterate all arrays ?

do you mean wildcard indices like `things[*].whatever`?

as a first shot, I did the simple thing but this could be done, too.

What would you imagine the API to be like?

For more than one wildcard like `things[*].children[*].whatever` it could be done recursively (with a callback?) or we'd have to allocate&keep state and require the user to clean up afterwards.

Is there any precedence for a similar API in the codebase?

2021-05-09 02:03 UTC, XVilka commented
The original issue and use case didn't require wildcards, so it's fine as is, I think.

2021-05-09 09:46 UTC, wargio commented
agree

2021-05-09 11:41 UTC, XVilka approved these changes

2021-05-10 00:48 UTC, wargio requested changes
LGTM

2021-05-10 00:48 UTC, wargio commented on librz/util/json_parser.c
> +				if (strchr(".[", key[keysize]))
parenthesis

2021-05-10 04:04 UTC, 0xfd000000 commented on librz/util/json_parser.c
> +				if (strchr(".[", key[keysize]))
done

2021-05-10 04:27 UTC, XVilka approved these changes

2021-05-10 05:20 UTC, merged