Remove freenode mentions in remaining files
rizinorg/rizin pull request #1218
Opened 2021-06-16 20:57 UTC by rbrishabh

Fixes #1217

Hi @xarkes! How does this look?
let me know if this needs any changes!
Thanks! (PS: Sorry for copy-pasting the same message on all PRs -- I'm not the most innovative today!)

2021-06-16 22:56 UTC, wargio approved these changes

2021-06-17 03:44 UTC, XVilka requested changes

2021-06-17 03:44 UTC, XVilka commented on README.md
> +- IRC: web.libera.chat
It's not. The right link for the IRC would be `irc.libera.chat`

2021-06-17 03:44 UTC, XVilka commented on README.md
> +- IRC: web.libera.chat
It has nothing to do with Web.

2021-06-17 10:22 UTC, wargio commented on README.md
> +- IRC: web.libera.chat
```suggestion
- IRC: [irc.libera.chat:6697 (TLS)](ircs://irc.libera.chat:6697)
```

2021-06-17 10:24 UTC, wargio commented on README.md
> +- IRC: [irc.libera.chat:6697 (TLS)](ircs://irc.libera.chat:6697)
```suggestion
- IRC: [irc.libera.chat:6697 with TLS support](ircs://irc.libera.chat:6697)
```

2021-06-17 10:25 UTC, merged