Some small variation to the stale bot configuration file
rizinorg/rizin pull request #1233
Opened 2021-06-21 09:18 UTC by ret2libc

I have installed probot stale on Rizin repository. The configuration file was already there, I just did some small variation. Please check if you think they are ok.

2021-06-21 09:20 UTC, wargio approved these changes
💗

2021-06-21 10:43 UTC, ITAYC0HEN approved these changes
Alright, looks good!

2021-06-22 03:55 UTC, XVilka requested changes

2021-06-22 03:55 UTC, XVilka commented on .github/stale.yml
> +daysUntilClose: 21
Why 21? I think marking until "stale" is fine, but lets give more time for someone when they got a notification from bot. I think 60 was a reasonable amount for a complex project such as Rizin is.

2021-06-22 03:55 UTC, XVilka commented on .github/stale.yml
> -  - New Architecture
I suggest to excempt also these:
- `high-priority`
- `documentation`
- probably also `infrastructure`

2021-06-22 07:05 UTC, XVilka approved these changes

2021-06-22 09:04 UTC, merged