[WIP] Refactor Tcache to use RzHeapBin
rizinorg/rizin pull request #1279
Opened 2021-07-07 04:58 UTC by PulakIIIT

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
Goals:
- Refactor the Tcache parsing code to use RzHeapBin so it can be easily integrated with Cutter. 

Side task:
- Try to issue #1259 

...

**Test plan**

...

**Closing issues**

...

2021-07-09 10:36 UTC, XVilka commented
There are some conflicts, please rebase on top of the latest `dev`.

2021-07-13 06:40 UTC, XVilka requested changes

2021-07-13 06:40 UTC, XVilka commented on librz/core/linux_heap_glibc.c
> +RZ_API bool GH(rz_heap_write_heap_chunk)(RzCore *core, RzHeapChunkSimple *chunk_simple) {
Please add Doxygen here since it's an API function

2021-07-13 06:40 UTC, XVilka commented on librz/core/linux_heap_glibc.c
> +RZ_API bool GH(rz_heap_write_heap_chunk)(RzCore *core, RzHeapChunkSimple *chunk_simple) {
Also it makes sense to check if chunk_simple is NULL

2021-07-14 20:38 UTC, yossizap approved these changes

2021-07-15 05:27 UTC, XVilka commented
@PulakIIIT is this still a draft?

2021-07-15 05:45 UTC, PulakIIIT commented
> @PulakIIIT is this still a draft?

@XVilka there is a couple of bug fixes I am working if I am able to resolve them Ill push to this branch today, this PR should be merged by today or tomorrow

2021-07-15 17:03 UTC, XVilka approved these changes

2021-07-16 08:46 UTC, wargio commented on librz/core/linux_heap_glibc.c
> +			eprintf("%s\n", fp + 1);
is this a debug string?

2021-07-16 09:49 UTC, PulakIIIT commented on librz/core/linux_heap_glibc.c
> +			eprintf("%s\n", fp + 1);
Nice catch! the eprintf was for debugging

2021-07-16 12:52 UTC, merged