Fix the broken integration test for CPU profiles
rizinorg/rizin pull request #1307
Opened 2021-07-14 14:26 UTC by officialcjunior

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
Since the the integration test breaks because `dir.prefix` points to a different place, the SDB file
is converted to bytes using the `pc` command and stored in a header file inside `unit/` and written
to temporary `.sdb` file and loaded for `RzArchTarget` and `RzArchPlatform`

**Test plan**

CI is green

**Closing issues**

None

2021-07-14 16:10 UTC, XVilka requested changes

2021-07-14 16:10 UTC, XVilka commented on test/integration/test_cpu_platform_profiles.c
> +	rz_file_dump(".tmp/test-cpu.sdb", cpu_buffer, 6649 ,false);
use `sizeof(cpu_buffer)` instead of the number.

2021-07-15 05:45 UTC, XVilka approved these changes
It is weird, but for now the solution is acceptable I think. Lets wait for opinions of others.

2021-07-15 08:13 UTC, wargio approved these changes

2021-07-15 08:13 UTC, merged