Pseudo fixes
rizinorg/rizin pull request #1308
Opened 2021-07-14 18:13 UTC by wargio

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This fixes mostly MIPS pseudo

2021-07-15 04:24 UTC, XVilka commented
Are there more representative tests for these fixes?

2021-07-15 05:38 UTC, XVilka requested changes

2021-07-15 05:38 UTC, XVilka commented on librz/core/cfile.c
> +			rz_core_cmd0(core, "s entry ; 10 aes");
Could you please use the API? Both have one.

2021-07-15 05:49 UTC, XVilka commented on librz/core/cfile.c
> +			rz_core_cmd0(core, "s entry ; 10 aes");
See `rz_core_seek_opt(core, n, true, !silent);` and `RZ_API bool rz_core_debug_step_one(RzCore *core, int times)`

2021-07-15 05:49 UTC, XVilka commented on librz/core/cfile.c
> +			rz_core_cmd0(core, "s entry ; 10 aes");
Or just `rz_core_seek(core, addr, false);`

2021-07-16 04:08 UTC, XVilka requested changes
Overall is good.

2021-07-16 04:08 UTC, XVilka commented on librz/parse/p/parse_z80_pseudo.c
> +	//	RZ_PSEUDO_DEFINE_GRAMMAR("ccf", "1 = 1 ? 2"),
Why those are commented?

2021-07-16 04:08 UTC, XVilka commented on librz/parse/parse.c
> +RZ_API char *rz_parse_parse(RzParse *p, const char *data) {
I suggest to rename the function and give it more meaningful name. Also please add a Doxygen

2021-07-16 08:27 UTC, wargio commented on librz/parse/p/parse_z80_pseudo.c
> +	//	RZ_PSEUDO_DEFINE_GRAMMAR("ccf", "1 = 1 ? 2"),
those are the missing instructions

2021-07-16 08:56 UTC, XVilka commented on librz/parse/p/parse_z80_pseudo.c
> +	//	RZ_PSEUDO_DEFINE_GRAMMAR("ccf", "1 = 1 ? 2"),
What do you mean by `missing`?

2021-07-16 08:59 UTC, wargio commented on librz/parse/p/parse_z80_pseudo.c
> +	//	RZ_PSEUDO_DEFINE_GRAMMAR("ccf", "1 = 1 ? 2"),
not implemented in pseudo

2021-07-16 09:02 UTC, XVilka commented on librz/parse/p/parse_z80_pseudo.c
> +	//	RZ_PSEUDO_DEFINE_GRAMMAR("ccf", "1 = 1 ? 2"),
ok.

2021-07-16 14:17 UTC, XVilka approved these changes

2021-07-19 04:48 UTC, XVilka approved these changes
Looks amazing. Lets see what others think and lets merge 👍 💯

2021-07-22 07:01 UTC, XVilka commented
It also fixes one of the tests broken on PPC: https://github.com/rizinorg/rizin/pull/1250

2021-07-22 08:13 UTC, wargio commented
yes it does.

2021-07-22 09:55 UTC, merged