`dc` to newshell
rizinorg/rizin pull request #1345
Opened 2021-07-21 11:16 UTC by PulakIIIT

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

A direct port of the `dc` commands from the old shell to new shell, did not alter logic of any command. As always open to feedback! I tested them in a debug session and compared them to old shell, seemed to work exact same for me. 
...

**Test plan**

CI is green

...

**Closing issues**

...

2021-07-21 11:25 UTC, XVilka requested changes

2021-07-21 11:25 UTC, XVilka commented on librz/core/agraph.c
> +	rz_cmd_debug_continue_execution_handler(core, 1, NULL);
What about using the proper API instead?
```c
CMD_CHECK_DEBUG_DEAD(core);
rz_cons_break_push(static_debug_stop, core->dbg);
rz_reg_arena_swap(core->dbg->reg, true);
#if __linux__
core->dbg->continue_all_threads = true;
#endif
rz_debug_continue(core->dbg);
dbg_follow_seek_register(core);
```
Or making it some function in the `librz/core/cdebug.c` and using it instead?
Reusing command handlers for pure API purpose doesn't seem right.

2021-07-21 11:25 UTC, XVilka commented on librz/core/panels.c
> +	rz_cmd_debug_continue_exception_handler(core, 1, NULL);
Same here.

2021-07-21 12:03 UTC, XVilka requested changes

2021-07-21 12:03 UTC, XVilka commented on librz/core/cmd_debug.c
> +		//	case 'c': // "dc"
Just remove this

2021-07-21 12:13 UTC, XVilka commented on librz/core/core_private.h
> +/*cmd_debug.c */
Missing space here.

2021-07-21 16:25 UTC, XVilka requested changes
Apart from that comment, everything else looks ok.

2021-07-21 16:25 UTC, XVilka commented on librz/core/cdebug.c
> +		rz_core_dbg_follow_seek_register(core);
Missing `rz_cons_break_pop()`

2021-07-21 17:43 UTC, wargio approved these changes

2021-07-22 04:58 UTC, XVilka approved these changes

2021-07-22 06:54 UTC, XVilka commented
Tested and can confirm as well.

2021-07-22 09:08 UTC, merged