Base find
rizinorg/rizin pull request #1382
Opened 2021-07-29 23:53 UTC by gnole

**Your checklist for this pull request**
- [ + ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ +- ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ - ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ - ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Implement basefind. https://github.com/rizinorg/rizin/issues/413
command: `rz-bin -Y file`
...

**Test plan**

...

**Closing issues**

...

2021-07-30 00:05 UTC, gnole commented
![RizinBasefind](https://user-images.githubusercontent.com/42045440/127580513-919206c1-4aaf-465a-b281-0b297cea9fa8.png)

2021-07-30 04:49 UTC, gnole commented
TODO Coding style/Rewrite code from C++ to C.
TODO Implement multithreading

2021-07-30 05:18 UTC, XVilka requested changes

2021-07-30 05:18 UTC, XVilka commented on librz/core/rz_basefind.cpp
> +//MIT Copyright (c) 2013 Michael Coppola
Use SPDX

2021-08-02 08:16 UTC, wargio requested changes

2021-08-02 08:16 UTC, wargio commented on librz/core/rz_basefind.cpp
> +typedef std::vector<std::pair<offset_t, unsigned>> scorecard;
for this you can use
```c
typedef rz_basefinds_t {
     offset_t offset;
     ut32 score;
} RzBasefinds;
```
The all `std::vector` and `std::unordered_set` you can use `rz_pvector` and use the `rz_pvector_find` to check if the set has the address.

2021-11-01 04:30 UTC, XVilka commented
Please reopen if you plan to continue the development. For now, I am closing as this is far from complete and stalled.

2021-11-01 04:30 UTC, closed without merging