Resolve minor bug in `rz_type_db_base_type_as_string`
rizinorg/rizin pull request #1402
Opened 2021-08-05 11:23 UTC by PulakIIIT

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
On my quest to fix types in  Cutter I saw that `rz_type_db_base_type_as_string` is not returning the name of the member of structs.
Old output:
```
struct foo { int; int;  }
```

New output
```
struct foo { int a; int b;  }
```

Should I add some new lines too??
The output will be like
```
struct foo { 
int a; 
int b; 
}
```

2021-08-05 13:14 UTC, ret2libc reviewed
LGTM! @XVilka your call!

2021-08-05 13:26 UTC, XVilka requested changes

2021-08-05 13:26 UTC, XVilka commented on librz/type/base.c
> +			rz_strbuf_appendf(buf, "%s %s; ", declaration, memb->name);
Add also the fix and test for unions as well

2021-08-05 13:37 UTC, PulakIIIT commented
@Xvilka Any thoughts on printing the members of the struct in a newline and putting a `;` at the end of struct and enums?

2021-08-05 13:48 UTC, XVilka commented
I remember the newlines and `;` were a problem for nested structures. See, for example, the similar printing code at `librz/core/ctypes.c`. I recommend to add a few levels of nested structures/unions in your tests as well to make sure this doesn't get broken.

2021-08-05 23:17 UTC, wargio approved these changes

2021-08-06 04:39 UTC, XVilka requested changes

2021-08-06 04:39 UTC, XVilka commented on test/unit/test_type.c
> +	mu_assert_streq(rz_type_db_base_type_as_string(typedb, base), "struct kappa { int32_t bar; int32_t cow;  }", "Incorrect conversion of struct to string");
Could you please add also a line with a nested structures to check this case?

2021-08-06 06:21 UTC, XVilka commented on test/unit/test_type.c
> +
What about the same for unions?

2021-08-06 06:31 UTC, PulakIIIT commented
In my last commit i meant `unions` not `enums`

2021-08-06 06:43 UTC, XVilka approved these changes

2021-08-06 09:40 UTC, merged