R2 backports 2
rizinorg/rizin pull request #1470
Opened 2021-08-17 15:35 UTC by ret2libc

Close https://github.com/rizinorg/rizin/issues/1430 .
Close https://github.com/rizinorg/rizin/issues/1428
Close https://github.com/rizinorg/rizin/issues/1427
Close https://github.com/rizinorg/rizin/issues/1426
Close https://github.com/rizinorg/rizin/issues/1425
Close https://github.com/rizinorg/rizin/issues/1424
Close https://github.com/rizinorg/rizin/issues/1422

2021-08-17 16:10 UTC, XVilka requested changes

2021-08-17 16:10 UTC, XVilka commented on librz/socket/run.c
> +		char *orig = r_sys_getenv("LIBRARY_PATH");
`rz_`

2021-08-17 16:19 UTC, ret2libc commented on librz/socket/run.c
> +		char *orig = r_sys_getenv("LIBRARY_PATH");
oh, nice catch :D

2021-08-18 01:42 UTC, XVilka commented
By the way, next time please use `import-patches` to trigger more CI jobs.

2021-08-18 06:10 UTC, XVilka approved these changes
Please fix the clang-format problem. Apart from that looks ok.

cc @devnexen regarding the HaikuOS patch - does it looks OK?

2021-08-18 06:16 UTC, devnexen commented
yes it does.

2021-08-18 07:16 UTC, merged