Fix #1506 - Fix unsigned integer overflow in RzIo cache skyline
rizinorg/rizin pull request #1512
Opened 2021-08-24 03:33 UTC by GustavoLCR

* Add test

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`RzSkyline` needs a `RzInterval` without wrap around.

**Test plan**

Test pass

**Closing issues**

Fixes #1506

2021-08-24 07:05 UTC, ret2libc reviewed
Would it make sense to have this overflow condition also in rz_skyline API (with rz_return_val_if_fail) so that if someone calls it with the wrong ranges we get a warning at least?

2021-08-24 07:11 UTC, ret2libc requested changes
Code looks good and I confirm it fixes the problem, thanks! I'd just wait for the rz_return_ on rz_skyline_add and rz_skyline_get_item_intersect.

2021-08-24 07:12 UTC, XVilka commented
@ret2libc good idea on overflow check in the API. If this possible it indeed might be helpful.

2021-08-24 09:10 UTC, wargio approved these changes

2021-08-25 02:49 UTC, XVilka commented
```
test_rz_io_mapsplit ERR
[XX] Fail at line 64: UT64_MAX not mapped: expected true, got false

test_rz_io_mapsplit2 ERR
[XX] Fail at line 81: UT64_MAX not mapped: expected true, got false

test_rz_io_mapsplit3 ERR
[XX] Fail at line 94: UT64_MAX - 1 not mapped: expected true, got false
```

2021-08-25 05:06 UTC, XVilka commented
```
[XX] db/cmd/cmd_px io.unalloc, io.unalloc.ch and pxc
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '. scripts/palette.rz
e io.unalloc=true
(dump; xc 0x00010060-0x0000ffd0 @ 0x0000ffd0-6)
e scr.color=3
e hex.comments=true
.(dump)
?e
e scr.color=0
.(dump)
?e
e hex.comments=false
e io.unalloc.ch=?
.(dump)
?e
e io.unalloc.ch=
.(dump)
' bins/elf/analysis/tiny.elf
-- stdout
--- expected
+++ actual
@@ -2,7 +2,7 @@
 0x0000ffca  .... .... .... .... .... .... .... ....                  
 0x0000ffda  .... .... .... .... .... .... .... ....                  
 0x0000ffea  .... .... .... .... .... .... .... ....                  
-0x0000fffa  .... .... .... 7f45 4c46 0100 0000 0000        .ELF......  ; segment.ehdr  ; [01] -rw- segment size 45 named ehdr
+0x0000fffa  .... .... ..ff 7f45 4c46 0100 0000 0000       ..ELF......  ; segment.ehdr  ; [01] -rw- segment size 45 named ehdr
 0x0001000a  0000 0000 0100 0200 0300 2000 0100 2000  .......... ... .
 0x0001001a  0100 0400 0000 b32a 31c0 40cd 8000 3400  .......*1.@...4.  ; entry0
 0x0001002a  2000 0100 0000 0000 0000 0000 0000 0000   ...............
@@ -13,7 +13,7 @@
 0x0000ffca  .... .... .... .... .... .... .... ....                  
 0x0000ffda  .... .... .... .... .... .... .... ....                  
 0x0000ffea  .... .... .... .... .... .... .... ....                  
-0x0000fffa  .... .... .... 7f45 4c46 0100 0000 0000        .ELF......  ; segment.ehdr  ; [01] -rw- segment size 45 named ehdr
+0x0000fffa  .... .... ..ff 7f45 4c46 0100 0000 0000       ..ELF......  ; segment.ehdr  ; [01] -rw- segment size 45 named ehdr
 0x0001000a  0000 0000 0100 0200 0300 2000 0100 2000  .......... ... .
 0x0001001a  0100 0400 0000 b32a 31c0 40cd 8000 3400  .......*1.@...4.  ; entry0
 0x0001002a  2000 0100 0000 0000 0000 0000 0000 0000   ...............
@@ -24,7 +24,7 @@
 0x0000ffca  ???? ???? ???? ???? ???? ???? ???? ????                  
 0x0000ffda  ???? ???? ???? ???? ???? ???? ???? ????                  
 0x0000ffea  ???? ???? ???? ???? ???? ???? ???? ????                  
-0x0000fffa  ???? ???? ???? 7f45 4c46 0100 0000 0000        .ELF......
+0x0000fffa  ???? ???? ??ff 7f45 4c46 0100 0000 0000       ..ELF......
 0x0001000a  0000 0000 0100 0200 0300 2000 0100 2000  .......... ... .
 0x0001001a  0100 0400 0000 b32a 31c0 40cd 8000 3400  .......*1.@...4.
 0x0001002a  2000 0100 0000 0000 0000 0000 0000 0000   ...............
@@ -35,7 +35,7 @@
 0x0000ffca                                                           
 0x0000ffda                                                           
 0x0000ffea                                                           
-0x0000fffa                 7f45 4c46 0100 0000 0000        .ELF......
+0x0000fffa              ff 7f45 4c46 0100 0000 0000       ..ELF......
 0x0001000a  0000 0000 0100 0200 0300 2000 0100 2000  .......... ... .
 0x0001001a  0100 0400 0000 b32a 31c0 40cd 8000 3400  .......*1.@...4.
 0x0001002a  2000 0100 0000 0000 0000 0000 0000 0000   ...............
[XX] db/cmd/cmd_print io.unalloc, io.unalloc.ch and prc
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '. scripts/palette.rz
(print; prc 0x00010032-0x0000fffa @ 0x0000fffa)
e io.unalloc=true
e scr.color=0
.(print)
?e
e io.unalloc.ch=-
.(print)
?e
e scr.color=3
e io.unalloc.ch=
.(print)
?e
e io.unalloc.ch=?
.(print)
' bins/elf/analysis/tiny.elf
-- stdout
--- expected
+++ actual
@@ -1,19 +1,19 @@
-0x0000fffa ????????????se,,,,,,            
+0x0000fffa ??????????##se,,,,,,            
 0x0001000a                     ..      ..  
 0x0001001a             en....OO,,OO;;  ..  
 0x0001002a ..              
 
-0x0000fffa ------------se,,,,,,            
+0x0000fffa ----------##se,,,,,,            
 0x0001000a                     ..      ..  
 0x0001001a             en....OO,,OO;;  ..  
 0x0001002a ..              
 
-0x0000fffa ..........[0m..se                  
+0x0000fffa ..........[38;2;0;0;0m  se                  
 0x0001000a                                 
 0x0001001a             en                  
 0x0001002a                 
 
-0x0000fffa ??????????[0m??se                  
+0x0000fffa ??????????[38;2;0;0;0m  se                  
 0x0001000a                                 
 0x0001001a             en                  
 0x0001002a                 

-- stderr
WARNING: Failed to read ELF header (e_phnum).
WARNING: Failed to read ELF header (e_shentsize).
WARNING: Failed to read ELF header (e_shnum).
WARNING: Failed to read ELF header (e_shstrndx).
WARNING: The binary seems to be a tiny elf (45 bytes). Reload e_phnum value.
WARNING: The segment 0 at 0x4 seems to be invalid.
WARNING: Failed to initialize section header.
```

2021-08-25 05:09 UTC, XVilka requested changes

2021-08-25 05:09 UTC, XVilka commented on librz/util/skyline.c
> +	rz_return_val_if_fail(skyline && (!rz_itv_size(itv) || !UT64_ADD_OVFCHK(rz_itv_begin(itv), rz_itv_size(itv) - 1)), false);
I think it's probably to extract this long check into multiple `rz_return_val_if_fail()` for readability.

2021-08-25 05:09 UTC, XVilka commented on librz/util/skyline.c
> +	rz_return_val_if_fail(skyline && len && !UT64_ADD_OVFCHK(addr, len - 1), NULL);
Probably better to split this `rz_return_val_if_fail()` in two.

2021-08-25 06:39 UTC, ret2libc commented on librz/util/skyline.c
> +		// Allow size 1 itv at UT64_MAX, block all other overflows
@GustavoLCR why this? Does this block itv.addr == UT64_MAX-1, len = 2 as well?

2021-08-25 06:41 UTC, ret2libc commented on test/unit/test_io.c
> +	mu_assert_true(rz_io_cache_read(io, 9, buf + 9, 2), "Cache read at 8 failed");
```suggestion
	mu_assert_true(rz_io_cache_read(io, 9, buf + 9, 2), "Cache read at 9 failed");
```

2021-08-25 06:44 UTC, ret2libc commented on librz/util/skyline.c
> +		// Allow size 1 itv at UT64_MAX, block all other overflows
Judging from the unit tests you wrote, it seems that UT64_MAX-1, len=2 is possible indeed. Maybe it's just the comment wrong?

2021-08-25 07:02 UTC, ret2libc approved these changes
Amazing!

2021-08-25 08:36 UTC, merged