Fix various bugs linked to fuzzing bins
rizinorg/rizin pull request #1529
Opened 2021-08-25 20:56 UTC by wargio

# squashme

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Resolves many binary parsing bugs.

2021-08-26 03:54 UTC, XVilka commented
It fails quite a bit of tests:
```
[XX] db/formats/le GNUGREP.DLL relocations
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'ir > $relocs
cat $relocs~?
cat $relocs~GNUREGEX~?
cat $relocs~EMXLIBC~?
cat $relocs~emx~?
' bins/le/GNUGREP.DLL
-- stdout
--- expected
+++ actual
@@ -1,4 +1,4 @@
-1170
 8
-183
+0
+3
 1
[XX] db/formats/ne NE Code
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'pi 10 @ sym.WNDPROC' bins/ne/anim8.exe
-- stdout
--- expected
+++ actual
@@ -1,10 +1,10 @@
-mov ax, ds
-nop
-inc bp
-push bp
-mov bp, sp
-push ds
-mov ds, ax
-mov ax, 0x5c
-call 0x4d35
-push si
+jae 0xb09
+mov ax, cx
+mov dx, bx
+add bx, 6
+jmp 0xaf1
+cmp dx, di
+je 0xb2d
+mov bx, dx
+cmp byte es:[bx], 0
+mov byte es:[bx], 0xff



[XX] db/formats/ne NE Relocs and resolve function ordinal names
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'ir~WIN87EM
ir~:0..11
' bins/ne/anim8.exe
-- stdout
--- expected
+++ actual
@@ -7,6 +7,11 @@
 0x000056a0 0x000056a0 ADD_16 WIN87EM.0
 0x000056b3 0x000056b3 ADD_16 WIN87EM.0
 0x00005891 0x00005891 ADD_16 WIN87EM.0
+0x000109ff 0x000109ff SET_16 WIN87EM.__FPMATH
+0x000109ff 0x000109ff SET_16 WIN87EM.__FPMATH
+0x000109ff 0x000109ff SET_32 WIN87EM.__FPMATH
+0x000109ff 0x000109ff SET_32 WIN87EM.__FPMATH
+0x000109ff 0x000109ff SET_32 WIN87EM.__FPMATH
 [Relocations]
 
 vaddr      paddr      type   name                             



[XX] db/formats/ne NE Relocs
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc ir~0x? bins/ne/anim8.exe
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-718
+933



[XX] db/formats/ne NE Symbols
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc is bins/ne/anim8.exe
-- stdout
--- expected
+++ actual
@@ -3,6 +3,7 @@
 nth paddr      vaddr      bind   type size lib name       
 ----------------------------------------------------------
 0   0x00000a00 0x00000a00 NONE   NONE 0        ANIM8
-1   0x00000d8e 0x00000d8e GLOBAL NONE 0        WNDPROC
-2   0x00002b5a 0x00002b5a GLOBAL NONE 0        DIAL_ABOUT
+1   0x00000b03 0x00000b03 GLOBAL NONE 0        WNDPROC
+2   0x00000b3f 0x00000b3f GLOBAL NONE 0        DIAL_ABOUT
 0   0x00000a00 0x00000a00 NONE   NONE 0        ANIM8
+4   0x00000a21 0x00000a21 GLOBAL NONE 0        entry3
```

2021-08-26 07:13 UTC, ret2libc approved these changes

2021-08-26 09:26 UTC, wargio commented
![image](https://user-images.githubusercontent.com/561184/130938181-33597f54-c1bf-476b-b248-7d98150413df.png)
Well, seems i have improved it.

2021-08-26 09:51 UTC, XVilka commented on test/db/formats/ne
> -2   0x00002b5a 0x00002b5a GLOBAL NONE 0        DIAL_ABOUT
Are you sure these changes are correct? Could you please check with any another program? Ghidra or Binary Ninja?

2021-08-26 09:51 UTC, XVilka commented on test/db/formats/ne
> +jae 0xb09
Same

2021-08-26 10:01 UTC, wargio commented on test/db/formats/ne
> -2   0x00002b5a 0x00002b5a GLOBAL NONE 0        DIAL_ABOUT
check the screenshot above.

2021-08-26 10:01 UTC, wargio commented on test/db/formats/ne
> +jae 0xb09
same as above

2021-08-27 04:58 UTC, XVilka commented
This is what IDA Pro 7.6sp2 says about NE binary from `bins/ne/anim8.exe`.
Here is the `WNDPROC` function. Note the address is `cseg01:038E`:
```
cseg01:038E ;
cseg01:038E ; External Entry #1 into the Module
cseg01:038E ; Attributes (0001): Moveable Exported
cseg01:038E ;
cseg01:038E
cseg01:038E ; =============== S U B R O U T I N E =======================================
cseg01:038E
cseg01:038E ; Attributes: bp-based frame
cseg01:038E
cseg01:038E                 public WNDPROC
cseg01:038E WNDPROC         proc far                ; DATA XREF: sub_170+4B↑o
cseg01:038E
cseg01:038E var_5E          = byte ptr -5Eh
cseg01:038E var_C           = word ptr -0Ch
cseg01:038E var_A           = word ptr -0Ah
cseg01:038E var_8           = word ptr -8
cseg01:038E var_6           = word ptr -6
cseg01:038E var_4           = word ptr -4
cseg01:038E arg_0           = dword ptr  6
cseg01:038E arg_4           = word ptr  0Ah
cseg01:038E arg_6           = word ptr  0Ch
cseg01:038E arg_8           = word ptr  0Eh
cseg01:038E
cseg01:038E                 mov     ax, ds          ; ANIM8_1
cseg01:0390                 nop
cseg01:0391                 inc     bp
cseg01:0392                 push    bp
cseg01:0393                 mov     bp, sp
cseg01:0395                 push    ds
cseg01:0396                 mov     ds, ax
cseg01:0398                 mov     ax, 5Ch ; '\'
cseg01:039B                 call    near ptr sub_4335
cseg01:039E                 push    si
cseg01:039F                 push    di
cseg01:03A0                 mov     dx, [bp+arg_8]
cseg01:03A3                 mov     di, [bp+arg_6]
cseg01:03A6                 mov     si, [bp+arg_4]
cseg01:03A9                 mov     word_9346, dx
cseg01:03AD                 mov     ax, di
cseg01:03AF                 cmp     ax, 101h
cseg01:03B2                 jnz     short loc_3B7
cseg01:03B4                 jmp     loc_4FB
cseg01:03B7 ; ---------------------------------------------------------------------------
cseg01:03B7
cseg01:03B7 loc_3B7:                                ; CODE XREF: WNDPROC+24↑j
cseg01:03B7                 ja      short loc_3E6
cseg01:03B9                 cmp     ax, 5
cseg01:03BC                 jnz     short loc_3C1
cseg01:03BE                 jmp     loc_598
cseg01:03C1 ; ---------------------------------------------------------------------------
cseg01:03C1
cseg01:03C1 loc_3C1:                                ; CODE XREF: WNDPROC+2E↑j
cseg01:03C1                 ja      short loc_3D3
cseg01:03C3                 cmp     ax, 1
cseg01:03C6                 jz      short loc_40E
cseg01:03C8                 cmp     ax, 2
cseg01:03CB                 jnz     short loc_3D0
cseg01:03CD                 jmp     loc_952
cseg01:03D0 ; ---------------------------------------------------------------------------
cseg01:03D0
cseg01:03D0 loc_3D0:                                ; CODE XREF: WNDPROC+3D↑j
cseg01:03D0                 jmp     def_70A         ; jumptable 0000070A default case
cseg01:03D3 ; ---------------------------------------------------------------------------
cseg01:03D3
cseg01:03D3 loc_3D3:                                ; CODE XREF: WNDPROC:loc_3C1↑j
cseg01:03D3                 cmp     ax, 10h
cseg01:03D6                 jnz     short loc_3DB
cseg01:03D8                 jmp     loc_868
cseg01:03DB ; ---------------------------------------------------------------------------
cseg01:03DB
cseg01:03DB loc_3DB:                                ; CODE XREF: WNDPROC+48↑j
cseg01:03DB                 cmp     ax, 37h ; '7'
cseg01:03DE                 jnz     short loc_3E3
cseg01:03E0                 jmp     loc_57E
cseg01:03E3 ; ---------------------------------------------------------------------------
cseg01:03E3
cseg01:03E3 loc_3E3:                                ; CODE XREF: WNDPROC+50↑j
cseg01:03E3                 jmp     def_70A         ; jumptable 0000070A default case
cseg01:03E6 ; ---------------------------------------------------------------------------
cseg01:03E6
cseg01:03E6 loc_3E6:                                ; CODE XREF: WNDPROC:loc_3B7↑j
cseg01:03E6                 cmp     ax, 116h
cseg01:03E9                 jnz     short loc_3EE
cseg01:03EB                 jmp     loc_4ED
cseg01:03EE ; ---------------------------------------------------------------------------
cseg01:03EE
cseg01:03EE loc_3EE:                                ; CODE XREF: WNDPROC+5B↑j
cseg01:03EE                 ja      short loc_403
cseg01:03F0                 cmp     ax, 111h
cseg01:03F3                 jnz     short loc_3F8
cseg01:03F5                 jmp     loc_6FB
cseg01:03F8 ; ---------------------------------------------------------------------------
cseg01:03F8
cseg01:03F8 loc_3F8:                                ; CODE XREF: WNDPROC+65↑j
cseg01:03F8                 cmp     ax, 113h
cseg01:03FB                 jnz     short loc_400
cseg01:03FD                 jmp     loc_5D5
cseg01:0400 ; ---------------------------------------------------------------------------
cseg01:0400
cseg01:0400 loc_400:                                ; CODE XREF: WNDPROC+6D↑j
cseg01:0400                 jmp     def_70A         ; jumptable 0000070A default case
cseg01:0403 ; ---------------------------------------------------------------------------
cseg01:0403
cseg01:0403 loc_403:                                ; CODE XREF: WNDPROC:loc_3EE↑j
cseg01:0403                 cmp     ax, 11Fh
cseg01:0406                 jnz     short loc_40B
cseg01:0408                 jmp     loc_533
cseg01:040B ; ---------------------------------------------------------------------------
cseg01:040B
cseg01:040B loc_40B:                                ; CODE XREF: WNDPROC+78↑j
cseg01:040B                 jmp     def_70A         ; jumptable 0000070A default case
cseg01:040E ; ---------------------------------------------------------------------------
cseg01:040E
cseg01:040E loc_40E:                                ; CODE XREF: WNDPROC+38↑j
cseg01:040E                 les     bx, [bp+arg_0]
cseg01:0411                 mov     ax, es:[bx+4]
cseg01:0415                 mov     word_935A, ax
cseg01:0418                 push    ax
cseg01:0419                 push    2718h
cseg01:041C                 push    ss
cseg01:041D                 lea     ax, [bp+var_5E]
cseg01:0420                 push    ax
cseg01:0421                 push    51h ; 'Q'
cseg01:0423                 call    LOADSTRING
cseg01:0428                 lea     ax, [bp+var_5E]
cseg01:042B                 push    ax
cseg01:042C                 push    0A61h
cseg01:042F                 call    sub_1FB0
cseg01:0432                 push    word_9346
cseg01:0436                 push    1
cseg01:0438                 push    1
cseg01:043A                 push    0
cseg01:043C                 push    0
cseg01:043E                 call    SETTIMER
cseg01:0443                 or      ax, ax
cseg01:0445                 jnz     short loc_44C
cseg01:0447                 mov     ax, 1
cseg01:044A                 jmp     short loc_44E
cseg01:044C ; ---------------------------------------------------------------------------
cseg01:044C
cseg01:044C loc_44C:                                ; CODE XREF: WNDPROC+B7↑j
cseg01:044C                 xor     ax, ax
cseg01:044E
cseg01:044E loc_44E:                                ; CODE XREF: WNDPROC+BC↑j
cseg01:044E                 push    ax
cseg01:044F                 push    43h ; 'C'
cseg01:0451                 push    62h ; 'b'
cseg01:0454                 push    0
cseg01:0456                 push    7Ah ; 'z'
cseg01:0458                 call    sub_20FE
cseg01:045B                 push    word_9346
cseg01:045F                 push    ds
cseg01:0460                 push    offset word_61AE
cseg01:0463                 call    GETCLIENTRECT
cseg01:0468                 push    0
cseg01:046A                 call    sub_2A08
cseg01:046D                 add     sp, 2
cseg01:0470                 push    ax
cseg01:0471                 call    sub_28DA
cseg01:0474                 add      [...]

2021-08-27 05:01 UTC, XVilka commented
This is the same file, `DIAL_ABOUT` function. Note the `cseg01:215A` function:
```
cseg01:215A ;
cseg01:215A ; External Entry #2 into the Module
cseg01:215A ; Attributes (0001): Moveable Exported
cseg01:215A ;
cseg01:215A
cseg01:215A ; =============== S U B R O U T I N E =======================================
cseg01:215A
cseg01:215A ; Attributes: bp-based frame
cseg01:215A
cseg01:215A                 public DIAL_ABOUT
cseg01:215A DIAL_ABOUT      proc far                ; DATA XREF: WNDPROC+457↑o
cseg01:215A
cseg01:215A var_22          = byte ptr -22h
cseg01:215A arg_4           = word ptr  0Ah
cseg01:215A arg_6           = word ptr  0Ch
cseg01:215A arg_8           = word ptr  0Eh
cseg01:215A
cseg01:215A                 mov     ax, ds          ; ANIM8_2
cseg01:215C                 nop
cseg01:215D                 inc     bp
cseg01:215E                 push    bp
cseg01:215F                 mov     bp, sp
cseg01:2161                 push    ds
cseg01:2162                 mov     ds, ax
cseg01:2164                 mov     ax, 20h ; ' '
cseg01:2167                 call    near ptr sub_4335
cseg01:216A                 push    si
cseg01:216B                 mov     si, [bp+arg_8]
cseg01:216E                 mov     ax, [bp+arg_6]
cseg01:2171                 cmp     ax, 0Fh
cseg01:2174                 jz      short loc_21AE
cseg01:2176                 cmp     ax, 110h
cseg01:2179                 jz      short loc_2186
cseg01:217B                 cmp     ax, 111h
cseg01:217E                 jnz     short loc_2183
cseg01:2180                 jmp     loc_221D
cseg01:2183 ; ---------------------------------------------------------------------------
cseg01:2183
cseg01:2183 loc_2183:                               ; CODE XREF: DIAL_ABOUT+24↑j
cseg01:2183                 jmp     loc_223A
cseg01:2186 ; ---------------------------------------------------------------------------
cseg01:2186
cseg01:2186 loc_2186:                               ; CODE XREF: DIAL_ABOUT+1F↑j
cseg01:2186                 push    word_935A
cseg01:218A                 push    ds
cseg01:218B                 push    offset aIconx_0 ; "ICONX"
cseg01:218E                 call    LOADICON
cseg01:2193                 mov     word_933C, ax
cseg01:2196                 push    si
cseg01:2197                 push    76h ; 'v'
cseg01:2199                 call    GETDLGITEM
cseg01:219E                 mov     word_933A, ax
cseg01:21A1                 mov     ax, 1
cseg01:21A4                 pop     si
cseg01:21A5                 lea     sp, [bp-2]
cseg01:21A8                 pop     ds
cseg01:21A9                 pop     bp
cseg01:21AA                 dec     bp
cseg01:21AB                 retf    0Ah
cseg01:21AE ; ---------------------------------------------------------------------------
cseg01:21AE
cseg01:21AE loc_21AE:                               ; CODE XREF: DIAL_ABOUT+1A↑j
cseg01:21AE                 cmp     word_933C, 0
cseg01:21B3                 jnz     short loc_21B8
cseg01:21B5                 jmp     loc_223A
cseg01:21B8 ; ---------------------------------------------------------------------------
cseg01:21B8
cseg01:21B8 loc_21B8:                               ; CODE XREF: DIAL_ABOUT+59↑j
cseg01:21B8                 cmp     word_933A, 0
cseg01:21BD                 jz      short loc_223A
cseg01:21BF                 push    si
cseg01:21C0                 push    ss
cseg01:21C1                 lea     ax, [bp+var_22]
cseg01:21C4                 push    ax
cseg01:21C5                 call    BEGINPAINT
cseg01:21CA                 push    si
cseg01:21CB                 push    ss
cseg01:21CC                 lea     ax, [bp+var_22]
cseg01:21CF                 push    ax
cseg01:21D0                 call    ENDPAINT
cseg01:21D5                 push    word_933A
cseg01:21D9                 push    ss
cseg01:21DA                 lea     ax, [bp+var_22]
cseg01:21DD                 push    ax
cseg01:21DE                 call    BEGINPAINT
cseg01:21E3                 mov     si, ax
cseg01:21E5                 or      si, si
cseg01:21E7                 jnz     short loc_21EE
cseg01:21E9                 mov     ax, 1
cseg01:21EC                 jmp     short loc_21F0
cseg01:21EE ; ---------------------------------------------------------------------------
cseg01:21EE
cseg01:21EE loc_21EE:                               ; CODE XREF: DIAL_ABOUT+8D↑j
cseg01:21EE                 xor     ax, ax
cseg01:21F0
cseg01:21F0 loc_21F0:                               ; CODE XREF: DIAL_ABOUT+92↑j
cseg01:21F0                 push    ax
cseg01:21F1                 push    2713h
cseg01:21F4                 push    184h
cseg01:21F7                 push    0
cseg01:21F9                 push    9Bh
cseg01:21FC                 call    sub_20FE
cseg01:21FF                 push    si
cseg01:2200                 push    0
cseg01:2202                 push    0
cseg01:2204                 push    word_933C
cseg01:2208                 call    DRAWICON
cseg01:220D                 push    word_933A
cseg01:2211                 push    ss
cseg01:2212                 lea     ax, [bp+var_22]
cseg01:2215                 push    ax
cseg01:2216                 call    ENDPAINT
cseg01:221B                 jmp     short loc_223A
cseg01:221D ; ---------------------------------------------------------------------------
cseg01:221D
cseg01:221D loc_221D:                               ; CODE XREF: DIAL_ABOUT+26↑j
cseg01:221D                 mov     ax, [bp+arg_4]
cseg01:2220                 cmp     ax, 2
cseg01:2223                 jnz     short loc_223A
cseg01:2225                 push    si
cseg01:2226                 push    0
cseg01:2228                 call    ENDDIALOG
cseg01:222D                 mov     ax, 1
cseg01:2230                 pop     si
cseg01:2231                 lea     sp, [bp-2]
cseg01:2234                 pop     ds
cseg01:2235                 pop     bp
cseg01:2236                 dec     bp
cseg01:2237                 retf    0Ah
cseg01:223A ; ---------------------------------------------------------------------------
cseg01:223A
cseg01:223A loc_223A:                               ; CODE XREF: DIAL_ABOUT:loc_2183↑j
cseg01:223A                                         ; DIAL_ABOUT+5B↑j ...
cseg01:223A                 xor     ax, ax
cseg01:223C                 pop     si
cseg01:223D                 lea     sp, [bp-2]
cseg01:2240                 pop     ds
cseg01:2241                 pop     bp
cseg01:2242                 dec     bp
cseg01:2243                 retf    0Ah
cseg01:2243 DIAL_ABOUT      endp
cseg01:2243
```

2021-08-27 05:01 UTC, XVilka requested changes

2021-08-27 05:01 UTC, XVilka commented on test/db/formats/ne
> +jae 0xb09
The previous output the valid, see the comment below.

2021-08-27 05:02 UTC, XVilka commented
Can you please remove the NE changes from this PR thus we can merge the rest of the fixes straight away? NE issues are trickier and should be addressed in the separate PR.

2021-08-27 05:04 UTC, XVilka commented on test/db/formats/ne
> -2   0x00002b5a 0x00002b5a GLOBAL NONE 0        DIAL_ABOUT
They aren't. See my comment.

2021-08-27 11:48 UTC, XVilka approved these changes

2021-08-27 11:51 UTC, merged