Add autocomplete function and cmd arg type for global variables
rizinorg/rizin pull request #1577
Opened 2021-09-02 13:41 UTC by DMaroo

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Now global variables support autocompletion (when `cfg.oldshell.autocompletion` is set to `false`).

**Test plan**

Add tests once the current changes are approved and reviewed.

**Closing issues**

Closes #1551.

2021-09-02 14:23 UTC, ret2libc requested changes

2021-09-02 14:23 UTC, ret2libc commented on librz/core/cautocmpl.c
> +	RzList *list = rz_analysis_var_global_get_all(core->analysis);
free the list

2021-09-02 16:10 UTC, DMaroo commented
Where should I add tests for this?

2021-09-02 16:46 UTC, ret2libc approved these changes

2021-09-02 16:48 UTC, ret2libc commented
> Where should I add tests for this?

You could look at `test_autocmplt.c` and see how test_autocmplt_fcn or others are done. In the case of global variables should be simpler because you don't even need a real file+RzCore but you can just open a malloc://10 and add global variables there.

2021-09-02 18:43 UTC, wargio approved these changes

2021-09-03 06:02 UTC, XVilka approved these changes

2021-09-03 06:42 UTC, ret2libc commented on test/unit/test_autocmplt.c
> +
```suggestion
```

2021-09-03 07:49 UTC, merged