Fix #469 by checking the value of `analysis.jmp.cref`
rizinorg/rizin pull request #1594
Opened 2021-09-04 16:19 UTC by theopechli

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This issue was that during `aaa`, the config variable `analysis.jmp.cref` is ignored and, as such, `aar` is run despite its value.

Note that its default value is `false`, which may be undesirable.

**Test plan**

I can add tests tomorrow, if needed.

**Closing issues**

closes #469

2021-09-05 01:27 UTC, wargio commented on librz/core/canalysis.c
> +	if (rz_config_get_b(core->config, "analysis.jmp.cref")) {
Maybe i'm missing something here. why this flag?

2021-09-05 12:41 UTC, wargio commented
not sure if this is the right way.. let's wait for the others and especially @pelijah

2021-09-05 19:30 UTC, pelijah commented
Well I have no idea how it should be done.

2021-09-06 07:43 UTC, XVilka commented
I checked some tests output with the `analysis.jmp.cref=true` by default and the output looks better, in fact. I am not sure it should be `false` by default. cc @wargio @thestr4ng3r @ret2libc

2021-09-06 07:47 UTC, wargio commented on test/db/tools/rz_diff
> +CMDS=!rz-diff -e analysis.jmp.cref=true -C -j -t graphs -0 fcn.00401ae0 -1 fcn.00401af0 bins/other/rz-diff/true bins/other/rz-diff/false
there is no `-e` option on rz-diff

2021-09-06 12:25 UTC, ret2libc requested changes
I think @wargio is right. Your PR run or does not run `rz_core_analysis_refs` based on the `analysis.jmp.cref` variable. However, `analysis.jmp.cref` says `analysis.jmp.cref: Create references for conditional jumps`, while `rz_core_analysis_refs` does much more than just analyzing refs for conditional jumps, it actually defines refs for calls, unconditional branches, data, etc.

I think you should look at `rz_core_analysis_refs` to see what to modifies and in particular at `rz_core_analysis_search_xrefs`. Please let us know if you need additional help!

2021-09-06 15:26 UTC, theopechli commented on test/db/tools/rz_diff
> +CMDS=!rz-diff -e analysis.jmp.cref=true -C -j -t graphs -0 fcn.00401ae0 -1 fcn.00401af0 bins/other/rz-diff/true bins/other/rz-diff/false
I've been fooled by `man rz-diff`

2021-09-06 20:03 UTC, wargio commented on test/db/tools/rz_diff
> +CMDS=!rz-diff -e analysis.jmp.cref=true -C -j -t graphs -0 fcn.00401ae0 -1 fcn.00401af0 bins/other/rz-diff/true bins/other/rz-diff/false
yeah. that one is old

2021-09-06 21:32 UTC, theopechli commented
The only test that's failing is `db/tools/rz_diff rz-diff graphs comparison with addresses JSON`, because `analysis.jmp.cref=false` by default and rz-diff has no option to configure variables, despite what `man rz-diff` prints.

Two obvious solutions are:
1. Set `analysis.jmp.cref` to true
2. Mark that test as broken

I don't know if I missed something else in this PR.

2021-09-08 08:12 UTC, wargio commented
> The only test that's failing is `db/tools/rz_diff rz-diff graphs comparison with addresses JSON`, because `analysis.jmp.cref=false` by default and rz-diff has no option to configure variables, despite what `man rz-diff` prints.
> 
> Two obvious solutions are:
> 
> 1. Set `analysis.jmp.cref` to true
> 2. Mark that test as broken
> 
> I don't know if I missed something else in this PR.

i will try to add `-e` option to rz-diff today so you can rebase and it should work.

2021-09-24 08:12 UTC, ret2libc commented
@wargio @theopechli what's the status of this? I think the patch looks good, why is it failing? Can we workaround the problem so that `-e` in rz-diff can be done at a later time?

2021-09-24 10:47 UTC, wargio commented
no. i need to patch rz-diff and add the -e flag.

2021-10-11 09:19 UTC, ret2libc commented
@wargio ping

2021-10-11 11:03 UTC, wargio commented
i'm so sorry for the delay. i have added the option. once it is merged, we can update this

2021-10-11 17:56 UTC, wargio approved these changes

2021-10-13 07:02 UTC, ret2libc approved these changes

2021-10-13 12:32 UTC, merged