Fixes for types serialization and deserialization
rizinorg/rizin pull request #1601
Opened 2021-09-06 06:11 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Fixes two bugs:
1. Atomic type formats were saved as `type.bool=b bool bool` while it should be `type.bool=b`
2. Bit-specific types (`types-16.sdb` for example) were loaded only if `arch` was defined as well, we fix the order now.

**Test plan**

CI is green

**Closing issues**

Aims to fix https://github.com/rizinorg/rizin/issues/1560

2021-09-06 10:03 UTC, wargio approved these changes

2021-09-06 10:03 UTC, wargio commented
is there a test for this?

2021-09-06 11:29 UTC, ret2libc requested changes
It seems I can still reproduce the problem in the referenced issue.

2021-09-06 12:03 UTC, ret2libc commented
[ls.rzdb.txt](https://github.com/rizinorg/rizin/files/7115838/ls.rzdb.txt)

2021-09-07 05:19 UTC, XVilka commented
@ret2libc it was because projects created before used `unknown_t` in the function, variable types, but not added in the `/core/analysis/types` section of the project. I bumped the version of project to 5 and added a migration step that adds the corresponding types. Added also the unit test for checking if it was added. If you have more ideas how to test this better - let me know.

2021-09-07 07:53 UTC, ret2libc commented
> @ret2libc it was because projects created before used `unknown_t` in the function, variable types, but not added in the `/core/analysis/types` section of the project. I bumped the version of project to 5 and added a migration step that adds the corresponding types. Added also the unit test for checking if it was added. If you have more ideas how to test this better - let me know.

Ok I think it kinda works now. The first time you load and save it it still gives a lot of `Cannot find base type "wchar_t"` errors, but after that first time it doesn't print errors anymore. It's ok, I think. Maybe wait for @thestr4ng3r to check the migration as well.

2021-09-07 09:29 UTC, thestr4ng3r approved these changes

2021-09-07 09:34 UTC, merged