Uplifting 8051 architecture to new IL
rizinorg/rizin pull request #1609
Opened 2021-09-07 09:10 UTC by Basstorm

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- [x] ADD
- [x] ADDC
- [x] SUBB
- [x] INC
- [x] DEC
- [x] MOV
- [x] ORL
- [x] ANL
- [x] XRL
- [ ] DIV
- [ ] MUL
- [x] XCH
- [ ] XCHD
- [ ] SWAP
- [ ] DA
- [ ] CLR
- [ ] CPL
- [ ] RR
- [ ] RRC
- [ ] RL
- [ ] RLC
- [ ] JMP
- [ ] MOVC
- [ ] MOVX
- [ ] SETB
- [ ] LJMP
- [ ] LCALL
- [ ] RET
- [ ] RETI
- [ ] AJMP
- [ ] ACALL
- [ ] JBC
- [ ] JB
- [ ] JNB
- [ ] JC
- [ ] JNC
- [ ] JZ
- [ ] JNZ
- [ ] SJMP
- [ ] PUSH
- [ ] POP
- [ ] DJNZ

**Test plan**

...

**Closing issues**

...

2021-09-07 17:27 UTC, XVilka commented
Please rebase on top of the latest IL branch, there are way too many conflicts.

2021-10-09 10:15 UTC, XVilka commented
@Basstorm please rebase on top of the latest `dev` and resolve the conflicts.

2021-10-19 04:45 UTC, XVilka commented
There are many failing tests. I recommend to start addressing them one by one

2021-10-19 07:20 UTC, ret2libc commented on librz/analysis/p/analysis_8051.c
> +RzPVector *i8051_movx(RzILVM *vm, ut64 id, const ut8 *buf, _8051_op_t op) {
how is this called?

2021-10-19 07:31 UTC, XVilka requested changes

2021-10-19 07:31 UTC, XVilka commented on librz/analysis/p/analysis_8051.c
>  	if (mask & RZ_ANALYSIS_OP_MASK_ESIL) {
I think ESIL here can be removed completely.

2021-10-19 07:31 UTC, XVilka commented on librz/analysis/p/analysis_8051.c
> +	// create core theory VM
Better to refer to it as RZIL VM outside of the RZIL module.

2021-10-19 07:31 UTC, XVilka commented on librz/analysis/p/analysis_8051.c
> +		eprintf("Already init\n");
Probably `RZ_LOG_WARNING()`

2021-10-19 07:31 UTC, XVilka commented on librz/analysis/p/analysis_8051.c
> +	RzILOp *int_ = rz_il_new_op(RZIL_OP_INT);
I wonder if we can shorten this pattern of:
```c
RzILOp *op = rz_il_new_op(RZIL_OP_TYPE);
op->op.something = x;
op->op.another = y;
```
@ret2libc @thestr4ng3r @wargio any ideas?

2021-10-19 07:31 UTC, XVilka commented on librz/analysis/p/analysis_8051.c
> +	RzPVector *oplist = rz_il_make_oplist(id, 8, var_a, var_b, div, mod, set_a, perform_a, set_b, perform_b);
I wonder if we want to add also the `rz_il_oplist_push()` that will allow to add the ops one by one. cc @Heersin @thestr4ng3r @ret2libc

2021-10-19 07:31 UTC, ret2libc commented on librz/analysis/p/analysis_8051.c
> +	char *regname = get_regname_bybase(buf[0], 0xE2);
where is this 0xE2 coming from?

2021-10-19 07:35 UTC, ret2libc reviewed
Few things:
1) how are we testing these conversions? As said in the past, I think we should configure a system to compare a piece of assembly code executed under the debugger and one executed with RzIL(generated from the original code) to make sure that the IL actually applies operation in the right way. Until we have such a system, these conversion will be hard/impossible to really review.
2) shall we have all these lifters somewhere else instead of p/analysis_x.c? I expect they will be quite big...

2021-10-20 07:21 UTC, XVilka commented
@ret2libc full testing can be done once whole architecture converted, then we can compare the debugger results with the emulated results of some trace.

2021-10-20 07:41 UTC, ret2libc commented
> @ret2libc full testing can be done once whole architecture converted, then we can compare the debugger results with the emulated results of some trace.

Not really necessary to convert a whole arch to start testing.

The idea is to have things like:
```
; START INSTRUCTIONS
inc eax
; END INSTRUCTIONS
```

This would be a test. You can start by converting just the `inc` instruction to make sure this test works.

Then you could have another test:
```
; START INSTRUCTIONS
mov eax, ebx
; END INSTRUCTIONS
```
And so on and so on. This way you have a very good way to develop without having to "hope" that everything will be alright at the end of the day. Until we have something like that that allows us to test pieces of assemblies, we are just blindly writing code hoping that it will work well.

I'm not saying this PR is not ok, but before we move too much forward with the IL I think testing is foundamental.

2021-10-20 07:41 UTC, ret2libc commented on librz/analysis/p/analysis_8051.c
> +	RzPVector *oplist = rz_il_make_oplist(id, 8, var_a, var_b, div, mod, set_a, perform_a, set_b, perform_b);
I think it makes sense

2021-10-20 07:42 UTC, thestr4ng3r commented on librz/analysis/p/analysis_8051.c
> +	RzILOp *int_ = rz_il_new_op(RZIL_OP_INT);
```c
static inline RzILOp *rz_il_new_op_int(ut64 /* or what the actual type is */ value, size_t length) {
    RzILOp *r = rz_il_new_op(RZIL_OP_INT);
    if (!r) {
        return NULL;
    }
    r->op.int_->value = value;
    r->op.int_->length = length;
    return r;
}
```
and add that for all op types

2021-10-20 07:44 UTC, ret2libc commented on librz/analysis/p/analysis_8051.c
> +	RzILOp *int_ = rz_il_new_op(RZIL_OP_INT);
I guess you mean to have this function for each type of il_op, right? If so, I agree with that.

So you'd have `rz_il_new_op_int`, `rz_il_new_op_logand`, `rz_il_new_op_shiftl`, `rz_il_new_op_shiftr`, etc.

2021-10-20 07:59 UTC, thestr4ng3r commented on librz/analysis/p/analysis_8051.c
> +	RzPVector *oplist = rz_il_make_oplist(id, 8, var_a, var_b, div, mod, set_a, perform_a, set_b, perform_b);
Wouldn't that be just `rz_pvector_push()`?

2021-10-20 08:00 UTC, thestr4ng3r commented on librz/analysis/p/analysis_8051.c
> +	RzILOp *int_ = rz_il_new_op(RZIL_OP_INT);
Yes. You could also compose them like `rz_il_new_op_shiftl(stuff, rz_il_new_op_int(42, 8))`.

2021-10-20 11:41 UTC, kazarmy commented
> Not really necessary to convert a whole arch to start testing.

I agree with @ret2libc that there should be a way to uplift progressively. Otherwise the uplifting of big, complex arches like x86 might become non-starters.

2021-10-26 04:23 UTC, XVilka commented on librz/analysis/p/analysis_8051.c
> +	RzPVector *oplist = rz_il_make_oplist(id, 8, var_a, var_b, div, mod, set_a, perform_a, set_b, perform_b);
Yes, but I think it would be nice to have a semantically-linked wrapper.

2021-10-26 14:59 UTC, Heersin commented on librz/analysis/p/analysis_8051.c
> +	RzILOp *int_ = rz_il_new_op(RZIL_OP_INT);
Agree, add family functions of `new_op`

2021-10-26 15:14 UTC, Heersin reviewed
LGTM. Is there any test file to check some of the instructions ?

2021-11-11 02:45 UTC, Basstorm commented on librz/analysis/p/analysis_8051.c
>  	if (mask & RZ_ANALYSIS_OP_MASK_ESIL) {
yes, will remove that when the uplifing work is done

2021-11-11 02:48 UTC, Basstorm commented on librz/analysis/p/analysis_8051.c
> +	RzILOp *int_ = rz_il_new_op(RZIL_OP_INT);
just add the family functons in this 8051? or add them into RZIL module?

2021-11-11 02:49 UTC, Basstorm commented on librz/analysis/p/analysis_8051.c
> +	char *regname = get_regname_bybase(buf[0], 0xE2);
from the Opcode table in the description of this PR.

2021-11-18 11:39 UTC, wargio commented
to test the code, please use `ao @ <offset> ~rzil` for RzIL semantic and `aezse` for execution changes.

2022-05-19 11:08 UTC, XVilka commented
@Basstorm do you have plans to finish this?

2022-06-08 13:15 UTC, XVilka commented
@imbillow assigned you, but I think it's probably better to start a new PR when you will work on it. Once you open a new one, feel free to close this.

2022-07-11 11:50 UTC, Basstorm commented
Will start a new one later.

2022-07-11 11:50 UTC, closed without merging