Add `RZ_BUILD_DEBUG` compile time definition for debug logging
rizinorg/rizin pull request #1616
Opened 2021-09-07 12:19 UTC by DMaroo

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`RZ_LOG_DEBUG` and `RZ_LOG_SILLY` are now only compiled when `RZ_BUILD_DEBUG` is set/defined.

**Test plan**

Green CI.

**Closing issues**

Closes #1612.

2021-09-07 12:19 UTC, DMaroo commented
Do I need to add tests for this?

2021-09-07 12:39 UTC, ret2libc requested changes
Instead of adding a new variable I'd suggest to use NDEBUG define.

You can do #ifdef NDEBUG and use add `default_options: ['b_ndebug=if-release']` in the `project` part of the main meson.build file.

2021-09-07 12:40 UTC, ret2libc commented
> Do I need to add tests for this?

It should not be needed. We already have several CI jobs that use both debug and release buildtypes.

2021-09-07 12:49 UTC, DMaroo commented
> Instead of adding a new variable I'd suggest to use NDEBUG define.
> 
> You can do #ifdef NDEBUG and use add `default_options: ['b_ndebug=if-release']` in the `project` part of the main meson.build file.

Since we are using our own logging functions, should we avoid using `NDEBUG`, since defining/un-defining it will affect other things as well, like assert macros? Just asking, I don't know which of the ways is preferred.

2021-09-07 13:12 UTC, ret2libc commented
> > Instead of adding a new variable I'd suggest to use NDEBUG define.
> > You can do #ifdef NDEBUG and use add `default_options: ['b_ndebug=if-release']` in the `project` part of the main meson.build file.
> 
> Since we are using our own logging functions, should we avoid using `NDEBUG`, since defining/un-defining it will affect other things as well, like assert macros? Just asking, I don't know which of the ways is preferred.

Yeah maybe you are right... We could also re-use the RZ_CHECKS_LEVEL define that we already have, which is 1 on release builds and 2 otherwise.

```
/*
 * RZ_CHECKS_LEVEL determines the behaviour of the rz_return_* set of functions.
 *
 * 0: completely disable every function and make them like no-operation
 * 1: silently enable checks. Check expressions and do return, but do not log anything
 * 2: enable checks and logging (DEFAULT)
 * 3: transform them into real assertion
 */
```
In that case, we should make RZ_LOG_DEBUG/SILLY no-op if RZ_CHECKS_LEVEL <= 1.

Or we could just use the additional define you did :D Not really so sure anymore...

@kazarmy @XVilka ?

2021-09-07 13:18 UTC, DMaroo commented
Also, since we are using `-Werror` in the Linux gcc build, therefore, errors such as `unused variable` are leading to failure (https://github.com/rizinorg/rizin/pull/1616/checks?check_run_id=3533582589). This is introduced because `RZ_DEBUG_LOG` becomes a no-op, and therefore, some of the variables are used nowhere. I think we can just do some sort of `(void)fmtstr` and same for rest of the arguments to avoid the warning.

2021-09-07 13:20 UTC, ret2libc commented
> Also, since we are using `-Werror` in the Linux gcc build, therefore, warnings such as `unused variable` are leading to failure (https://github.com/rizinorg/rizin/pull/1616/checks?check_run_id=3533582589). This is introduced because `RZ_DEBUG_LOG` becomes a no-op, and therefore, some of the variables are used nowhere. I think we can just do some sort of `(void)fmtstr` and same for rest of the arguments to avoid the warning.

Yeah that should be easily fixed. Only few cases, it seems so far.

2021-09-07 16:39 UTC, wargio reviewed
How about this way?

2021-09-07 16:39 UTC, wargio commented on librz/type/parser/c_cpp_parser.c
>  	RZ_LOG_DEBUG("File size is %" PFMT64d " bytes, read %zu bytes\n", file_size, read_bytes);
```suggestion
	RZ_LOG_DEBUG("File size is %" PFMT64d " bytes, read %zu bytes\n", rz_file_size(path), read_bytes);
```

2021-09-07 16:39 UTC, wargio commented on librz/type/parser/c_cpp_parser.c
>  	RZ_LOG_DEBUG("File size is %" PFMT64d " bytes, read %zu bytes\n", file_size, read_bytes);
```suggestion
	RZ_LOG_DEBUG("File size is %" PFMT64d " bytes, read %zu bytes\n", rz_file_size(path), read_bytes);
```

2021-09-07 17:37 UTC, ret2libc commented on meson.build
> +endif
Let's put this thing in rz_userconf.h.in and set it similar to the other variables there. That way people using the API can also see if rizin was compiled in debug mode or not.

2021-09-07 17:55 UTC, DMaroo commented on librz/type/parser/c_cpp_parser.c
>  	RZ_LOG_DEBUG("File size is %" PFMT64d " bytes, read %zu bytes\n", file_size, read_bytes);
Makes sense to me. Thanks.

2021-09-08 03:27 UTC, XVilka approved these changes

2021-09-08 03:28 UTC, XVilka commented
I think it would be worth to cherry-pick it into 0.3.0 as well, to reduce the size of the binaries (slightly).

2021-09-08 06:46 UTC, ret2libc approved these changes

2021-09-08 06:47 UTC, merged