Fixes for macOS 10.5/ppc64
rizinorg/rizin pull request #1641
Opened 2021-09-09 21:43 UTC by thestr4ng3r

2021-09-10 00:26 UTC, XVilka commented on meson.build
> +have_environ = false # cc.links(code, name: 'have extern char **environ')
This doesn't look right

2021-10-24 12:22 UTC, XVilka requested changes

2021-10-24 12:22 UTC, XVilka commented on binrz/rizin/macos_sign.sh
> +#!/bin/bash
Is this possible to do without bash? Especially, considering that later MacOS versions switched to the Zsh as the default one.

2021-10-24 12:22 UTC, XVilka commented on librz/util/sys.c
> +#if __APPLE__ && !HAVE_ENVIRON
@ret2libc please take a look, maybe it's better to move to Meson checks as well?

2021-10-24 18:35 UTC, thestr4ng3r commented on librz/util/sys.c
> +#if __APPLE__ && !HAVE_ENVIRON
Could be done I think, but `__NSGetEnviron()` is both macOS/iOS-specific and always available there so `__APPLE__` would be the right indicator without needing to check compilation.

2021-10-24 18:43 UTC, thestr4ng3r commented on binrz/rizin/macos_sign.sh
> +#!/bin/bash
The relevant part is
```
OSVER=$(uname -r)
if [ "${OSVER%%.*}" -lt 10 ]; then
```
I think this should still work with sh. At least shellcheck does not complain. So I will just have to revert the shebang.

2021-10-26 02:25 UTC, XVilka approved these changes
LGTM, but could you please send from the `dist-` branch instead? Just to be sure it doesn't break any of the existing CI builds.

2021-10-26 06:56 UTC, closed without merging