Rzil op root approach
rizinorg/rizin pull request #1658
Opened 2021-09-12 06:01 UTC by Heersin

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

1. [New IL](https://github.com/BinaryAnalysisPlatform/bap/pull/960) as an independent library which relies on `rz_util` only.
2. IL in core analysis are moved to `core/cil.c`.  (Related pr of moving esil -> #1360 )
3. Change the tech of collecting `stats` and `trace` in the old ESIL
4. Fix some bugs in the old pr #1361 #1451

**Test plan**

Should pass the old rizin tests.

**Closing issues**

closes #277 

**More Info**
0. Use tree-like approach
1. This pr created for `asan build` to detect bug.
2. Only enabled in `analysis_bf.c`. 
2. `Register arena` changes in other module (such as `debug`) are not covered in current new IL.

2021-09-12 06:44 UTC, XVilka commented
Can you please use the branch from the repository instead? To trigger more CI jobs like AppVeyor, BSD, etc?

2021-09-12 07:14 UTC, XVilka requested changes

2021-09-12 07:14 UTC, XVilka commented on librz/analysis/rzil/rzil.c
> +	if (!rzil) {
Silent cleanup

2021-09-12 07:14 UTC, XVilka commented on librz/analysis/rzil/rzil.c
> +	if (rzil) {
Reverse the condition

2021-09-12 07:14 UTC, XVilka commented on librz/analysis/rzil/rzil.c
> +		eprintf("uninitialized rzil, cannot set op\n");
`RZ_LOG_ERROR()`

2021-09-12 07:14 UTC, XVilka commented on librz/analysis/rzil/rzil_trace.c
> +	eprintf("Fail to init RZIL trace\n");
`RZ_LOG_ERROR()`

2021-09-12 07:14 UTC, XVilka commented on librz/core/cmd_analysis.c
> +			rz_core_cmd0(core, "ae?~aes");
It should print the help, not like this.

2021-09-12 07:14 UTC, XVilka commented on librz/il/definitions/bag.c
> +		printf("[Cannot Carry More Values]\n");
`RZ_LOG_ERROR()`

2021-09-13 01:53 UTC, Heersin commented
Sorry I pushed a temporary branch from my repo. I will create a real pr instead. Sorry about the noise

2021-09-13 01:55 UTC, closed without merging