Fix `toe` command
rizinorg/rizin pull request #1659
Opened 2021-09-12 06:42 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Changed the `toe` implementation to accept only one type name per call, fixed bugs.

**Test plan**

Try `toe tm` for example

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/1642

2021-09-12 07:55 UTC, thestr4ng3r commented on librz/core/ctypes.c
> +	char *tmp = rz_core_editor(core, NULL, str);
Please add the code below as an API, so we can use it in Cutter.

2021-09-12 09:01 UTC, wargio approved these changes

2021-09-12 13:30 UTC, ret2libc requested changes
Doesn't this suffer from the problem we discussed the other day? That is that if the new type is invalid, you will end up deleting the existing type?

Few solutions:
1) save the original C string representation and re-parse it in case the new one fails
2) remove the original basetype from the hashtable, but don't free it. If the new one fails you re-insert the basetype in the hashtable

2021-09-12 13:36 UTC, XVilka commented
@ret2libc it already does that: https://github.com/rizinorg/rizin/pull/1659/files#diff-9ad7c99ed0a1b70e3fd759554220a7ff325910afc935d78fb8c342387de91e81R1119

2021-09-12 16:32 UTC, thestr4ng3r commented on librz/core/ctypes.c
> +		int result = rz_type_parse_string_stateless(typedb->parser, old, &error_msg);
What about not using `rz_type_db_delete_base_type()` to delete the base type entirely, but just removing it from the hashtable without freeing to re-insert it later?
Using the `old` string means that it must be guaranteed that printing a type to C and then parsing it again will always result in exactly the original type, which I would not trust if not strictly necessary.

2021-09-13 06:57 UTC, XVilka commented
@thestr4ng3r @ret2libc added new API function:
```c
/**
 * \brief Edits the existing base type given the new C code
 *
 * Searches the base type in the types database given the \p name.
 * If it exists - parses the \p typestr as the new C type. If there is
 * any error during the parsing it restores the original type in the
 * database.
 *
 * \param typedb Type Database instance
 * \param name Name of the base type
 * \param typestr C string of the new definition of the type
 */
RZ_API bool rz_type_db_edit_base_type(RzTypeDB *typedb, RZ_NONNULL const char *name, RZ_NONNULL const char *typestr)
```

2021-09-13 09:32 UTC, thestr4ng3r approved these changes
Perfect!

2021-09-13 09:33 UTC, merged