[import] backport of some zignature commits from radare2
rizinorg/rizin pull request #1738
Opened 2021-09-23 12:52 UTC by wargio

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Backports the following commits:

- [ ] https://github.com/radareorg/radare2/commit/0a10c3f13a5fb5548d7035ef5e54d2f840424069
- [ ] https://github.com/radareorg/radare2/commit/98150ad1829df99e52a96f2ed91fe4399c1ead5c
- [ ] https://github.com/radareorg/radare2/commit/086038fecaada0a6db3c8e1c49927614204d675a
- [ ] https://github.com/radareorg/radare2/commit/74b8b3cc99f293f101a616099a728247256a8e65
- [ ] https://github.com/radareorg/radare2/commit/00e8fd12533a6a6753dcc62e95e0eae8a74dc0e4

linked to: https://github.com/rizinorg/rizin/issues/747

2021-09-23 15:42 UTC, XVilka requested changes

2021-09-23 15:42 UTC, XVilka commented on librz/include/rz_sign.h
> +	RZ_SIGN_END = '\x00', // used for sentenal value
Sentinel

2021-09-23 15:42 UTC, XVilka commented on librz/analysis/sign.c
> +	if (fmt == 'j') {
Need to be converted to the `RzOutputMode` enum after

2021-09-23 17:11 UTC, XVilka approved these changes

2021-09-23 17:30 UTC, wargio commented
`[XX] db/archos/linux-x64/dbg_oo ood check for ptrace errors` is a false positive. 100% not related to this PR

2021-09-24 07:02 UTC, ret2libc approved these changes

2021-09-24 07:03 UTC, ret2libc commented
CI was red even for windows. Let's see.

2021-09-24 07:48 UTC, wargio commented
I have no clue why this is happening.

2021-09-24 07:48 UTC, wargio commented
i will convert this to draft for now.

2021-10-13 12:25 UTC, closed without merging