Reduce registers shown in the output of `dr` and `Vpp` when analysing an ARM64 executable [WIP]
rizinorg/rizin pull request #1739
Opened 2021-09-23 13:21 UTC by DMaroo

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Avoids printing system registers when analyzing registers in an ARM64 executable. Does not completely remove other registers as well (will implement that soon), but prunes majority of unnecessary registers.

**Test plan**

Refactor existing tests according to the API changes, and write new ones once the API implementation is complete.

**Closing issues**

Closes #1716.

2021-09-27 09:22 UTC, XVilka requested changes

2021-09-27 09:22 UTC, XVilka commented on librz/reg/reg.c
> +	"gpr", "drx", "fpu", "mmx", "xmm", "ymm", "flg", "seg", "sys", "pauth", NULL
Instead of `pauth` here, I suggest more generic `"sec"`. `pauth` is too ARM and implementation specific.

2021-09-27 09:22 UTC, XVilka commented on shlr/gdb/src/gdbclient/xml.c
> +				typegroup = "pauth";
`"sec"` then too.

2021-09-27 09:31 UTC, DMaroo commented
Should I add any tests for this?

2021-09-27 09:32 UTC, XVilka commented on shlr/gdb/src/gdbclient/xml.c
> +			} else if ((tmp1 = strstr(regstr, "sec")) != NULL && tmp1 < feature_end) {
Shouldn't be `pauth` here, in the the detection?

2021-09-27 09:38 UTC, XVilka commented
You could add a dump of GDB response and add a new unit test for this. That would be a good start.

2021-09-27 16:30 UTC, XVilka approved these changes

2021-09-28 05:57 UTC, XVilka commented
I get the following warning, not important probably, just for the information:
```
[i] ℤ rizin -a arm -b 64 -d gdb://localhost:12345                                                                                                                                                                                 13:55:36 
WARNING: rz_file_exists: assertion '!RZ_STR_ISEMPTY(str)' failed (line 172)
Ignoring duplicated register definition 'DBGWVR'
Ignoring duplicated register definition 'DBGWVR'
Ignoring duplicated register definition 'DBGWCR'
Ignoring duplicated register definition 'DBGBVR'
Ignoring duplicated register definition 'DBGWCR'
Ignoring duplicated register definition 'DBGBVR'
Ignoring duplicated register definition 'DBGBCR'
Ignoring duplicated register definition 'DBGBCR'
Ignoring duplicated register definition 'DBGWVR'
Ignoring duplicated register definition 'DBGWVR'
Ignoring duplicated register definition 'DBGWCR'
Ignoring duplicated register definition 'DBGBVR'
Ignoring duplicated register definition 'DBGWCR'
Ignoring duplicated register definition 'DBGBVR'
Ignoring duplicated register definition 'DBGBCR'
Ignoring duplicated register definition 'DBGBCR'
= attach 1 984639
```

2021-09-28 05:59 UTC, DMaroo commented
Yes. I also encountered these warnings. Looks like a register is being re-parsed. I'll have a look and fix it if possible without breaking other stuff.

2021-09-28 15:28 UTC, yossizap approved these changes

2021-09-28 15:49 UTC, merged