Convert `ec` to newshell
rizinorg/rizin pull request #1809
Opened 2021-10-08 09:40 UTC by officialcjunior

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Converts `ec` and its tree of commands to RzShell.

**Test plan**

- [ ] Check the implementation and fix the broken tests, if any.

**Closing issues**

Partially addresses #1676

2021-10-09 05:16 UTC, XVilka commented
Missing also the `echo` command.

2021-10-11 07:57 UTC, ret2libc reviewed
go ahead and also remove the old handlers for `ec`! ;)

2021-10-11 07:57 UTC, ret2libc commented on librz/core/cmd_descs/cmd_eval.yaml
> +            optional: true
actually I'd move this directly under `e` instead of under `ec`.

2021-10-11 07:57 UTC, ret2libc commented on librz/core/cmd_descs/cmd_eval.yaml
> +            args: [ ]
we use `[]` usually, not `[ ]`

2021-10-11 07:57 UTC, ret2libc commented on librz/core/cmd_descs/cmd_eval.yaml
> +            args: [ ]
replace this everywhere in your additions.

2021-10-11 07:57 UTC, ret2libc commented on librz/core/cmd_eval.c
> +
```suggestion
```

2021-10-11 07:57 UTC, ret2libc commented on librz/core/cmd_descs/cmd_eval.yaml
> +            optional: true
i'd remove the `optional` field and add `flags: RZ_CMD_ARG_FLAG_ARRAY`.

2021-10-11 07:57 UTC, ret2libc commented on librz/core/cmd_eval.c
> +		if (input) {
I would remove completely the rz_core_echo function (it does not seem to be used anywhere). For the `rz_cmd_echo_handler` function, just `rz_str_array_join` and print the resulting string.

2021-10-11 07:57 UTC, ret2libc commented on librz/core/cmd_eval.c
> +		return RZ_CMD_STATUS_OK;
```suggestion
		if (!rz_cons_pal_set(argv[1], argv[2])) {
			return RZ_CMD_STATUS_ERROR;
		}
		rz_cons_pal_update_event();
		return RZ_CMD_STATUS_OK;
```

2021-10-11 07:57 UTC, ret2libc commented on librz/core/cmd_eval.c
> +	color_code = rz_cons_pal_parse(dup, NULL);
```suggestion
	char *color_code = rz_cons_pal_parse(dup, NULL);
```

2021-10-14 09:08 UTC, officialcjunior commented
```bash
echo foo = "\x33\x44\x88" | rz-ax -F
```
This is the test that fails now. I'm starting to wonder whether this should be possible in newshell.

2021-10-14 09:21 UTC, ret2libc commented
> ```shell
> echo foo = "\x33\x44\x88" | rz-ax -F
> ```
> 
> This is the test that fails now. I'm starting to wonder whether this should be possible in newshell.

Use:
```shell
echo foo = '"\x33\x44\x88"' | rz-ax -F
```
Apparently `rz-ax` wants the `"`. Given that rzshell works similarly to other shells like bash, doing `"hello world"` just prints `hello world`. If you really want to include the quotes, you have to double quote the string with `'"hello world"'`

2021-10-17 09:39 UTC, officialcjunior commented
`rz_cons_pal_list()` has a lot of stuff going on. It handles a JSON mode as well as in other printing things. Would working on the PJ be the the best place to begin?

2021-10-18 08:01 UTC, ret2libc commented
> `rz_cons_pal_list()` has a lot of stuff going on. It handles a JSON mode as well as in other printing things. Would working on the PJ be the the best place to begin?

Yeah, I'd say so. However, if this PR already works well I'm ok to first merge this and then do the refactoring for rz_cons_pal_list in a separate PR. Is that ok with you? Is this PR ready for merging in your opinion?

2021-10-20 05:27 UTC, officialcjunior commented
> > rz_cons_pal_list() has a lot of stuff going on. It handles a JSON mode as well as in other printing things. Would working on the PJ be the the best place to begin?
> 
> Yeah, I'd say so. However, if this PR already works well I'm ok to first merge this and then do the refactoring for rz_cons_pal_list in a separate PR. Is that ok with you? Is this PR ready for merging in your opinion?

Yes, I think it's ready to merge, as well. 👍🏽 Will do the refactoring on another one.

2021-10-20 05:31 UTC, XVilka requested changes

2021-10-20 05:31 UTC, XVilka commented on librz/core/cmd/cmd_eval.c
> +		rz_core_load_theme(core, argv[1]);
Please check the result of `rz_core_load_theme()` and return using the function `bool2status()`

2021-10-20 05:31 UTC, XVilka commented on librz/core/cmd/cmd_eval.c
> +		rz_core_theme_nextpal(core, 'j');
I also suggest to refactor the `rz_core_theme_nextpal()` to use `rz_core_list_themes()` and proper output modes. Moreover, `'n`' and `'p'` modes probably should be extracted in separate function[s]. In function `rz_eval_color()` for the JSON mode it's better to use the better name like `rz_core_themes_print()` and use also `rz_core_list_themes()` API and `RzOutputMode` enum.

2021-10-20 07:44 UTC, ret2libc commented on librz/core/cmd/cmd_eval.c
> +
```suggestion
```

2021-10-20 07:46 UTC, ret2libc commented on librz/core/cmd/cmd_eval.c
> +		rz_core_theme_nextpal(core, 'j');
For next refactoring I'd say, to keep this not too big and move it forward.

2021-10-20 10:20 UTC, officialcjunior commented on librz/core/cmd/cmd_eval.c
> +		rz_core_load_theme(core, argv[1]);
I can't seem to call `bool2status()` from `cmd_eval.c` due to the implicit declaration error since `cmd_info.c` isn't compiled before `cmd_eval.c`, I think.
How should get around that? Maybe we can declare it somewhere?
 
Meanwhile, I was wondering about such a workaround:
```suggestion
		bool res = rz_core_load_theme(core, argv[1]);
		return res ? RZ_CMD_STATUS_OK : RZ_CMD_STATUS_ERROR;
```

2021-10-20 10:22 UTC, XVilka commented on librz/core/cmd/cmd_eval.c
> +		rz_core_load_theme(core, argv[1]);
@ret2libc maybe make `bool2status()` an `RZ_IPI`?

2021-10-20 10:31 UTC, ret2libc commented on librz/core/cmd/cmd_eval.c
> +		rz_core_load_theme(core, argv[1]);
i suggest to just re-define it in your file. Hopefully the compiler will just compile everything away as it is a very basic typing thing. Moving it to RZ_IPI would probably prevent such optimizations.

2021-10-21 05:11 UTC, XVilka approved these changes
OK as is, but would be nice to continue the refactoring of these functions.

2021-10-21 07:18 UTC, ret2libc approved these changes

2021-10-21 07:27 UTC, ret2libc requested changes
```
[0x00006b60]> ecHj
ecHi rgb:00007f @ 0x00006b60
[0x00006b60]> ecH*
ecHi rgb:00007f @ 0x00006b60
```

`ecHj` should print json, `ecH*` rizin commands. This was working before AFAIK.

2021-10-22 04:22 UTC, XVilka approved these changes

2021-10-22 05:33 UTC, merged

2021-10-22 05:44 UTC, officialcjunior commented on librz/core/cmd/cmd_eval.c
> +		rz_core_theme_nextpal(core, 'j');
I've added this on the end of the bullet list at #1676