Remove global state from RzCons dietline
rizinorg/rizin pull request #1826
Opened 2021-10-12 10:03 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Remove global state from dietline.

**Test plan**

Try to use `yank` actions in various modes in the Rizin command line.

See commands in https://book.rizin.re/basic_commands/dietline.html
In particular, commands like `Ctrl-k`, `Ctrl-w`, `Ctrl-y` in Emacs mode and `dw`, `d$`, `p` in the Vi mode.

**Closing issues**

Partially addresses https://github.com/rizinorg/rizin/issues/276

2021-10-12 10:10 UTC, wargio approved these changes

2021-10-13 07:51 UTC, ret2libc requested changes

2021-10-13 07:51 UTC, ret2libc commented on librz/cons/dietline.c
> +static void paste(bool enable_yank_pop) {
in this function `enable_yank_pop` is set to true, but by moving it as an argument, the change to the variable is lost at the end of the function.

2021-10-13 09:29 UTC, XVilka commented on librz/cons/dietline.c
> +static void paste(bool enable_yank_pop) {
Good catch, now I pass pointers everywhere instead!

2021-10-13 09:32 UTC, ret2libc approved these changes

2021-10-13 12:40 UTC, ret2libc reviewed
Only one thing... maybe the property shall go in RzCons?

2021-10-13 14:02 UTC, XVilka commented
@ret2libc I thought about that, it's unclear where it should exactly go - RzCons structure already has too many parameters, there are two contexts - global and input ones. Maybe we should introduce a new context?

2021-10-13 14:20 UTC, ret2libc commented
> @ret2libc I thought about that, it's unclear where it should exactly go - RzCons structure already has too many parameters, there are two contexts - global and input ones. Maybe we should introduce a new context?

I have no idea eheh i'm not that familiar with the rzcons module to know that. I'm ok with this approach for now until someone has the time/will to really review the whole module.

2021-10-14 07:31 UTC, ret2libc approved these changes
OK. CTRL-w/CTRL-y seem a bit broken anyway, but it's unrelated to your changes.

2021-10-29 07:16 UTC, merged