Fix a crash during variables type propagation
rizinorg/rizin pull request #1829
Opened 2021-10-12 14:23 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Clone the variables vector before retyping it, since retyping might trigger overlapping var deletion in case of the new type is big enough to overshadow the next variables.

**Test plan**

CI is green

2021-10-12 14:33 UTC, wargio approved these changes

2021-10-13 07:49 UTC, ret2libc requested changes

2021-10-13 07:49 UTC, ret2libc commented on librz/core/analysis_tp.c
> +	RzPVector *cloned_vars = (RzPVector *)rz_vector_clone((RzVector *)&fcn->vars);
the _clone method just duplicates the pointers, not the content, so even if the variables are deleted you are going to access anyway freed memory, I think.

2022-01-24 09:58 UTC, XVilka commented
Closed in favor of https://github.com/rizinorg/rizin/pull/2222

2022-01-24 09:58 UTC, closed without merging