Add files required to build packages for OBS
rizinorg/rizin pull request #1853
Opened 2021-10-18 14:07 UTC by ret2libc

These files will be used by https://build.opensuse.org/package/show/home:RizinOrg/rizin to build the Rizin package for the various systems/architectures.

2021-10-18 14:27 UTC, XVilka requested changes

2021-10-18 14:27 UTC, XVilka commented on dist/deb/README.md
> +This files are mainly created to support the [Open Build
"This file", also no line split of the URL please.

2021-10-18 14:27 UTC, XVilka commented on dist/deb/debian-10-patch-meson.patch
> ++++ rizin-v0.3.0.new/librz/analysis/d/meson.build	2021-10-08 16:57:14.563122846 +0200
Is this patch necessary? Why not just support starting from the Debian 11?

2021-10-18 14:27 UTC, XVilka commented on dist/deb/debian.compat
> +13
What does this mean? AFAIK there is no Debian 13 yet.

2021-10-18 14:27 UTC, XVilka commented on dist/deb/debian.changelog
> +  * First import from parrot of the debian package
I guess Parrot here should start from the capital letter.

2021-10-18 14:27 UTC, XVilka commented on dist/deb/debian.control
> +Standards-Version: 4.5.1
Where this is from?

2021-10-18 14:27 UTC, XVilka commented on dist/deb/debian.rules
> +#override_dh_install:
Maybe remove those since commented out?

2021-10-18 14:27 UTC, XVilka commented on dist/deb/rizin-Debian_10.dsc
> +Standards-Version: 4.5.1
Same

2021-10-18 14:27 UTC, XVilka commented on dist/deb/rizin-xUbuntu_20.04.dsc
> +Standards-Version: 4.5.1
Same

2021-10-18 14:27 UTC, XVilka commented on dist/rpm/rizin.spec
> +# shlr/java - Apache 2.0
I think it was removed.

2021-10-18 14:27 UTC, XVilka commented on dist/rpm/rizin.spec
> +# shlr/lz4 - 3 clause BSD (system installed shared lz4 is used instead)
Same.

2021-10-18 14:27 UTC, XVilka commented on dist/rpm/rizin.spec
> +# shlr/spp - MIT
Duplicate item.

2021-10-18 15:20 UTC, ret2libc commented on dist/deb/rizin-Debian_10.dsc
> +Standards-Version: 4.5.1
please don't ask... :D i don't know, but I know it works eheh

2021-10-18 15:20 UTC, ret2libc commented on dist/deb/rizin-xUbuntu_20.04.dsc
> +Standards-Version: 4.5.1
same as before, don't ask :D

2021-10-18 15:20 UTC, ret2libc commented on dist/deb/debian.control
> +Standards-Version: 4.5.1
same as before, don't ask :D

2021-10-18 15:21 UTC, ret2libc commented on dist/deb/debian.compat
> +13
i've spent quite some time on this number, it's some debian stuff for packaging, not the debian version. it works ;)

2021-10-18 15:22 UTC, ret2libc commented on dist/deb/debian-10-patch-meson.patch
> ++++ rizin-v0.3.0.new/librz/analysis/d/meson.build	2021-10-08 16:57:14.563122846 +0200
well, we could avoid this but we would not have packages for older ubuntu (20.04/20.10) and debian(10) so i think it's better to keep it at least for now or until it becomes too messy to maintain.

2021-10-19 07:24 UTC, XVilka requested changes

2021-10-19 07:24 UTC, XVilka commented on dist/deb/README.md
> +These files are mainly created to support the [Open Build
Please don't split these lines.

2021-10-19 07:24 UTC, XVilka commented on dist/deb/debian.rules
> +#EXTRA_FLAGS+= -Duse_sys_libzip_openssl=auto
If it's not used - maybe remove it?

2021-10-19 07:24 UTC, XVilka commented on dist/rpm/rizin.spec
> +
Unnecessary empty lines?

2021-10-19 07:24 UTC, XVilka commented on dist/deb/debian.rules
> +# kfreebsd and hurd are not supported
I think kFreeBSD could be supported, actually - we have debugger working on FreeBSD, NetBSD, OpenBSD, likely it will work out of the box.

2021-10-19 07:24 UTC, XVilka commented
I am not sure we should target 0.3.0 for the OBS - it's probably better to setup it starting from the 0.4.0.

2021-10-19 09:09 UTC, wargio commented on dist/rpm/rizin.spec
>  # shlr/sdb/src - MIT
can't we remove these comments since we have reuse? so we do not have even to maintain them

2021-10-19 09:16 UTC, ret2libc commented on dist/deb/README.md
> +These files are mainly created to support the [Open Build
why?

2021-10-19 09:17 UTC, ret2libc commented
> I am not sure we should target 0.3.0 for the OBS - it's probably better to setup it starting from the 0.4.0.

I can configure just manual files for 0.3.0 in OBS, so we start to have it and we can have it fully working for 0.4.0.

2021-10-19 09:17 UTC, XVilka commented on dist/deb/README.md
> +These files are mainly created to support the [Open Build
Splitting the link is a bad idea.

2021-10-19 09:18 UTC, ret2libc commented on dist/deb/README.md
> +These files are mainly created to support the [Open Build
it's not the link, it's the text of the link

2021-10-19 09:21 UTC, ret2libc commented
> > I am not sure we should target 0.3.0 for the OBS - it's probably better to setup it starting from the 0.4.0.
> 
> I can configure just manual files for 0.3.0 in OBS, so we start to have it and we can have it fully working for 0.4.0.

By "manual files" i mean that i put the .spec and .dsc files directly in OBS. I've already tested that it works well.

2021-10-19 09:21 UTC, XVilka commented on dist/deb/README.md
> +These files are mainly created to support the [Open Build
Text of the link is the integral part of the link.

2021-10-19 09:22 UTC, ret2libc commented
With following releases and with the right configuration in place on OBS, a new tag here should trigger a rebuild on OBS that uses the .spec/.dsc files from this repo, automatically providing an update for the rizin package to those using the repositories.

2021-10-19 09:30 UTC, XVilka approved these changes
Once Debian 12 is out, we remove these awful patches, OK?

2021-10-19 13:42 UTC, merged