RzShell: tmp statements autocompletion (@, @a:, @b:, @f, etc.)
rizinorg/rizin pull request #1861
Opened 2021-10-20 11:23 UTC by ret2libc

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Adds autocompletion for all relevant temporary modifiers listed in `@`, except `@o:` (will do after converting `o` as well and once i'm more familiar with the API).

Major change coming with this PR: `@` needs a space after it, otherwise it won't work. WDYT?

- next: `@@`

**Test plan**

Play with the shell with `e cfg.oldshell.autocompletion=false` and try to do things like `pd 1@<TAB>`, `pd 1 @a<TAB>`, `pd 1 @ <TAB>`, `pd 1 @a:<TAB>`, `pd 1 @a:x86:<TAB>`, etc.

**Closing issues**

Closes #1807 
Partially address #1808

2021-10-20 11:28 UTC, XVilka requested changes

2021-10-20 11:28 UTC, XVilka commented on librz/core/cautocmpl.c
> +		"@ ",
Is it possible not to hardcode them somehow?

2021-10-20 11:28 UTC, XVilka commented on librz/core/cautocmpl.c
> +			if (i & bits) {
Condense this please

2021-10-20 11:28 UTC, XVilka commented on librz/core/cmd_descs/cmd_descs.c
> +	{ .text = "<cmd> @ ", .arg_str = "<addr>", .comment = "Temporary seek to <addr>" },
Why this space is necessary?

2021-10-20 12:53 UTC, ret2libc commented on librz/core/cautocmpl.c
> +		"@ ",
I can put them in a #define or something similar, but I can't discover these automatically because they are part of the grammar itself :(

2021-10-20 12:54 UTC, ret2libc commented on librz/core/cmd_descs/cmd_descs.c
> +	{ .text = "<cmd> @ ", .arg_str = "<addr>", .comment = "Temporary seek to <addr>" },
`@..` is actually just `@ <addr>` where `<addr>` starts with `..`.

2021-10-20 17:39 UTC, XVilka requested changes
All tests with `@bla` are broken (370 XX)

2021-10-22 05:22 UTC, XVilka commented
There are similar fixes required in other subdirectories of `test/db`:
```
 [**]                  db/archos/linux-x64/dbg_cont_back    14174 OK       975 BR      284 XX       27 FX
```

2021-10-25 14:38 UTC, XVilka approved these changes
We should force to have a space *before* the `@` as well, I think. But that's for later or for up for discussion.

2021-10-27 07:31 UTC, merged