Port shell commands to new shell
rizinorg/rizin pull request #1875
Opened 2021-10-22 08:41 UTC by DMaroo

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

It would be nice to finish this before porting `c` commands (#1854).

Commands to port:
 - [x] uniq
 - [x] uname
 - [x] ls
 - [x] rm
 - [x] env
 - [x] exit
 - [x] sleep
 - [x] cd
 - [x] cat
 - [x] cp
 - [x] mv
 - [x] echo
 - [x] mkdir
 - [x] pwd
 - [x] sort
 - [x] clear
 - [x] cls

Please add any missing commands to the above list.

**Test plan**

Green CI. Will add tests if I find that the commands are untested.

**Closing issues**

Closes #1840.

2021-10-22 09:49 UTC, XVilka commented
@ret2libc We should also think when to show the help screen for these commands.

2021-10-22 09:55 UTC, DMaroo commented
> @ret2libc We should also think when to show the help screen for these commands.

For now, there is an entry `shell` in the root commands. Using `shell?` shows the help for these commands.

2021-10-22 10:47 UTC, XVilka requested changes

2021-10-22 10:47 UTC, XVilka commented on librz/util/sys.c
>  RZ_API bool rz_sys_chdir(const char *s) {
Maybe add `RZ_NONNULL const char *s` here and in the header too?

2021-10-22 11:55 UTC, DMaroo commented
Please add any missing commands in the task list.

2021-10-22 12:19 UTC, XVilka requested changes

2021-10-22 12:19 UTC, XVilka commented on librz/core/cmd_descs/cmd_shell.yaml
> +  - name: cp.
This is the weird command and not sure if really needed. Could be emulated with `cp $f $f.ext`, for example, while remove `$f` and substitute it with `$jf` instead. Moreover, it's not entirely correct since multiple different files can be loaded at the same time.

2021-10-22 12:19 UTC, XVilka commented on librz/util/syscmd.c
>  	if (file) {
Just convert this into `if (!file) return`. Even better just do not allow `file` being NULL, add `RZ_NONNULL` and `rz_return_val_if_fail()`

2021-10-22 12:19 UTC, XVilka commented on librz/util/syscmd.c
> +RZ_API RZ_OWN char *rz_syscmd_sort(const char *file) {
Same with this, add `RZ_NONNULL`, etc

2021-10-22 12:19 UTC, XVilka commented on librz/include/rz_util/rz_sys.h
> +RZ_API RZ_OWN char *rz_syscmd_uniq(const char *file);
Add `RZ_NONNULL` whenever appropriate to those filenames.

2021-10-22 12:33 UTC, DMaroo commented on librz/core/cmd_descs/cmd_shell.yaml
> +  - name: cp.
Agreed. I'll remove it.

2021-10-22 14:43 UTC, XVilka commented
```
cd `e dir.tmp`
-- stderr
Wrong number of arguments passed to `cd`, see its help with `cd?`
Usage: cd <dir>   # Change directory to <dir>

mkdir .tmp
+Usage: mkdir [-p] [directory]

-- stderr
WARNING: rz_str_trim_head_ro: assertion 'str' failed (line 87)
cp: cannot create regular file '.tmp/strenc-bin': No such file or directory
ERROR: Failed to copy bins/elf/analysis/x86-helloworld-gcc to .tmp/strenc-bin

[XX] db/cmd/project load with file using saved absolute file path after project file was moved
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e cfg.oldshell=false
e asm.bytes=true
f i_do_hope_that_no_entity_knocks_over_my_beverage @ 0x080483d8
Ps .tmp_load_move_project.rzdb
o--
mkdir -p .tmp_load_move_project
mv .tmp_load_move_project.rzdb .tmp_load_move_project/
cd .tmp_load_move_project
Po .tmp_load_move_project.rzdb
rm .tmp_load_move_project.rzdb
cd ..
rm .tmp_load_move_project
pdi 3 @ 0x080483d8
' bins/elf/crackme0x05
-- stdout
--- expected
+++ actual
@@ -1,4 +1,3 @@
-0x080483d8   i_do_hope_that_no_entity_knocks_over_my_beverage:
-0x080483d8                   50  push eax
-0x080483d9                   54  push esp
-0x080483da                   52  push edx
+0x080483d8                   ff  invalid
+0x080483d9                   ff  invalid
+0x080483da                   ff  invalid

-- stderr
All core files, io, analysis and flags info purged.
mv: cannot stat 'mv': No such file or directory
Failed to load project: file access error
  failed to read database file
```

2021-10-22 14:51 UTC, DMaroo commented
`e dir.tmp` seems to return an empty string on my machine. So the error makes sense. But the question is how the test was passing before.

2021-10-24 02:29 UTC, XVilka commented
```
[XX] db/formats/le cdogs.exe relocations
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'ir > $relocs
cat $relocs~?
cat $relocs~0x00010~?
cat $relocs~0x00011~?
cat $relocs~0x00012~?
cat $relocs~0x00013~?
cat $relocs~0x00014~?
cat $relocs~0x00015~
...

-- stderr
No such file or directory
No such file or directory
No such file or directory
No such file or directory
No such file or directory
```

2021-10-24 08:06 UTC, XVilka approved these changes

2021-10-25 08:33 UTC, ret2libc commented on librz/core/cmd/cmd_shell.c
> +	free(arg);
move this before the `if (!res)` above, otherwise it may leak.

2021-10-25 08:33 UTC, ret2libc commented on librz/core/cmd/cmd_shell.c
> +	}
Can we remove this? @XVilka ?

2021-10-25 08:36 UTC, XVilka commented on librz/core/cmd/cmd_shell.c
> +	}
@ret2libc I think without this it was breaking `cat $relocs` testcases.

2021-10-25 11:26 UTC, DMaroo commented on librz/core/cmd/cmd_shell.c
> +	}
Yes. Alias substitution is not working, so I need to hard code it in `cat`.

2021-10-25 11:28 UTC, ret2libc commented on librz/core/cmd/cmd_shell.c
> +	}
do we really care about `cat $relocs` testcases?

2021-10-25 11:42 UTC, DMaroo commented on librz/core/cmd/cmd_shell.c
> +	}
I think this can be removed once the shell command parser substitutes all the aliases on it's own. Removing it prematurely is a reverse compatibility breaking change.

2021-10-25 13:38 UTC, ret2libc commented on librz/core/cmd/cmd_shell.c
> +	}
Do we know where aliases are accepted apart from `cat` command? I think many/most other commands do not work well with aliases, am I wrong?

2021-10-25 13:54 UTC, DMaroo commented on librz/core/cmd/cmd_shell.c
> +	}
Oh. That I don't know. Maybe that is the case. So, should I remove this?

2021-10-25 14:25 UTC, ret2libc commented on librz/core/cmd/cmd_shell.c
> +	}
@XVilka WDYT?

2021-10-25 14:33 UTC, XVilka commented on librz/core/cmd/cmd_shell.c
> +	}
@ret2libc I suggest to keep this as is, at least until we port aliases to the newshell first. Step by step.

2021-10-25 14:43 UTC, XVilka commented
@DMaroo please resolve conflicts

2021-10-25 15:54 UTC, XVilka approved these changes

2021-10-26 04:04 UTC, merged