Refactor APIs related to themes and remove global variables from `cmd_eval`
rizinorg/rizin pull request #1879
Opened 2021-10-23 05:28 UTC by officialcjunior

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Current status:
* Refactored `rz_core_theme_nextpal()` to use `rz_core_list_themes()`
* Used PJ for `ecoj`
*  Added tests for `ecp`, `ecn` and `ecoj`
* Remove all global values from `cmd_eval.c`.
      - Added `curtheme` into `RzCore` which points to the current name of the theme.
* Sorts the themes according to the name so that it shows up the same way on all platforms.
* This part from the linked issue: `In function rz_eval_color() for the JSON mode it's better to use the better name like rz_core_themes_print() and use also rz_core_list_themes() API and RzOutputMode enum`
* Renames the APIs related to the themes to follow a standard nomenclature.
```
RZ_API RzList *rz_core_theme_list(RzCore *core);
RZ_API char *rz_core_theme_get(void);
RZ_API bool rz_core_theme_load(RzCore *core, const char *name);
RZ_API void rz_core_theme_nextpal(RzCore *core, RzConsPalSeekMode mode);
```

**Test plan**

- [x] CI passes

**Closing issues**

Partially address #1676

2021-10-24 02:37 UTC, XVilka requested changes

2021-10-24 02:37 UTC, XVilka commented on librz/core/cmd/cmd_eval.c
> +	files = rz_core_list_themes(core);
Just move definition here: `RzList *files = ...`

2021-10-24 02:37 UTC, XVilka commented on librz/core/cmd/cmd_eval.c
> +	case RZ_OUTPUT_MODE_JSON: {
Maybe makes sense to port this command to use `RzCmdStateOutput` then and just use `state.pj`?

2021-10-24 02:37 UTC, XVilka commented on librz/core/cmd/cmd_eval.c
> +		themes_list = rz_core_list_themes(core);
Check for NULL here please

2021-10-24 09:52 UTC, officialcjunior commented on librz/core/cmd/cmd_eval.c
> +		themes_list = rz_core_list_themes(core);
Sure. Should I `break;` or return `RZ_CMD_STATUS_ERROR`?

2021-10-24 10:17 UTC, officialcjunior commented on librz/core/cmd/cmd_eval.c
> +	case RZ_OUTPUT_MODE_JSON: {
Yeah, I'll do that.

2021-10-24 12:07 UTC, XVilka commented on librz/core/cmd/cmd_eval.c
> +		themes_list = rz_core_list_themes(core);
ERROR, I think

2021-10-25 06:45 UTC, officialcjunior commented
https://github.com/rizinorg/rizin/pull/1809#discussion_r732423844
> In function rz_eval_color() for the JSON mode it's better to use the better name like rz_core_themes_print() and use also rz_core_list_themes() API and RzOutputMode enum.

This part is now covered, right? I'm a bit confused with which function exactly did you mean by `rz_eval_color()`

2021-10-25 06:50 UTC, XVilka commented
@officialcjunior yes, it's covered now. It was refering to the `rz_eval_color()` before your previous refactoring.

2021-10-25 06:55 UTC, XVilka commented
@officialcjunior I was suggesting to split ` nextpal_item()` function to the one that returns next/previous palette, and printing logic:
```
switch (mode) {
	case 'j': // json
		rz_cons_printf("%s\"%s\"", ctr ? "," : "", fn);
		break;
	case 'l': // list
		rz_cons_println(fn);
		break;
```
Remove these from the `nextpal_item()`. I also suggest to rename it to `pal_seek()` and a special enum - `RzConsPalSeekMode` with `RZ_CONS_PAL_SEEK_PREVIOUS` and `RZ_CONS_PAL_SEEK_NEXT` members.
And switch `mode` type to this enum. For printing another function should be used.

2021-10-25 07:52 UTC, ret2libc commented
I think it should be `rz_core_themes_list` instead of `rz_core_list_themes`.

2021-10-25 07:52 UTC, ret2libc reviewed
Is it possible to remove the global `curtheme` as part of this PR?

2021-10-26 06:34 UTC, officialcjunior commented
> I think it should be `rz_core_themes_list` instead of `rz_core_list_themes`.

So, I was looking into all the API related to the themes:
```bash
RZ_API RzList *rz_core_list_themes(RzCore *core);
RZ_API char *rz_core_get_theme(void);
RZ_API bool rz_core_load_theme(RzCore *core, const char *name);
RZ_API void rz_core_theme_nextpal(RzCore *core, RzConsPalSeekMode mode);
```

Well, the word 'theme' seem to be at different places in the names of the APIs related to it.
Which way should we stick to?

2021-10-26 06:44 UTC, officialcjunior commented
> Is it possible to remove the global `curtheme` as part of this PR?

Yeah, there's also `getNext`, which is also global. I am assuming that we can eliminate that with by changing the logic.
But, I'm not sure about `curtheme`. Can we put in inside some thing and pass it around? How do you think we should do this?

2021-10-26 06:52 UTC, XVilka commented
I suggest to rename them all:
```c
RZ_API RzList *rz_core_theme_list(RzCore *core);
RZ_API char *rz_core_theme_get(void);
RZ_API bool rz_core_theme_load(RzCore *core, const char *name);
RZ_API void rz_core_theme_nextpal(RzCore *core, RzConsPalSeekMode mode);
```
Regarding the `curtheme`, it's either for `RzCore` or for `RzCons`. @ret2libc what do you think?

2021-10-27 07:21 UTC, ret2libc commented
> I suggest to rename them all:
> 
> ```c
> RZ_API RzList *rz_core_theme_list(RzCore *core);
> RZ_API char *rz_core_theme_get(void);
> RZ_API bool rz_core_theme_load(RzCore *core, const char *name);
> RZ_API void rz_core_theme_nextpal(RzCore *core, RzConsPalSeekMode mode);
> ```
> 
> Regarding the `curtheme`, it's either for `RzCore` or for `RzCons`. @ret2libc what do you think?

RzCore for now.

`rz_core_theme_get` will probably need to have `RzCore` as arg.

2021-10-27 09:17 UTC, XVilka commented
Please rebase, since I did some changes in the same code recently, note the changes as well: https://github.com/rizinorg/rizin/commit/91ef6da7adc2559d9a96f01f2145b437b04b9d4a

2021-10-28 06:46 UTC, XVilka approved these changes
Looks good now. Please fix the tests and this could be merged, IMHO.

2021-10-28 07:08 UTC, officialcjunior commented
On Linux and macOS, the order of the themes are different for some reason I didn't get time to look into. That makes `ecn` and `ecp` load a different theme on the different OSes even if we have currently selected the same theme. And the tests succeed in Linux because I had used Linux for developing this and added its output.

https://github.com/rizinorg/rizin/runs/4031176426?check_suite_focus=true#step:16:584

2021-10-28 08:01 UTC, ret2libc commented on librz/core/cmd/cmd_eval.c
> +	switch (state->mode) {
Get the list of themes outside the `switch` and put the switch inside the loop instead of doing the same things 3 times.

That is:
```C
themes_list = rz_core_theme_list(core);
if (!themes_list) {
...
}
rz_list_foreach (themes_list, th_iter, th) {
   switch (mode) {
   case RZ_OUTPUT_MODE_STANDARD:
      ....
      ....
  }
}
```

2021-10-28 08:01 UTC, ret2libc reviewed
I guess the removal of global `curtheme` will be done another time, right?

2021-10-29 04:48 UTC, officialcjunior commented on librz/core/cmd/cmd_eval.c
> +	switch (state->mode) {
Great catch. I hope that the fix is alright now.

2021-10-29 05:29 UTC, XVilka approved these changes

2021-10-29 05:47 UTC, XVilka commented
@officialcjunior I think it might be related that these lists are unsorted. I recommend to sort list on loading themes, this will ensure the same order on all systems.

2021-10-29 05:48 UTC, officialcjunior commented
> @officialcjunior I think it might be related that these lists are unsorted. I recommend to sort list on loading themes, this will ensure the same order on all systems.

Yes. I've had the same idea. I am looking into it. :+1

2021-10-29 07:35 UTC, ret2libc commented on librz/core/cmd/cmd_eval.c
> +	rz_list_sort(list, cmpthemes);
just use `strcmp` directly with a cast, if necessary.

2021-10-29 08:53 UTC, ret2libc approved these changes

2021-10-29 12:25 UTC, merged