Add simple POST-command and changed upload path (##remote)
rizinorg/rizin pull request #1897
Opened 2021-10-28 11:10 UTC by ogre2007

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (test plan)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (will do after rz-pipe pr)

**Detailed description**

remote files can be uploaded now via /upload/<filename>, because root of the POST request path (/<filename>) shoud not be used for this
commands now can be transmitted via POST body, because its not good to transmit special characters via URI path (allows pipelinig, etc.)
should be enough to update rz-pipe in order to enable remote analysis

**Test plan**

start rizin as an HTTP-service:
`rizin -q -e http.port=8080 -e http.root=$(pwd) -e http.upload=1 -e http.uproot=$(pwd) -cRh`
upload file as "temp":
`curl -si http://localhost:8080/upload/temp -F upload=@/bin/true`
analyze uploaded file:
`curl -si http://localhost:8080/cmd/ -d "o temp;pd  @ main;o-*"`
and see the result.
**Closing issues**

idk

2021-10-29 01:55 UTC, XVilka commented
Please add a test

2021-10-29 03:48 UTC, XVilka requested changes

2021-10-29 03:48 UTC, XVilka commented on librz/core/rtr_http.c
> +			if (!strncmp(rs->path, "/upload/", 8)) {
While you are on it, I wonder if you are willing to also split this giant function into multiple. Something like router + handlers style.

2021-10-29 06:42 UTC, XVilka commented
You need also to run it as part of the rz-test, see e.g. `test/db/cmd/cmd_pipe`. Please also run `black` on this Python file.

2021-10-29 07:34 UTC, ret2libc requested changes
Blocking this to discuss further:

why do we need this? Isn't it the same as moving the file with `nc` or with some other ways?

2021-10-29 08:04 UTC, XVilka commented
@ret2libc I think the idea is to allow the upload file to the remotely opened Rizin session.

2021-10-29 09:02 UTC, ogre2007 commented
> Blocking this to discuss further:
> 
> why do we need this? Isn't it the same as moving the file with `nc` or with some other ways?

The idea behind this is to allow uploading data (via rz-pipe with further changes, for example), and analyze it. However, this functions already were in r2/rizin, I've just refactored them a little now and added a feature that allows transmitting command not over GET-request path, but in POST-request body, which is more handy.

2021-10-29 09:05 UTC, ret2libc commented
> I've just refactored them a little now and added a feature that allows transmitting command not over GET-request path, but in POST-request body, which is more handy.

This seems better indeed, thanks for that!

> I think the idea is to allow the upload file to the remotely opened Rizin session.

@XVilka what's the difference with doing a separate `nc`(or something) to upload the binary and then analyzing it? You are assuming anyway that on the test machine there is a way to send a POST request to a remote server.

2021-11-01 11:06 UTC, XVilka commented
You need to install them first:
```
[XX] db/cmd/cmd_http_post http-post-cmd
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!python3 scripts/http_post_cmd_upload.py
' =
-- stdout
--- expected
+++ actual
@@ -1,2 +1,0 @@
-New and old cmd results equal
-Test succeeded

-- stderr
Traceback (most recent call last):
  File "/Users/runner/work/rizin/rizin/test/scripts/http_post_cmd_upload.py", line 14, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

```
python -m pip install requests
````
```

2021-11-01 11:07 UTC, XVilka commented on librz/core/rtr_http.c
> +		//snprintf (path, sizeof (path), "%s/%s", root, rs->path);
Remove all unused code also.

2021-11-01 12:15 UTC, XVilka requested changes

2021-11-01 12:15 UTC, XVilka commented on test/db/cmd/cmd_http_post
> +!python3 -m pip install requests
No, this is not the way to do it. Please update these files instead:
- `.builds/*`
- `.github/workflows/*`
- `.appveyor.yml`
- `.travis.yml`

2021-11-03 09:04 UTC, ret2libc commented on librz/core/rtr_http.c
> +	//const char *index = rz_config_get(core->config, "http.index");
remove instead of commenting

2021-11-04 04:57 UTC, XVilka commented
Use files from `test/bins/` instead:
```

[XX] db/cmd/cmd_http_post http-post-cmd
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!python3 scripts/http_post_cmd_upload.py
' =
-- stdout
--- expected
+++ actual
@@ -1,1 +1,0 @@
-Test succeeded

-- stderr
Traceback (most recent call last):
  File "/Users/runner/work/rizin/rizin/test/scripts/http_post_cmd_upload.py", line 85, in <module>
    main()
  File "/Users/runner/work/rizin/rizin/test/scripts/http_post_cmd_upload.py", line 52, in main
    with open(TARGET, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/bin/true'

[**]                               db/cmd/cmd_http_post    14372 OK       961 BR        1 XX       22 FX
```

2023-04-23 04:13 UTC, XVilka commented
@ogre2007 any plans to finish this?

2024-01-17 07:17 UTC, closed without merging