Refactor code
rizinorg/rizin pull request #1907
Opened 2021-10-30 09:04 UTC by Sergaster

1. Fix misc memory leaks & some bugs
2. Handle malloc, strdup etc return values
3. Refactor plugins loading/unloading (not tested, no plugins)

2021-10-30 11:13 UTC, wargio requested changes
Thanks for the contrib, please test the code on Windows and Linux (due your changes) and also run `./sys/clang-format.py` (you need clang-format to be installed on your system) for the formatting

2021-10-30 11:13 UTC, wargio commented on librz/analysis/analysis.c
> +	char *p, *dir_prefix;
please initialize the values to NULL.

2021-10-30 11:13 UTC, wargio commented on librz/analysis/analysis.c
> +			if (dir_prefix == NULL)
use `!dir_prefix` and always use the brackets `{}`

2021-10-30 11:13 UTC, wargio commented on librz/analysis/analysis.c
> +	int v;
initialize the values to NULL and -1

2021-10-30 11:13 UTC, wargio commented on librz/config/config.c
> +		free (cn->desc);
brackets also no need to check the pointer for NULL pointer when calling `free`

2021-10-30 11:13 UTC, wargio commented on librz/config/config.c
> +		free(node->desc);
brackets also no need to check the pointer for NULL pointer when calling `free`

2021-10-30 11:13 UTC, wargio commented on librz/config/config.c
> +	return;
no need for a return on void returning function

2021-10-30 11:13 UTC, wargio commented on librz/config/config.c
> +	RzConfigNode *node;
initialize it to NULL

2021-10-30 11:13 UTC, wargio commented on librz/config/config.c
> +		return node->value;
remove the else and just return the `node->value`

2021-10-30 11:13 UTC, wargio commented on librz/config/config.c
> +	RzConfigNode *node;
initialize it to NULL

2021-10-30 11:13 UTC, wargio commented on librz/config/config.c
> +	return;
no need to add the return in a void returning function

2021-10-30 11:13 UTC, wargio commented on librz/config/config.c
> +	rz_list_free(cfg->nodes);
free methods could be called with cfg NULL, which will cause a null deref; so either revert back or add `ìf (!cfg) { return; }`

2021-10-30 11:13 UTC, wargio commented on librz/core/cconfig.c
> +		if (s == NULL) {
`!s`

2021-10-30 11:13 UTC, wargio commented on librz/core/cconfig.c
> +	if (!core->io || !core->io->desc || !core->io->desc->plugin)
brackets

2021-10-30 11:13 UTC, wargio commented on librz/core/cconfig.c
> +	if (core->io->desc->plugin->name && !strcmp(core->io->desc->plugin->name, "gdb")) {
else if

2021-10-30 11:13 UTC, wargio commented on librz/core/cconfig.c
> +	s = rz_sys_prefix(node->value);
one line.

2021-10-30 11:13 UTC, wargio commented on librz/core/cconfig.c
>  	RzConfigNode *n;
initialize all the values

2021-10-30 11:13 UTC, wargio commented on librz/core/cconfig.c
> +		pfx = rz_sys_getenv("RZ_PREFIX");
one line

2021-10-30 11:13 UTC, wargio commented on librz/core/cconfig.c
> +				eprintf ("Malloc error for RZ_PREFIX default\n");
```suggestion
				RZ_LOG_ERROR("cannot allocate buffer for RZ_PREFIX\n");
```

2021-10-30 11:13 UTC, wargio commented on librz/core/cmd/cmd_open.c
> +			rz_lib_openfile(core->lib, input + 2);
probably is better to have an `RZ_LOG_WARN("failed to open library %s", input + 2);` since this is a command

2021-10-30 11:13 UTC, wargio commented on librz/core/cmd/cmd_plugins.c
> +	if (rz_lib_already_loaded(core->lib, rz_str_trim_head_ro(argv[1]))) {
ehm. this is wrong @ret2libc  (referring to `rz_str_trim_head_ro`)

2021-10-30 11:13 UTC, wargio commented on librz/core/fortune.c
> +	if (strncmp(type, "tips", 4) && strncmp(type, "fun", 3))
brackets

2021-10-30 11:13 UTC, wargio commented on librz/core/fortune.c
> +	char *sys, *s;
initialize the pointers

2021-10-30 11:13 UTC, wargio commented on librz/core/fortune.c
> +	if (sys == NULL)
brackets and `!sys`

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +	char *p;
initialize the pointers

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +	if (path)
brackets

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +		if (p != NULL) {
`if (p)`

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +			if (*p) {
you can squash the previous if with this one and just use `if (RZ_STR_ISNOTEMPTY(p)) {` and still free it outside the if since free accepts a NULL pointer

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +		if (p != NULL) {
same as above

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +	return;
no need to return on void function

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +	if (core->lib == NULL) {
`!core->lib`

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +		eprintf ("Failed to allocate new libs data\n");
```suggestion
		RZ_LOG_ERROR("Failed to allocate new libs data\n");
```

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +	return;
no need to return on void functions

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +	if (ext == NULL) {
`!ext`

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
>  	}
```suggestion
	return !strcmp(ext, "py") || !strcmp(ext, "js") || !strcmp(ext, "lua");
```

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +	RzListIter *iter;
null pointers

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +	if (homeplugindir == NULL) {
`!homeplugindir`

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +		eprintf("Failed to alloc string %s\n", RZ_HOME_PLUGINS);
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +			snprintf (user_path, MAX_FILE_NAME_SIZE, "%s%s", RZ_SYS_DIR, x); \
```suggestion
			rz_strf(user_path, "%s%s", RZ_SYS_DIR, x); \
```

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +		if (dir_plugins == NULL || !rz_str_endswith(dir_plugins, x)) { \
!dir_plugins

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +		snprintf(script_file, MAX_FILE_NAME_SIZE, "%s/%s", homeplugindir, file);
```suggestion
		rz_strf(script_file, RZ_JOIN_2_PATHS("%s", "%s"), homeplugindir, file);
```

2021-10-30 11:13 UTC, wargio commented on librz/core/libs.c
> +			eprintf("Cannot find script '%s'\n", script_file);
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	if (lib == NULL)
brackets and `!lib`

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	if (lib->symname == NULL)
brackets and `!lib->symname`

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	if (lib->symnamefunc == NULL)
brackets and `!lib->symnamefunc`

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> -	}
as before, free methods needs to check for null pointers because it has to be possible to pass a NULL pointer and not cause a null deref bug

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	return;
no need to return on void function

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
>  	RzLibPlugin *p;
add an `rz_return_if_fail(lib && file, -1);` here

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		if (!strstr(p->file, file))
brackets

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +RZ_API bool rz_lib_already_loaded(RzLib *lib, const char *file) {
do we really need this to be exposed? @ret2libc @XVilka

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	if (fileName == NULL)
`!fileName` and brackets

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	char *a, *p;
initialize the pointers

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	if ((a = strdup(s)) == NULL) {
```suggestion
	if (!(a = strdup(s))) {
```

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		bool mismatch;
null pointers

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +			eprintf("Failed to get version for file %s (%s), alloc error\n",
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +			eprintf("Failed to get version for file %s (%s), alloc error\n",
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +					eprintf("rz-pm -ci %s\n", stru->pkgname);
hmmm. not sure. @ret2libc  @XVilka

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		eprintf("Library plugin allocation error for file %s\n", file);
`!p` and RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	if ((p->file = strdup(file)) == NULL) {
```suggestion
	if (!(p->file = strdup(file))) {
```

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	RZ_FREE(p);
you can free normally since `RZ_FREE` frees and set the pointer to NULL, but here you are going to return another value

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	RzLibStruct *stru;
null pointers and as before add `rz_return_if_fail(lib && file)`

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		eprintf("Invalid library extension: %s, ignored\n", file);
```suggestion
		RZ_LOG_ERROR("Invalid library extension: %s, ignored\n", file);
```

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		eprintf("Not loading library because it has already been loaded from somewhere else: '%s'\n", file);
```suggestion
		RZ_LOG_ERROR("Not loading library because it has already been loaded from somewhere else: '%s'\n", file);
```

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		eprintf("Cannot open library: '%s'\n", file);
```suggestion
		RZ_LOG_ERROR("Cannot open library: '%s'\n", file);
```

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	if (rz_lib_already_loaded(lib, file)) {
is this correct?

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	if (strf == NULL) {
!strf

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		if (stru == NULL) {
same here

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		free (strf);
hmmmmm not sure, why freeing a function pointer?

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +	wchar_t file[MAX_FILE_NAME_SIZE];
not sure about these changes

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +RZ_API void rz_lib_opendir(RzLib *lib, const char *path) {
why?

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		eprintf("No path specified for plugins\n");
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		eprintf("Failed to convert path from UTF-8 to UTF-16 %s\n", path);
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		eprintf("Cannot open directory %ls\n", wcpath);
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +			eprintf("Failed to convert file name from UTF-8 to UTF-16 %s\n", path);
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		if (wctocbuff == NULL) {
```suggestion
		if (!wctocbuff) {
```

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		eprintf("Cannot open directory '%s'\n", path);
RZ_LOG_ERROR

2021-10-30 11:13 UTC, wargio commented on librz/util/lib.c
> +		printf(" %5s %s \n", __lib_types_get(p->type), p->file);
RZ_LOG_DEBUG

2021-10-30 11:13 UTC, wargio commented on librz/util/str.c
> +	if (sys == NULL)
brackets and !sys

2021-10-30 11:13 UTC, wargio commented on librz/util/sys.c
> +		free(crash_handler_cmd);
brackets and !s

2021-10-30 11:13 UTC, wargio commented on librz/util/sys.c
> +	env = rz_sys_getenv(key);
one line

2021-10-30 11:13 UTC, wargio commented on librz/util/sys.c
> +		return false;
brackets and !env

2021-10-30 11:13 UTC, wargio commented on librz/util/unum.c
> +		return NULL;
brackets and !num->cb_from_value

2021-10-30 11:13 UTC, wargio commented on librz/util/unum.c
> +	if (msg && *msg) {
```suggestion
	if (RZ_STR_ISEMPTY(msg)) {
```

2021-10-30 11:13 UTC, wargio commented on librz/util/unum.c
>  	}
no need for this else, just return the NULL

2021-10-30 11:14 UTC, wargio commented
i think this PR should be splitted in 2, one for the mem leaks and one for the refactoring on plugin loading

2021-10-30 16:55 UTC, XVilka commented on librz/analysis/analysis.c
> +	char *p, *dir_prefix;
Better to define them at the first assignment, as it was before.

2021-10-30 17:00 UTC, XVilka requested changes
Please combine definition and assignment wherever possible, we use C99. Asserts should be the first in function. I recommend to check developers guide first.

2021-10-30 17:00 UTC, XVilka commented on librz/analysis/analysis.c
> +			bool is_hack;
Combine definition and assignment wherever possible.

2021-10-30 17:00 UTC, XVilka commented on librz/config/config.c
> +	RzConfigNode *node;
Same, unnecessary change.

2021-10-30 17:00 UTC, XVilka commented on librz/config/config.c
> +	RzConfigNode *node;
Same

2021-11-03 10:10 UTC, ret2libc reviewed
I suggest you try to split your PRs/changes in logically related changes so that the review and changes can be done more easily and quicker.

2022-05-19 10:43 UTC, XVilka commented
@Sergaster do you plan to continue working on this? As you see, the big PRs left unmaintained produce a lot of conflicts with time. I suggest opening smaller PRs which we can review, test, and merge faster. Thus, I am closing this one, in case of the need we can reopen.

2022-05-19 10:43 UTC, closed without merging