Rename and refactor to use `RzBitVector` instead of `RzILBitVector`
rizinorg/rizin pull request #2048
Opened 2021-11-29 20:09 UTC by DMaroo

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Refactor and extract `RzILBitVector` from `rz_il` to `rz_util` for more generalized use.

**Test plan**

Green CI.

**Closing issues**

Closes #2010.

2021-11-30 04:59 UTC, XVilka requested changes

2021-11-30 04:59 UTC, XVilka commented on test/unit/test_il_definitions.c
>  bool test_rzil_bv_init64(void) {
It makes sense to separate just bitvector unit tests from the `test_il_definitions.c` into a new C file, with correspondingly named functions.

2021-11-30 08:50 UTC, thestr4ng3r commented
I think we can keep the `bv` naming, i.e. have the `RzBitVector` type and `rz_bv_*` functions. I expect bitvectors to be used in many places of the code and `bv` is way more convenient. But I would also like to hear other opinions @XVilka @ret2libc @wargio.

2021-11-30 09:15 UTC, ret2libc commented
> I think we can keep the `bv` naming, i.e. have the `RzBitVector` type and `rz_bv_*` functions. I expect bitvectors to be used in many places of the code and `bv` is way more convenient. But I would also like to hear other opinions @XVilka @ret2libc @wargio.

I'm ok with `rz_bv_*`.

2021-11-30 10:07 UTC, wargio commented
> more convenient. But I would also like to hear other o

same. i'm ok with that, but i would avoid moving it in utils, for now.

2021-11-30 16:11 UTC, XVilka commented
`rz_bv_` is ok for me. But I think it's time to move to the RzUtil, why not?

2021-12-01 02:53 UTC, XVilka approved these changes

2021-12-01 08:48 UTC, thestr4ng3r approved these changes

2021-12-01 08:58 UTC, merged