Disable GPL code and Added RISC-V support via Capstone 5
rizinorg/rizin pull request #2087
Opened 2021-12-10 13:51 UTC by wargio

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

1. Extends the support of `use_gpl` meson option to rizin.

When `-Duse_gpl=false` the following plugins are disabled:
```
Asm: arc, arm_gnu, cris_gnu, hppa_gnu, lanai_gnu, mips_gnu, nios2, ppc_gnu, riscv, sh, sparc_gnu, tricore, vax, xtensa, z80
Analysis: arc, arm_gnu, cris, mips_gnu, nios2, ppc_gnu, riscv, sh, sparc_gnu, tricore, vax, xtensa, z80
Debug: qnx
IO: qnx
```
Also `sflib` files are not installed.

2. Adds RISC-V support via Capstone 5

When Capstone 5 is detected, adds the analysis and asm plugins as `riscv_cs` to rizin.

2021-12-10 14:03 UTC, XVilka requested changes

2021-12-10 14:03 UTC, XVilka commented on librz/analysis/meson.build
> +    'p/analysis_ppc_gnu.c',
Just remove PPC GNU completely, it seems also unmaintained and untested for years.

2021-12-10 14:03 UTC, XVilka commented on librz/analysis/meson.build
> +    'p/analysis_arm_gnu.c',
Would be unnecessary after https://github.com/rizinorg/rizin/pull/2085

2021-12-10 14:03 UTC, XVilka commented on librz/asm/meson.build
> +    #'arch/hexagon/gnu/hexagon-dis.c',
Remove those - they were removed long time ago

2021-12-10 14:03 UTC, XVilka commented on librz/asm/meson.build
> +    'arch/ppc/gnu/ppc-dis.c',
Same, if you remove PPC GNU plugin.

2021-12-10 14:03 UTC, XVilka commented on librz/asm/meson.build
> +    #'p/asm_hexagon_gnu.c',
Remove it - it's no longer in the tree for a looong time.

2021-12-10 14:03 UTC, XVilka commented on librz/meson.build
> +    #'hexagon_gnu',
Remove this

2021-12-10 14:04 UTC, XVilka commented on librz/analysis/meson.build
> +    'p/analysis_ppc_gnu.c',
Could be done in a separate PR, like I did for ARM GNU and WineDbg

2021-12-10 18:54 UTC, ret2libc reviewed
LGTM!

2021-12-11 00:14 UTC, XVilka approved these changes

2021-12-11 12:30 UTC, merged