[RzIL] Refactor definitions and VM
rizinorg/rizin pull request #2094
Opened 2021-12-11 16:45 UTC by wargio

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Refactors various methods in IL definitions and VM.

2021-12-11 16:47 UTC, wargio commented on librz/include/rz_il/definitions/value.h
> -} RZIL_TEMP_TYPE;
this is not used.

2021-12-12 03:37 UTC, XVilka approved these changes
Looks good. A few minor nitpicks, and please wait for @thestr4ng3r to take a look first before merging.

2021-12-12 03:37 UTC, XVilka commented on librz/il/definitions/value.c
>   * New an empty value
Update Doxygen then too

2021-12-12 03:37 UTC, XVilka commented on librz/il/definitions/value.c
> +RZ_API RZ_OWN RzILVal *rz_il_value_new_bitv(RZ_NONNULL RzBitVector *bv) {
Add Doxygen please, since those are `RZ_API` functions.

2021-12-12 03:37 UTC, XVilka commented on librz/il/definitions/value.c
> +RZ_API RZ_OWN RzILVal *rz_il_value_new_bool(RZ_NONNULL RzILBool *b) {
Doxygen.

2021-12-12 03:37 UTC, XVilka commented on librz/il/rzil_vm.c
>  	RzILEffectLabel *label = ht_pp_find(lbl_table, lbl_name, &found);
You can use the pointer here directly.

2021-12-12 08:43 UTC, thestr4ng3r approved these changes

2021-12-12 16:39 UTC, wargio commented
ok i'll push more changes in here, because i found some bugs.

2021-12-13 14:58 UTC, XVilka requested changes

2021-12-13 14:58 UTC, XVilka commented on librz/core/cil.c
> +static void rzil_print_register_bool(const char *reg_name, bool value, RzStrBuf *sb, RzTable *tbl, PJ *pj) {
Instead of passing `sb`, `pj`, and `tbl` every time, you could create some kind of context union and use in all these functions.

2021-12-13 14:58 UTC, XVilka commented on librz/core/cil.c
> +		rz_strbuf_appendf(sb, " %s: %u ", reg_name, n);
Probably better to output `true`/`false` instead, just use `rz_str_bool()`

2021-12-13 14:58 UTC, XVilka commented on librz/core/cil.c
> +		rz_table_add_rowf(tbl, "sss", reg_name, "bool", value ? "true" : "false");
Use `rz_str_bool()`

2021-12-13 14:58 UTC, XVilka commented on librz/core/cil.c
> +		RZ_LOG_ERROR("cannot print events if all the events are disabled (check rzil.step.events.read & rzil.step.events.write).");
Maybe put the variable names in quotes?

2021-12-13 14:58 UTC, XVilka commented on librz/core/cmd_descs/cmd_analysis.yaml
> +        summary: Steps N instructions within the RzIL Virtual Machine
"Step"

2021-12-13 14:58 UTC, XVilka commented on librz/core/cmd_descs/cmd_analysis.yaml
> +        summary: Steps N instructions within the RzIL VM and output VM changes (read & write)
"Step"

2021-12-14 02:22 UTC, XVilka approved these changes

2021-12-14 11:34 UTC, merged