Remove oldshell handlers from cmd_analysis.c
rizinorg/rizin pull request #2106
Opened 2021-12-14 21:55 UTC by pelijah

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2021-12-14 22:47 UTC, pelijah commented
Well I am not sure about `afvb-*`/`afvr-*`. As I see you can use `afvb- *`/`afvr- *`.

2021-12-15 01:55 UTC, XVilka approved these changes

2021-12-15 09:56 UTC, ret2libc requested changes
I suggest to keep only `afvb-*` and `afvX-*` and remove the behaviour of `afvb- *`. It seems that most of the new commands that were converted use the command with `-*` (e.g. `tn-*`, `tl-*`, `db-*`, `afb-*`, `C-*`, `ech-*`, `om-*`, etc.)

2021-12-16 03:17 UTC, XVilka approved these changes

2021-12-16 03:18 UTC, merged