Convert afn commands to rzshell
rizinorg/rizin pull request #2139
Opened 2021-12-25 09:19 UTC by pelijah

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- `rz_core_analysis_fcn_autoname()` was splitted on `rz_core_analysis_function_autoname()` (get autoname) and `rz_core_analysis_function_strings_print()` (print referenced string flags)
- `afn base64:......` was removed
- `afn` (w/o args) was removed since we have `afl.`

**Test plan**

...

**Closing issues**

Related #1442

2021-12-26 11:27 UTC, wargio requested changes

2021-12-26 11:27 UTC, wargio commented on librz/core/canalysis.c
> + * @brief Suggest a name for the function
```suggestion
 * \brief Suggest a name for the function
```

2021-12-26 11:28 UTC, wargio commented
looks good. just change that tiny detail and i think we can merge it.

2021-12-26 12:22 UTC, XVilka approved these changes
LGTM, with a minor nitpick

2021-12-26 12:22 UTC, XVilka commented on librz/core/canalysis.c
> + * @brief Print all string flags referenced by the function
`\brief`

2021-12-26 18:02 UTC, Maijin commented on librz/core/canalysis.c
> +static bool blacklisted_word(const char *name) {
I would suggest to use that refactoring to move that in a static file that way, it will be easier for people to contribute

2021-12-26 23:01 UTC, wargio approved these changes

2021-12-27 04:04 UTC, XVilka approved these changes

2021-12-27 17:19 UTC, merged