Remove Rapatch
rizinorg/rizin pull request #215
Opened 2020-12-17 20:48 UTC by Maijin

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

Remove rapatch - untested, not working and dup with other features thus confusing.

2020-12-17 20:50 UTC, wargio approved these changes

2020-12-17 22:08 UTC, ret2libc commented
The cmd_descs files are autogenerated, as you can see from the headers at the top. You should change cmd_descs.yaml

2020-12-18 04:48 UTC, XVilka approved these changes
Please fix the commands YAML, but overall is good. Always good to remove unnecessary code 👍 
We probably should support better existing patching programs or reimplement it from scratch.

2020-12-18 08:52 UTC, ret2libc requested changes
Also, I think you should remove patch.o from the Makefile as well.

2020-12-18 08:52 UTC, ret2libc commented on librz/main/rizin.c
> +	if (!quiet) {
mmm i think this should be always done.
The condition becomes:
`if ((false && !quiet) || !false)` which is equal to `if (false || true)` -> `if (true)`. Right?

2020-12-18 10:02 UTC, wargio commented
`make[3]: *** No rule to make target 'patch.o', needed by 'librz_core.so'.  Stop.`

2020-12-18 10:32 UTC, ret2libc approved these changes

2020-12-18 10:37 UTC, XVilka commented
```
[XX] db/cmd/cmd_w wp
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'echo 0x10 "hello" > .rz-wp.test
echo 0x20 01020304 >> .rz-wp.test
cat .rz-wp.test
wp .rz-wp.test
rm .rz-wp.test
ps @ 0x10
p8 3 @ 0x20
' -
-- stdout
@@ -1,4 +1,2 @@
 0x10 "hello"
 0x20 01020304
-hello
-010203


-- stderr
Error while executing command: wp .rz-wp.test
```

2020-12-18 12:38 UTC, Maijin commented
Current broken tests don't seem related.

2020-12-18 12:45 UTC, wargio commented
i'm merging this even if red since the issue is unrelated to this one.

2020-12-18 12:46 UTC, ret2libc commented
Yeah it's very likely just MacOS on maintenance on GHA.

2020-12-18 12:46 UTC, merged