Fix memory leak in rz_debug_free()
rizinorg/rizin pull request #2186
Opened 2022-01-08 20:25 UTC by pelijah

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2022-01-09 09:53 UTC, yossizap requested changes

2022-01-09 09:53 UTC, yossizap commented on librz/debug/debug.c
> +		rz_reg_free(dbg->reg);
You can replace/remove the comment@416 and remove the todo

2022-01-10 09:53 UTC, ret2libc commented
@thestr4ng3r ccing you here since you recently touched the reg stuff.

2022-01-10 11:24 UTC, thestr4ng3r commented
After addressing @yossizap's comment, this should be correct. `dbg->reg` was changed from randomly being changed to a reference to `analysis->reg` to being owned by `RzDebug`.

2022-01-15 11:28 UTC, thestr4ng3r approved these changes

2022-01-15 15:48 UTC, XVilka approved these changes

2022-01-15 15:49 UTC, merged