str_trim.c: trim specific char in str
rizinorg/rizin pull request #2259
Opened 2022-01-27 14:59 UTC by PeiweiHu

This commit contains two parts. One is adding functions
  used to trim specific char in str. The other one is a
  fix to remove redundant slash in tail.

 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

While using `rz-find -s abc /bin/`, the output will contain duplicate slash, like `/bin//ls`. 

...

**Test plan**

...

**Closing issues**

...

2022-01-27 16:50 UTC, ret2libc requested changes
I think we don't need to do all this, because the problem is that the directory is just concatenated to the filename in `rzfind_open_dir`. I suggest to replace `rz_str_newf` there with `rz_file_path_join`.

2022-01-28 02:19 UTC, PeiweiHu commented
> I think we don't need to do all this, because the problem is that the directory is just concatenated to the filename in `rzfind_open_dir`. I suggest to replace `rz_str_newf` there with `rz_file_path_join`.

Totally agree. I just saw that API......

2022-01-28 04:03 UTC, XVilka approved these changes

2022-01-28 08:55 UTC, ret2libc approved these changes

2022-01-28 09:19 UTC, merged