PDB parsing fixes
rizinorg/rizin pull request #2349
Opened 2022-02-22 08:05 UTC by GustavoLCR

# Please don't squash
 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Test plan**

Tests pass

**Closing issues**

None

2022-02-22 08:18 UTC, XVilka requested changes
A typo:
```
../librz/analysis/type_pdb.c:467: error: ',' expected (got "": Redefining type %s.\n"")
```

2022-02-22 08:18 UTC, XVilka commented on librz/analysis/type_pdb.c
> +static inline const char *base_type_kind_as_string(RzBaseTypeKind kind) {
Please move this function and make an API to `librz/type/base.c`.

2022-02-22 08:18 UTC, XVilka commented on librz/bin/pdb/pdb.c
>  	RZ_FREE(pdb);
Can be just `free(pdb)` as well.

2022-02-22 08:20 UTC, XVilka commented
@GustavoLCR since you are working on PDB, could you please take a quick look at https://github.com/rizinorg/rizin/issues/2270?
It makes sense to bundle the fix here if it's not too big.

2022-02-22 09:00 UTC, ret2libc commented
Hey @GustavoLCR could you provide a more detailed summary of the PR? What kind of fixes are these?

2022-02-23 05:37 UTC, XVilka requested changes
1. Please rebase on top of the latest `dev`.
2. Please fix clang-format:
```
Ubuntu clang-format version 13.0.1-++20220120110924+75e33f71c2da-1~exp1~20220120231001.58
librz/type/base.c:28:4: error: code should be clang-formatted [-Wclang-format-violations]
/**
   ^
librz/type/base.c:29:59: error: code should be clang-formatted [-Wclang-format-violations]
* \brief Returns string representing the kind of base type
                                                          ^
librz/type/base.c:30:2: error: code should be clang-formatted [-Wclang-format-violations]
* 
 ^
librz/type/base.c:31:64: error: code should be clang-formatted [-Wclang-format-violations]
* \param kind RzBaseTypeKind to return string representation of
                                                               ^
```
3. There are two broken tests:
```
[XX] db/tools/rz_bin rz-bin -Pj
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-bin -Pj ${RZ_FILE}~{}
?e
' bins/pdb/minimal.pdb
-- stdout
--- expected
+++ actual
@@ -26,7 +26,7 @@
         },
         {
           "type": "union",
-          "name": "<unnamed-tag>",
+          "name": "type_0x1004",
           "size": 4,
           "members": [
             {
@@ -47,7 +47,7 @@
           "size": 8,
           "members": [
             {
-              "member_type": "union <unnamed-tag>",
+              "member_type": "union type_0x1004",
               "member_name": "a",
               "offset": 0
             },

-- stderr
Warning: Cannot find base address, flags will probably be misplaced
Warning: Cannot find base address, flags will probably be misplaced
[XX] db/cmd/cmd_idp idpij
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'idpij bins/pdb/minimal.pdb~{}' =
-- stdout
--- expected
+++ actual
@@ -25,7 +25,7 @@
       },
       {
         "type": "union",
-        "name": "<unnamed-tag>",
+        "name": "type_0x1004",
         "size": 4,
         "members": [
           {
@@ -46,7 +46,7 @@
         "size": 8,
         "members": [
           {
-            "member_type": "union <unnamed-tag>",
+            "member_type": "union type_0x1004",
             "member_name": "a",
             "offset": 0
           },

-- stderr
Warning: Cannot find base address, flags will probably be misplaced
Warning: Cannot find base address, flags will probably be misplaced

```
4. Please fix the following warning:
```
../librz/analysis/type_pdb.c:432:23: error: implicit conversion from enumeration type 'RzBaseTypeKind' to different enumeration type 'RzTypeIdentifierKind' [-Werror,-Wenum-conversion]
        t->identifier.kind = kind;
                           ~ ^~~~
1 error generated.
```

2022-02-25 04:05 UTC, XVilka approved these changes

2022-02-25 05:17 UTC, merged