v850 support for getting main offset
rizinorg/rizin pull request #2380
Opened 2022-03-04 06:42 UTC by PeiweiHu

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Fix https://github.com/rizinorg/rizin/issues/2316. This pr adds support for v850 while getting main offset. 

...

**Test plan**

If possible, I hope more v850 samples can be provided for the test (I searched but found only a few). 

...

**Closing issues**

...

2022-03-04 08:39 UTC, ret2libc commented on librz/bin/format/elf/elf_info.c
> +static ut64 get_main_offset_v850(ELFOBJ *bin, ut64 entry, ut8 *buf) {
can you provide the disassembly of what these instructions are in a comment? So that we can understand what this function is trying to recognize

2022-03-04 13:11 UTC, XVilka requested changes
Please add a testcase.

2022-03-04 13:11 UTC, XVilka commented on librz/bin/format/elf/elf_info.c
> +	if (delta) {
I recommend inverting the check and doing a quick return instead.

2022-03-04 19:32 UTC, wargio commented
Can you also add a test? (open a PR on rizin bin repo)

2022-03-07 02:28 UTC, PeiweiHu commented
Explanation for changing `test/db/analysis/v850`:

I ran `aaa; afl` on other samples, `main` is displayed instead of `sym.main`.

2022-03-07 10:40 UTC, wargio commented
i think we need to test this on a bin without symbols.

2022-04-17 15:54 UTC, XVilka commented
@PeiweiHu could you please rebase and update this PR?

2022-05-14 16:34 UTC, XVilka commented
@PeiweiHu could you please rebase and update the PR?

2022-05-14 23:25 UTC, PeiweiHu commented
> @PeiweiHu could you please rebase and update the PR?

Sorry for the late response. Since this pr is not thoroughly tested, I will refine and reopen this in June (after some of my deadlines) if nobody solves it.

2024-01-14 01:57 UTC, XVilka commented
@PeiweiHu could you please reopen this one again? It would help the ongoing V850 RzIL conversion: https://github.com/rizinorg/rizin/pull/4103

For creating testcases these toolchains could be used: 
- https://llvm-gcc-renesas.com/v850/v850-download-toolchains/
- https://github.com/dkulacz/gcc-v850-elf-toolchain
- https://hub.docker.com/r/mikoto2000/v850-toolchain
- https://eclipse-update.iar.com/v850/4.10/

cc @imbillow

2024-01-15 04:54 UTC, PeiweiHu commented
Ok, I will try to finish this when I am free. cc @XVilka

2024-01-15 07:15 UTC, wargio reviewed
nice

2024-01-16 00:25 UTC, XVilka approved these changes

2024-01-16 00:25 UTC, merged