Implement getting a backtrace from a Windows Kernel Dump for x64
rizinorg/rizin pull request #2387
Opened 2022-03-06 12:05 UTC by GustavoLCR

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

* Implements getting a backtrace from a windows kernel dump for x64 targets
* Fixes `ompb` command not setting the priority of maps
* Add PE header to mappings

**Test plan**

Tests pass

**Closing issues**

None

2022-03-06 13:16 UTC, XVilka requested changes

2022-03-06 13:16 UTC, XVilka commented on librz/debug/p/debug_dmp.c
> +	if (ctx->type == DMP_DUMPTYPE_TRIAGE) {
Maybe better to reverse this condition?

2022-03-06 13:16 UTC, XVilka commented on librz/debug/p/native/bt/windows-x64.c
> +static bool backtrace_windows_x64_internal(RZ_IN RzDebug *dbg, RZ_INOUT RzList **out_frames, RZ_INOUT struct context_type_amd64 *context) {
I recommend to split this function into smaller.

2022-03-06 17:12 UTC, wargio commented on librz/debug/p/debug_dmp.c
> +		}
maybe comment here?

2022-03-06 17:12 UTC, wargio commented on librz/debug/p/debug_dmp.c
> +			RZ_LOG_DEBUG("TODO\n");
same?

2022-03-15 03:04 UTC, XVilka approved these changes

2022-03-15 09:45 UTC, merged