Updated Shellforge in librz/include/sflib
rizinorg/rizin pull request #2428
Opened 2022-03-21 14:23 UTC by BraveBoii

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pull request solves the librz/include/sflib part of the Update Shellforge issue (https://github.com/rizinorg/rizin/issues/154).
I generated the updated sflib using gensflib.py in the shellforge github and replaced all the old files with the new ones, updating the meson.build file and the .reuse/dep5 license for sflib.

**Test plan**

...

**Closing issues**

...

2022-03-21 16:53 UTC, wargio commented
looks like you have deleted the ios syscalls support.

2022-03-21 17:19 UTC, DavidAfonsoValente commented
> looks like you have deleted the ios syscalls support, also probably is better to whitelist the files on `sys/clang-format.py`

Yes, the ios syscalls were in the darwin-ARM-64 dir which I thought was to be replaced, should I add it back?
And by whitelisting do you mean adding them to the skiplist?

2022-03-21 17:44 UTC, wargio commented
1. I think they should be restored back, @XVilka @ret2libc @thestr4ng3r what do you think?
2. Yes, add the path to the skiplist

2022-03-22 01:13 UTC, XVilka commented
Yes, please restore.

2022-03-22 14:24 UTC, BraveBoii commented
Done, I've restored the darwin arm 64 lib with the ios syscalls

2022-03-22 15:29 UTC, wargio commented
looks like you are on windows, be sure to save the files with unix encoding.

2022-03-22 20:08 UTC, wargio commented
@BraveBoii i suggest to just set `git config --global core.autocrlf input ` this option once. so this will convert windows CRLF to LF

2022-03-22 20:19 UTC, BraveBoii commented
> ###

Yes, thank you, I´ve done that, just had to revert some changes because i accidentaly ran dos2unix and changed the encoding on some other files

2022-03-23 08:17 UTC, ret2libc commented
Do we have a test case that covers these files? If not, we should add some tests.

2022-03-27 20:34 UTC, BraveBoii commented
> Do we have a test case that covers these files? If not, we should add some tests.

The updated libs already pass the existing tests, however to test the new architectures that should be supported by the gsoc project such as MIPS and PowerPc rz-gg and many other subfiles and functions still need to be adapted to support these archs.

2022-03-28 08:04 UTC, ret2libc requested changes
Please provide tests

2022-03-29 07:49 UTC, BraveBoii commented
Seen as integrating support for the new architectures would still require a lot of changes and additions, eg creating the emit.c files, changing egg.c, egg_Cfile.c, which should be done one at a time and would require more time, I would propose either removing the new architectures that were added and just updating the existing ones or update the old ones and leave the new ones in without adding new tests because they would still be unusable

2022-03-29 07:55 UTC, ret2libc commented
> Seen as integrating support for the new architectures would still require a lot of changes and additions, eg creating the emit.c files, changing egg.c, egg_Cfile.c, which should be done one at a time and would require more time, I would propose either removing the new architectures that were added and just updating the existing ones or update the old ones and leave the new ones in without adding new tests because they would still be unusable

I'm ok to remove the new architectures if they require too much work, but I'd still double check that there are tests for existing ones. If not, I think it makes sense to add them here.

@XVilka cc?

2022-03-30 11:11 UTC, BraveBoii commented
> > Seen as integrating support for the new architectures would still require a lot of changes and additions, eg creating the emit.c files, changing egg.c, egg_Cfile.c, which should be done one at a time and would require more time, I would propose either removing the new architectures that were added and just updating the existing ones or update the old ones and leave the new ones in without adding new tests because they would still be unusable
> 
> I'm ok to remove the new architectures if they require too much work, but I'd still double check that there are tests for existing ones. If not, I think it makes sense to add them here.
> 
> @XVilka cc?

There are only x86 tests afaik, should I add them for arm and darwin as well?

2022-03-30 11:14 UTC, BraveBoii commented
All of them are working besides ARM64 which is having problems because it is using the emit_arm.c file which contains ARM 32 assembly instructions and they're different sets.

2022-03-30 12:46 UTC, ret2libc commented
> > > Seen as integrating support for the new architectures would still require a lot of changes and additions, eg creating the emit.c files, changing egg.c, egg_Cfile.c, which should be done one at a time and would require more time, I would propose either removing the new architectures that were added and just updating the existing ones or update the old ones and leave the new ones in without adding new tests because they would still be unusable
> > 
> > 
> > I'm ok to remove the new architectures if they require too much work, but I'd still double check that there are tests for existing ones. If not, I think it makes sense to add them here.
> > @XVilka cc?
> 
> There are only x86 tests afaik, should I add them for arm and darwin as well?

Yes please. In general, we try to add tests as they miss. It's a good practice, it helps you understand how things are used and it helps the project cover as much code as possible, to make sure functions don't regress.

2022-03-30 17:20 UTC, wargio commented
i would say to add also broken tests so we can fix them later. what do you think @ret2libc ?

2022-03-31 13:43 UTC, BraveBoii commented
I've updated the archs and added new tests for the archs.

2022-05-19 11:12 UTC, XVilka requested changes
Please rebase on top of the latest `dev`

2022-05-19 23:15 UTC, BraveBoii commented
> Please rebase on top of the latest `dev`. I also suggest squashing and rearranging commits to be more self-contained.

Done.

2022-05-22 08:48 UTC, XVilka commented
Two failing tests:
```
[XX] db/tools/rz_gg rz-gg -i exec -k darwin -a x86 -b 32 -p n3N3
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-gg -i exec -k darwin -a x86 -b 32 -p n3N3' =
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-"\x41\xb0\x02\x49\xc1\xe0\x18\x49\x83\xc8\x17\xeb\x12\x5f\x49\x83\xc0\x24\x4c\x89\xc0\x48\x31\xd2\x52\x57\x48\x89\xe6\x0f\x05\xe8\xe9\xff\xff\xff\x2f\x62\x69\x6e\x2f\x73\x68"
+90909041b00249c1e0184983c817eb125f4983c0244c89c04831d252574889e60f05e8e9ffffff2f62696e2f7368909090



[XX] db/tools/rz_gg rz-gg -k darwin -a x86 -b 32 -p n2t2a2s2
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-gg -k darwin -a x86 -b 32 -p n2t2a2s2' =
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-4141414141414141414121000000000000004141
+00004141cccc9090
```
https://github.com/rizinorg/rizin/runs/6518164428?check_suite_focus=true#step:12:694

2022-05-24 15:44 UTC, XVilka approved these changes
Looks good now.
Please fix the `black` error:
```
Run export PATH=${HOME}/Library/Python/3.8/bin:${HOME}/Library/Python/3.9/bin:${HOME}/.local/bin:${PATH}
would reformat librz/include/sflib/darwin-arm-64/ios-syscalls.py
would reformat sys/clang-format.py

Oh no! 💥 💔 💥
2 files would be reformatted, 18 files would be left unchanged.
Error: Process completed with exit code 123.
```
Also, please don't forget to open issues for these broken tests you added.

I think it's good to merge after 0.4.0 is out, for 0.5.0 release, added to the corresponding milestone.

2022-06-08 12:50 UTC, merged

2022-06-08 13:11 UTC, XVilka commented
Thank you!