Convert rz-bin cmd call in rz-find to API
rizinorg/rizin pull request #2441
Opened 2022-03-23 15:19 UTC by chinggg

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- [x] Convert `rz-bin -qzzz` call in case `RZ_SEARCH_STRING` to internal API
  - https://github.com/rizinorg/rizin/blob/dev/librz/main/rz-bin.c#L1189
- [ ] `RZ_SEARCH_MAGIC`
- [ ] `RZ_SEARCH_ESIL`
...

**Test plan**

...

**Closing issues**

closes #1475
...

2022-03-23 15:31 UTC, ret2libc requested changes
How is `state` used here? Also, is it really necessary to have `core`?

2022-03-23 15:41 UTC, wargio approved these changes

2022-03-23 16:06 UTC, XVilka approved these changes

2022-03-24 00:42 UTC, chinggg commented
> How is state used here? Also, is it really necessary to have core?

You are right, `state` is not used since the output mode is specified by `bf->strmode`.

If RzCore is not used, more code is needed
```c
RzBin *bin = rz_bin_new();
RzIO *rio = rz_io_new();
rio->cb_printf = rz_cons_printf;
rz_io_bind(rio, &bin->iob);
// ..
rz_bin_free(bin);
rz_io_free(rio);
```

2022-03-24 00:45 UTC, wargio commented
you can just printf without rz_cons

2022-03-24 00:55 UTC, XVilka approved these changes

2022-03-24 08:13 UTC, ret2libc commented on librz/main/rz-find.c
> +	}
```suggestion
	bf->strmode = ro->json ? RZ_MODE_JSON : RZ_MODE_SIMPLE;
```

I think in this case a ternary operator fits very well and it's very readable.

2022-03-24 08:13 UTC, ret2libc commented on librz/main/rz-find.c
> +	RzBin *bin = core.bin;
I think it's alright to avoid RzCore and do RzBin+RzIO, if necessary.

2022-03-24 11:42 UTC, ret2libc approved these changes
Thanks!

Damn, `rz_bin_dump_strings` API is really bad...

2022-03-24 11:47 UTC, chinggg commented
Yes. In fact I think sometimes it is more convenient to use command especially if the API is not well-designed. 
For the other usage of `rz_sys_cmdf` in the same function `rzfind_open_file`, should it be replaced by internal API?

2022-03-24 11:47 UTC, wargio commented
> Thanks!
> 
> Damn, `rz_bin_dump_strings` API is really bad...

i will remove it in one of my PRs on RzPrint

2022-03-24 12:47 UTC, merged