Convert command an to new shell
rizinorg/rizin pull request #2447
Opened 2022-03-25 06:43 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

CI is green.

...

**Closing issues**

partially address https://github.com/rizinorg/rizin/issues/1442

...

2022-03-25 08:23 UTC, ret2libc requested changes

2022-03-25 08:23 UTC, ret2libc commented on librz/core/cmd/cmd_analysis.c
> +static int core_analysis_name(RzCore *core, const char *name) {
Return a bool or a RzCmdStatus directly.

2022-03-25 08:23 UTC, ret2libc commented on librz/core/cmd/cmd_analysis.c
> +static int core_analysis_name_json(RzCore *core, const char *name, PJ *pj) {
Return a bool or a RzCmdStatus directly.

2022-03-25 08:23 UTC, ret2libc commented on librz/core/cmd/cmd_analysis.c
> +static int core_analysis_name_json(RzCore *core, const char *name, PJ *pj) {
this function could be easily merged with `core_analysis_name` by just replacing the printing part of it.

2022-03-27 11:33 UTC, XVilka approved these changes

2022-03-28 08:00 UTC, ret2libc approved these changes

2022-03-28 10:06 UTC, wargio approved these changes

2022-03-28 10:06 UTC, merged