Fix #2124 - Normalize paths
rizinorg/rizin pull request #2485
Opened 2022-04-02 05:04 UTC by GustavoLCR

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

On Windows, substitutes `/` for `\`.
Consolidate multiple path separators, remove trailing slashes and escape `\` it so it can be used in c strings

**Test plan**

Tests pass

**Closing issues**

Fixes #2124

2022-04-02 07:34 UTC, thestr4ng3r requested changes
This should not use python as that tends to introduce massive overhead. Meson has string handling functions too: https://mesonbuild.com/Reference-manual_elementary_str.html#string-methods But maybe there are even better alternatives provided by meson too.

2022-04-02 10:45 UTC, wargio reviewed
i understand the reasoning behind this, but if we want to do this, then is kinda better to create a script which is invoked by meson. like we do for checking the git repos.

2022-04-02 21:05 UTC, GustavoLCR commented
Seems that `fs.as_posix()` does normalization, so i just need to subs `/` for `\\` on the result 0744d0fc053cbeff94c159a25aac7f9e4a3818ec

2022-04-03 01:09 UTC, XVilka approved these changes

2022-04-03 07:15 UTC, thestr4ng3r approved these changes

2022-04-03 07:44 UTC, merged