Add `RzConfig` for asm plugins
rizinorg/rizin pull request #2488
Opened 2022-04-02 11:39 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Adds an `RzConfig` to asm plugins and some callbacks to communicate with them.

It also updates the hexagon asm plugin to use the new plugins config.

It works roughly like that:

- On plugin `init()`: Plugin initializes its `RzConfig` struct and adds settings (see `hexagon_init(void **user)`).
- `RzAsm.get_config` callback returns the `RzConfig` struct from the plugin.
- On plugin load the config nodes are copied to the `RzCore` config.
- If a config is set via the shell, it sets the `RzCores` copy of the config node.
- The callback of this setting is called and the `RzCores` copy of the node is given to it.
- The cb should be implemented by the plugin!
  In the Hexagon case it simply copies the newly set settings from the `RzCore` node the plugins node.
  But in general the plugin can do with the information as it pleases.
- If the asm plugin was put out of use the `RzCores` copies of the config nodes are deleted.

**Test plan**

- The hexagon analysis tests cover the working of plugin settings.
- (un)set of plugins settings on asm plugin init was tested manually. 

**Closing issues**

None
Prerequisite for https://github.com/rizinorg/rizin/pull/2453

2022-04-02 15:51 UTC, Rot127 commented
Would also add an entry in Rizin Book. But currently missing the time for that.

2022-04-02 15:56 UTC, Rot127 commented
Also, if plugin settings are set in `./config/rizin/rizinrc` they won;t be applied because the plugin is not loaded yet.
I would like to address this bug after the next release. Because time and, I assume, most people won't need it yet.

2022-04-02 16:53 UTC, thestr4ng3r requested changes
Apart from that, lgtm. The config registration should maybe happen at plugin load time rather than `rz_asm_use()` but since the init/fini also happens there, I think this is ok for now.

2022-04-02 16:53 UTC, thestr4ng3r commented on librz/config/config.c
> +	RZ_LOG_WARN("Config locked. Plugin config node not copied.\n");
Free the node here

2022-04-02 17:01 UTC, XVilka requested changes

2022-04-02 17:01 UTC, XVilka commented on librz/asm/asm.c
> +			RZ_LOG_WARN("Failed add %s to the global config.\n", n->name)
I recommend putting the name in the quotes: `\"%s\"`
Also `failed add` sounds odd.

2022-04-02 17:01 UTC, XVilka commented on librz/asm/asm.c
> +			RZ_LOG_WARN("Failed remove %s from the global config.", n->name)
Same here

2022-04-02 17:01 UTC, XVilka commented on librz/asm/asm.c
> +	RzConfig *conf = ((RzCore *)(rz_asm->core))->config;
I don't like this kind of access. But I guess right now there is no better way.

2022-04-02 17:01 UTC, XVilka commented on librz/config/config.c
> +RZ_API bool rz_config_add_node(RZ_BORROW RzConfig *cfg, RZ_OWN RzConfigNode *node) {
Add Doxygen please.

2022-04-02 17:01 UTC, XVilka commented on librz/config/config.c
> +	if (!cfg->lock) {
Maybe reverse the condition?

2022-04-03 08:59 UTC, XVilka approved these changes

2022-04-03 09:11 UTC, thestr4ng3r approved these changes

2022-04-03 12:44 UTC, merged