Add big endian PPC relocs
rizinorg/rizin pull request #2502
Opened 2022-04-05 10:44 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Extracts the PPC changes made here: https://github.com/rizinorg/rizin/pull/1699

**Test plan**

Two tests for `R_PPC_JMP_SLOT` and `R_PPC_RELATIVE` were added.
The expected values are from IDA.

Unfortunately both tests fail and are therefore marked as broken.

Based on a little debugging the `P` values are incorrect. Possibly a general bug in the elf relocation code?

**Closing issues**

...

2022-04-05 11:48 UTC, wargio approved these changes

2022-04-05 12:20 UTC, ret2libc requested changes
I think it's better to keep the `word` as 1/2/4/8 because it seems to be so in the rest of the file.

2022-04-05 15:16 UTC, ret2libc requested changes
Are you sure about the `rz_buf_write_ble32_at(rbuf, patch_addr, ...`? Before it was using `rz_write_le32` and I think it makes more sense because rbuf is probably 8 bytes at most, or somethning like that.

2022-04-05 15:49 UTC, Rot127 commented
TBH I did not really thought about it. @08A  noted it in https://github.com/rizinorg/rizin/pull/1699 and I just assumed it is better.
But I agree that  `rz_write_ble32_at` is not necessary.
Anyways. Found a typo this way.

2022-04-06 00:37 UTC, XVilka approved these changes

2022-04-06 01:18 UTC, merged