RzCore: save/restore bits and arch config values while printing
rizinorg/rizin pull request #2509
Opened 2022-04-06 09:33 UTC by ret2libc

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

rz_analysis_op calls archbits in RzCoreBind, which sets the arch/bits according to the hints. However, when you delete a hint it finds that they are NULL, thus it does not set them anymore, leaving the older hint in place. Fix this by saving/restoring the config options before doing print_disasm.

NOTE: `pdi` does not work any way, because it uses rz_asm_op instead of rz_analysis_op, but this is not fixed here because it would be a mess...

**Test plan**

...

**Closing issues**

Closes #2185

2022-04-06 09:34 UTC, ret2libc commented
cc @pelijah

2022-04-06 10:05 UTC, XVilka commented
```
WARNING: rz_config_get: assertion 'cfg && RZ_STR_ISNOTEMPTY(name)' failed (line 76)
```

2022-04-06 11:09 UTC, ret2libc commented
> ```
> WARNING: rz_config_get: assertion 'cfg && RZ_STR_ISNOTEMPTY(name)' failed (line 76)
> ```

I forgot the final NULL.

2022-04-06 12:07 UTC, wargio approved these changes

2022-04-06 13:05 UTC, wargio commented on librz/core/disasm.c
> +	RzConfigHold *rch = rz_config_hold_new(core->config);
alloc failure check?

2022-04-06 13:06 UTC, wargio commented
![image](https://user-images.githubusercontent.com/561184/161981348-bae68891-d9cf-482c-94cd-4f1ca92c770b.png)

2022-04-06 15:47 UTC, ret2libc commented
I have removed from `ds`, in rz_print_disasm, the show_offseg variable and just got the value directly from RzCOnfig. This is because at the moment `ds` is initialized the value of asm.segoff might be wrong and it will be updated accordingly to RzAnalysisHints or whatever else could change that variable.

I think the same problem could happen for other vars as well...

2022-04-07 03:51 UTC, XVilka requested changes

2022-04-07 03:51 UTC, XVilka commented on test/db/cmd/cmd_pd
> +e asm.functions=false
`e asm.arch=x86`

2022-04-07 13:14 UTC, XVilka approved these changes

2022-04-07 14:41 UTC, merged