Fix bug in rz_copy_nbits and add unit test
rizinorg/rizin pull request #2547
Opened 2022-04-17 10:54 UTC by Heersin

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
Suppose we intend to copy `n` bits from a bitvector of length `x` into a bitvector of length `y`, if `copy` operation is valid, `rz_bv_copy_nbits` would copy as many as possible bits instead of `n` bits. 

Example bug case : 
copy 3 bits(0,1,2) into a new bitvector which has the same length. 
- assume the `src bitvector` is `0110 0101`
- expected bitvecotr should be : 0000 0101 
- actual bitvector : 0110 0101 

** Affected Code **
No. Currently rizin only uses it in `il_reg.c`, the `src` and `dst` has the same length 

**Test plan**
see test/unit/test_bitvector.c

2022-04-17 15:27 UTC, wargio approved these changes

2022-04-17 15:35 UTC, wargio requested changes
~~i think the current behavior is correct~~ Hmm. not sure

2022-04-17 15:50 UTC, XVilka approved these changes

2022-04-17 15:57 UTC, wargio commented
can you add a non zero test? like a bitvector with a number in which is copied another number?

2022-04-17 16:03 UTC, Heersin commented
> ~i think the current behavior is correct~ Hmm. not sure

I found this confused behavior when trying to copy lowest `23` bits only from a 32-bitvector to another 32-bitvector, but it copied the whole `32` bits.

2022-04-17 16:07 UTC, Heersin commented
> can you add a non zero test? like a bitvector with a number in which is copied another number?

sorry, what's a non-zero test ? Could u give me an example ?

2022-04-17 16:58 UTC, wargio commented
in your tests you always copy over a zero-filled bitv, can you add an extra test with one with a value?
```
dst = 0x12345678901235566
src = 0x19384
copy_n_bits(dst, src, 33)

2022-04-18 02:57 UTC, Heersin commented
> in your tests you always copy over a zero-filled bitv, can you add an extra test with one with a value?
> 
> ```
> dst = 0x12345678901235566
> src = 0x19384
> copy_n_bits(dst, src, 33)
> ```

Thanks, I added it in the latest commit

2022-04-18 16:45 UTC, thestr4ng3r approved these changes

2022-04-18 16:47 UTC, merged