Convert afM, afm, aft commands to rzshell
rizinorg/rizin pull request #2550
Opened 2022-04-18 20:19 UTC by pelijah

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2022-04-19 12:04 UTC, XVilka requested changes

2022-04-19 12:04 UTC, XVilka commented on librz/core/tui/vmenus.c
> +		rz_core_cmdf(core, "afm $$+$F @ 0x%08" PFMT64x, off);
Please convert this to use the API, if possible.

2022-04-19 18:30 UTC, pelijah commented on librz/core/tui/vmenus.c
> +		rz_core_cmdf(core, "afm $$+$F @ 0x%08" PFMT64x, off);
Idk what `$$+$F` means

2022-04-20 01:35 UTC, XVilka commented on librz/core/tui/vmenus.c
> +		rz_core_cmdf(core, "afm $$+$F @ 0x%08" PFMT64x, off);
See the output of `?$?` - `$$` is the current seek, `$F` is the function beginning (same as `$FB`), at least according to the help.

2022-04-20 19:10 UTC, pelijah commented on librz/core/tui/vmenus.c
> +		rz_core_cmdf(core, "afm $$+$F @ 0x%08" PFMT64x, off);
Ok seems it is equal to (`core->offset` + `addr of function in core->offset`). Super weird.

2022-04-21 10:58 UTC, XVilka approved these changes

2022-04-21 11:55 UTC, wargio approved these changes

2022-04-21 11:56 UTC, merged

2022-04-21 18:57 UTC, pelijah commented on librz/core/tui/vmenus.c
> +		rz_core_cmdf(core, "afm $$+$F @ 0x%08" PFMT64x, off);
I guess it should be `$F+$FS`.