Refactor `afs` and `afsj`
rizinorg/rizin pull request #2578
Opened 2022-05-01 20:04 UTC by theopechli

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pull request fixes a bug in `afsj`.

I tried to use `rz_type_func_save` inside `rz_analysis_function_derive_type` but it would segfault IIRC, so it is only used when `afsj` is called.

**Test plan**

...

**Closing issues**

closes #2561

2022-05-02 02:04 UTC, XVilka requested changes

2022-05-02 02:04 UTC, XVilka commented on librz/analysis/fcn.c
> +RZ_API RZ_OWN RzCallable *rz_analysis_function_clone_type(RzAnalysis *analysis, const RzAnalysisFunction *f) {
Add a brief Doxygen description please

2022-05-02 02:04 UTC, XVilka commented on librz/analysis/fcn.c
> + * by searching in the types database and returns it.
`and returning it`.

2022-05-02 02:04 UTC, XVilka commented on librz/analysis/fcn.c
>  	// At this point the `callable` pointer is *owned*
Can remove this comment then.

2022-05-02 02:04 UTC, XVilka commented on librz/analysis/fcn.c
> +RZ_API RZ_OWN bool rz_analysis_function_derive_args(RzAnalysis *analysis, RzAnalysisFunction *f, RzCallable **callable) {
Same

2022-05-02 02:04 UTC, XVilka commented on librz/analysis/fcn.c
> +RZ_API RZ_OWN void rz_analysis_function_derive_return_type(RzAnalysisFunction *f, RzCallable **callable) {
RZ_OWN is unnecessary then.

2022-05-02 10:57 UTC, XVilka approved these changes
LGTM with a few nitpicks.

2022-05-02 10:57 UTC, XVilka commented on librz/analysis/fcn.c
> +			rz_warn_if_reached();
Remove the `rz_warn_if_reached()`.

2022-05-02 10:57 UTC, XVilka commented on librz/analysis/fcn.c
> +			rz_warn_if_reached();
Remove the `rz_warn_if_reached()`

2022-05-02 10:57 UTC, XVilka commented on librz/analysis/fcn.c
>  	// At this point the `callable` pointer is *owned*
Forgot about this?

2022-05-02 11:04 UTC, theopechli commented on librz/analysis/fcn.c
>  	// At this point the `callable` pointer is *owned*
You want me to remove those 3 comments? Are they not needed?

2022-05-02 11:26 UTC, ret2libc commented on librz/analysis/fcn.c
> +			rz_warn_if_reached();
these are not resolved

2022-05-02 11:28 UTC, XVilka commented on librz/analysis/fcn.c
>  	// At this point the `callable` pointer is *owned*
It was needed when it was a part of the function, now it's always owned. Only two lines, keep the TODO

2022-05-02 11:29 UTC, theopechli commented on librz/analysis/fcn.c
> +			rz_warn_if_reached();
yea i just pushed, sorry

2022-05-03 03:07 UTC, XVilka approved these changes

2022-05-03 03:08 UTC, merged