RzCore: add scr.prompt.flag.only config var
rizinorg/rizin pull request #2606
Opened 2022-05-12 07:27 UTC by ret2libc

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

Fixes #866

2022-05-12 12:12 UTC, XVilka commented
I am not sure `hello_world:` part is needed. What about hiding it?

2022-05-12 12:18 UTC, ret2libc commented
> I am not sure `hello_world:` part is needed. What about hiding it?

It is just to show a full example. hello_world is the name of the binary and it is shown only when scr.prompt.file=true.

Before it was like this:
```
[0x00005e50]> e scr.prompt.file=true
"ls"[0x00005e50]> 
```

And I find it not that good to look at.

2022-05-12 14:49 UTC, XVilka requested changes
Please add tests. The idea looks good.

2022-05-13 08:01 UTC, ret2libc commented
> Please add tests. The idea looks good.

I'm having troubles capturing the prompt in the tests actually...

2022-05-13 14:01 UTC, XVilka requested changes

2022-05-13 14:01 UTC, XVilka commented on librz/core/core.c
> +	if (rz_config_get_i(core->config, "scr.prompt.flag")) {
Use `rz_config_get_b()` for booleans.

2022-05-13 14:01 UTC, XVilka commented on librz/core/core.c
> +	if (!rz_config_get_i(core->config, "scr.prompt.sect")) {
`rz_config_get_b()`?

2022-05-13 14:01 UTC, XVilka commented on librz/core/core.c
> +	if (rz_config_get_i(core->config, "asm.segoff")) {
It's probably also a boolean, right?

2022-05-14 04:58 UTC, kazarmy reviewed
> I'm having troubles capturing the prompt in the tests actually...

Technically I think you can:
https://github.com/rizinorg/rizin/blob/a1c2ed18d762d3641e6690e0cb6b58b45f1c3609/test/db/tools/rz#L183-L188
but due to the way the prompt works, there will probably be a ton of test output.

2022-05-14 05:00 UTC, kazarmy commented
Or you can just set config vars using `-e` and see what the initial prompt is.

2022-05-16 08:36 UTC, ret2libc commented
Thanks @kazarmy ! @XVilka I added the test and fixed the comments, please review again.

2022-05-16 10:01 UTC, wargio approved these changes

2022-05-16 11:04 UTC, XVilka approved these changes

2022-05-16 11:16 UTC, merged