RzUtil: fix rz_path_prefix in case of portable build
rizinorg/rizin pull request #2642
Opened 2022-05-27 15:43 UTC by ret2libc

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Before this patch the function was using RZ_PREFIX even when IS_PORTABLE
was set, making the function not working well because RZ_PREFIX might
not exist in the system where the portable build is used (the path was
passed to realpath(), which requires an existing path).

This patch fixes the problem by searching for the BINDIR without using
realpath() on the RZ_PREFIX. Moreover, it avoid retrieving the same
prefix every time by saving it in a global variable.

**Test plan**

- Build with -Dportable=true, `eco` should list all themes
- Build with -Dportable=true --bindir=., `eco` should list all themes
- Build with -Dportable=false, `eco` should list all themes

To better test, spawn a clean container so that files are not loaded from user home dir or other system places.

@wargio Would this work for Cutter as well?

2022-05-27 16:57 UTC, XVilka commented on librz/util/path.c
> +	if (rz_str_startswith(filename, "test_")) {
Why is that?

2022-05-27 16:58 UTC, XVilka commented on librz/util/path.c
> + * Executables starting with "test_" are considered to be part of the testing
Never mind, I see. Maybe duplicate comment there?

2022-05-27 19:40 UTC, wargio commented on librz/util/path.c
> +	if (rz_str_startswith(filename, "test_")) {
i think is related to the test suite.

2022-05-27 19:42 UTC, wargio approved these changes

2022-05-28 03:17 UTC, XVilka requested changes
Windows builds should be fixed. Please also use `dist-` branch to be sure it works on all systems supported by CI.

2022-05-30 11:06 UTC, ret2libc commented
https://github.com/rizinorg/rizin/pull/2646

2022-05-30 11:06 UTC, closed without merging