Multithread string search
rizinorg/rizin pull request #2665
Opened 2022-06-06 09:03 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2022-06-22 14:36 UTC, XVilka requested changes
Looks great! And definitely faster

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +	// Rust
A bit more elaborate comment would be nice

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +	// beg critical section
"beg"?

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +			// beg critical section
Same

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +static bool create_string_search_thread(RzThreadPool *pool, RzThreadLock *lock, RzBinFile *bf, size_t min_length, RzThreadQueue *intervals, HtUP *strings_db) {
Maybe split this long line?

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +	} else if (b->paddr > a->paddr) {
Maybe reverse the condition to exit quickly?

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +	// load objc/swift strings from cfstring table section
`CFstring` I think?

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +			RZ_LOG_WARN("bin_file_strings: search interval size (0x%" PFMT64x ") exeeds bin.maxstrbuf (0x%" PFMT64x "), skipping it.\n", section->size, max_interval);
Split this line please

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +RZ_API RZ_OWN RzList *rz_bin_file_strings(RZ_NONNULL RzBinFile *bf, size_t min_length, bool raw_strings) {
Can be `min_length == 0`? Should check with the assert and add a comment please

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +		if (section_size & (0x10000 - 1)) {
extract this constant into the define and use it

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +			RZ_LOG_WARN("bin_file_strings: search interval size (0x%" PFMT64x ") exeeds bin.maxstrbuf (0x%" PFMT64x "), skipping it.\n", section_size, max_interval);
Split the long line

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +				RZ_LOG_WARN("bin_file_strings: search interval size (0x%" PFMT64x ") exeeds bin.maxstrbuf (0x%" PFMT64x "), skipping it.\n", section->size, max_interval);
Split

2022-06-22 14:36 UTC, XVilka commented on librz/bin/bfile_string.c
> +			if (is_data_section(bf, section)) {
You can do `if !is_data_section() { continue }`

2022-06-22 15:22 UTC, wargio commented on librz/bin/bfile_string.c
> +	// Rust
that is actually a copy and paste

2022-06-27 14:48 UTC, XVilka approved these changes

2022-06-27 21:34 UTC, merged