Bump version to v0.5.0 for development
rizinorg/rizin pull request #2669
Opened 2022-06-06 17:26 UTC by ret2libc

2022-06-06 18:27 UTC, wargio requested changes
Let's wait for the release before bumping

2022-06-06 23:26 UTC, XVilka approved these changes

2022-06-08 06:59 UTC, ret2libc commented
@wargio I would go ahead with this. At this point we have already merged dev in stable, so the rest of the fixes need to be cherry-picked and we can move forward with dev.

2022-06-08 08:09 UTC, wargio approved these changes

2022-06-08 08:09 UTC, merged