Optimizations for printing disassembly
rizinorg/rizin pull request #2687
Opened 2022-06-11 06:01 UTC by GustavoLCR

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

* Stops rizin from reloading arch profiles every time you move in disassembly
* Optimizes calculating current row/column
* Caches console output buffer size to avoid expensive syscall

**Test plan**

Tests pass, disassembly works

**Closing issues**

None

2022-06-11 08:42 UTC, wargio commented on librz/include/rz_cons.h
> +	// Memoized last calculated row/column inside buffer
Save the last calculated row/column...

2022-06-11 08:42 UTC, wargio commented on librz/include/rz_util/rz_print.h
> +	// Memoized current row number to calculate screen_bounds
Save current row number ...

2022-06-11 13:04 UTC, XVilka requested changes
It broke some of the output in tests:
```

[XX] db/cmd/cmd_pd asm.cmt.esil
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -F prg -Qc 'e asm.cmt.esil=1
e asm.cmt.right=0
pd 3 @ 0x80e
?e --
e asm.cmt.right=1
pd 3 @ 0x80e
' bins/prg/t01.prg
-- stdout
--- expected
+++ actual
@@ -1,10 +1,7 @@
-            ; 0x41,a,=,$z,Z,:=,7,$s,N,:=
             0x0000080e      lda #0x41
-            ; 0xff,x,=,$z,Z,:=,7,$s,N,:=
             0x00000810      ldx #0xff
-            ; a,x,0x03ff,+,=[1]
             0x00000812      sta 0x03ff,x
 --
-            0x0000080e      lda   #0x41                                ; 0x41,a,=,$z,Z,:=,7,$s,N,:=
-            0x00000810      ldx   #0xff                                ; 0xff,x,=,$z,Z,:=,7,$s,N,:=
-            0x00000812      sta   0x03ff,x                             ; a,x,0x03ff,+,=[1]
+            0x0000080e      lda   #0x41
+            0x00000810      ldx   #0xff
+            0x00000812      sta   0x03ff,x
-- stderr
WARNING: No calling convention defined for this file, analysis may be inaccurate.
[XX] db/cmd/cmd_pd asm.cmt.il
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -F prg -Qc 'e asm.cmt.il=1
e asm.cmt.right=0
pd 3 @ 0x80e
?e --
e asm.cmt.right=1
pd 3 @ 0x80e
' bins/prg/t01.prg
-- stdout
--- expected
+++ actual
@@ -1,10 +1,7 @@
-            ; (seq (set a (bv 8 0x41)) (set Z (is_zero (var a))) (set N (msb (var a))))
             0x0000080e      lda #0x41
-            ; (seq (set x (bv 8 0xff)) (set Z (is_zero (var x))) (set N (msb (var x))))
             0x00000810      ldx #0xff
-            ; (store 0 (+ (bv 16 0x3ff) (cast 16 false (var x))) (var a))
             0x00000812      sta 0x03ff,x
 --
-            0x0000080e      lda   #0x41                                ; (seq (set a (bv 8 0x41)) (set Z (is_zero (var a))) (set N (msb (var a))))
-            0x00000810      ldx   #0xff                                ; (seq (set x (bv 8 0xff)) (set Z (is_zero (var x))) (set N (msb (var x))))
-            0x00000812      sta   0x03ff,x                             ; (store 0 (+ (bv 16 0x3ff) (cast 16 false (var x))) (var a))
+            0x0000080e      lda   #0x41
+            0x00000810      ldx   #0xff
+            0x00000812      sta   0x03ff,x
-- stderr
WARNING: No calling convention defined for this file, analysis may be inaccurate.
[XX] db/analysis/avr avr DISasm: IO-Ports
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'pd 13 @ 0x00000282' bins/firmware/arduino_avr.bin
-- stdout
--- expected
+++ actual
@@ -1,13 +1,13 @@
-            0x00000282      in    r24, 0x12                            ; IO Output pins/pullups address for port D
+            0x00000282      in    r24, 0x12
             0x00000284      subi  r24, 0x80
-            0x00000286      out   0x12, r24                            ; IO Output pins/pullups address for port D
+            0x00000286      out   0x12, r24
             0x00000288      ret
             0x0000028a      ldi   r22, 0x7d
             0x0000028c      ldi   r23, 0x01
             0x0000028e      ldi   r24, 0x2f
             0x00000290      ldi   r25, 0x02
             0x00000292      call  0x8e6
-            0x00000296      in    r24, 0x18                            ; IO Output pins/pullups address for port B
+            0x00000296      in    r24, 0x18
             0x00000298      subi  r24, 0x80
-            0x0000029a      out   0x18, r24                            ; IO Output pins/pullups address for port B
+            0x0000029a      out   0x18, r24
             0x0000029c      ret
```
https://github.com/rizinorg/rizin/runs/6841381548?check_suite_focus=true#step:12:280

2022-06-11 13:04 UTC, XVilka commented on librz/util/print.c
>  /* set screen_bounds to addr if the cursor is not visible on the screen anymore.
If you change this function - please convert the description to Doxygen.

2022-06-12 11:59 UTC, XVilka requested changes
Looks good from the code PoV but there are two tests broken:
```

[XX] db/cmd/cmd_pd asm.cmt.esil
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -F prg -Qc 'e asm.cmt.esil=1
e asm.cmt.right=0
pd 3 @ 0x80e
?e --
e asm.cmt.right=1
pd 3 @ 0x80e
' bins/prg/t01.prg
-- stdout
--- expected
+++ actual
@@ -1,10 +1,7 @@
-            ; 0x41,a,=,$z,Z,:=,7,$s,N,:=
             0x0000080e      lda #0x41
-            ; 0xff,x,=,$z,Z,:=,7,$s,N,:=
             0x00000810      ldx #0xff
-            ; a,x,0x03ff,+,=[1]
             0x00000812      sta 0x03ff,x
 --
-            0x0000080e      lda   #0x41                                ; 0x41,a,=,$z,Z,:=,7,$s,N,:=
-            0x00000810      ldx   #0xff                                ; 0xff,x,=,$z,Z,:=,7,$s,N,:=
-            0x00000812      sta   0x03ff,x                             ; a,x,0x03ff,+,=[1]
+            0x0000080e      lda   #0x41
+            0x00000810      ldx   #0xff
+            0x00000812      sta   0x03ff,x
-- stderr
WARNING: No calling convention defined for this file, analysis may be inaccurate.

[XX] db/analysis/arm arm-or-thumb visual bug
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e scr.interactive=1
e scr.null=1
Vprdfq
e scr.null=0
afi~^size[1]
' bins/mach0/arm-or-thumb
-- stdout
--- expected
+++ actual
@@ -1,1 +1,0 @@
-32
-- exit status: -1
[**]                        
```

2022-06-12 11:59 UTC, XVilka commented on librz/core/disasm.c
> +#define DS_ANALYSIS_OP_MASK (RZ_ANALYSIS_OP_MASK_BASIC | RZ_ANALYSIS_OP_MASK_ESIL | RZ_ANALYSIS_OP_MASK_VAL | (ds->show_cmt_il ? RZ_ANALYSIS_OP_MASK_IL : 0))
Please split this long line.

2022-06-17 07:36 UTC, ret2libc commented on librz/include/rz_arch.h
> +	char *path;
doxygen doc of what this represents

2022-06-17 13:52 UTC, XVilka approved these changes
Looks good overall, please address these small comments.

2022-06-17 13:52 UTC, XVilka commented on librz/cons/cons.c
> -	int i, col = 0;
I recommend also adding `rz_return_val_if_fail(rows, 0)` and `RZ_NONNULL`

2022-06-19 04:10 UTC, XVilka approved these changes

2022-06-19 08:43 UTC, wargio approved these changes

2022-06-19 09:29 UTC, merged