Better False-Positive Detection in rz_scan_strings
rizinorg/rizin pull request #2691
Opened 2022-06-13 18:42 UTC by borzacchiello

Hello everyone!
I tried to improve rz_scan_strings, with the main goal of making the false-positive check more robust, and fix #1836.
I also added a global option to activate/deactivate a check in the false-positive detection function. I am not sure that I added it in the correct way, so let me know.

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This PR adds the following features:
- Extend the false-positive check on ASCII frequencies to all UTF strings (previously it was performed only on UTF16LE strings).
- Add a global option to activate/deactivate the above mentioned check.
- Improve the false-positive heuristic adding a special case for extended-ASCII strings. This is useful for European languages.

I had to modify some regression test, because some of them checked the number of detected strings that is changed due to the PR.
The removed strings should be only false-positives: this [zip file (https://github.com/rizinorg/rizin/files/8893588/strings_diff.zip) contains a diff for each binary of the regression tests for which the number of strings found changed due to this PR.

**Test plan**

...

**Closing issues**

closes #1836

2022-06-13 20:18 UTC, wargio approved these changes

2022-06-14 00:12 UTC, XVilka requested changes
Looks good! I will check more with non-European languages tonight and will merge if it works well. Awesome job! 💯

2022-06-14 00:12 UTC, XVilka commented on librz/core/cconfig.c
> +	SETCB("str.search.check_ascii_freq", "true", &cb_strsearch_check_ascii_freq, "Skip ASCII frequency analysis when looking for false positives during string search");
Split the long line

2022-06-14 06:54 UTC, borzacchiello commented on librz/core/cconfig.c
> +	SETCB("str.search.check_ascii_freq", "true", &cb_strsearch_check_ascii_freq, "Skip ASCII frequency analysis when looking for false positives during string search");
done!

2022-06-14 13:51 UTC, XVilka approved these changes
Does not cause regressions on non-European languages. 👍

2022-06-14 14:14 UTC, merged