Rz-test: assign the expected successful and failed test
rizinorg/rizin pull request #2693
Opened 2022-06-14 07:29 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**
closes https://github.com/rizinorg/rizin/issues/2029

...

2022-06-14 13:06 UTC, XVilka approved these changes

2022-06-14 14:59 UTC, ret2libc requested changes

2022-06-14 14:59 UTC, ret2libc commented on binrz/rz-test/rz-test.c
> +			if (!rz_str_isnumber(opt.arg) || expect_succ < 0) {
rz_num_is_valid_input

2022-06-14 14:59 UTC, ret2libc commented on binrz/rz-test/rz-test.c
> +			if (!rz_str_isnumber(opt.arg) || expect_fail < 0) {
rz_num_is_valid_input

2022-06-16 07:00 UTC, ret2libc approved these changes

2022-06-16 08:46 UTC, wargio approved these changes

2022-06-16 10:14 UTC, merged