Add libmspack and add idpx to extracts compressed pdb
rizinorg/rizin pull request #2728
Opened 2022-06-22 23:01 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Removes the need to call cabextract/expand and directly embeds libmspack which does unpack cabs files.
Also adds `idpx <file.pdb> <output_dir>` which allows to extract a compressed PDB file to a folder

2022-06-22 23:37 UTC, wargio commented
@GustavoLCR wanna check this?

2022-06-24 03:29 UTC, GustavoLCR approved these changes

2022-06-24 14:54 UTC, XVilka requested changes
Looks good, but:
```
 [XX] db/formats/pdb Extract pdb via idbx
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'idpi bins/pdb/basic32.pd_
e log.level=3
idpx bins/pdb/basic32.pd_ .tmp
!rz-hash -a md5 .tmp/basic32.pdb
' =
-- stderr
--- expected
+++ actual
@@ --1,4 +-1,5 @@
 ERROR: The pdb file bins/pdb/basic32.pd_ seems to be compressed, please use idpx command to extract the contents.
+../subprojects/libmspack/libmspack/mspack/cabd.c:1403:66: runtime error: left shift of 156 by 24 places cannot be represented in type 'int'
 INFO: cab_extract: extracted .tmp/basic32.pdb
 ```
 ```
 ../subprojects/libmspack/libmspack/mspack/chmd.c: In function ‘chmd_extract’:
../subprojects/libmspack/libmspack/mspack/chmd.c:1139:10: error: ‘length’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1139 |   length -= self->d->offset;
      |          ^~
../subprojects/libmspack/libmspack/mspack/chmd.c:1042:9: note: ‘length’ was declared here
 1042 |   off_t length, offset;
      |         ^~~~~~
cc1: all warnings being treated as errors
```

2022-06-24 14:54 UTC, XVilka commented on librz/bin/pdb/cab_extract.c
> + * \brief  Extracts compressed pdb files into a folder.
It's PDB not pdb

2022-06-27 13:42 UTC, XVilka approved these changes
Please send PR with a patch upstream

2022-06-27 21:51 UTC, wargio commented
PR pushed, if it gets merged, i will remove the patches and update the commit

2022-06-27 21:52 UTC, merged