In Vv mode allow filter flags in the left column
rizinorg/rizin pull request #2764
Opened 2022-07-01 10:18 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Add filter in Vv mode. `f` adds the new keyword. `F` clears all keywords. This pr also adds hints of the current keywords. 

...
![2022-07-04_10-37-48](https://user-images.githubusercontent.com/58985155/177072858-6fd2411e-edb5-40b7-a82b-5926ca25ec71.gif)

**Test plan**

CI is green. 

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/2750
...

2022-07-01 14:45 UTC, XVilka requested changes

2022-07-01 14:45 UTC, XVilka commented on librz/include/rz_core.h
> +	RzList *visual_filter; // store the filter keywords in visual mode
I don't see any deletion of the elements, I wonder if RzPVector would be a better fit here.

2022-07-01 14:45 UTC, XVilka commented on librz/core/tui/vmenus.c
> +			char *keyword = malloc(256);
Please extract this number at least to `#define`, here and below.

2022-07-01 17:04 UTC, PeiweiHu commented on librz/include/rz_core.h
> +	RzList *visual_filter; // store the filter keywords in visual mode
Ok. I will change it later.

2022-07-02 02:28 UTC, XVilka requested changes
I tested this and it works, thank you!
One minor thing - I think it's better to show the filter keywords outside of the "legend" area, maybe below the function list? Though that's my opinion, lets see what others say.

2022-07-02 02:41 UTC, PeiweiHu commented
> Another question would be, if it makes sense to start filtering _during the typing_, thus the results will be clear immediately. For example, you often can mistype or get the lowercase/uppercase wrong. Filtering on the go has some _explorative_ spirit.

Good idea. I'd like to give it a shot.

2022-07-04 02:54 UTC, PeiweiHu commented
> Another question would be, if it makes sense to start filtering _during the typing_, thus the results will be clear immediately. For example, you often can mistype or get the lowercase/uppercase wrong. Filtering on the go has some _explorative_ spirit.

Now it supports filtering on the go, as shown in the gif.

2022-07-05 16:50 UTC, wargio approved these changes

2022-07-06 09:47 UTC, XVilka approved these changes

2022-07-06 09:50 UTC, merged