Use `rz_buf_fwd_scan()` API
rizinorg/rizin pull request #2772
Opened 2022-07-03 03:21 UTC by GustavoLCR

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Use `rz_buf_fwd_scan()` API instead of reimplementing the logic

**Test plan**

Tests pass

**Closing issues**

None

2022-07-03 03:33 UTC, XVilka approved these changes

2022-07-03 03:40 UTC, XVilka requested changes
Looks like it produced different results:
```

[XX] db/cmd/cmd_i it2
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'mkdir .tmp
cp bins/mach0/fatmach0-3true .tmp/it2-modfile
o .tmp/it2-modfile
oo+
it
wx 0x90
it
o--
rm .tmp/it2-modfile
' --
-- stdout
--- expected
+++ actual
@@ -1,5 +1,5 @@
-md5 84144530144b53a704c84d9c65ab5f92
-sha1 9016e215a321184c42c28ab03847554851932713
-sha256 95debaecaaaf89c7f5151218def15ef18c8be375aeccf0564a3b16416c361012
-crc32 611b58cd
-entropy 2.959094
+md5 8230c469bb584af01ebe4be05c69a34e
+sha1 3fa51350460086c97c8ede286bac92f716672ec9
+sha256 ea416d7ff1d0917fde0fa7a70ddb64287763fee3457ecff16e406a05af63b336
+crc32 57524658
+entropy 3.534027
-- stderr
--- expected
+++ actual
@@ --1,13 +-1,13 @@
 File has been modified.
-- md5 84144530144b53a704c84d9c65ab5f92
-+ md5 9a99cca7bf3e27ee1c8964141cfad053
-- sha1 9016e215a321184c42c28ab03847554851932713
-+ sha1 17c5b6331a420fc3b48defe782090295294fee2e
-- sha256 95debaecaaaf89c7f5151218def15ef18c8be375aeccf0564a3b16416c361012
-+ sha256 53cb8b3aec20da6a313ac996ca8f518bca9fa4768ff771d35513be09a387f025
-- crc32 611b58cd
-+ crc32 1ae319dc
-- entropy 2.959094
-+ entropy 2.959088
+- md5 8230c469bb584af01ebe4be05c69a34e
++ md5 ba994b1c7cfb6d2226172f27c83d1694
+- sha1 3fa51350460086c97c8ede286bac92f716672ec9
++ sha1 b4eff789af9150d74e502cae4d4f12c8667f59c0
+- sha256 ea416d7ff1d0917fde0fa7a70ddb64287763fee3457ecff16e406a05af63b336
++ sha256 90e87e9a13c350b3968e4f107436e8d865712fd36d7eab8559136b7b0363bdff
+- crc32 57524658
++ crc32 39f81e9a
+- entropy 3.534027
++ entropy 3.533999
```

2022-07-03 10:07 UTC, ret2libc approved these changes
Awesome!

2022-07-04 00:00 UTC, XVilka approved these changes

2022-07-04 12:54 UTC, merged

2022-07-04 13:58 UTC, XVilka commented
It caused one fuzzing error:
```

[XX] /home/runner/work/rizin/rizin/test/bins/fuzzed <fuzz> /home/runner/work/rizin/rizin/test/bins/fuzzed/0ab867f76e0ccc0cd3c53abf6ba909d7
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc aaa /home/runner/work/rizin/rizin/test/bins/fuzzed/0ab867f76e0ccc0cd3c53abf6ba909d7
-- stdout
-- stderr
-- exit status: -1
[**]     /home/runner/work/rizin/rizin/test/bins/fuzzed      545 OK         0 BR        1 XX        0 FX
```