Remove command aC
rizinorg/rizin pull request #2793
Opened 2022-07-08 08:05 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Convert command `aC` to new shell.
- Function `show_reg_args` is moved to **canalysis.c** from **cmd_analysis.c**.
- Function `cmd_analysis_aC` is renamed to `rz_core_analysis_call_args` and moved to **canalysis.c** from **cmd_analysis.c**.
- No functional changes except for trivial hints and return value. 

**Test plan**

CI is green. 

**Closing issues**

partially address https://github.com/rizinorg/rizin/issues/1442

2022-07-08 08:40 UTC, XVilka requested changes

2022-07-08 08:40 UTC, XVilka commented on librz/core/canalysis.c
> +RZ_API char *rz_core_analysis_call_args(RzCore *core, ut64 pcv) {
Add return value ownership and Doxygen

2022-07-08 08:40 UTC, XVilka commented on librz/include/rz_core.h
> +RZ_API char *rz_core_analysis_call_args(RzCore *core, ut64 pcv);
Return value ownership

2022-07-08 09:03 UTC, wargio commented on librz/core/canalysis.c
> +	if (go_on) {
can you remove these `if (go_on)` ? essentially each time there is `go_on = false`, just replace it with `return rz_strbuf_drain(sb);`.

2022-07-08 09:09 UTC, ret2libc requested changes
This whole command is not even tested currently as you can see from the coverage at https://app.codecov.io/gh/rizinorg/rizin/blob/dev/librz/core/cmd/cmd_analysis.c . It should be covered .

Also, probably the old code can be rewritten in a much cleaner way to improve readability. It would benefit also from some error message instead of just printing "random" things.

2022-07-08 09:09 UTC, ret2libc commented on librz/core/cmd_descs/cmd_analysis.yaml
> +        type: RZ_CMD_ARG_TYPE_RZNUM
remove this arg and juts use core->offset. Users can change address through `@`.

2022-07-08 09:09 UTC, ret2libc commented on librz/core/canalysis.c
> +RZ_API char *rz_core_analysis_call_args(RzCore *core, ut64 pcv) {
also, what is `pcv`?

2022-07-08 09:09 UTC, ret2libc commented on librz/core/canalysis.c
> +	if (go_on) {
just exit earlier if `!go_on` because nothing will be executed anyway apart from the last `rz_strbuf_drain`.

2022-07-08 09:09 UTC, ret2libc commented on librz/core/canalysis.c
> +		char *key = (fcn_name) ? resolve_fcn_name(core->analysis, fcn_name) : NULL;
```suggestion
		char *key = fcn_name ? resolve_fcn_name(core->analysis, fcn_name) : NULL;
```

2022-07-08 09:09 UTC, ret2libc commented on librz/core/canalysis.c
> +	}
i don't see this function being called anywhere with a `nargs` value != -1

2022-07-20 13:52 UTC, XVilka commented
Please remove them, force push, and lets merge it.

2022-07-20 15:27 UTC, PeiweiHu commented
`aC` is removed currently.

2022-07-20 15:30 UTC, XVilka approved these changes

2022-07-20 18:46 UTC, wargio approved these changes

2022-07-20 18:46 UTC, merged