Fix #2856 - Fix rizin on Windows over OpenSSH
rizinorg/rizin pull request #2896
Opened 2022-08-10 07:54 UTC by GustavoLCR

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Fixes for rizin under terminal emulators such as `mintty` and over an OpenSSH connection.
Stops using `TERM` environment variable to determining VT compatibility.
Uses stdin file name to detect `msys` and `cygwin` ptys

**Test plan**

Tested manually

**Closing issues**

Fixes #2856

2022-08-10 13:57 UTC, XVilka requested changes

2022-08-10 13:57 UTC, XVilka commented on librz/cons/cons.c
>  			ret = __xterm_get_size();
If you rename `term_xterm` to `term_pty`, maybe it makes sense also to rename this function?

2022-08-10 13:57 UTC, XVilka commented on librz/cons/cons.c
> +static inline bool is_win_10_creators_or_above(DWORD major, DWORD minor, DWORD release) {
Add a small comment, please why do we check for this, what has changed?

2022-08-10 13:57 UTC, XVilka commented on librz/cons/cons.c
> +		if (ENABLE_VIRTUAL_TERMINAL_PROCESSING && is_win_10_creators_or_above(major, minor, release)) {
Or here

2022-08-10 13:58 UTC, XVilka commented
@GustavoLCR it also seem to break Windows unit tests:
```
Summary of Failures:
 21/111 rizin:unit / compare                               TIMEOUT        300.21s   exit status 1
 22/111 rizin:unit / cons                                  TIMEOUT        300.18s   exit status 1
Ok:                 109 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            2 
```

2022-08-15 07:56 UTC, thestr4ng3r approved these changes
Tested and works on my setup. Thank you very much!

2022-08-15 07:58 UTC, thestr4ng3r commented
@GustavoLCR The history looks nice, should we rebase+merge instead of squash here?

2022-08-15 13:33 UTC, XVilka approved these changes

2022-08-18 12:11 UTC, XVilka commented
Let's keep history for future generations.

2022-08-18 12:11 UTC, merged