Set asm.tabs to 6
rizinorg/rizin pull request #290
Opened 2021-01-03 13:26 UTC by ITAYC0HEN

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2021-01-03 19:51 UTC, ret2libc commented
I don't like the extra (and unnecessary) space after the first operand. Otherwise it is fine for me.

2021-01-03 20:51 UTC, ITAYC0HEN commented
The screenshot I put is wrong.will update tomorrow.
The pr enables asm.tabs.once that doesn't add spaces after operands

2021-01-04 08:45 UTC, ret2libc approved these changes
It looks nicer to me, but I suggest this gets all the 6 approvals before merging.

2021-01-04 11:50 UTC, wargio approved these changes

2021-01-04 13:40 UTC, XVilka approved these changes
It might become problematic on super-long instructions probably, like some AVX instructions or TMS320CXX ones.

2021-01-04 13:42 UTC, ITAYC0HEN commented
On AVX it still looks better than the default `asm.tabs=0`. I tested

2021-01-04 13:54 UTC, thestr4ng3r approved these changes

2021-01-04 14:17 UTC, kazarmy approved these changes

2021-01-04 14:37 UTC, yossizap approved these changes
Much better :+1:

2021-01-04 14:49 UTC, kazarmy commented
Tests need to be fixed, but something like `pdr~addu t0[7]` is going to be very sensitive to disasm format imo.

2021-01-04 15:04 UTC, kazarmy commented on test/db/cmd/cmd_pdr
>  wx 48c7c01000000075084805b8000000eb064805e60000004889c7c3
```suggestion
e asm.tabs=0
wx 48c7c01000000075084805b8000000eb064805e60000004889c7c3
```

2021-01-04 15:05 UTC, kazarmy commented on test/db/cmd/cmd_pdr
> +pdr~add   rax[6]
```suggestion
pdr~add rax[6]
```

2021-01-04 15:06 UTC, kazarmy commented on test/db/cmd/cmd_pdr
> +e asm.lines.fcn=false
```suggestion
e asm.lines.fcn=false
e asm.tabs=0
```

2021-01-04 15:07 UTC, kazarmy commented on test/db/cmd/cmd_pdr
> +e asm.lines.fcn=false
```suggestion
e asm.lines.fcn=false
e asm.tabs=0
```

2021-01-04 15:07 UTC, kazarmy commented on test/db/cmd/cmd_pdr
> +pdr~addu  t0[7]
```suggestion
pdr~addu t0[7]
```

2021-01-04 15:08 UTC, kazarmy requested changes
Doesn't seem very likely that someone will be counting spaces tbh.

2021-01-04 15:14 UTC, kazarmy approved these changes

2021-01-04 15:45 UTC, merged