Fix android binaries and missing main callbacks
rizinorg/rizin pull request #3044
Opened 2022-09-22 22:18 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The android build seems to call rz_main which tries to find the program name, but the issue is that list is missing some commands and has some old names.

2022-09-22 22:49 UTC, XVilka requested changes

2022-09-22 22:49 UTC, XVilka commented on librz/main/main.c
> +	{ "rz", rz_main_rizin },
There might be a tool installed, called `rz` and completely unrelated to the Rizin.

2022-09-23 07:38 UTC, ret2libc approved these changes
LGTM apart from xvilka's comment.

2022-09-23 08:17 UTC, XVilka approved these changes

2022-09-23 09:30 UTC, merged