Rewrite RzReg to use RzBitVector + RzFloat 128-bit
rizinorg/rizin pull request #3140
Opened 2022-10-30 03:10 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- Rewrite RzReg to use RzBitVector
- Implement 128-bit float

2022-10-30 03:58 UTC, XVilka requested changes
Nice cleanup! Due to how this depends on the target platform, I suggest resending it from `dist-asan-fuzz-*` branch, though.

2022-10-30 03:58 UTC, XVilka commented on librz/util/float/float.c
> + * \brief return a numeric string of the float
I suggest to provide an example in detailed description

2022-10-30 03:58 UTC, XVilka commented on librz/util/float/float.c
> +RZ_API RZ_OWN RzFloat *rz_float_new_from_quadruple(long double value) {
Add Doxygen

2022-10-30 04:24 UTC, XVilka commented
582 broken tests - most of them are related to the output of the same value.

2022-10-30 11:05 UTC, Heersin commented
> 

why does it affect the esil test ? or the esil tests are already broken?

2022-10-30 13:33 UTC, wargio commented
> > 
> 
> why does it affect the esil test ? or the esil tests are already broken?

i just broke everything, but it does affect ESIL because i have removed the old RzReg code

2022-10-31 01:09 UTC, XVilka approved these changes
LGTM, but please resend from `dist-*` branch to trigger everything.

2022-10-31 01:11 UTC, XVilka commented
@wargio Windows build is broken:
```
FAILED: librz/util/rz_util.lib.p/float_float.c.obj 
"cl" "-Ilibrz\util\rz_util.lib.p" "-I." "-I.." "-Ilibrz" "-I..\librz" "-Ilibrz\include" "-I..\librz\include" "-Ilibrz\util\sdb\src" "-I..\librz\util\sdb\src" "-Ilibrz\util\sdb" "-I..\librz\util\sdb" "-Isubprojects\zlib-1.2.12" "-I..\subprojects\zlib-1.2.12" "-I..\subprojects\xz-5.2.5\src\liblzma\api" "/MT" "/nologo" "/showIncludes" "/utf-8" "/W2" "/O2" "/Gw" "-DPSAPI_VERSION=1" "-DRZ_PLUGIN_INCORE=1" "-DLZMA_API_STATIC" "/Fdlibrz\util\rz_util.lib.p\float_float.c.pdb" /Folibrz/util/rz_util.lib.p/float_float.c.obj "/c" ../librz/util/float/float.c
../librz/util/float/float.c(454): error C2065: 'INFINITY': undeclared identifier
../librz/util/float/float.c(481): error C2065: 'INFINITY': undeclared identifier
../librz/util/float/float.c(510): error C2065: 'INFINITY': undeclared identifier
../librz/util/float/float.c(539): error C2065: 'INFINITY': undeclared identifier
../librz/util/float/float.c(2073): warning C4146: unary minus operator applied to unsigned type, result still unsigned
[186/1940] Compiling C object librz/util/rz_util.lib.p/calc.c.obj
```
```
FAILED: librz/util/rz_util-0.5.dll.p/float_float.c.obj 
"clang-cl" "-Ilibrz\util\rz_util-0.5.dll.p" "-I." "-I.." "-Ilibrz" "-I..\librz" "-Ilibrz\include" "-I..\librz\include" "-Ilibrz\util\sdb\src" "-I..\librz\util\sdb\src" "-Ilibrz\util\sdb" "-I..\librz\util\sdb" "-Isubprojects\zlib-1.2.12" "-I..\subprojects\zlib-1.2.12" "-I..\subprojects\xz-5.2.5\src\liblzma\api" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/O2" "-DPSAPI_VERSION=1" "-fcommon" "-D__STDC__=1" "-D_CRT_DECLARE_NONSTDC_NAMES " "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_NONSTDC_NO_DEPRECATE" "-DRZ_PLUGIN_INCORE=1" "-Werror=sizeof-pointer-memaccess" "-DLZMA_API_STATIC" "/Fdlibrz\util\rz_util-0.5.dll.p\float_float.c.pdb" /Folibrz/util/rz_util-0.5.dll.p/float_float.c.obj "/c" ../librz/util/float/float.c
../librz/util/float/float.c(193,35): warning: format specifies type 'double' but the argument has type 'long double' [-Wformat]
        return rz_str_newf("%" LDBLFMTg, result);
                            ~~~~~~~~~~~  ^~~~~~
../librz/util/float/float.c(454,61): error: use of undeclared identifier 'INFINITY'
                return rz_float_new_inf(RZ_FLOAT_IEEE754_BIN_32, value != F32_PINF);
                                                                          ^
..\librz\include\rz_types_base.h(100,27): note: expanded from macro 'F32_PINF'
#define F32_PINF  ((float)INFINITY)
                          ^
../librz/util/float/float.c(481,61): error: use of undeclared identifier 'INFINITY'
                return rz_float_new_inf(RZ_FLOAT_IEEE754_BIN_64, value != F64_PINF);
                                                                          ^
..\librz\include\rz_types_base.h(103,20): note: expanded from macro 'F64_PINF'
#define F64_PINF  (INFINITY)
                   ^
../librz/util/float/float.c(510,61): error: use of undeclared identifier 'INFINITY'
                return rz_float_new_inf(RZ_FLOAT_IEEE754_BIN_80, value != F128_PINF);
                                                                          ^
..\librz\include\rz_types_base.h(106,33): note: expanded from macro 'F128_PINF'
#define F128_PINF ((long double)INFINITY)
                                ^
../librz/util/float/float.c(539,62): error: use of undeclared identifier 'INFINITY'
                return rz_float_new_inf(RZ_FLOAT_IEEE754_BIN_128, value != F128_PINF);
                                                                           ^
..\librz\include\rz_types_base.h(106,33): note: expanded from macro 'F128_PINF'
#define F128_PINF ((long double)INFINITY)
                                ^
1 warning and 4 errors generated.
```

2022-10-31 01:53 UTC, wargio commented
> LGTM, but please resend from `dist-*` branch to trigger everything.

i will do it once i see it green here.

2022-10-31 02:08 UTC, closed without merging