Add a test for `arS` ##test
rizinorg/rizin pull request #318
Opened 2021-01-06 06:16 UTC by officialcjunior

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Adds a test for `arS`. Basically, I've analyzed a test binary and ran `arS`

**Test plan**

- [ ] Test passes the CI and everyone agrees on the test.

**Closing issues**
Closes #236

2021-01-06 11:41 UTC, Maijin approved these changes

2021-01-09 11:29 UTC, ret2libc requested changes
As discussed on Mattermost, let's kill `arS`.

2021-01-09 14:24 UTC, Maijin commented
You can remove the test then

2021-01-09 14:24 UTC, Maijin approved these changes

2021-01-09 22:53 UTC, ret2libc approved these changes

2021-01-10 11:53 UTC, wargio approved these changes

2021-01-10 11:54 UTC, merged