Convert `pi` commands to rzshell
rizinorg/rizin pull request #3187
Opened 2022-11-14 14:37 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- Convert all `pi` commands to rzshell
- Remove some unreachable code

**Test plan**

- CI is green
- Try different `pi` commands

**Closing issues**

Partially addresses https://github.com/rizinorg/rizin/issues/1590

2022-11-15 08:20 UTC, ret2libc approved these changes

2022-11-15 08:20 UTC, ret2libc commented on librz/core/cmd_descs/cmd_print.yaml
> +        summary: Print instructions using recursive disassembly algorithm
there should be a different description here, otherwise they seem the same.

2022-11-15 08:22 UTC, ret2libc commented on librz/core/cmd/cmd_print.c
> +		rz_core_cmdf(core, "pdfj");
I think there is already an API for this command?

2022-11-15 16:58 UTC, wargio requested changes
Please replace the eprintf at line `3350` inside `cmd_print.c` with `RZ_LOG_ERROR`

2022-11-15 16:58 UTC, wargio commented on librz/core/cmd/cmd_print.c
>  	const bool show_color = core->print->flags & RZ_PRINT_FLAGS_COLOR;
use config api for the color

2022-11-15 16:58 UTC, wargio commented on librz/core/cmd/cmd_print.c
>  	for (i = 0; i < limit; i++) {
define the i into the for loop

2022-11-16 07:28 UTC, ret2libc approved these changes

2022-11-16 09:51 UTC, wargio commented on librz/core/cmd/cmd_print.c
>  	rz_config_set_i(core->config, "asm.bb.middle", false);
This is set but never restored :/

2022-11-16 09:51 UTC, wargio approved these changes

2022-11-16 09:51 UTC, merged