Heap buf rzlog
rizinorg/rizin pull request #3247
Opened 2022-12-14 22:44 UTC by ret2libc

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Before this patch the rz_vlog function was using a local array of 512 bytes, however when dealing with colors and escape chars (e.g. like when printing the commands help after you insert the wrong number of args) the string can easily become very long and it was truncated because of that.

This PR fixes it by just using a RzStrBuf to take care of the growing string to log. It might be a bit slower overall, but we don't care because it is just logging.

I have also removed the `core: ` prefix when printing the error message after inserting the wrong number of args for some commands. User do not care about the error being `core` or something else, they just want to see what to do and the `core: ` makes things harder to read for no good reason. I think we went a bit too far with adding logging information as much as I now see `core: ` or similar everywhere, but we are using RZ_LOG_ERROR also for printing user-displayed errors.

**Test plan**

Running invalid commands like `aesp` or `wv` should still print the correct error message.

**Closing issues**

...

2022-12-15 01:03 UTC, XVilka requested changes
```
gcc-12 -Itest/unit/test_log.p -I. -I.. -Ilibrz -I../librz -Ilibrz/include -I../librz/include -Itest/unit -I../test/unit -Ilibrz/util/sdb/src -I../librz/util/sdb/src -Ilibrz/util/sdb -I../librz/util/sdb -I../librz/asm/arch/include -I../librz/asm/arch -I../librz/asm/arch/h8300 -I../librz/asm/arch/hexagon -I../librz/asm/arch/msp430 -I../librz/asm/arch/rsp -I../librz/asm/arch/mcore -I../librz/asm/arch/v850 -I../librz/asm/arch/propeller -I../librz/asm/arch/ebc -I../librz/asm/arch/cr16 -I../librz/asm/arch/8051 -I../librz/asm/arch/v810 -I../librz/asm/arch/or1k -I../librz/analysis/arch/gb -I../librz/bin/format/elf -I../librz/bin/format/dmp -I../librz/bin/format/mdmp -I../librz/bin/format/pe -I../librz/bin/format -Ilibrz/core/cmd_descs -I../librz/core/cmd_descs -I../librz/type/parser -fdiagnostics-color=always -fsanitize=address,undefined -fno-omit-frame-pointer -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O2 -g -Wimplicit-fallthrough=3 -DRZ_PLUGIN_INCORE=1 -D_GNU_SOURCE --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -DASAN=1 -DRZ_ASSERT_STDOUT=1 -Wno-cpp -MD -MQ test/unit/test_log.p/test_log.c.o -MF test/unit/test_log.p/test_log.c.o.d -o test/unit/test_log.p/test_log.c.o -c ../test/unit/test_log.c
In file included from /usr/include/string.h:535,
                 from ../librz/include/rz_types.h:202,
                 from ../librz/include/rz_util.h:7,
                 from ../test/unit/test_log.c:4:
In function ‘memset’,
    inlined from ‘large_check’ at ../test/unit/test_log.c:17:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:59:10: error: ‘__builtin_memset’ offset [0, 998] is out of the bounds [0, 0] [-Werror=array-bounds]
   59 |   return __builtin___memset_chk (__dest, __ch, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   60 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
```
[XX] db/cmd/cmd_w w_escape
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'wv8\@10
' =
-- stderr
--- expected
+++ actual
@@ -1,7 +1,7 @@
-ERROR: core: Command 'wv8@10' does not exist.
-ERROR: core: Displaying the help of command 'wv8'.
+ERROR: Command 'wv8@10' does not exist.
+ERROR: Displaying the help of command 'wv8'.
 
-ERROR: core: Usage: wv8 <value>   # Write value of 8 byte
+ERROR: Usage: wv8 <value>   # Write value of 8 byte
 
 Write the number passed as argument at the current offset as 8 - bytes, respecting the cfg.bigendian variable
 ```

2022-12-15 01:49 UTC, wargio commented on librz/core/cmd/cmd.c
> +				RZ_LOG_ERROR("Displaying the help of command '%s'.\n\n", hcd->name);
why removing `core:` ?

2022-12-15 08:11 UTC, ret2libc commented on librz/core/cmd/cmd.c
> +				RZ_LOG_ERROR("Displaying the help of command '%s'.\n\n", hcd->name);
See description of the PR

2022-12-15 09:28 UTC, wargio commented
```
FAILED: test/unit/test_log.p/test_log.c.o 
gcc-12 -Itest/unit/test_log.p -I. -I.. -Ilibrz -I../librz -Ilibrz/include -I../librz/include -Itest/unit -I../test/unit -Ilibrz/util/sdb/src -I../librz/util/sdb/src -Ilibrz/util/sdb -I../librz/util/sdb -I../librz/asm/arch/include -I../librz/asm/arch -I../librz/asm/arch/h8300 -I../librz/asm/arch/hexagon -I../librz/asm/arch/msp430 -I../librz/asm/arch/rsp -I../librz/asm/arch/mcore -I../librz/asm/arch/v850 -I../librz/asm/arch/propeller -I../librz/asm/arch/ebc -I../librz/asm/arch/cr16 -I../librz/asm/arch/8051 -I../librz/asm/arch/v810 -I../librz/asm/arch/or1k -I../librz/analysis/arch/gb -I../librz/bin/format/elf -I../librz/bin/format/dmp -I../librz/bin/format/mdmp -I../librz/bin/format/pe -I../librz/bin/format -Ilibrz/core/cmd_descs -I../librz/core/cmd_descs -I../librz/type/parser -fdiagnostics-color=always -fsanitize=address,undefined -fno-omit-frame-pointer -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O2 -g -Wimplicit-fallthrough=3 -DRZ_PLUGIN_INCORE=1 -D_GNU_SOURCE --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -DASAN=1 -DRZ_ASSERT_STDOUT=1 -Wno-cpp -MD -MQ test/unit/test_log.p/test_log.c.o -MF test/unit/test_log.p/test_log.c.o.d -o test/unit/test_log.p/test_log.c.o -c ../test/unit/test_log.c
In file included from /usr/include/string.h:535,
                 from ../librz/include/rz_types.h:202,
                 from ../librz/include/rz_util.h:7,
                 from ../test/unit/test_log.c:4:
In function ‘memset’,
    inlined from ‘large_check’ at ../test/unit/test_log.c:17:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:59:10: error: ‘__builtin_memset’ offset [0, 998] is out of the bounds [0, 0] [-Werror=array-bounds]
   59 |   return __builtin___memset_chk (__dest, __ch, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   60 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

2022-12-19 10:16 UTC, XVilka approved these changes
Ignore Muon failed build - it's a bug in the Muon itself, I will report it later.

2022-12-19 10:46 UTC, merged