Fix: grep(~) will change the original result when ignores case
rizinorg/rizin pull request #3259
Opened 2022-12-23 15:36 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Insensitive grep(~) will change the original result when ignores the case.

run:
```
rizin bins/pe/libzmq-v100-mt-4_0_4.dll
fl~+0x1004e0f4[2]
```
expected: 
```
sym.imp.MSVCP100.dll_public:_void___thiscall_std::basic_ostream_char__struct_std::char_traits_char__::_Osfx_void
```

actual:
```
sym.imp.msvcp100.dll_public:_void___thiscall_std::basic_ostream_char__struct_std::char_traits_char__::_osfx_void
```

**Test plan**

CI is green.

**Closing issues**

...

2022-12-23 16:11 UTC, ret2libc reviewed
Please add a small unit test for `rz_str_case_nstr` in test_str.c

2022-12-23 16:28 UTC, XVilka requested changes

2022-12-23 16:28 UTC, XVilka commented on librz/util/str.c
> +RZ_API const char *rz_str_case_nstr(const char *s, const char *find, int slen) {
check for NULL with asserts, add `RZ_NONNULL`

2022-12-23 16:28 UTC, XVilka commented on librz/util/str.c
>  	const char *ch, *p = a;
Same

2022-12-24 03:03 UTC, kazarmy requested changes
https://github.com/rizinorg/rizin/blob/13cd3942d12b61911e27ab82baef045adf57d77c/test/db/formats/demangling_bin#L71-L73

Modify the test as well.

2022-12-24 15:47 UTC, PeiweiHu commented
Thanks for the constructive comments. Apply all suggestions.

2022-12-24 16:51 UTC, XVilka approved these changes

2022-12-24 23:12 UTC, kazarmy approved these changes

2022-12-25 00:01 UTC, merged