Add FreeBSD x86_64 debug tests
rizinorg/rizin pull request #3273
Opened 2023-01-08 04:11 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Adds basic FreeBSD x86_64 debug tests.

Requires https://github.com/rizinorg/rizin-testbins/pull/101

**Test plan**

FreeBSD CI is green

**Closing issues**

Partially addresses https://github.com/rizinorg/rizin/issues/3072

2023-11-01 12:03 UTC, XVilka commented
@arrowd, you might be interested in this one, by the way. Feel free to send a new PR if you want.

2024-06-01 15:53 UTC, XVilka commented
@kazarmy as you can see, even FreeBSD debugging doesn't work:
```
[XX] db/archos/freebsd-x64/dbg write gpr
RZ_NOPLUGINS=1 /home/build/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -d -qc 'db @ main + 64
dc
dr rax
dr rax = 1337
dc
' bins/elf/calculate-freebsd-x64
-- stdout
--- expected
+++ actual
@@ -1,2 +1,2 @@
-rax = 0x000000000000002a
-Result = 1337
+Result = 42
+Debugging is not enabled. Run ood?

-- stderr
--- expected
+++ actual
@@ -1,4 +1,27 @@
-hit breakpoint at: f70
+Process 
+with 
+PID 
+387 
+child 
+exited 
+with 
+status 
+Process 
+finished
 
-Process finished
 
+ERROR: 
+Failed 
+to 
+read 
+ERROR: 
+No 
+such 
+register 
+or 
+register 
+type: 
+ERROR: 
+Failed 
+to 

```
https://builds.sr.ht/~thestr4ng3r/job/1239045

2024-06-01 16:17 UTC, kazarmy commented
Well that's one reason why no testing was done in #4524 - debugging might have been broken well before the build itself broke

2024-06-02 03:49 UTC, wargio approved these changes

2025-06-23 12:51 UTC, well-mannered-goat commented
Wrote some changes description in the PR

Also in FreeBSD `sysctl` is used to fetch maps first, because `procfs` is not mounted on `\proc\` hence no pid directories are there by default. Also the parsing logic is kind of flawed because of different map format (after mounting procfs)
They aren't fetched from `/proc/` (its the second option if `sysctl` does not work), so I thought this is redundant code and with bugs. Should I remove it?

2025-06-23 15:43 UTC, notxvilka approved these changes

2025-06-23 15:44 UTC, notxvilka commented
> Wrote some changes description in the PR
> 
> Also in FreeBSD `sysctl` is used to fetch maps first, because `procfs` is not mounted on `\proc\` hence no pid directories are there by default. Also the parsing logic is kind of flawed because of different map format (after mounting procfs) They aren't fetched from `/proc/` (its the second option if `sysctl` does not work), so I thought this is redundant code and with bugs. Should I remove it?

It's better to keep but open an issue about it, then we can decide what to do with it in a separate PR.

2025-06-23 16:05 UTC, wargio requested changes
Nice improvement

2025-06-23 16:05 UTC, wargio commented on librz/core/cfile.c
> +		if (map->perm & 4) {
Please use macros for constants. Also there are already macros for the perms.

2025-06-23 16:05 UTC, wargio commented on librz/core/cfile.c
> +		if (map->perm & 4) { // r--
Same here

2025-06-23 16:05 UTC, wargio commented on librz/core/cfile.c
> +		if (map->perm & 4) {
Add also a comment explaining why that value is needed

2025-06-23 16:05 UTC, wargio commented on librz/debug/p/native/bsd/bsd_debug.c
> +	char *name;
Initialize these new values to null/0

2025-06-23 16:05 UTC, wargio commented on librz/debug/p/native/kfbsd.c
> +int match_pid(const void *pid_o, const void *th_o, void *user) {
Is this a boolean,? If yes use true / false

2025-06-23 16:05 UTC, wargio commented on librz/debug/p/native/kfbsd.c
> +	return (pid == th->pid) ? 0 : 1;
Why not just `return pid != th->pid` ?

2025-06-23 16:05 UTC, wargio commented on librz/debug/p/native/kfbsd.c
> +	eprintf("Here is your reason for wait %d\n", reason);
Warn? Also can you rephrase this to be more professional ?

2025-06-24 01:28 UTC, well-mannered-goat commented on librz/core/cfile.c
> +		if (map->perm & 4) {
Yep, forgot about that
Comment as in? initially it fetched base from map which had r-x permissions which would shift up the symbols address to higher address. This is just fetches the base of the whole process.

2025-06-24 01:34 UTC, well-mannered-goat commented on librz/debug/p/native/kfbsd.c
> +int match_pid(const void *pid_o, const void *th_o, void *user) {
Nope, its used as comparator in rz_list_find

2025-06-24 01:36 UTC, well-mannered-goat commented on librz/debug/p/native/kfbsd.c
> +	eprintf("Here is your reason for wait %d\n", reason);
Oops, sorry about that. Used it for debugging in VMs :sweat_smile: . Cant really use debuggers inside VM

2025-06-24 01:38 UTC, well-mannered-goat commented
Forgot about the step over test, will also add it

2025-06-24 01:39 UTC, well-mannered-goat commented
> > Wrote some changes description in the PR
> > Also in FreeBSD `sysctl` is used to fetch maps first, because `procfs` is not mounted on `\proc\` hence no pid directories are there by default. Also the parsing logic is kind of flawed because of different map format (after mounting procfs) They aren't fetched from `/proc/` (its the second option if `sysctl` does not work), so I thought this is redundant code and with bugs. Should I remove it?
> 
> It's better to keep but open an issue about it, then we can decide what to do with it in a separate PR.

I'll just open up an issue then.

2025-06-24 02:35 UTC, wargio commented on librz/core/cfile.c
> +		if (map->perm & 4) {
like in the line below. `// r--`

2025-06-24 07:13 UTC, wargio approved these changes

2025-06-24 11:33 UTC, Rot127 approved these changes

2025-06-24 11:33 UTC, Rot127 commented on librz/debug/p/native/kfbsd.c
> +				RZ_LOG_WARN("(%d) Process exited with status=0x%x\n", pid, WEXITSTATUS(status));
```suggestion
				RZ_LOG_WARN("(%" PFMT32d ") Process exited with status=0x%x\n", pid, WEXITSTATUS(status));
```

2025-06-24 11:33 UTC, Rot127 commented on librz/debug/p/native/kfbsd.c
> +				RZ_LOG_WARN("(%d) Thread exited with status=0x%x\n", pid, WEXITSTATUS(status));
```suggestion
				RZ_LOG_WARN("(%" PFMT32d ") Thread exited with status=0x%x\n", pid, WEXITSTATUS(status));
```

2025-06-24 13:19 UTC, merged