ci: add CI for rz-bindgen
rizinorg/rizin pull request #3285
Opened 2023-01-11 08:36 UTC by ret2libc

2023-01-11 11:06 UTC, XVilka requested changes
```
[4/7] Generating bindgen_outputs with a custom command
FAILED: rizin.i 
/usr/bin/python ../src/main.py -o . --clang-path /usr/lib/llvm-14/lib --clang-args ' -resource-dir=/usr/lib/llvm-14/lib/clang/14.0.0' --rizin-include-path /usr/include/librz --targets SWIG
Warning:  Ignored fields on class RzIO do not exist: priv_w32dbg_wrap
Traceback (most recent call last):
  File "/home/runner/work/rizin/rizin/rz-bindgen/build/../src/main.py", line [51](https://github.com/rizinorg/rizin/actions/runs/3891051274/jobs/6640946193#step:8:52), in <module>
    bindings.run()
  File "/home/runner/work/rizin/rizin/rz-bindgen/src/bindings.py", line [52](https://github.com/rizinorg/rizin/actions/runs/3891051274/jobs/6640946193#step:8:53), in run
    func(Header(translation_unit, builder))
  File "/home/runner/work/rizin/rizin/rz-bindgen/src/bindings.py", line 387, in bind_main
    rz_main = Class(main_h, typedef="RzMain")
  File "/home/runner/work/rizin/rizin/rz-bindgen/src/binding_class.py", line 92, in __init__
    typedef_cursor = header.pop(CursorKind.TYPEDEF_DECL, typedef)
  File "/home/runner/work/rizin/rizin/rz-bindgen/src/cparser_header.py", line 208, in pop
    return self.cursors[kind].pop(name)
KeyError: 'RzMain'
```

2023-01-11 20:22 UTC, ret2libc commented on .github/workflows/ci.yml
> +          meson install -C build
```suggestion
          sudo meson install -C build
```

2023-01-11 23:51 UTC, XVilka requested changes
```
Run rizin -ql ./build/plugin/librz-bindings-plugin.* -c "Ll" | grep "Python SWIG"
ERROR: [d] Cannot open directory
Error: Process completed with exit code 1.
```

2023-01-16 13:01 UTC, XVilka commented
```
[2/7] Compiling C object plugin/librz-bindings-plugin.so.p/plugin.c.o
FAILED: plugin/librz-bindings-plugin.so.p/plugin.c.o 
cc -Iplugin/librz-bindings-plugin.so.p -Iplugin -I../plugin -I/usr/include/python3.10 -I/usr/include/librz -I/usr/include/librz/sdb -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -fPIC -MD -MQ plugin/librz-bindings-plugin.so.p/plugin.c.o -MF plugin/librz-bindings-plugin.so.p/plugin.c.o.d -o plugin/librz-bindings-plugin.so.p/plugin.c.o -c ../plugin/plugin.c
../plugin/plugin.c:177:6: error: ‘RzLibStruct’ {aka ‘struct rz_lib_struct_t’} has no member named ‘pkgname’
  177 |     .pkgname = "rz-bindings",
      |      ^~~~~~~
../plugin/plugin.c:177:16: warning: excess elements in struct initializer
  177 |     .pkgname = "rz-bindings",
      |                ^~~~~~~~~~~~~
../plugin/plugin.c:177:16: note: (near initialization for ‘rizin_plugin’)
[3/7] Generating bindgen_outputs with a custom command
Warning:  Ignored fields on class RzIO do not exist: priv_w32dbg_wrap
ninja: build stopped: subcommand failed.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/local/bin/ninja -C /home/runner/work/rizin/rizin/rz-bindgen/build
```

2023-01-16 14:18 UTC, XVilka approved these changes

2023-01-16 23:02 UTC, merged