Use clang-format 15 instead of 14
rizinorg/rizin pull request #3314
Opened 2023-01-22 14:23 UTC by rizan21

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Using `clang-format` 15 instead of 14

**Test plan**

Linter CI should pass

**Closing issues**

None

2023-01-23 03:07 UTC, XVilka requested changes

2023-01-23 03:07 UTC, XVilka commented on librz/bin/format/java/class_attribute.c
> +		am->
Looks terrible

2023-01-23 03:07 UTC, XVilka commented on librz/bin/format/java/class_attribute.h
> +	ModuleRequire *
As well.

2023-01-24 17:34 UTC, DMaroo approved these changes

2023-01-25 03:02 UTC, XVilka approved these changes

2023-01-25 08:01 UTC, ret2libc approved these changes

2023-01-25 12:06 UTC, kazarmy approved these changes

2023-01-25 14:02 UTC, merged