Enable scroll in non-default printCmds in Vv mode
rizinorg/rizin pull request #3352
Opened 2023-02-06 03:17 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

* Enable scroll by j and k in the right view of the Vv mode
* Cache the result of printCmds to avoid duplicated analysis
* Fix the unreasonable change of the right view while pressing tab (i.e. jump to pdf automatically while switching from the right view to the left view by pressing tab)

The following git shows scroll in the right view.

![tui](https://user-images.githubusercontent.com/58985155/216876021-11b2a556-3cfc-42a9-a89f-28f98c435bd4.gif)

PS:

Currently, the following part is static, I will try to refine them in the subsequent pr. This pr focuses on scroll in the right
view of the Vv mode.
```c
static int level = 0;
static st64 delta = 0;
// output is used to store the result of printCmds
// and avoid duplicated analysis while j and k is pressed
static char *output = NULL;
// output_mode labels which printCmds' result is stored in output
static int output_mode = -1;
static int output_addr = -1;
static int option = 0;
static int variable_option = 0;
static int printMode = 0;
static bool selectPanel = false;
```

**Test plan**

CI is green.

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/3021

2023-02-06 14:03 UTC, XVilka requested changes
As we strive to remove globals everywhere, let's avoid adding even more:
- https://github.com/rizinorg/rizin/issues/1874
- https://github.com/rizinorg/rizin/issues/276

2023-02-06 16:03 UTC, XVilka approved these changes
On a second thought it is still an improvement

2023-02-07 00:56 UTC, wargio commented
i agree on the globals, but this is an UI so we won't have such issue anyway, because UIs do not need multithreads

2023-02-07 00:56 UTC, wargio approved these changes

2023-02-07 01:13 UTC, merged