8051 IL fixes
rizinorg/rizin pull request #3413
Opened 2023-03-02 16:01 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The fixes I made when doing trace tests, using a modified [emu8051](https://github.com/imbillow/emu8051_bapframes)

**Test plan**

...

**Closing issues**

...

2023-03-03 02:35 UTC, wargio commented on librz/analysis/arch/8051/8051_il.c
> +// SPDX-FileCopyrightText: 2023 billow <billow.fun@gmail.com>
```suggestion
// SPDX-FileCopyrightText: 2022-2023 billow <billow.fun@gmail.com>
```

2023-03-03 02:38 UTC, XVilka requested changes
As long as it passes the tracetest, looks good.

2023-03-03 02:38 UTC, XVilka commented on librz/analysis/arch/8051/8051_il.c
> +	RzILOpPure *v = (op->argv[0]->mode == I8051_ADDRESSING_REGISTER && i8051_reg_is_psw_bit(op->argv[0]->d.reg)) || op->argv[0]->mode == I8051_ADDRESSING_BIT
Usually, for such long conditions I recommend creating a separate `static inline` function with the descriptive na,e, which will be substituted by the compiler, see [DEVELOPERS.md](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md).

2023-03-03 02:41 UTC, XVilka commented
Please also send a PR to `rz-tracetest`, and if the modifications of `8051emu` are ready - transfer the repo to `rizinorg/` organization.

2023-03-03 19:32 UTC, imbillow commented
https://github.com/rizinorg/rz-tracetest/pull/9

A PR for 8051 Trace Adapter

2023-03-03 20:02 UTC, imbillow commented
I haven't tested much of the 8051 code, so the tests I've done may not be very comprehensive.

2023-03-04 16:20 UTC, XVilka approved these changes

2023-03-05 03:31 UTC, wargio approved these changes

2023-03-05 04:54 UTC, merged