Dwarf sourceline info
rizinorg/rizin pull request #3449
Opened 2023-04-04 12:41 UTC by Sidhub723

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Added a handler in `ds_print_dwarf()` function in `librz/core/disasm.c`, if the variable asm.dwarf.lines is set to true. asm.dwarf.lines is set to false by default.

...

**Test plan**

...

**Closing issues**
This PR is with regards to [issue 653](https://github.com/rizinorg/rizin/issues/653)

...

2023-04-05 07:16 UTC, ret2libc commented
Can you show here on GH how the output changes before and after your PR? What is the difference between `asm.dwarf` and `asm.dwarf.lines`?

2023-04-05 11:48 UTC, wargio commented
add a test, please

2023-04-08 09:06 UTC, Sidhub723 commented
When only asm.dwarf is set to true and asm.dwarf.lines is set to false, below would be the disassembly output:
![image](https://user-images.githubusercontent.com/100401346/230712232-9c6a7e7d-9cf5-4c66-8658-025e21001ce0.png)
When asm.dwarf is still true, and line debug info display is enabled by setting asm.dwarf.lines to true, the disassembly changes to:
![image](https://user-images.githubusercontent.com/100401346/230713297-de35be23-9422-4309-be82-75ad2e054a4d.png)
One thing i still remain unsure about it how to make the `Line Number -xx` be displayed in a color which matches the console theme.

2023-04-09 14:39 UTC, XVilka requested changes
PLease add a test

2023-04-09 14:39 UTC, XVilka commented on librz/core/disasm.c
> +// static void ds_print_dwarf(RzDisasmState *ds);
Remove

2023-04-09 14:39 UTC, XVilka commented on librz/core/disasm.c
> +		// rz_cons_printf("No file loaded.\n");
Remove

2023-04-09 14:39 UTC, XVilka commented on librz/core/disasm.c
> +		// rz_cons_printf("No Source line information available");
Same

2023-04-09 14:39 UTC, XVilka commented on librz/core/disasm.c
> +
Unnecessary empty line

2023-04-09 14:39 UTC, XVilka commented on librz/core/disasm.c
> +
Same

2023-04-09 14:39 UTC, XVilka commented on librz/core/disasm.c
> +
You can extract that part into a separate static function for clarity

2023-04-09 14:40 UTC, XVilka commented
The overall format should be `filename:line`, e.g. `bla.c:315`, without `Line number...`, etc

2023-04-09 17:52 UTC, Sidhub723 commented
Will work on making these changes ASAP, thanks for the feedback!

2023-04-10 14:11 UTC, wargio commented
also it should be like a comment so ` ; bla.c:315`

2023-04-23 04:08 UTC, XVilka requested changes
Please add a test, for both disabled and enabled states.

2023-05-05 04:13 UTC, XVilka commented
@imbillow feel free to take over as part of your GSoC

2023-05-05 10:46 UTC, imbillow commented
> @imbillow feel free to take over as part of your GSoC



> @imbillow feel free to take over as part of your GSoC

What do you mean by 'take over'? Should I review the PR, or close it, open a new one and continue working from there?

2023-05-06 18:22 UTC, Sidhub723 commented
Sorry that I couldnt finish it quick. Goodluck to @imbillow !

2023-05-07 02:42 UTC, wargio commented
> > @imbillow feel free to take over as part of your GSoC
> 
> What do you mean by 'take over'? Should I review the PR, or close it, open a new one and continue working from there?

take over

2023-05-14 21:10 UTC, imbillow commented
Follow-up work in the new PR #3511

2023-05-14 21:10 UTC, closed without merging