fixed vn_cnt bug
rizinorg/rizin pull request #3460
Opened 2023-04-14 18:44 UTC by ifyGecko

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

I found another condition with symbol versioning in the elf code that can have a big impact on load time. Elfxx_Verneed structures in the .gnu.version_r section have a field vn_cnt that declares the number of Elfxx_Vernaux structures after it. This value can be edited to 0xFFFF with out impacting binary functionality but will impact load times in rizin by continually iterating on the last entry since vna_next will be 0 on the last entry.

The fix is simple, just break the loop when vna_next is 0 regardless of vn_cnt. This brought the load time from about 2 minutes for a few KB test file to a few seconds. The load times would just get worse if multiple Elfxx_Verneed structures had modified vn_cnt values.

**Test plan**

Pick a test binary, I just used /bin/clear since its simple and small
Use readelf -V to get the address to a Elfxx_Verneed
edit the vn_cnt of the chosen Elfxx_Verneed to 0xFFFF
run 'rizin test.elf'

2023-04-17 09:48 UTC, XVilka requested changes
Code looks fine, but it's better to add a test:
- `test/db/`
- https://github.com/rizinorg/rizin-testbins/tree/master/elf

2023-04-17 18:30 UTC, ret2libc approved these changes

2023-04-18 16:02 UTC, ifyGecko commented
@XVilka I can do that, I just submitted another PR for another version bug and had done another a little while back. Want me to just edit a binary to cover each of the 3 issues or break them up individually? Which ever, just let me know but fyi it might not be until the weekend I can pull that in. thanks.

2023-04-19 02:17 UTC, XVilka commented
@ifyGecko we can wait, no problem. You could use the same binary to test multiple things - all your fixes, for example, in one test.

2023-04-21 16:41 UTC, closed without merging