subprojects/xz: include immintrin.h to find _BitScanForward
rizinorg/rizin pull request #3471
Opened 2023-04-19 13:01 UTC by ret2libc

Hopefully it fixes the problem with appveyor

2023-04-19 13:26 UTC, ret2libc commented
Oops, it's intrin.h, not immintrin.h

2023-04-19 14:44 UTC, XVilka commented
@ret2libc see https://github.com/tukaani-project/xz/issues/48#issuecomment-1514859469

2023-04-20 02:05 UTC, XVilka requested changes
It fixed the xz problem, now there is one with libzip:
```
./subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(45,5): error: incompatible function pointer types initializing 'HANDLE (*)(const void *, DWORD, DWORD, PSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE) __attribute__((stdcall))' (aka 'void *(*)(const void *, unsigned long, unsigned long, struct _SECURITY_ATTRIBUTES *, unsigned long, unsigned long, void *)') with an expression of type 'HANDLE (const char *, DWORD, DWORD, PSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE) __attribute__((stdcall))' (aka 'void *(const char *, unsigned long, unsigned long, struct _SECURITY_ATTRIBUTES *, unsigned long, unsigned long, void *)') [-Wincompatible-function-pointer-types]
    utf16_create_file,
    ^~~~~~~~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(46,5): error: incompatible function pointer types initializing 'BOOL (*)(const void *) __attribute__((stdcall))' (aka 'int (*)(const void *)') with an expression of type 'BOOL (LPCWSTR) __attribute__((stdcall))' (aka 'int (const unsigned short *)') [-Wincompatible-function-pointer-types]
    DeleteFileW,
    ^~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(47,5): error: incompatible function pointer types initializing 'DWORD (*)(const void *) __attribute__((stdcall))' (aka 'unsigned long (*)(const void *)') with an expression of type 'DWORD (LPCWSTR) __attribute__((stdcall))' (aka 'unsigned long (const unsigned short *)') [-Wincompatible-function-pointer-types]
    GetFileAttributesW,
    ^~~~~~~~~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(48,5): error: incompatible function pointer types initializing 'BOOL (*)(const void *, GET_FILEEX_INFO_LEVELS, void *) __attribute__((stdcall))' (aka 'int (*)(const void *, enum _GET_FILEEX_INFO_LEVELS, void *)') with an expression of type 'BOOL (LPCWSTR, GET_FILEEX_INFO_LEVELS, LPVOID) __attribute__((stdcall))' (aka 'int (const unsigned short *, enum _GET_FILEEX_INFO_LEVELS, void *)') [-Wincompatible-function-pointer-types]
    GetFileAttributesExW,
    ^~~~~~~~~~~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(50,5): error: incompatible function pointer types initializing 'BOOL (*)(const void *, const void *, DWORD) __attribute__((stdcall))' (aka 'int (*)(const void *, const void *, unsigned long)') with an expression of type 'BOOL (LPCWSTR, LPCWSTR, DWORD) __attribute__((stdcall))' (aka 'int (const unsigned short *, const unsigned short *, unsigned long)') [-Wincompatible-function-pointer-types]
    MoveFileExW,
    ^~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(51,5): error: incompatible function pointer types initializing 'BOOL (*)(const void *, DWORD) __attribute__((stdcall))' (aka 'int (*)(const void *, unsigned long)') with an expression of type 'BOOL (LPCWSTR, DWORD) __attribute__((stdcall))' (aka 'int (const unsigned short *, unsigned long)') [-Wincompatible-function-pointer-types]
    SetFileAttributesW,
    ^~~~~~~~~~~~~~~~~~
```

Opened a bug in libzip repo: https://github.com/nih-at/libzip/issues/375

2023-04-20 02:05 UTC, XVilka commented on subprojects/packagefiles/xz-f41df2ac2fed347d3f107f3533e76e000d29c6cb/config.h.meson
> +
This probably could be removed.

2023-04-21 16:10 UTC, XVilka commented
@ret2libc you can use "master" branch for `xz` now, it was merged and will be a part of the next release.

2023-05-05 02:59 UTC, XVilka commented
@ret2libc you can use xz-5.4.3 now:
- https://github.com/tukaani-project/xz/releases/tag/v5.4.3

2023-05-07 02:39 UTC, wargio commented
```
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(45,5): error: incompatible function pointer types initializing 'HANDLE (*)(const void *, DWORD, DWORD, PSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE) __attribute__((stdcall))' (aka 'void *(*)(const void *, unsigned long, unsigned long, struct _SECURITY_ATTRIBUTES *, unsigned long, unsigned long, void *)') with an expression of type 'HANDLE (const char *, DWORD, DWORD, PSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE) __attribute__((stdcall))' (aka 'void *(const char *, unsigned long, unsigned long, struct _SECURITY_ATTRIBUTES *, unsigned long, unsigned long, void *)') [-Wincompatible-function-pointer-types]
    utf16_create_file,
    ^~~~~~~~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(46,5): error: incompatible function pointer types initializing 'BOOL (*)(const void *) __attribute__((stdcall))' (aka 'int (*)(const void *)') with an expression of type 'BOOL (LPCWSTR) __attribute__((stdcall))' (aka 'int (const unsigned short *)') [-Wincompatible-function-pointer-types]
    DeleteFileW,
    ^~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(47,5): error: incompatible function pointer types initializing 'DWORD (*)(const void *) __attribute__((stdcall))' (aka 'unsigned long (*)(const void *)') with an expression of type 'DWORD (LPCWSTR) __attribute__((stdcall))' (aka 'unsigned long (const unsigned short *)') [-Wincompatible-function-pointer-types]
    GetFileAttributesW,
    ^~~~~~~~~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(48,5): error: incompatible function pointer types initializing 'BOOL (*)(const void *, GET_FILEEX_INFO_LEVELS, void *) __attribute__((stdcall))' (aka 'int (*)(const void *, enum _GET_FILEEX_INFO_LEVELS, void *)') with an expression of type 'BOOL (LPCWSTR, GET_FILEEX_INFO_LEVELS, LPVOID) __attribute__((stdcall))' (aka 'int (const unsigned short *, enum _GET_FILEEX_INFO_LEVELS, void *)') [-Wincompatible-function-pointer-types]
    GetFileAttributesExW,
    ^~~~~~~~~~~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(50,5): error: incompatible function pointer types initializing 'BOOL (*)(const void *, const void *, DWORD) __attribute__((stdcall))' (aka 'int (*)(const void *, const void *, unsigned long)') with an expression of type 'BOOL (LPCWSTR, LPCWSTR, DWORD) __attribute__((stdcall))' (aka 'int (const unsigned short *, const unsigned short *, unsigned long)') [-Wincompatible-function-pointer-types]
    MoveFileExW,
    ^~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_utf16.c(51,5): error: incompatible function pointer types initializing 'BOOL (*)(const void *, DWORD) __attribute__((stdcall))' (aka 'int (*)(const void *, unsigned long)') with an expression of type 'BOOL (LPCWSTR, DWORD) __attribute__((stdcall))' (aka 'int (const unsigned short *, unsigned long)') [-Wincompatible-function-pointer-types]
    SetFileAttributesW,
    ^~~~~~~~~~~~~~~~~~
```

2023-05-08 12:51 UTC, XVilka commented
```
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_ansi.c(43,5): error: incompatible function pointer types initializing 'create_file_td' (aka 'void *(*)(const void *, unsigned long, unsigned long, struct _SECURITY_ATTRIBUTES *, unsigned long, unsigned long, void *)') with an expression of type 'HANDLE (LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE) __attribute__((stdcall))' (aka 'void *(const char *, unsigned long, unsigned long, struct _SECURITY_ATTRIBUTES *, unsigned long, unsigned long, void *)') [-Wincompatible-function-pointer-types]
    CreateFileA,
    ^~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_ansi.c(44,5): error: incompatible function pointer types initializing 'delete_file_td' (aka 'int (*)(const void *)') with an expression of type 'BOOL (LPCSTR) __attribute__((stdcall))' (aka 'int (const char *)') [-Wincompatible-function-pointer-types]
    DeleteFileA,
    ^~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_ansi.c(45,5): error: incompatible function pointer types initializing 'get_file_attributes_td' (aka 'unsigned long (*)(const void *)') with an expression of type 'DWORD (LPCSTR) __attribute__((stdcall))' (aka 'unsigned long (const char *)') [-Wincompatible-function-pointer-types]
    GetFileAttributesA,
    ^~~~~~~~~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_ansi.c(46,5): error: incompatible function pointer types initializing 'get_file_attributes_ex_td' (aka 'int (*)(const void *, enum _GET_FILEEX_INFO_LEVELS, void *)') with an expression of type 'BOOL (LPCSTR, GET_FILEEX_INFO_LEVELS, LPVOID) __attribute__((stdcall))' (aka 'int (const char *, enum _GET_FILEEX_INFO_LEVELS, void *)') [-Wincompatible-function-pointer-types]
    GetFileAttributesExA,
    ^~~~~~~~~~~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_ansi.c(48,5): error: incompatible function pointer types initializing 'move_file_td' (aka 'int (*)(const void *, const void *, unsigned long)') with an expression of type 'BOOL (LPCSTR, LPCSTR, DWORD) __attribute__((stdcall))' (aka 'int (const char *, const char *, unsigned long)') [-Wincompatible-function-pointer-types]
    MoveFileExA,
    ^~~~~~~~~~~
../subprojects/libzip-1.9.2/lib/zip_source_file_win32_ansi.c(49,5): error: incompatible function pointer types initializing 'set_file_attributes_td' (aka 'int (*)(const void *, unsigned long)') with an expression of type 'BOOL (LPCSTR, DWORD) __attribute__((stdcall))' (aka 'int (const char *, unsigned long)') [-Wincompatible-function-pointer-types]
    SetFileAttributesA,
    ^~~~~~~~~~~~~~~~~~
```

2023-05-09 01:31 UTC, XVilka approved these changes
xz and libzip problems are solved. Though I hope libzip addresses the problem in their code eventually. The one problem that still left is:
```
../librz/util/thread.c(22,9): error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'DWORD' (aka 'unsigned long') [-Wint-conversion]
        return NULL;
               ^~~~
C:\Program Files\LLVM\lib\clang\16\include\stddef.h(89,16): note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
1 error generated.
[379/1978] Compiling C object librz/util/rz_util-0.6.dll.p/table.c.obj
[380/1978] Compiling C object librz/util/rz_util-0.6.dll.p/thread_cond.c.obj
```
I think it can be addressed separately, thus merging this PR as is.

2023-05-09 01:31 UTC, merged

2023-05-09 05:59 UTC, wargio commented
https://github.com/rizinorg/rizin/pull/3504