librz: fix UAF in plugin deletion
rizinorg/rizin pull request #3485
Opened 2023-04-25 20:28 UTC by ret2libc

Some libraries have a global "plugin_data" that is initialized only for the current plugin, thus the fini method should only be called for the current plugin as well and not for the others.

 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2023-04-26 03:21 UTC, wargio approved these changes

2023-05-07 00:40 UTC, XVilka requested changes
It broke all Windows builds, please also rebase to fix Travis build:
```
[191/1950] Generating subprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/zip_err_str with a custom command
[192/1950] Compiling C object subprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/liblibzip.a.p/lib_zip_add.c.obj
FAILED: subprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/liblibzip.a.p/lib_zip_add.c.obj 
"cl" "-Isubprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740\liblibzip.a.p" "-Isubprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740" "-I..\subprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740" "-I..\subprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740\lib" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "/MT" "/nologo" "/showIncludes" "/utf-8" "/W2" "/O2" "/Gw" "/Fdsubprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740\liblibzip.a.p\lib_zip_add.c.pdb" /Fosubprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/liblibzip.a.p/lib_zip_add.c.obj "/c" ../subprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/lib/zip_add.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wstdio.h(1698): error C2059: syntax error: '('
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_memcpy_s.h(44): error C2059: syntax error: '('
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\string.h(49): error C2059: syntax error: '('
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\string.h(65): error C2059: syntax error: '('
[193/1950] Compiling C object subprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/liblibzip.a.p/meson-generated_.._zip_err_str.c.obj
FAILED: subprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/liblibzip.a.p/meson-generated_.._zip_err_str.c.obj 
"cl" "-Isubprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740\liblibzip.a.p" "-Isubprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740" "-I..\subprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740" "-I..\subprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740\lib" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "/MT" "/nologo" "/showIncludes" "/utf-8" "/W2" "/O2" "/Gw" "/Fdsubprojects\libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740\liblibzip.a.p\meson-generated_.._zip_err_str.c.pdb" /Fosubprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/liblibzip.a.p/meson-generated_.._zip_err_str.c.obj "/c" subprojects/libzip-3c55695085486ba5dbe41335245d8dfbe9f5f740/zip_err_str.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_wstdio.h(1698): error C2059: syntax error: '('
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_memcpy_s.h(44): error C2059: syntax error: '('
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\string.h(49): error C2059: syntax error: '('
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\string.h(65): error C2059: syntax error: '('
[194/1950] Compiling C object subprojects/xz-f41df2ac2fed347d3f107f3533e76e000d29c6cb/src/liblzma/liblzma.a.p/lzma_lzma2_encoder.c.obj
ninja: build stopped: subcommand failed.
Command exited with code 1
```

2023-05-07 00:40 UTC, XVilka commented on subprojects/liblzma.wrap
> +# source_fallback_url = https://tukaani.org/xz/xz-5.4.2.tar.gz // has different hash, let's prefer github
5.4.3

2023-05-09 22:02 UTC, XVilka commented
@ret2libc please rebase again now that `dev` is green

2023-05-12 02:38 UTC, XVilka approved these changes

2023-05-12 02:38 UTC, merged