RzIL MIPS Uplifting
rizinorg/rizin pull request #3508
Opened 2023-05-11 12:29 UTC by brightprogrammer

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
This PR is related to my GSoC 2023 summer project on MIPS uplifting. 

**Test plan**

TODO

...

**Closing issues**

...

2023-05-11 12:53 UTC, wargio commented on librz/analysis/arch/mips/mips_il.h
> +#ifndef MIPS_IL_H_
please use the same naming convention as for the other header files.
`MIPS_IL_H`

2023-05-11 12:53 UTC, wargio commented on librz/analysis/arch/mips/mips_il.h
> +#ifndef MIPS_IL_H_
don't forget to add the licence etc..

2023-05-11 12:53 UTC, wargio commented on librz/analysis/arch/mips/mips32_il.c
> + * @note
```suggestion
 * \note
```

2023-05-12 03:26 UTC, XVilka requested changes
I recommend also to start cleaning up and extracting ESIL uplifting in `librz/analysis/p/analysis_mips_cs.c` in separate functions, so that when time comes it can be removed quickly and painlessly.

Also, there are some tests in this file, that check `mips.gnu`, we should make sure they pass with `mips.cs` as well:
```
test/db/analysis/mips
99:e asm.arch=mips.gnu
121:e asm.arch=mips.gnu
527:e asm.arch=mips.gnu
748:NAME=mips.gnu regs
751:e asm.arch=mips.gnu
```
Or modified/removed

2023-05-19 02:53 UTC, XVilka commented
@brightprogrammer please maintain the current status/TODO in the PR description

2023-06-05 02:46 UTC, XVilka requested changes
Please start adding tests. Otherwise you have a risk of writing a lot of wrong code.

2023-06-06 02:00 UTC, XVilka commented
Please maintain the list of functions that are not uplifted yet.

2023-06-06 04:05 UTC, brightprogrammer commented
> Please maintain the list of instructions that are not uplifted yet.

I'm maintaining a per architecture offline copy of instructions that are lifted and aren't lifted yet, do I need to make it visible here too?

2023-06-07 02:21 UTC, XVilka commented
> > Please maintain the list of instructions that are not uplifted yet.
> 
> I'm maintaining a per architecture offline copy of instructions that are lifted and aren't lifted yet, do I need to make it visible here too?

How big is it? I think it could be fit in the PR description, just put it under the spoiler probably?

2023-06-07 04:39 UTC, brightprogrammer commented
> > > Please maintain the list of instructions that are not uplifted yet.
> > 
> > I'm maintaining a per architecture offline copy of instructions that are lifted and aren't lifted yet, do I need to make it visible here too?
> 
> How big is it? I think it could be fit in the PR description, just put it under the spoiler probably?

I'm marking instructions in a hardcopies of ISA manuals that I printed. I can add temporary MD files in mips folder that'll be deleted before PR merge. I can track instructions there

2023-06-07 04:47 UTC, XVilka commented
> I can add temporary MD files in mips folder that'll be deleted before PR merge. I can track instructions there

Sounds good.

2023-06-16 02:40 UTC, XVilka requested changes
Currently it's not integrated in the `mips_cs` analysis plugin yet.

2023-07-06 03:09 UTC, XVilka commented
Please rebase to fix the conflicts

2023-07-11 02:42 UTC, XVilka commented
See also this: https://lore.kernel.org/qemu-devel/20230710222611.50978-1-philmd@linaro.org/T/#t

This is an extension of MIPS but would be nice to have at some point in the future as well.

2023-07-27 06:20 UTC, XVilka commented
You can remove `status_update.py` now, I think, and have it locally only. It will make the CI green as well.

2025-03-13 12:37 UTC, closed without merging