Rename `asm.dwarf` to `asm.debuginfo`
rizinorg/rizin pull request #3513
Opened 2023-05-15 12:27 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

just link https://github.com/rizinorg/rizin/issues/907

2023-05-15 12:50 UTC, XVilka requested changes

2023-05-15 12:50 UTC, XVilka commented on librz/core/cconfig.c
> +	SETBPREF("asm.debuginfo.file", "true", "Show filename of asm.debuginfo in pd");
Maybe `Show file name from the debug information in disassembly`?

2023-05-15 12:50 UTC, XVilka commented on librz/core/cconfig.c
> +	SETBPREF("asm.debuginfo.abspath", "false", "Show absolute path in asm.debuginfo");
`Show absolute path for file from the debug information`?

2023-05-15 12:50 UTC, XVilka commented on librz/core/cconfig.c
> +	SETBPREF("asm.debuginfo", "false", "Show debug info comment at disassembly");
`Show debug information in disassembly`

2023-05-15 12:50 UTC, XVilka commented on librz/core/cconfig.c
> +	SETBPREF("asm.debuginfo.lines", "true", "Show debug info source line information at disassembly");
`Shoe source line information from debug metadata at dissassembly`?

2023-05-15 12:50 UTC, XVilka commented on librz/core/disasm.c
> +	bool asm_debuginfo_file;
maybe remove `asm_` prefix? It's a structure of the disasm state after all.

2023-05-15 12:50 UTC, XVilka commented on librz/core/disasm.c
> +	bool asm_debuginfo;
Same

2023-05-15 12:50 UTC, XVilka commented on librz/core/disasm.c
> +	bool asm_debuginfo_file;
Also maybe make it a substructure instead? So that it could be modified/extended easily when necessary?

2023-05-15 14:46 UTC, imbillow commented
Or maybe we can use `RzBitVector` to store all the flags?

2023-05-15 14:54 UTC, XVilka commented
@imbillow, why not just structure with bools? This structure should not have too many copies in the memory anyway - it's only used for disassembly.

2023-05-15 14:59 UTC, wargio commented
i'm actually very ok with a bitmask

2023-05-15 15:06 UTC, imbillow commented
> @imbillow, why not just structure with bools? This structure should not have too many copies in the memory anyway - it's only used for disassembly.

I'm just a bit obsessive-compulsive. When I think about how a bool in C takes up 1 byte, yet its information content is only 1 bit.

2023-05-16 01:25 UTC, XVilka approved these changes

2023-05-16 02:55 UTC, merged