Remove unused rz_big
rizinorg/rizin pull request #3553
Opened 2023-06-04 06:19 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Its is unused and slims down the libs

2023-06-04 06:24 UTC, XVilka requested changes
Wait, it might be useful for the big numbers in rz-ax, as well as in RzIL

2023-06-04 06:25 UTC, XVilka commented
See, e.g. https://github.com/rizinorg/rizin/issues/3331

2023-06-04 06:38 UTC, wargio commented
> Wait, it might be useful for the big numbers in rz-ax, as well as in RzIL

i don't see the need for this. BitVec is enough also for rz-ax.
Besides, is not used anywhere, besides on the unit test

2023-06-04 06:40 UTC, XVilka commented
Performing big number arithmetic by converting to bitvectors where there is no need for them will be very slow. Please pause this PR, we need better discussion about it

2025-05-11 06:09 UTC, notxvilka commented
Closing this as it will be a part of https://github.com/rizinorg/rizin/pull/4326 (plan to do it before 0.9.0)

2025-05-11 06:09 UTC, closed without merging