Populate Mach-O relocs from chained fixups and parse and use chained imports
rizinorg/rizin pull request #3602
Opened 2023-06-24 14:11 UTC by thestr4ng3r

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Summary:
* Relocs are created from all chained fixups (`ir`)
* New chained imports are parsed too and replace the old info from indirect syms (`ii`)
* Combining the two points above, relocs also have their name set to the symbol name (displayed in `ir`)
* The above point also has the effect that imported objc superclasses are resolved correctly (`ic`, see updated tests)
* Chained bind fixups are now also patched to have meaningful pointers to imports rather than the unpatched chained fixup value (looks like garbage data otherwise)

**Test plan**

Before (relocs are incomplete, `objc_alloc(0x8020000000000005)` makes no sense):
![Bildschirmfoto 2023-06-24 um 16 10 06](https://github.com/rizinorg/rizin/assets/1460997/2d884565-45f1-48d9-b3cd-1c76fe8ad011)

After:
![Bildschirmfoto 2023-06-24 um 16 09 18](https://github.com/rizinorg/rizin/assets/1460997/92a26183-c9d7-40bf-8754-a191d19f0099)

2023-06-24 16:46 UTC, XVilka requested changes
A tremendous amount of work! Their logic is so complex...
LGTM with two minor things.

2023-06-24 16:46 UTC, XVilka commented on librz/bin/format/mach0/mach0_chained_fixups.c
> +RZ_API RZ_OWN bool MACH0_(get_chained_import)(struct MACH0_(obj_t) * obj, ut32 ordinal, struct MACH0_(chained_import_t) * dst) {
Unnecessary marker for a `bool`

2023-06-24 16:46 UTC, XVilka commented on librz/bin/format/mach0/mach0_relocs.c
> +RZ_BORROW RzSkipList *MACH0_(get_relocs)(struct MACH0_(obj_t) * bin) {
Add list element type in comments please

2023-06-25 02:27 UTC, XVilka requested changes
```
Run python3 rz-bindgen/src/lint.py \
Type comment at <rizin/librz/bin/format/mach0/mach0.h:21[7](https://github.com/rizinorg/rizin/actions/runs/5366343464/jobs/9735715767?pr=3602#step:6:8):37> for unknown type RzSkipList
Type comment at <rizin/librz/bin/format/mach0/mach0.h:244:46> for unknown type RzSkipList
Type comment at <rizin/librz/bin/format/mach0/mach0_relocs.c:521:46> for unknown type RzSkipList
```

2023-06-25 02:30 UTC, wargio approved these changes

2023-06-25 08:17 UTC, XVilka commented
@thestr4ng3r does it also resolve https://github.com/rizinorg/rizin/issues/3459?

2023-06-25 10:01 UTC, thestr4ng3r commented
I don't think so, seems unrelated.

2023-06-25 10:38 UTC, XVilka approved these changes

2023-06-25 11:39 UTC, merged