Always search for preludes.
rizinorg/rizin pull request #3615
Opened 2023-06-29 13:13 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Fix #995

2023-06-29 14:02 UTC, XVilka approved these changes
Nice, new results are better

2023-06-29 14:22 UTC, XVilka commented
Now it timeouts more often on:
```
[XX] TIMEOUT db/archos/linux-x64/dbg_aaa_dcu dbg.aaa
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -dA -Qc 'dcu main
fd
afi @ main~?name: main
' bins/elf/true
-- stdout
--- expected
+++ actual
@@ -1,2 +1,0 @@
-main
-1

-- stderr
Process with PID 22751 started...
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[ ] Analyze function calls
[
[x] Analyze function calls
[ ] find and analyze function preludes
[
-- exit status: -1
```

2023-06-29 16:21 UTC, XVilka commented
It is so much slower now on Windows

2023-06-30 02:58 UTC, XVilka requested changes
Seems it affects the performance too much. Likely there is a huge bottleneck somewhere in the analysis. Have you tried to check the flamegraph for this timeouted test?

2023-06-30 02:58 UTC, XVilka commented on test/db/archos/linux-x64/dbg_aaa_dcu
>  NAME=dbg.aaa
Then name should be changed too.

2023-06-30 03:00 UTC, wargio commented
so, we don't really need to search for preludes on x86.

2023-06-30 04:26 UTC, XVilka approved these changes

2023-06-30 05:20 UTC, merged

2023-06-30 07:17 UTC, XVilka commented
@wargio it broke fuzzing tests:
```
[XX] TIMEOUT /home/runner/work/rizin/rizin/test/bins/fuzzed <fuzz> /home/runner/work/rizin/rizin/test/bins/fuzzed/poc-radare2-invalid-memory-access-elf-758
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc aaa /home/runner/work/rizin/rizin/test/bins/fuzzed/poc-radare2-invalid-memory-access-elf-758
-- stdout

-- stderr
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[ ] Analyze function calls
[
[x] Analyze function calls
[ ] find and analyze function preludes
[
-- exit status: -1
[**]     /home/runner/work/rizin/rizin/test/bins/fuzzed      592 OK         0 BR        1 XX        0 FX
```