Not an error
rizinorg/rizin pull request #3660
Opened 2023-07-16 20:47 UTC by dvertx

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
1. Reopening debugged file with `ood` prints out an error of *ERROR: File xxx reopened in read-write mode*, instead of written as an info with RZ_LOG_INFO:
```shell
$ rizin /bin/ls
 -- Find expanded AES keys in memory with '/ca'
[0x00006ab0]> ood
ERROR: rz-run: invalid hexpair string `0`
Process with PID 5677 started...
ERROR: File dbg:///usr/bin/ls reopened in read-write mode
[0x7f94745a72b0]>
```

2. Running rizin with `-d` **always** outputs an error message of *invalid hexpair string*, also when reopened with `ood` (see number 1 above):
```shell
$ rizin -d /bin/ls
ERROR: rz-run: invalid hexpair string `0`
Process with PID 5606 started...
 -- Temporally drop the verbosity prefixing the commands with ':'
[0x7f46f789a2b0]>
```
My understanding is that `resolve_value()` gets called many times iteratively by other functions, therefore will **always** reach a `src_len`  value of 1.

...  

**Test plan**

...

**Closing issues**

...

2023-07-17 03:10 UTC, wargio commented on librz/core/cfile.c
> +		RZ_LOG_INFO("File %s reopened in %s mode\n", path,
probably this should be a warning. also delete the comment above this line.

2023-07-17 03:10 UTC, wargio commented on librz/socket/run.c
> -			RZ_LOG_ERROR("rz-run: invalid hexpair string `%s`\n", copy);
convert this into INFO instead.

2023-07-17 03:11 UTC, wargio requested changes
.

2023-07-18 00:27 UTC, wargio approved these changes

2023-07-18 01:06 UTC, XVilka requested changes
Fix the test please;
```
 [XX] db/archos/linux-x64/dbg_oo ood check for ptrace errors
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -e log.level=5 -Qc 'ood
' bins/elf/analysis/x86-helloworld-gcc
-- stderr
--- expected
+++ actual
@@ -1,1 +1,1 @@
-Process with PID File -helloworld-gcc reopened in read-write mode
+Process with PID 
```

2023-07-18 10:20 UTC, dvertx commented
Done. All checks now passes

2023-07-18 11:13 UTC, wargio approved these changes

2023-07-24 07:21 UTC, ret2libc approved these changes

2023-07-25 03:02 UTC, XVilka approved these changes

2023-07-25 03:02 UTC, merged