Make rz_core_analysis_var_display work with stack vars when debugging
rizinorg/rizin pull request #3687
Opened 2023-07-22 12:42 UTC by frmdstryr

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The `rz_analysis_var_addr` does not pull from the correct registers when debugging causing the stack address to be incorrect. This inlines the address calculation in `rz_core_analysis_var_display` and uses `rz_core_reg_getv_by_role_or_name` to read it correctly.

**Test plan**

For https://github.com/rizinorg/cutter/pull/3206

Before
![Screenshot_20230721_084938](https://github.com/rizinorg/rizin/assets/380158/f96c8d1a-37c4-4838-80bb-a04bf864f2fe)

After

![Screenshot_20230721_123759](https://github.com/rizinorg/rizin/assets/380158/aae24d1c-d403-4284-8094-311474deb97d)

**Closing issues**

N/A

2023-07-22 12:48 UTC, XVilka reviewed
Not sure if the fix is correct. Could you please add a test in `test/db/`? I remember that function is used in `afvd`, right?

2023-07-22 13:18 UTC, frmdstryr commented
Yes `afvd` is `rz_analysis_function_vars_display_handler` which calls `rz_core_analysis_var_display`. 

Is there an example of testing cmds while in a debug session somewhere?

2023-07-22 13:37 UTC, XVilka commented
> Yes `afvd` is `rz_analysis_function_vars_display_handler` which calls `rz_core_analysis_var_display`.
> 
> Is there an example of testing cmds while in a debug session somewhere?

Yes, see `test/db/archos/linux-x64/` for example - these are debug tests that will run only on Linux x86_64

2023-07-22 14:42 UTC, wargio commented on librz/core/canalysis.c
> +		ut64 addr = stack + var->fcn->bp_off + var->storage.stack_off;
probably this should be enabled only when debugging.

2023-07-22 14:43 UTC, wargio commented on librz/core/canalysis.c
> +		ut64 addr = stack + var->fcn->bp_off + var->storage.stack_off;
And probably this should be done within `rz_analysis_var_addr`

2023-07-24 07:39 UTC, ret2libc commented
Nice fix, thanks! I agree with @XVilka though that the fix looks a bit out of place there though.

What if we rename/move `rz_analysis_var_addr` into `core/rz_core_analysis_var_addr(RzCore *, RzAnalysisVar *)` that uses `rz_core_reg_getv_by_role_or_name` instead of `rz_reg_getv`?

BTW, if you use `rz_core_reg_getv_by_role_or_name` you should be able to directly use `RZ_REG_NAME_BP` as argument.

2023-07-24 13:14 UTC, frmdstryr commented
Well, something is still not correct.. the test I added is broken. The rbp register still returns UT64_MAX for some reason. 

When debugging bin/cat (the test I added) the address is still incorrect but it seems to work for the other binary I was trying (`structs` from https://github.com/wrongbaud/hackaday-u/tree/master/session-three/exercises). I'm not sure what the difference is?

2023-07-27 12:54 UTC, XVilka commented
> Well, something is still not correct.. the test I added is broken. The rbp register still returns UT64_MAX for some reason.
> 
> When debugging bin/cat (the test I added) the address is still incorrect but it seems to work for the other binary I was trying (`structs` from https://github.com/wrongbaud/hackaday-u/tree/master/session-three/exercises). I'm not sure what the difference is?

You seem to debug the binary from the system, you need to use the binary that wouldn't change during the CI image upgrade - e.g. from rizin-testbins. This way you have full control on what is being run and avert breakage in case of the changed binary on the CI.

2023-07-27 14:58 UTC, XVilka requested changes
It seems some CI jobs get slightly different value:
```
 [XX] db/archos/linux-x64/dbg_afvd dbg.afvd
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -d -A -Qc 'aa
dcu main
ds 8
afvd var_ch
' bins/elf/struct64
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-(qword)0x0000000100005661
+(qword)0x0000000100000061
```

2023-07-27 15:13 UTC, frmdstryr commented
I tried a few different bins but couldn't really find a good one to use for a test, any suggestions?

For some reason the var type is int64_t but it should be a single char/byte with just 0x61. I guess it seems to be using the padding or something. 

![image](https://github.com/rizinorg/rizin/assets/380158/cc0f1bef-98f4-4c87-b620-087bc7fa8f94)

2023-07-27 15:15 UTC, XVilka commented
> I tried a few different bins but couldn't really find a good one to use for a test, any suggestions?
> 
> For some reason the var type is int64_t but it should be a single char/byte with just 0x61. I guess it seems to be using the padding or something.

you can change the variable type with `afvt`

2023-07-27 15:17 UTC, XVilka commented
As for autodetection - please open a new issue, I will check after the release

2023-07-27 15:32 UTC, XVilka approved these changes

2023-07-27 15:32 UTC, XVilka commented on librz/core/canalysis.c
> +RZ_API ut64 rz_core_analysis_var_addr(RZ_NONNULL RzCore *core, RZ_NONNULL RzAnalysisVar *var) {
Please add Doxygen

2023-07-27 15:50 UTC, XVilka requested changes

2023-07-27 15:50 UTC, XVilka commented on librz/include/rz_core.h
> + * @brief Get the address of a stack variable.
We use `\brief` and `\param` syntax. `\ref` also

2023-07-27 15:50 UTC, XVilka commented on librz/include/rz_core.h
> + * @brief Get the address of a stack variable.
See https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#documentation

2023-07-27 15:51 UTC, XVilka requested changes

2023-07-27 15:51 UTC, XVilka commented on librz/include/rz_core.h
> + * \brief Get the address of a stack variable.
Please move the comment to the function in the C file,not in header

2023-07-27 15:53 UTC, XVilka approved these changes

2023-07-27 17:40 UTC, merged