meson: do not use `add_global_arguments()`
rizinorg/rizin pull request #3706
Opened 2023-08-01 05:48 UTC by XVilka

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`add_global_arguments()` prevents using Rizin as a subproject for Meson WrapDB:

Switch to use `add_project_arguments()` instead:

https://mesonbuild.com/Reference-manual_functions.html#add_project_arguments

Necessary for 

**Test plan**

CI is green

2023-08-01 06:20 UTC, ret2libc requested changes
I remember this was done to transmit args to rizin subprojects as well. Please check rizin builds well everywhere

2023-08-01 06:38 UTC, XVilka commented
Sigh, looks like Meson isn't advanced enough to fallback from `gnu99` to `c99`. It's such an obvious thing to do.

2023-08-01 07:00 UTC, XVilka commented
Curiously, Meson uses SPDX in `license:` field but it never checked if the identifier is even valid: https://github.com/fsfe/reuse-tool/issues/816

2023-08-01 07:23 UTC, XVilka commented
No easy solution, moving to the next release

2024-10-18 16:06 UTC, amibranch commented
I'm currently looking to add rizin as a meson-subproject to projects and came across the same problems. What's the state? I don't see any blocker in the license problem, to replace `add_global_arguments` with `add_project_arguments`?
I wasn't able to compile (a rebased) state of this change, as rzrar and rzwinkd seem to require `-D*:c_std=gnu99` (instead of c99).
Also note that using rizin in a subproject correctly, requires some more fixes. I've created a dedicated branch, containing two additional commits (and rebased on dev):
https://github.com/rizinorg/rizin/compare/dev...amibranch:rizin:rizin_as_subproject
- A first commit including all necessary changes I found so far, in order to add rizin as subproject to other projects
- A second commit, containing changes to the default `c_std`-option and a small change, necessary for muon

However, I couldn't yet test the CI on my branch and the results from the PR are expired

2024-10-18 23:11 UTC, XVilka commented
@amibranch could you please send a PR with your changes?

2024-10-21 10:44 UTC, XVilka commented
Sigh:
```
 FAILED: subprojects/libzip-1.9.2/liblibzip.a.p/lib/zip_name_locate.c.o 
cc -std=c99 -g -Og -Wall -fdiagnostics-color=always -I subprojects/libzip-1.9.2 -I ../subprojects/libzip-1.9.2 -I ../subprojects/libzip-1.9.2/lib -fPIC -MD -MQ subprojects/libzip-1.9.2/liblibzip.a.p/lib/zip_name_locate.c.o -MF subprojects/libzip-1.9.2/liblibzip.a.p/lib/zip_name_locate.c.o.d -o subprojects/libzip-1.9.2/liblibzip.a.p/lib/zip_name_locate.c.o -c ../subprojects/libzip-1.9.2/lib/zip_name_locate.c
../subprojects/libzip-1.9.2/lib/zip_name_locate.c: In function ‘_zip_name_locate’:
../subprojects/libzip-1.9.2/lib/zip_name_locate.c:76:41: error: ‘strcasecmp’ undeclared (first use in this function); did you mean ‘strncmp’?
   76 |         cmp = (flags & ZIP_FL_NOCASE) ? strcasecmp : strcmp;
      |                                         ^~~~~~~~~~
      |                                         strncmp
../subprojects/libzip-1.9.2/lib/zip_name_locate.c:76:41: note: each undeclared identifier is reported only once for each function it appears in
```
```
FAILED: subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_dirent.c.o 
cc -Isubprojects/libzip-1.9.2/liblibzip.a.p -Isubprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2/lib -Isubprojects/zlib-1.3.1 -I../subprojects/zlib-1.3.1 -I../subprojects/xz-5.2.9/src/liblzma/api -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c99 -O3 -Wno-cpp -fPIC -DLZMA_API_STATIC -MD -MQ subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_dirent.c.o -MF subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_dirent.c.o.d -o subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_dirent.c.o -c ../subprojects/libzip-1.9.2/lib/zip_dirent.c
../subprojects/libzip-1.9.2/lib/zip_dirent.c: In function ‘_zip_u2d_time’:
../subprojects/libzip-1.9.2/lib/zip_dirent.c:1095:11: error: implicit declaration of function ‘localtime_r’; did you mean ‘localtime’? [-Werror=implicit-function-declaration]
 1095 |     tpm = localtime_r(&intime, &tm);
      |           ^~~~~~~~~~~
      |           localtime
../subprojects/libzip-1.9.2/lib/zip_dirent.c:1095:9: error: assignment to ‘struct tm *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
 1095 |     tpm = localtime_r(&intime, &tm);
      |         ^
```
```
gcc -Isubprojects/libzip-1.9.2/liblibzip.a.p -Isubprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2/lib -Isubprojects/zlib-1.3.1 -I../subprojects/zlib-1.3.1 -I../subprojects/xz-5.2.9/src/liblzma/api -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c99 -O3 -DRZ_ASSERT_STDOUT=1 -Wno-cpp -fPIC -DLZMA_API_STATIC -MD -MQ subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_fdopen.c.o -MF subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_fdopen.c.o.d -o subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_fdopen.c.o -c ../subprojects/libzip-1.9.2/lib/zip_fdopen.c
../subprojects/libzip-1.9.2/lib/zip_fdopen.c: In function ‘zip_fdopen’:
../subprojects/libzip-1.9.2/lib/zip_fdopen.c:62:15: error: implicit declaration of function ‘fdopen’; did you mean ‘fopen’? [-Werror=implicit-function-declaration]
   62 |     if ((fp = fdopen(fd, "rb")) == NULL) {
      |               ^~~~~~
      |               fopen
../subprojects/libzip-1.9.2/lib/zip_fdopen.c:62:13: error: assignment to ‘FILE *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
   62 |     if ((fp = fdopen(fd, "rb")) == NULL) {
      |             ^
cc1: all warnings being treated as errors
```

2024-10-22 18:16 UTC, amibranch commented
@XVilka , I could base https://github.com/rizinorg/rizin/pull/4684 on this PR (and set the destination branch) - or we close this PR and https://github.com/rizinorg/rizin/pull/4684 will take over and be merged in dev (which means one round of reviews and CI). Your preference?

2024-10-23 12:17 UTC, closed without merging