Fold same-typed variables if there are more than 3
rizinorg/rizin pull request #3770
Opened 2023-08-17 12:10 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

There are three choice for `asm.var.fold`:
+ 0 -> no fold
+ 1 -> fold three variables in each group
+ 2 -> group the first two variables with ellipsis in tail

as shown in the following picture.

![Screenshot from 2023-08-17 19-29-51](https://github.com/rizinorg/rizin/assets/58985155/98a397f4-3097-47ac-bf1f-614241befcef)

**Test plan**

...

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/3701

2023-08-17 15:47 UTC, ret2libc commented
Minor thing, but instead of the various 1,2,3,etc. we were used to use in many cases, I think it makes more sense to use options.

See for example:
```c
	SETDESC(n, "Select assembly syntax");
	SETOPTIONS(n, "att", "intel", "masm", "jz", "regnum", NULL);
```
we could use `asm.var.fold=none`, `asm.var.fold=group`, `asm.var.fold=hide`. Or other values that you think fit better :)

2023-08-18 02:05 UTC, XVilka requested changes
Agree with @ret2libc. The output looks good also.

2023-08-18 02:05 UTC, XVilka commented on librz/core/disasm.c
> +				if (ds->fold_var && !rz_analysis_var_is_arg(var)) {
I suggest extracting that in the separate function

2023-08-18 02:05 UTC, XVilka commented on librz/core/disasm.c
> +						char *temp_vartype = rz_type_as_string(core->analysis->typedb, temp_var->type);
Beware of the NULL here, both `temp_var` and `temp_vartype` could be that.

2023-08-19 08:17 UTC, PeiweiHu commented
Thanks for the review. The pr is changed as suggested :)

2023-08-19 12:14 UTC, XVilka approved these changes

2023-08-19 16:11 UTC, wargio approved these changes

2023-08-19 18:27 UTC, ret2libc approved these changes

2023-08-19 18:29 UTC, ret2libc approved these changes

2023-08-19 18:38 UTC, merged