librz: add some initial documentation
rizinorg/rizin pull request #3782
Opened 2023-08-24 07:10 UTC by ret2libc

Partially addresses https://github.com/rizinorg/rizin/issues/286

2023-08-24 07:26 UTC, XVilka requested changes

2023-08-24 07:26 UTC, XVilka commented on librz/util/README.md
> +- Functions that are very common and not specific to other modules
Numbers/math

2023-09-29 12:22 UTC, ret2libc commented
@wargio @thestr4ng3r @XVilka please review if the two files i added for now are ok. If so I think we can merge so that also others, if they want, can start filling the docs.

2023-09-29 13:19 UTC, XVilka requested changes
Yes, once feedback is addressed I think we can merge. Step by step.

2023-09-29 13:19 UTC, XVilka commented on librz/README.md
> +a nice reverse-engineering framework useful for a variety of use-cases and
Remove `a nice`.

2023-09-29 13:19 UTC, XVilka commented on librz/io/README.md
> +- RzIO Plugins to perform I/O operations on various kinds of resources
Put `RzIO` into backticks

2023-09-29 13:19 UTC, XVilka commented on librz/util/README.md
> +## What can I expect here?
Add floating point, SDB. Also worth mentioning providing OS/platform-independent common abstractions.

2023-10-11 07:32 UTC, ret2libc commented
@XVilka feedback addressed.

2023-10-13 05:46 UTC, XVilka approved these changes

2023-10-13 05:46 UTC, merged