Updating_man
rizinorg/rizin pull request #3783
Opened 2023-08-24 12:46 UTC by sohail1734

**Your checklist for this pull request**
- [yes ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
updated the man pages of rizin.1 and rz-diff.1

...

**Test plan**

...

**Closing issues**

...

2023-08-24 12:50 UTC, wargio commented on binrz/man/rz-diff.1
> +				     ssdeep | Context triggered piecewise hashing comparison
these spaces looks weird

2023-08-25 00:48 UTC, XVilka requested changes

2023-08-25 00:48 UTC, XVilka commented on binrz/man/rz-diff.1
> +.Dd  10, 2018
Broken date

2023-08-25 00:48 UTC, XVilka commented on binrz/man/rizin.1
> +.Dd 24 Aug, 2023
Please use the same format

2023-08-25 00:48 UTC, XVilka commented on binrz/man/rizin.1
> +.It Fl H ([var])
Probably worth noting that just `-H` without any argument prints useful information about the installation - location of various paths - config file, plugins, etc:
```
rizin -H
RZ_VERSION=0.7.0
RZ_PREFIX=/Users/user/.local
RZ_EXTRA_PREFIX=
RZ_MAGICPATH=/Users/user/.local/share/rizin/magic
RZ_INCDIR=/Users/user/.local/include/librz
RZ_LIBDIR=/Users/user/.local/lib
RZ_SIGDB=/Users/user/.local/share/rizin/sigdb
RZ_EXTRA_SIGDB=
RZ_LIBEXT=dylib
RZ_RCONFIGHOME=/Users/user/.config/rizin
RZ_RDATAHOME=/Users/user/.local/share/rizin
RZ_RCACHEHOME=/Users/user/.cache/rizin
RZ_LIBR_PLUGINS=/Users/user/.local/lib/rizin/plugins
RZ_EXTRA_PLUGINS=
RZ_USER_PLUGINS=/Users/user/.local/lib/rizin/plugins
RZ_IS_PORTABLE=0
```

2023-08-25 00:48 UTC, XVilka commented on binrz/man/rizin.1
> +Disables loading any scripts or plugins.
Please be consistent. Sometimes it `disable`, sometimes it `disables`. I suggest follow the same style everywhere.

2023-08-25 16:36 UTC, wargio approved these changes
LGTM besides an extra stupid space.

2023-08-25 16:37 UTC, wargio commented on binrz/man/rz-diff.1
> +.Dd  Aug 25, 2023
extra useless space

2023-08-25 16:41 UTC, XVilka approved these changes

2023-08-26 01:38 UTC, merged