Refactor the pointer command to use the API
rizinorg/rizin pull request #3788
Opened 2023-08-25 15:24 UTC by laomaiweng

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [X] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

See issue #3780. The `*` command still uses `rz_core_cmdf`, and the read case even invokes an no-longer-existent command (`?v` instead of `%v`).

This PR fixes the `*` command for read (and I'll also try to do writes shortly) by using the API.

This is a fix, no documentation or book updates needed.

**Test plan**

I've included a _pointer read_ test case in `test/db/cmd/feat_arithmetic` (might not be the ideal place for this but seemed close enough, feel free to rearrange).

The test case does **not** pass currently, being broken for `asm.bits=8`, for reasons I can't fathom. I debugged it and upon calling `pointer_read`, `asm.bits` is still 64 instead of the expected 8. This could be a separate bug, I don't know. Please advise.

**Closing issues**

closes #3780

2023-08-25 15:41 UTC, ret2libc commented
@thestr4ng3r @wargio Any idea why this comment?

```
// this is wrong, there is more than big and little endian
RZ_API bool rz_io_read_i(RzIO *io, ut64 addr, ut64 *val, int size, bool endian) {
	ut8 buf[8];
	rz_return_val_if_fail(io && val, false);
	size = RZ_DIM(size, 1, 8);
	if (!rz_io_read_at(io, addr, buf, size)) {
		return false;
	}
	// size says the number of bytes to read transform to bits for rz_read_ble
	*val = rz_read_ble(buf, endian, size * 8);
	return true;
}
```
This code does not seem to be used too much around the codebase.

2023-08-25 15:59 UTC, laomaiweng commented
> Any idea why this comment?

(FWIW I thought this was because _rz_endian.h_ also supports middle-endian?)

2023-08-25 16:07 UTC, ret2libc commented
Yeah that's one thing I noticed too. Maybe it's just for that.

2023-08-25 16:33 UTC, XVilka requested changes
The last case fails:
```
[XX] db/cmd/feat_arithmetic pointer read
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'wv8 0xdeadbeefdeadbeef
*0
*0 @e:asm.bits=64
*0 @e:asm.bits=32
*0 @e:asm.bits=16
*0 @e:asm.bits=8
' malloc://1024
-- stdout
--- expected
+++ actual
@@ -2,4 +2,4 @@
 0xdeadbeefdeadbeef
 0xdeadbeef
 0xbeef
-0xef
+0xdeadbeefdeadbeef
```

2023-08-25 17:43 UTC, laomaiweng commented
> The last case fails

Yeah as mentioned I don't know why this happens:

> The test case does **not** pass currently, being broken for `asm.bits=8`, for reasons I can't fathom. I debugged it and upon calling `pointer_read`, `asm.bits` is still 64 instead of the expected 8. This could be a separate bug, I don't know. Please advise.

2023-08-25 18:05 UTC, Rot127 commented
@laomaiweng Didn't looked too deep into it. But try to set a break point in `rz_asm_set_bits()` and check if it gets set. It maybe doesn't because the default arch set, doesn't support 8bits and `has_bits()` returns false.

2023-08-25 20:35 UTC, laomaiweng commented
@Rot127 Yes that was it, thanks! I've amended the test to use an 8-bit compatible arch. Should pass fine now.

2023-08-25 20:45 UTC, Rot127 commented
Nice! While you are at it. Could you please add a warning if the setting of bits fails? A simple `else { RZ_LOG_WARN(...); }` should do it.

2023-08-26 01:13 UTC, laomaiweng commented
@Rot127 Not sure what you mean, I'm not calling `rz_asm_set_bits` directly? The test just runs with `rz-test` and uses `@e:asm bits=<8|16|32|64>`.

2023-08-26 01:39 UTC, XVilka approved these changes

2023-08-26 02:12 UTC, merged