Fix div by zero in 's++' and 's--'
rizinorg/rizin pull request #3803
Opened 2023-08-28 09:51 UTC by ttxine

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Running `s-- 0` and `s++ 0` causes floating point exception.

`rz_seek_blocksize_backward_handler` and `rz_seek_blocksize_forward_handler` didn't check for `n` to be non-zero.

**Test plan**

Run `s++ 0` and `s-- 0`.

2023-08-28 14:49 UTC, XVilka approved these changes

2023-08-28 15:44 UTC, wargio commented on librz/core/cmd/cmd_seek.c
> +		RZ_LOG_ERROR("n could not be negative or zero\n");
i would write more `Invalid argument: number is negative or zero`

2023-08-28 15:45 UTC, wargio requested changes
missing test.

2023-08-29 06:41 UTC, ret2libc approved these changes
LGTM after addressing @wargio 's comment.

2023-08-29 08:59 UTC, kazarmy approved these changes

2023-08-29 09:27 UTC, wargio approved these changes

2023-08-29 15:04 UTC, merged