Trycatch
rizinorg/rizin pull request #3859
Opened 2023-09-14 17:12 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

+ Refactor `trycatch` and `classes` from RzList to RzPVector.
+ Remove the deprecated API rz_bin_get_classes.

**Test plan**

CI is green.

**Closing issues**

partially address https://github.com/rizinorg/rizin/issues/3755
partially address https://github.com/rizinorg/rizin/issues/3775

2023-09-15 01:19 UTC, XVilka approved these changes

2023-09-15 02:32 UTC, XVilka requested changes
```
[XX] db/formats/pe/2331 PE: #2331
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -A -Qc q! bins/pe/2331
-- stdout
--- expected
+++ actual
@@ -1,0 +1,1 @@
+WARNING: rz_bin_object_get_classes: assertion 'obj' failed (line 740)

-- stderr
ERROR: File is not PE
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[ ] Analyze function calls
[
[x] Analyze function calls
[ ] Analyze len bytes of instructions for references
[
[x] Analyze len bytes of instructions for references
[ ] Check for classes
[
[x] Check for classes
[ ] Analyze local variables and arguments
[
[x] Analyze local variables and arguments
[ ] Type matching analysis for all functions
[
[x] Type matching analysis for all functions
[ ] Applying signatures from sigdb
[
[x] Applied 0 FLIRT signatures via sigdb
[ ] Propagate noreturn information
[
[x] Propagate noreturn information
[ ] Integrate dwarf function information.
[
[x] Integrate dwarf function information.
[ ] Resolve pointers to data sections
[
[x] Resolve pointers to data sections

[x] Use -AA or aaaa to perform additional experimental analysis.

[XX] db/formats/pe/tinyXP PE: corkami tinyXP.exe - open
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -A -Qc q! bins/pe/tinyXP.exe
-- stdout
--- expected
+++ actual
@@ -1,0 +1,1 @@
+WARNING: rz_bin_object_get_classes: assertion 'obj' failed (line 740)

-- stderr
ERROR: File is not PE
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[ ] Analyze function calls
[
[x] Analyze function calls
[ ] Analyze len bytes of instructions for references
[
[x] Analyze len bytes of instructions for references
[ ] Check for classes
[
[x] Check for classes
[ ] Analyze local variables and arguments
[
[x] Analyze local variables and arguments
[ ] Type matching analysis for all functions
[
[x] Type matching analysis for all functions
[ ] Applying signatures from sigdb
[
[x] Applied 0 FLIRT signatures via sigdb
[ ] Propagate noreturn information
[
[x] Propagate noreturn information
[ ] Integrate dwarf function information.
[
[x] Integrate dwarf function information.
[ ] Resolve pointers to data sections
[
[x] Resolve pointers to data sections

[x] Use -AA or aaaa to perform additional experimental analysis.

[XX] db/formats/dyldcache dyldcache CVE-[202](https://github.com/rizinorg/rizin/actions/runs/6192682267/job/16813115663?pr=3859#step:19:203)2-1[244](https://github.com/rizinorg/rizin/actions/runs/6192682267/job/16813115663?pr=3859#step:19:245)
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'aaa
q
' bins/dyldcache/CVE-2022-1244
-- stdout
--- expected
+++ actual
@@ -1,0 +1,1 @@
+WARNING: rz_bin_object_get_classes: assertion 'obj' failed (line 740)[XX] db/formats/pe/2331 PE: #2331
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -A -Qc q! bins/pe/2331
-- stdout
--- expected
+++ actual
@@ -1,0 +1,1 @@
+WARNING: rz_bin_object_get_classes: assertion 'obj' failed (line 740)

-- stderr
ERROR: File is not PE
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[ ] Analyze function calls
[
[x] Analyze function calls
[ ] Analyze len bytes of instructions for references
[
[x] Analyze len bytes of instructions for references
[ ] Check for classes
[
[x] Check for classes
[ ] Analyze local variables and arguments
[
[x] Analyze local variables and arguments
[ ] Type matching analysis for all functions
[
[x] Type matching analysis for all functions
[ ] Applying signatures from sigdb
[
[x] Applied 0 FLIRT signatures via sigdb
[ ] Propagate noreturn information
[
[x] Propagate noreturn information
[ ] Integrate dwarf function information.
[
[x] Integrate dwarf function information.
[ ] Resolve pointers to data sections
[
[x] Resolve pointers to data sections

[x] Use -AA or aaaa to perform additional experimental analysis.

[XX] db/formats/dyldcache dyldcache CVE-[202](https://github.com/rizinorg/rizin/actions/runs/6192682267/job/16813115663?pr=3859#step:19:203)2-1[244](https://github.com/rizinorg/rizin/actions/runs/6192682267/job/16813115663?pr=3859#step:19:245)
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'aaa
q
' bins/dyldcache/CVE-2022-1244
-- stdout
--- expected
+++ actual
@@ -1,0 +1,1 @@
+WARNING: rz_bin_object_get_classes: assertion 'obj' failed (line 740)
```

2023-09-15 02:34 UTC, XVilka requested changes

2023-09-15 02:34 UTC, XVilka commented on librz/bin/bfile.c
> +RZ_API RzPVector /*<RzBinTrycatch *>*/ *rz_bin_file_get_trycatch(RZ_NONNULL RzBinFile *bf) {
Please add ownership

2023-09-15 02:34 UTC, XVilka commented on librz/bin/format/objc/mach0_classes.c
> +RZ_API RzPVector /*<RzBinClass *>*/ *MACH0_(parse_classes)(RzBinFile *bf, objc_cache_opt_info *oi) {
Ownership of the return value

2023-09-15 02:34 UTC, XVilka commented on librz/bin/format/objc/mach0_classes.h
> +RZ_API RzPVector /*<RzBinClass *>*/ *MACH0_(parse_classes)(RzBinFile *bf, objc_cache_opt_info *oi);
Ownership

2023-09-15 02:34 UTC, XVilka commented on librz/include/rz_bin.h
> +RZ_API RzPVector /*<RzBinTrycatch *>*/ *rz_bin_file_get_trycatch(RZ_NONNULL RzBinFile *bf);
Ownership

2023-09-15 06:31 UTC, wargio commented
nice changes! might speedup a lot stuff.

2023-09-16 14:45 UTC, wargio approved these changes

2023-09-16 15:18 UTC, wargio commented on librz/analysis/class.c
> +		rz_cons_break_pop();
this shouldn't be here. only in core.

2023-09-17 02:56 UTC, XVilka approved these changes

2023-09-17 02:57 UTC, merged