Make it clear the "details" of command are available
rizinorg/rizin pull request #3890
Opened 2023-09-26 08:00 UTC by byteninjaa0

**Your checklist for this pull request**
- [ yes] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
now when we run the w? command it will show that w?? option is also available

...

**Test plan**

...

**Closing issues**

Closes #3879

2023-09-26 08:23 UTC, ret2libc requested changes
Hi and thanks for the contribution! Some comments on the PR:

- I don't think this is exactly what @XVilka meant in his bug. We would like something that would be generic and not specific to the `w` command. There are many other commands that have `??` available and we want to show a similar help message for all of them. That's why we have [rzshell](https://github.com/rizinorg/rizin/blob/dev/doc/rzshell.md)
- these `cmd_descs.c`/`cmd_descs.h` files, as you can read at the head of the files, are automatically generated from the `.yaml` files you can find at https://github.com/rizinorg/rizin/tree/dev/librz/core/cmd_descs . You should modify the .yaml files and re-build the project (this will update the `cmd_descs.c`/`cmd_descs.h` files).
- However, since this change should be done for all commands that have some "details" available, I believe this change should be done somewhere in cmd_api.c

2023-09-26 08:30 UTC, sohail1734 commented
show i do the same for other commands too?

2023-09-26 08:40 UTC, ret2libc commented
> show i do the same for other commands too?

Yes but in a general way. You should not modify the summary of each command manually.

2023-09-27 01:14 UTC, wargio commented on librz/core/cmd_descs/cmd_descs.c
> +	.summary = "Write string (see 'w??' for more help)",
Please modify the yaml file not, the generated c file.

2023-09-27 04:24 UTC, wargio commented on librz/core/cmd/cmd_api.c
> +    	}
format.

2023-09-27 08:32 UTC, wargio commented
please install pyaml and clang-format, then rebuild and run ./sys/clang-format.py before pushing.

2023-09-30 09:05 UTC, sohail1734 commented
when i am run w? it is showing the message four times .

2023-10-03 08:35 UTC, wargio approved these changes

2023-10-03 20:37 UTC, ret2libc requested changes
![image](https://github.com/rizinorg/rizin/assets/562321/6f83c808-c798-4cf7-889a-7aec76f471af)

I don't like how this looks. 
IMHO something like `(%s?? for more details)` should be appended to the summary of the top command

![image](https://github.com/rizinorg/rizin/assets/562321/3beeb752-1bde-4264-9565-0f9766efeefa)

2023-10-09 08:00 UTC, ret2libc commented
Please show a screenshot of how it looks like now!

2023-10-09 10:15 UTC, byteninjaa0 commented
![image](https://github.com/rizinorg/rizin/assets/62786136/992739a7-2f96-45e7-8cb8-872c7690c8e2)

2023-10-10 11:45 UTC, ret2libc commented
I think it is not working as expected yet. Like, `wv?` does not show the message. Or `we?` says to use `we??` but actually only `wex` has details...

Now, I think given that when a command is a leaf (there are no subcommands) the details are automatically displayed (try `wex?`, for example), I think we can just show the message `<x>?? for more details` near the summary of the subcommand with the same name as the group name.

For example:
- `w` is both a group (`w?` displays the sub-commands) and a command (`w??` shows the detail of the `w` command). In this case, it would make sense to have in the `w?` screen the message `(w?? for more details)` near the `w` command.

- `we` is the name of a group (`we?` shows the sub-commands), but there is no sub-command with the same name (there is no `we` command), thus nothing should be shown.
- `wex` is a leaf command, thus nothing should be shown. When you do `wex?` it already shows the details
- `wv` is both a group (`wv?` displays the sub-commands) and a command (`wv?? shows the details of the `wv` command). In this case it would make sense to have in the `wv?` screen the message `(wv?? for more details)` near the `wv` command.

I hope it make sense.

2023-10-10 15:03 UTC, byteninjaa0 commented
thank you for the detailed explanation, making a commit soon!

2023-10-11 00:31 UTC, wargio commented
what if we do something like tree view where if there are more subcommands to it we have a `+` instead of `|` at the beginning of the line?

2023-10-11 07:21 UTC, ret2libc commented
> what if we do something like tree view where if there are more subcommands to it we have a `+` instead of `|` at the beginning of the line? @ret2libc @XVilka

Interesting ideas... We'd need to see how it looks like, but in theory I don't mind it. It would make things clearer immediately. However, it's a slightly different problem. The `+`/`|` says whether a command has some subcommands or not. The `(use <cmd>?? for more details)` tells you whether you should use `<cmd>??` to get more info about a subcommand with the same name as the name of a group (`w` group and `w` command, for example).

2023-10-11 07:48 UTC, wargio commented
> The `(use <cmd>?? for more details)` tells you whether you should use `<cmd>??` to get more info about a subcommand with the same name as the name of a group (`w` group and `w` command, for example).

The issue i see is that this might make the command line long.

2023-10-22 06:31 UTC, byteninjaa0 commented
![Screenshot 2023-10-22 115942](https://github.com/rizinorg/rizin/assets/62786136/b9f3fe24-96bd-42f9-b214-87411ba7a426)
![Screenshot 2023-10-22 120009](https://github.com/rizinorg/rizin/assets/62786136/8210fd19-8f76-4a25-a0bd-d9ebc872e3b6)
![Screenshot 2023-10-22 120033](https://github.com/rizinorg/rizin/assets/62786136/aaa44625-bbbc-44c6-8de2-757632d681c6)
![Screenshot 2023-10-22 120056](https://github.com/rizinorg/rizin/assets/62786136/a1aa0cca-0e47-442f-a8fa-01019726ed9a)

2023-10-22 11:39 UTC, wargio commented on librz/core/cmd/cmd_api.c
> +      		if (strcmp(child->name, cd->name) == 0) {
```suggestion
      		if (!strcmp(child->name, cd->name)) {
```

2023-10-22 11:40 UTC, wargio requested changes
run clang format (requires clang format 16 and then run `./sys/clang-format.py`)

2023-10-23 07:45 UTC, ret2libc commented
Sorry for requesting changes again :(

> Now, I think given that when a command is a leaf (there are no subcommands) the details are automatically displayed (try `wex?`, for example), I think we can just show the message `<x>?? for more details` near the summary of the subcommand with the same name as the group name.

As mentioned above, I think it makes more sense to have the `<x>?? for more details` message near the *subcommand* and not near the group summary. Right now you are displaying the msg in the summary of the command group, but I think it makes more sense on the *subcommand*.

2023-10-23 13:38 UTC, byteninjaa0 commented
No problem I'll make a commit as soon as I figure out the solution btw thanks for your support and patience.

2023-12-17 11:20 UTC, XVilka commented
@byteninjaa0 have you had a chance to tackle this?

2023-12-17 13:06 UTC, byteninjaa0 commented
![image](https://github.com/rizinorg/rizin/assets/62786136/7aa68f79-3b8e-4451-8291-d00df8410f2e)
it is not show the "see w?? for more details " for w subcommand other than that its working fine i guess.

2023-12-17 13:09 UTC, XVilka commented
You need to update the unit test:
```
 test_cmd_argv_state ERR
[XX] Fail at line 665: zj, zJ and zq are considered in the help: expected Usage: [.][times][cmd][~grep][@[@iter]addr][|>pipe] ; ...
| z[jqJ] # group summary
, got Usage: [.][times][cmd][~grep][@[@iter]addr][|>pipe] ; ...
| z[jqJ] # group summary (see z?? for more details)
.

test_cmd_group_argv_modes ERR
[XX] Fail at line 713: zd is considered in the help: expected Usage: [.][times][cmd][~grep][@[@iter]addr][|>pipe] ; ...
| z[jqd] # z group summary
, got Usage: [.][times][cmd][~grep][@[@iter]addr][|>pipe] ; ...
| z[jqd] # z group summary (see z?? for more details)
.
```
Can you move this message below the first line?

2023-12-17 13:39 UTC, byteninjaa0 commented
same test is failed again i am seeing into the issue i think we have to make our unit test flexible for the edited summary of subcommand

2023-12-25 05:17 UTC, byteninjaa0 commented
is there anything else left in this?

2023-12-25 11:16 UTC, XVilka commented
> is there anything else left in this?

green CI

2023-12-25 22:59 UTC, XVilka approved these changes

2023-12-25 23:41 UTC, merged