Update DEVELOPERS.md
rizinorg/rizin pull request #3891
Opened 2023-09-26 18:17 UTC by createyourpersonalaccount

Be explicit about where docstrings go.

 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Clarifying the documentation on docstring placement. The `findMinMax()` example is actually documented in the source file but it is wrongly shown as documented in its declaration.

...

**Test plan**

...

**Closing issues**

...

2023-09-26 18:22 UTC, createyourpersonalaccount commented
Is this style consistent across the project? Or do some Doxygen docstrings exist in header files too?

When the documentation is in the header files, they are distributed and it is helpful to the programmer to read them. When they are in the source files, the header files are leaner, so the installation is leaner; but the separate option to install documentation must be used.

2023-09-27 01:11 UTC, wargio commented
> Is this style consistent across the project? Or do some Doxygen docstrings exist in header files too?

Doxygen comments are only in source files, not headers.

2023-09-27 01:12 UTC, wargio approved these changes

2023-09-27 01:12 UTC, wargio commented on DEVELOPERS.md
> +static int findMinMax(RzList *maps, ut64 *min, ut64 *max, int skip, int width) { /* ... */ }
```suggestion
static int find_min_max(RzList *maps, ut64 *min, ut64 *max, int skip, int width) { /* ... */ }
```
This should not be in camel case.

2023-09-27 03:07 UTC, createyourpersonalaccount commented
@wargio the camel case you corrected actually exists in the source code https://github.com/rizinorg/rizin/blob/dev/librz/core/cdebug.c#L550

2023-09-27 03:23 UTC, XVilka requested changes

2023-09-27 03:23 UTC, XVilka commented on DEVELOPERS.md
> +Documentation goes into the source files (not the header files)
End sentences with dot please.

2023-09-27 03:57 UTC, XVilka approved these changes

2023-09-27 04:23 UTC, wargio commented
> @wargio the camel case you corrected actually exists in the source code
> 
> https://github.com/rizinorg/rizin/blob/71679b0800c657ad03fa374e989b2cd87433bd29/librz/core/cdebug.c#L550
> I think you should revert that.

yes but still it should not be in camel case.

2023-09-29 13:14 UTC, merged