quitconfirm in debug session solved
rizinorg/rizin pull request #3916
Opened 2023-10-12 04:58 UTC by vanshjangir

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

In `librz/main/rizin.c` , when in debugger session the program ask for quit confirmation independent of `scr.confirmquit` true or false. 
So if the program ask for quit confirmation in debugger session, `scr.confirmquit` is set to false to not ask for quit confirmation twice.

**Test plan**

...

**Closing issues**

...

2023-10-12 07:28 UTC, ret2libc reviewed
What if we move the `if (debug)` code below the 
```
			if (rz_config_get_i(r->config, "scr.confirmquit")) {
				if (!rz_cons_yesno('n', "Do you want to quit? (Y/n)")) {
					continue;
				}
			}
```
? 

It would need some adjustments, but I think it would make more sense. There's some duplicated code here.

2023-10-12 15:44 UTC, ret2libc requested changes

2023-10-12 15:44 UTC, ret2libc commented on librz/main/rizin.c
> +						rz_config_set_i(r->config, "scr.confirmquit", false);
this is not needed anymore?!

2023-10-12 16:17 UTC, vanshjangir commented on librz/main/rizin.c
> +						rz_config_set_i(r->config, "scr.confirmquit", false);
I understood, here is my approach

What I have done here is 
if `scr.confirmquit` is true, then the program will ask for quit confirmation and continue if n is returned.
if y is returned then the program will ask for to kill the process is and will not continue to the loop in any case.

2023-10-13 07:26 UTC, ret2libc approved these changes

2023-10-13 07:31 UTC, wargio commented on librz/main/rizin.c
> +					if (rz_config_get_i(r->config, "dbg.exitkills") &&
merge this.

2023-10-13 18:26 UTC, 8dcc commented
(Closes #3818)

2023-10-20 07:26 UTC, ret2libc commented on librz/main/rizin.c
> +					if (rz_config_get_i(r->config, "dbg.exitkills") &&
what do you mean @wargio ?

2023-10-20 07:27 UTC, ret2libc commented
IMO the PR is in good shape. @wargio ?

2023-10-20 09:26 UTC, wargio commented on librz/main/rizin.c
> +					if (rz_config_get_i(r->config, "dbg.exitkills") &&
just make this `else` an `else if` directly and avoid that double indentation.

2023-10-22 12:26 UTC, XVilka approved these changes

2023-10-23 05:34 UTC, wargio approved these changes

2023-10-23 05:35 UTC, merged

2023-10-23 05:35 UTC, wargio commented
Thank you <3