Allow parsing go 1.20 pclntab
rizinorg/rizin pull request #3947
Opened 2023-11-01 15:18 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This is a quick patch for allowing parsing go 1.20 pclntab.

From the go changes, i don't see differences between 1.18/1.19 and 1.20.

**i haven't added tests.**

2023-11-01 16:14 UTC, XVilka requested changes
Please add also the 1.21 support as it's the latest stable release.

2023-11-02 03:16 UTC, wargio commented
failures are un-related to this PR

2023-11-02 05:27 UTC, reuteras commented
This patch solved my problem with the Golang compiler go1.20.2 mentioned on Mattermost. Now I get the names for the function names in the stripped binary.

2023-11-02 08:29 UTC, merged

2023-11-02 08:29 UTC, wargio commented
approved in side channel