build: fix compilation with meson 1.3.0
rizinorg/rizin pull request #3995
Opened 2023-11-21 14:10 UTC by ret2libc

2023-11-21 15:16 UTC, XVilka requested changes
Looks like it broke unit tests for some reason

2023-11-24 10:06 UTC, XVilka requested changes
```
[libzip] configuring '/home/runner/work/rizin/rizin/build/subprojects/libzip-1.9.2/config.h'
/home/runner/work/rizin/rizin/subprojects/libzip-1.9.2/cmake-config.h.in:8:30: error cmakedefine only supports two modes:
	--> #cmakedefine HAVE___PROGNAME
 	--> #cmakedefine HAVE___PROGNAME @HAVE___PROGNAME@
In particular, no value other than "HAVE___PROGNAME" will be substituted and
no extra characters (comments, etc.) are allowed on the line.
  8 | #cmakedefine HAVE___PROGNAME ${HAVE___PROGNAME}
                                   ^
/home/runner/work/rizin/rizin/subprojects/libzip-1.9.2/meson.build:114:12: error in function configure_file()
114 | config_h = configure_file(
                 ^
/home/runner/work/rizin/rizin/meson.build:575:17: error in function subproject()
575 |   libzip_proj = subproject('libzip', default_options: [
                      ^
Error: Process completed with exit code 1.
```

2023-12-01 12:47 UTC, XVilka approved these changes

2023-12-01 13:25 UTC, ret2libc commented
```
>>> ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 MALLOC_PERTURB_=252 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 /__w/rizin/rizin/rizin/build/test/unit/test_subprocess
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
test_noargs_noinput_outerr OK
Hello World
Hello World
test_args OK
test_env OK
test_stdin OK
test_multi OK
test_specialchar_args OK
test_nopipes OK
test_stdoutonly OK
test_stderronly OK
test_stdoutstderr OK
test_interactive OK
test_interactive_pty OK
test_interactive_custom_pty OK
test_interactive_not_raw_pty ERR
[XX] Fail at line 367: No 3 + 5 + c: expected 2072314[104](https://github.com/rizinorg/rizin/actions/runs/7059979643/job/19218680371?pr=3995#step:7:105), got 2072.

stderr:
This is on err
This is on err
```


I saw this failing also on separate PR :( i'd be for merging this anyway and fix this before release.

2023-12-01 15:32 UTC, merged