Enable generation of inter-procedual control flow graph.
rizinorg/rizin pull request #4001
Opened 2023-11-24 20:48 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Adds the ability to generate a inter-procedual control flow graph.

One thing to discuss before merge:

The graph uses `RzGraphNodeInfo` instead of a simple `RzGraphNode`. This wastes space (at least the two `char *` members) because `iCFGs` will get enormous.

But if the graph is supposed to be returned by `rz_core_graph` it is basically forced to use it. Using only the node prevents printing it. Which would only be annoying for testing. 

**Test plan**

Test added

**Closing issues**

None

2023-11-25 02:58 UTC, wargio approved these changes

2023-11-25 03:23 UTC, wargio commented
@Rot127 is missing the changes on the YAML file.

2023-11-26 02:39 UTC, XVilka requested changes

2023-11-26 02:39 UTC, XVilka commented on librz/util/graph.c
>  /* users of this function should be aware they can't access n anymore */
Convert comment to doxygen while you are on it

2023-11-27 15:37 UTC, XVilka approved these changes

2023-12-03 05:00 UTC, XVilka requested changes
```
Missing type comment at <rizin/librz/core/cgraph.c:796:69> (token is not a comment)
Missing type comment at <rizin/librz/core/cgraph.c:817:72> (token is not a comment)
```
Also:
```
Run ./librz/core/cmd_descs/cmd_descs_generate.py --output-dir /tmp ./librz/core/cmd_descs/*.yaml
218d217
< static const RzCmdDescArg analysis_graph_icfg_args[2];
Error: Process completed with exit code 1.
```

2023-12-03 05:30 UTC, XVilka commented
@Rot127 still not synchronized YAML and C/H command handlers files:
```
Run ./librz/core/cmd_descs/cmd_descs_generate.py --output-dir /tmp ./librz/core/cmd_descs/*.yaml
218d217
< static const RzCmdDescArg analysis_graph_icfg_args[2];
Error: Process completed with exit code 1.
```

2023-12-03 05:52 UTC, XVilka approved these changes

2023-12-03 13:16 UTC, XVilka commented
Regarding this:

> The graph uses RzGraphNodeInfo instead of a simple RzGraphNode. This wastes space (at least the two char * members) because iCFGs will get enormous.
>
> But if the graph is supposed to be returned by rz_core_graph it is basically forced to use it. Using only the node prevents printing it. Which would only be annoying for testing.

Our graph API is in very poor shape, to be honest. We should have better graph data structures, just plain graphs and "enriched" with metainformation that is ready for printing: https://github.com/rizinorg/rizin/issues/992 (see also https://github.com/rizinorg/rizin/issues/397)

2023-12-14 14:34 UTC, merged