Create global variables from PDB
rizinorg/rizin pull request #4021
Opened 2023-12-05 02:33 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

closes #3625

2023-12-05 13:46 UTC, XVilka requested changes
I think it might make sense to try fixing also https://github.com/rizinorg/rizin/issues/955 in the same PR (if it's easy enough, of course)

2023-12-05 13:46 UTC, XVilka commented on librz/bin/pdb/omap.c
> +static ut64 rz_bin_pdb_omap_remap(RZ_NONNULL RzPdbOmapStream *omap_stream, ut64 address) {
If it's static, please remove `rz_` prefix

2023-12-05 13:46 UTC, XVilka commented on librz/bin/pdb/omap.c
> +RZ_API ut64 rz_bin_pdb_to_rva(RZ_NONNULL const RzPdb *pdb, const PDBSectionOffset *section_offset) {
Please add Doxygen

2023-12-05 13:46 UTC, XVilka commented on librz/bin/pdb/tpi.c
>   * \return RzList *
Update Doxygen too

2023-12-05 13:46 UTC, XVilka commented on librz/include/rz_util/rz_buf.h
> +static inline ut8 rz_buf_peek(RZ_NONNULL RzBuffer *b) {
Please add Doxygen for those

2023-12-05 13:46 UTC, XVilka commented on test/db/formats/pdb
> +EXPECT=<<EOF
Could you also please add a test that checks if those (just a few, at least two) global variables are referenced? E.g. using both `avgx` and `pd`/`pdf` commands?

2023-12-05 13:46 UTC, XVilka commented on test/db/formats/pdb
> +EXPECT=<<EOF
This way, we make sure that these globals are picked up by the analysis.

2023-12-06 03:20 UTC, wargio commented on librz/bin/pdb/tpi.h
> +	RzPVector /* <char *> */ method_names; // array of names.
```suggestion
	RzPVector /*<char *>*/ method_names; // array of names.
```

2023-12-06 05:57 UTC, merged