Mention tools in README
rizinorg/rizin pull request #4065
Opened 2024-01-03 16:27 UTC by XVilka

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Very few people are aware that Rizin also provides different helpful tools apart from `rizin` itself. Put them on the "first page," therefore.

2024-01-04 10:30 UTC, Rot127 requested changes
Definitely a good addition IMHO.

2024-01-04 10:30 UTC, Rot127 commented on README.md
> +Apart from the main tool - `rizin` there are also other tools tailored for specific purpose and
```suggestion
Apart from the main tool `rizin`, there are also other tools tailored for specific purposes and 
```

2024-01-04 10:30 UTC, Rot127 commented on README.md
> +useful for shell scripting or as a separate standalone tools:
```suggestion
useful for shell scripting or as separate standalone tools:
```

2024-01-04 10:30 UTC, Rot127 commented on README.md
> +- `rz-hash` - allows to calculate different hashes or even encrypt the Data
```suggestion
- `rz-hash` - allows to calculate different hashes or even encrypt data
```

2024-01-04 15:21 UTC, wargio commented on README.md
> +- `rz-sign` - tool to work with FLIRT signatures
```suggestion
- `rz-sign` - tool to create, convert and parse FLIRT signatures
```

2024-01-05 04:29 UTC, wargio approved these changes

2024-01-05 04:29 UTC, merged