Refactor sections in RzBinPlugin from list to pvector
rizinorg/rizin pull request #4089
Opened 2024-01-09 16:18 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

CI is green.

**Closing issues**

partially address https://github.com/rizinorg/rizin/issues/3755
partially address https://github.com/rizinorg/rizin/issues/3775

2024-01-10 11:25 UTC, XVilka requested changes
LGTM with two small nitpicks

2024-01-10 11:25 UTC, XVilka commented on librz/util/vector.c
> +
Unnecessary empty line

2024-01-10 11:25 UTC, XVilka commented on librz/util/vector.c
> +		rz_pvector_push(pvec1, *it);
Can't we use `memmove` to speed up this somehow? Both are contiguous chunks of memory.

2024-01-10 11:39 UTC, XVilka commented on librz/util/vector.c
> +		rz_pvector_push(pvec1, *it);
For example, calling `RESIZE_OR_RETURN_NULL` first, then `memmove` might be faster than iterations if there are many elements in `pvec2`.

2024-01-11 04:19 UTC, wargio approved these changes

2024-01-11 04:19 UTC, merged