Fix generic asm color inconsistencies
rizinorg/rizin pull request #4095
Opened 2024-01-11 12:14 UTC by giridharprasath

- Enhanced unknown string parsing in asm generic tokenization

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- Added more checks for parsing the generic asm str buf

...

**Test plan**
Tested on 2 binaries (x86-64, arm64)
Output before:
![ScreenShot_2024-01-11_at_05:00:43-AM](https://github.com/rizinorg/rizin/assets/17312540/5b9e78de-6489-47eb-8958-dc11d5c42492)

Now:
![ScreenShot_2024-01-11_at_04:53:58-AM](https://github.com/rizinorg/rizin/assets/17312540/21e7dcf9-8d0f-4759-8b80-154b036df21a)

Before:
`ch` was getting recognized as a register
![ScreenShot_2024-01-11_at_05:01:04-AM](https://github.com/rizinorg/rizin/assets/17312540/a114b451-ecd9-4ec1-987b-f4d77a3f1adf)

Now:
![ScreenShot_2024-01-11_at_05:01:40-AM](https://github.com/rizinorg/rizin/assets/17312540/8e5c3c53-0c06-4826-87a1-ff931b34772b)

...

**Closing issues**

...

2024-01-11 14:03 UTC, Rot127 requested changes

2024-01-11 14:03 UTC, Rot127 commented on librz/asm/asm.c
> +	return (is_operator(str + prev - 1) || is_separator(str + prev - 1)) &&
Please document this function. The comment you already wrote here can be move to brief + descriptions of the parameters.

2024-01-12 09:10 UTC, Rot127 approved these changes

2024-01-12 10:42 UTC, XVilka approved these changes

2024-01-12 10:43 UTC, merged