Refactor the <entries> in RzBinPlugin from list to pvector
rizinorg/rizin pull request #4118
Opened 2024-01-17 09:01 UTC by PeiweiHu

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

CI is green.

**Closing issues**

partially address https://github.com/rizinorg/rizin/issues/3755
closes address https://github.com/rizinorg/rizin/issues/3775

2024-01-17 10:30 UTC, XVilka requested changes
Broken tests with errors like those:
```
[XX] db/formats/pe/exe2pe PE: corkami exe2pe.exe - open and don't parse oob relocs
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc ir bins/pe/exe2pe.exe
-- stdout
--- expected
+++ actual
@@ -0,3 +0,4 @@
 vaddr paddr type name 
 ----------------------
+WARNING: rz_pvector_at: assertion 'vec && index < vec->v.len' failed (line 272)
```

2024-01-19 10:47 UTC, XVilka commented
@PeiweiHu still fails on ASAN builds, but the error is unclear from the logs. I recommend to run it locally to check and see the problem.

2024-01-20 13:02 UTC, wargio approved these changes

2024-01-29 15:44 UTC, wargio commented on librz/bin/bobj.c
> +RZ_API const RzPVector /*<RzBinAddr *>*/ *rz_bin_object_get_entries(RZ_NONNULL RzBinObject *obj) {
add the RZ_BORROW

2024-02-06 14:54 UTC, XVilka commented
@PeiweiHu Hi! Any progress with this? Would be nice to get this merged before the release (roughly in 2 weeks or so).

2024-02-07 02:15 UTC, PeiweiHu commented
> @PeiweiHu Hi! Any progress with this? Would be nice to get this merged before the release (roughly in 2 weeks or so).

Too busy these days. But I think I can finish this in 2 weeks.

2024-02-16 15:11 UTC, PeiweiHu commented
The output before and after adopting PR is different during the test:
```
ASAN_OPTIONS=detect_leaks=0:detect_odr_violation=0:allocator_may_return_null=1 rz-test test/db/analysis/dalvik
```

The error is shown as follows. But I don't understand why this PR can cause this....

```
[XX] /Users/none/Codebase/rizin/test/db/analysis/dalvik Resolve also exception paths found after gotos/returns
RZ_NOPLUGINS=1 /usr/local/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'aaa
axg @ 0x800000021c
' apk://bins/dex/ade8bef0ac29fa363fc9afd958af0074478aef650adeb0318517b48bd996d5d5.apk
-- stdout
../librz/diff/diff.c:388:12: runtime error: call to function line_elem_at through pointer to incorrect function type 'const void *(*)(const void *, unsigned int)'
lines_diff.c:50: note: line_elem_at defined here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../librz/diff/diff.c:388:12 in
../librz/diff/unified_diff.c:95:10: runtime error: call to function line_elem_at through pointer to incorrect function type 'const void *(*)(const void *, unsigned int)'
lines_diff.c:50: note: line_elem_at defined here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../librz/diff/unified_diff.c:95:10 in
../librz/diff/unified_diff.c:96:3: runtime error: call to function line_stringify through pointer to incorrect function type 'void (*)(const void *, RzStrBuf *)'
lines_diff.c:62: note: line_stringify defined here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../librz/diff/unified_diff.c:96:3 in
../librz/util/list.c:193:3: runtime error: call to function group_op_free through pointer to incorrect function type 'void (*)(void *)'
diff.c:702: note: group_op_free defined here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../librz/util/list.c:193:3 in
--- expected
+++ actual
@@ -1,77 +1,0 @@
-- 0x800000021c fcn 0x800000021c sym.android.telephony.TelephonyManager.String_getDeviceId
-  - 0x100018936 fcn 0x1000186b0 method.public.static.com.network.android.SmsReceiver.void_a_org.xmlpull.v1.XmlSerializer__java.io.StringWriter__android.content.Context
-  - 0x1000186b0 fcn 0x1000186b0 method.public.static.com.network.android.SmsReceiver.void_a_org.xmlpull.v1.XmlSerializer__java.io.StringWriter__android.content.Context
-    - 0x100025f78 fcn 0x100025f70 fcn.100025f70
-    - 0x100025f70 fcn 0x100025f70 fcn.100025f70
-      - 0x10002666c fcn 0x10002653c method.public.static.com.network.android.g.a
-      - 0x10002653c fcn 0x10002653c method.public.static.com.network.android.g.a
-        - 0x100019cac fcn 0x100019c60 method.public.static.com.network.android.a.c.void_a_android.content.Context__int
-        - 0x100019c60 fcn 0x100019c60 method.public.static.com.network.android.a.c.void_a_android.content.Context__int
-          - 0x100019d1c fcn 0x100019c60 method.public.static.com.network.android.a.c.void_a_android.content.Context__int
-          - 0x100019e00 fcn 0x100019c60 method.public.static.com.network.android.a.c.void_a_android.content.Context__int
-          - 0x10001c7a0 fcn 0x10001c6f0 method.public.final.com.network.android.a.j.void_run
-        - 0x10001ac02 fcn 0x10001abb8 method.public.static.com.network.android.a.c.void_a_android.content.Context__byte____boolean__boolean
-        - 0x10001abb8 fcn 0x10001abb8 method.public.static.com.network.android.a.c.void_a_android.content.Context__byte____boolean__boolean
-          - 0x10001ab9e fcn 0x10001ab9c method.public.static.com.network.android.a.c.void_a_android.content.Context__byte
-          - 0x10001ab9c fcn 0x10001ab9c method.public.static.com.network.android.a.c.void_a_android.content.Context__byte
-            - 0x100027fe2 fcn 0x100027fb4 method.public.static.com.network.android.j.boolean_a_android.content.Context__boolean__boolean__short
-            - 0x100027fb4 fcn 0x100027fb4 method.public.static.com.network.android.j.boolean_a_android.content.Context__boolean__boolean__short
-              - 0x100027e8e fcn 0x100027df0 method.public.static.com.network.android.j.boolean_a_android.content.Context__boolean__boolean
-              - 0x100027df0 fcn 0x100027df0 method.public.static.com.network.android.j.boolean_a_android.content.Context__boolean__boolean
-                - 0x10001c948 fcn 0x10001c918 method.public.final.com.network.android.a.l.void_run
-                - 0x10001c918 fcn 0x10001c918 method.public.final.com.network.android.a.l.void_run
-                  - 0x10000ed93 ???
-                - 0x10001dcd4 fcn 0x10001dcb0 method.public.static.com.network.android.agent.NetworkApp.void_b_android.content.Context
-                - 0x10001dcb0 fcn 0x10001dcb0 method.public.static.com.network.android.agent.NetworkApp.void_b_android.content.Context
-                  - 0x10001dc44 fcn 0x10001daf4 method.static.synthetic.com.network.android.agent.NetworkApp.void_a_com.network.android.agent.NetworkApp
-                  - 0x10001daf4 fcn 0x10001daf4 method.static.synthetic.com.network.android.agent.NetworkApp.void_a_com.network.android.agent.NetworkApp
-                    - 0x10001e918 fcn 0x10001e914 method.public.final.com.network.android.agent.c.void_run
-                  - 0x10001ea30 fcn 0x10001ea2c method.public.final.com.network.android.agent.e.void_run
-                - 0x10001dd60 fcn 0x10001dcb0 method.public.static.com.network.android.agent.NetworkApp.void_b_android.content.Context
-                - 0x10001ddb0 fcn 0x10001dcb0 method.public.static.com.network.android.agent.NetworkApp.void_b_android.content.Context
-                - 0x10001ed72 fcn 0x10001eca0 method.protected.final.com.network.android.android.monitor.AppServicePinger.void_onHandleIntent_android.content.Intent
-                - 0x1000285e2 fcn 0x1000285d4 method.public.static.com.network.android.j.boolean_c_android.content.Context
-                - 0x1000285d4 fcn 0x1000285d4 method.public.static.com.network.android.j.boolean_c_android.content.Context
-                  - 0x100028322 fcn 0x1000282fc method.public.static.com.network.android.j.void_b_android.content.Context
-                  - 0x1000282fc fcn 0x1000282fc method.public.static.com.network.android.j.void_b_android.content.Context
-                    - 0x100028812 fcn 0x1000287f4 method.public.final.com.network.android.l.void_run
-                  - 0x100028802 fcn 0x1000287f4 method.public.final.com.network.android.l.void_run
-                - 0x100045a44 fcn 0x100045a1c method.public.final.com.network.h.k.void_run
-              - 0x10002d7aa fcn 0x10002d714 method.protected.static.com.network.android.monitor.observer.BatteryReceiver.void_a_android.content.Intent__android.content.Context
-              - 0x10002d714 fcn 0x10002d714 method.protected.static.com.network.android.monitor.observer.BatteryReceiver.void_a_android.content.Intent__android.content.Context
-                - 0x10002d6f8 fcn 0x10002d6c4 method.public.static.com.network.android.monitor.observer.BatteryReceiver.String_a_android.content.Context
-                - 0x10002d6c4 fcn 0x10002d6c4 method.public.static.com.network.android.monitor.observer.BatteryReceiver.String_a_android.content.Context
-                  - 0x1000188ec fcn 0x1000186b0 method.public.static.com.network.android.SmsReceiver.void_a_org.xmlpull.v1.XmlSerializer__java.io.StringWriter__android.content.Context
-                - 0x10002fc8c fcn 0x10002fc84 method.public.final.com.network.android.monitor.observer.s.void_run
-            - 0x10002811a fcn 0x100028064 method.public.static.com.network.android.j.boolean_a_android.telephony.TelephonyManager__android.content.Context__boolean__android.net.ConnectivityManager
-            - 0x100028064 fcn 0x100028064 method.public.static.com.network.android.j.boolean_a_android.telephony.TelephonyManager__android.content.Context__boolean__android.net.ConnectivityManager
-              - 0x10001eb52 fcn 0x10001eac4 method.public.final.com.network.android.agent.g.void_run
-              - 0x100027f7 [...]

2024-02-17 05:46 UTC, wargio commented on librz/include/rz_vector.h
> +	if (index >= vec->v.len) {
did you get warnings about this?

2024-02-17 05:59 UTC, wargio commented on librz/include/rz_vector.h
> +	if (index >= vec->v.len) {
oh i see. rz_list_get_n has the same behaviour.

2024-02-24 16:50 UTC, XVilka approved these changes

2024-02-25 11:15 UTC, wargio approved these changes

2024-02-25 11:42 UTC, merged