removed sdb_fmt
rizinorg/rizin pull request #4123
Opened 2024-01-17 18:04 UTC by HN026

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

Partially addresses #1168 
...

2024-01-17 21:09 UTC, pelijah commented
IMO allocating strings on heap is not the best choice.

2024-01-17 21:17 UTC, HN026 commented
> IMO allocating strings on heap is not the best choice.

Other alternatives come w their trade-offs

2024-01-18 02:09 UTC, wargio commented on librz/asm/arch/6502/6502dis.c
> +			char *buf_asm = rz_str_newf("invalid");
You could start as `NULL` and if it stays NULL before the end then you can set this as `rz_str_new("invalid")`

2024-01-18 02:17 UTC, wargio commented on librz/asm/arch/6502/6502dis.c
> +					buf_asm = rz_str_newf("truncated");
use `rz_str_newf` only for those strings that requires formatting (`"foo %d %s..."`) and for strings like these instead just `rz_str_new`

2024-01-18 02:17 UTC, wargio commented on librz/asm/arch/6502/6502dis.c
> +			char *buf_asm = rz_str_newf("invalid");
set this to NULL.

2024-01-18 02:18 UTC, wargio commented on librz/asm/arch/6502/6502dis.c
> +				free(buf_asm);
```suggestion
				buf_asm = rz_str_new("invalid");
```

2024-01-18 02:18 UTC, wargio commented on librz/asm/arch/6502/6502dis.c
> +			char *buf_asm = rz_str_newf("invalid");
and remove all the free calls but not the one after `rz_strbuf_set`

2024-01-18 02:20 UTC, wargio commented on librz/asm/arch/gb/gbdis.c
>  	}
add a `default` case and use that to set the `invalid` string.

2024-01-18 02:21 UTC, wargio commented on librz/asm/arch/i4004/i4004dis.c
> +	char *buf_asm = rz_str_newf("invalid");
same here. add a `default` case, set the invalid there and remove the added `free` but not the one after the `rz_strbuf_set`

2024-01-18 02:25 UTC, wargio commented
> IMO allocating strings on heap is not the best choice.

true but `sdb_fmt` uses an internal `static char buffer[SIZE]` which forbids us to do multithreading.

2024-01-18 06:18 UTC, wargio commented
@pelijah i have added this change so @HN026 can use this instead of allocating mem https://github.com/rizinorg/rizin/pull/4124

2024-01-18 08:28 UTC, wargio commented
@HN026 Please rebase and use the new `setf_asm` function

2024-01-19 02:09 UTC, wargio requested changes
Looks almost perfect besides for the issue in `librz/asm/arch/6502/6502dis.c`

2024-01-19 02:09 UTC, wargio commented on librz/asm/arch/6502/6502dis.c
> +	rz_asm_op_set_asm(op, "invalid");
no. this overwrites the other `rz_asm_op_set_asm`. move this into the `default` case. (see the other comment.)

2024-01-19 02:09 UTC, wargio commented on librz/asm/arch/6502/6502dis.c
> -				free(buf_asm);
Move here the `rz_asm_op_set_asm(op, "invalid");`

2024-01-19 10:50 UTC, XVilka approved these changes

2024-01-19 10:50 UTC, merged