Dist fuzz pcre2
rizinorg/rizin pull request #4185
Opened 2024-02-04 01:16 UTC by Rot127

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Supersedes https://github.com/rizinorg/rizin/pull/4033

**Test plan**

...

**Closing issues**

...

2024-02-04 01:28 UTC, XVilka approved these changes
LGTM if all green

2024-02-04 05:55 UTC, wargio approved these changes

2024-02-04 10:56 UTC, XVilka requested changes
Cross-build fails:
```
librz/util/meson.build:172:19: ERROR: Tried to mix libraries for machines build machine and host machine in target 'rz_util_native' This is not possible in a cross build.
```
 Just define native dependency for cross-build separately, like other libs in the same file

2024-02-05 04:49 UTC, wargio commented on librz/cons/less.c
>  #include <rz_util.h>
`#include <rz_util/rz_regex.h>` should be added in `#include <rz_util.h>`

2024-02-05 04:49 UTC, wargio commented on librz/cons/less.c
> +#include "rz_vector.h"
also this is global not local.

2024-02-05 04:51 UTC, merged

2024-02-25 16:21 UTC, arrowd commented
Why use static linking here? I'm getting
```
ld: error: relocation R_X86_64_32S cannot be used against symbol '_pcre2_ucd_records_8'; recompile with -fPIC
```
on FreeBSD when building against system pcre2.

2024-02-26 01:36 UTC, wargio commented
@Rot127

2024-02-26 08:43 UTC, Rot127 commented
Thanks for the report! Will fix it in two days.

If you need a quick fix, you can add the C flag in  `subprojects/packagefiles/pcre2/meson.build`.
And run `git clean -dxff subprojects/pcre2*` afterwards.