Add different types of RzGraphNodeInfos.
rizinorg/rizin pull request #4189
Opened 2024-02-06 08:56 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This adds support for multiple graph node infos.
It removes the assumption that information of
a graph node must be some strings and an offset.

**Test plan**

All green.
And more to ccome for CFG and iCFGs

**Closing issues**

None

2024-02-06 12:23 UTC, ret2libc requested changes
Can we add at least a unit test for these new graph features?

2024-02-06 12:29 UTC, Rot127 commented
Yes, of course. It's on the list above. Going to add them tomorrow.

2024-02-09 10:08 UTC, XVilka requested changes
Few minor nitpicks but overall LGTM

2024-02-09 10:08 UTC, XVilka commented on librz/core/cgraph.c
> +static bool add_edge_to_cfg(RZ_NONNULL RzGraph /*<RzGraphNodeInfo *>*/ *graph,
Please update Doxygen too since you renamed parameters

2024-02-09 10:08 UTC, XVilka commented on librz/util/graph_drawable.c
>  RZ_API void rz_graph_free_node_info(void *ptr) {
Add NULLABLE here pls

2024-02-09 10:08 UTC, XVilka commented on librz/util/graph_drawable.c
> +	if (data) {
Invert this condition to avoid unnecessary nesting

2024-02-09 10:08 UTC, XVilka commented on librz/util/graph_drawable.c
>  	if (data) {
Invert this condition to avoid unnecessary nesting

2024-02-09 10:08 UTC, XVilka commented on librz/util/graph_drawable.c
> +	if (data) {
Invert this condition to avoid unnecessary nesting

2024-02-09 12:20 UTC, XVilka approved these changes

2024-02-09 12:34 UTC, XVilka commented
@Rot127 one minor thing left:
```
Mismatched function annotation for rz_graph_free_node_info at <rizin/librz/include/rz_util/rz_graph_drawable.h:82:13> : None (was RZ_NULLABLE at <rizin/librz/util/graph_drawable.c:31:13>
```

2024-02-09 14:23 UTC, merged