Refactor how ASLR is supported in rizin.
rizinorg/rizin pull request #4202
Opened 2024-02-10 06:15 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Refactors the code and moves the code into the same function.

Adds support to windows via `SetProcessMitigationPolicy` and macos following the GDB approach.

**Test plan**

Unfortunately this cannot be tested easily in the regression suite.

- Build the following C code by `gcc example.c`
```c
#include <stdio.h>

const char *test = "test";

int main() {
  printf("%p\n", (void*)test);
  return 0;
}
```

- Then create the following rz-run file `noaslr.rz`:

```bash
aslr=no
program=a.out
```

Then run `rz-run noaslr.rz` multiple times.

If the value output is the same then ASLR is correctly disabled.

**Closing issues**

Fix #4147

2024-02-10 06:33 UTC, wargio commented
@gogo2464 if you want to try this on windows, it could be useful.

2024-02-10 09:54 UTC, wargio commented
i'm currently testing this on windows.

2024-02-11 16:20 UTC, wargio commented
So i have tested this extensively on windows and you cannot disable ASLR programmatically, only enable it.

2024-02-11 17:46 UTC, XVilka commented
> So i have tested this extensively on windows and you cannot disable ASLR programmatically, only enable it.

This makes perfect sense from the security PoV.

2024-02-11 17:52 UTC, XVilka requested changes
These files are an absolute mess; thanks for making them a bit more readable. As for other platforms, maybe @arrowd and @devnexen could help us?

2024-02-11 17:52 UTC, XVilka commented on librz/util/sys.c
>  /**
Add a note about Windows limitation here

2024-02-11 17:52 UTC, XVilka commented on librz/util/sys.c
> +	// Apple supports this by using the spawn api.
Most other multiline comments are `/**/`. Lets be consistent.

2024-02-11 17:52 UTC, XVilka commented on librz/util/sys.c
>  RZ_API int rz_sys_execv(const char *pathname, char *const argv[]) {
Could you please add a Doxygen to this function while you are at it?

2024-02-11 17:53 UTC, XVilka commented
It breaks one unit test on Windows:
```
 66/119 rizin:unit / run                                   FAIL             0.02s   (exit status 4294967295 or signal 4294967167 SIGinvalid)                 
```

2024-02-11 20:02 UTC, devnexen commented
> These files are an absolute mess; thanks for making them a bit more readable. As for other platforms, maybe @arrowd and @devnexen could help us?

it builds and has the same succesful unit tests than `dev` on haiku.

2024-02-12 03:07 UTC, XVilka commented
Static build fails subprocess unit test:
```
Summary of Failures:

 90/119 rizin:unit / subprocess                            FAIL            0.01s   exit status 1
```

2024-02-12 03:08 UTC, XVilka approved these changes

2024-02-12 04:22 UTC, merged

2024-03-02 15:02 UTC, gogo2464 commented
> So i have tested this extensively on windows and you cannot disable ASLR programmatically, only enable it.

does `-R aslr=no` works now?

2024-03-02 15:08 UTC, arrowd commented
Is `rz_sys_aslr()` intended to change a global system-wide ASLR setting?

2024-03-02 15:14 UTC, gogo2464 commented
> Is `rz_sys_aslr()` intended to change a global system-wide ASLR setting?

only for the current process, check: https://github.com/rizinorg/rizin/blob/d86e8aebade8bdc232d09d1699ad5969e794f9c1/librz/util/sys.c#L762

2024-03-02 15:54 UTC, wargio commented
> > So i have tested this extensively on windows and you cannot disable ASLR programmatically, only enable it.
> 
> does `-R aslr=no` works now?

on windows no.

2024-03-02 15:56 UTC, wargio commented
> Is `rz_sys_aslr()` intended to change a global system-wide ASLR setting?

it is supposed to be used for spawning processes with aslr or not.
that function will change in the future and will be only used in the debugger.

2024-03-03 12:13 UTC, arrowd commented
Then the FreeBSD case is wrong. Changing sysctl is global and affects all processes that are started after the switch.

On FreeBSD it is possible to do `elfctl -e +noaslr file` to force an executable file to be started without ASLR. Pretty much, just like the Windows case.

2024-03-03 12:18 UTC, gogo2464 commented
> > > So i have tested this extensively on windows and you cannot disable ASLR programmatically, only enable it.
> > 
> > 
> > does `-R aslr=no` works now?
> 
> on windows no and never will.
> 
> ```c
> 		RZ_LOG_ERROR("On Windows, ASLR mitigation policies cannot be made less restrictive if they are already enabled.\n");
> 		RZ_LOG_ERROR("It is possible to disable ASLR by modifying the PE header and removing the following flags:\n");
> 		RZ_LOG_ERROR("- IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE\n");
> 		RZ_LOG_ERROR("- IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA.\n");
> 		RZ_LOG_ERROR("Or as Administrator from PowerShell by running: `Set-ProcessMitigation -Name file.exe -Disable ForceRelocateImages`\n");
> ```

might we consider patching the PEB for disabling aslr?

2024-03-03 12:26 UTC, arrowd commented
> might we consider patching the PEB for disabling aslr?

I'd say it makes sense, because it follows all other plaforms except Linux and MacOS for which it is possible to set ASLR state on the program startup.

2024-03-03 12:33 UTC, devnexen commented
> Then the FreeBSD case is wrong. Changing sysctl is global and affects all processes that are started after the switch.
> 
> On FreeBSD it is possible to do `elfctl -e +noaslr file` to force an executable file to be started without ASLR. Pretty much, just like the Windows case.

or you can use [the procctl api with PROC_ASLR_CTL](https://man.freebsd.org/cgi/man.cgi?procctl(2)).