Dwarf refactor
rizinorg/rizin pull request #4313
Opened 2024-03-01 19:16 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2024-03-02 10:52 UTC, XVilka commented
```
../librz/bin/dwarf/attr.c(44): error C2440: 'type cast': cannot convert from 'ut128' to 'ut128'
```

2024-03-02 10:54 UTC, XVilka requested changes
Please add a high-level description of what changes were done for DWARF refactoring and why it will improve performance.

2024-03-02 12:40 UTC, imbillow commented
> Please add a high-level description of what changes were done for DWARF refactoring and why it will improve performance.

In theory it should increase performance because of some optimizations to EndianReader.

- All `read_xxx` functions are now inline.
- The `read_cstring` and `read_block` functions no longer need to allocate memory, and it gives a reference to `EndianReader->data`.

2024-03-08 08:30 UTC, b1llow commented on test/db/cmd/dwarf
> +|           0x0000813c      push  {r4, lr}                             ; test.c:27
In addition to performance improvements, this PR also improves DWARF Print and fixes some source line behavior.

2024-03-08 12:27 UTC, XVilka requested changes
Looks good with a couple of nitpicks. Please fix them and we can merge

2024-03-08 12:27 UTC, XVilka commented on librz/bin/dwarf/abbrev.c
> +	rz_return_val_if_fail(abbrevs && sb, NULL);
false. Also this function could probably be just `void`

2024-03-08 12:27 UTC, XVilka commented on librz/bin/dwarf/endian_reader.c
> +RZ_IPI RzBinEndianReader *rz_bin_dwarf_section_reader(RzBinFile *binfile, RzBinSection *section) {
Please add ownership mark

2024-03-08 12:27 UTC, XVilka commented on librz/bin/dwarf/loclists.c
> +RZ_API RZ_OWN RzBinDwarfLocation *rz_bin_dwarf_location_clone(RZ_BORROW RZ_NONNULL Location *self) {
This is the API function, I wonder if it's better to keep the `Location` type name the old way, since it's not a generic concept, if I am not wrong.

2024-03-08 12:28 UTC, XVilka commented
You might want also to group your commits, e.g. ULEB128 fix, DWARF fixes, etc

2024-03-09 01:36 UTC, XVilka approved these changes

2024-03-09 01:41 UTC, merged