[WIP] Rewriting RzNum parser and calculator
rizinorg/rizin pull request #4326
Opened 2024-03-04 11:59 UTC by XVilka

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- Port RzNum grammar to the Tree-Sitter
- Rewrite RzNum to use the new parser
- Keep old function `rz_num_math()` behavior under the new name `rz_num_math_ut64()`, which will likely be deprecated in the future
- Introduce new data type/structure - `RzNumValue` to store any kind of value, not only `ut64` - integers, floats, bitvectors, etc.

**Test plan**

CI is green

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/3754
Closes https://github.com/rizinorg/rizin/issues/3455
Partially addresses https://github.com/rizinorg/rizin/issues/3035
Partially addresses https://github.com/rizinorg/rizin/issues/3331

2026-06-23 22:21 UTC, b1llow commented
I have a few questions:
- We have `RZ_NUM_KIND_BIG`, which supports integers of arbitrary precision, but the precision of decimal seems to be limited to `Float64`. Wouldn’t it be more intuitive to provide decimal with arbitrary precision?
- Why does `rz_num_il_lift()` return a string of type `RzIL` rather than a value of type `RzILOpPure` or `RzILOpEffect`?

2026-06-24 03:07 UTC, notxvilka commented
> I have a few questions:
> 
>     * We have `RZ_NUM_KIND_BIG`, which supports integers of arbitrary precision, but the precision of decimal seems to be limited to `Float64`. Wouldn’t it be more intuitive to provide decimal with arbitrary precision?
> 
>     * Why does `rz_num_il_lift()` return a string of type `RzIL` rather than a value of type `RzILOpPure` or `RzILOpEffect`?

Noted and will implement your suggestions.

2026-06-27 13:31 UTC, Rot127 requested changes
I just checked the docs for now. I might have overlooked something because Github likes to randomly jump to different locations on the webpage.

I started with `math-il-lift.md`. So if you think one of the comments there doesn't make sense because it is documented in `math.md`, then simply add a link there to `math.md` as reference.

Besides that I am very nitpicky about the docs (and will stay so).
Nothing is more frustrating for users than too complicated docs. They should be crystal clear, no matter the skill level of the user.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +| `<<` `>>`            | `shiftl` `shiftr`      | `≪ … ⊥` | `<< … ⊥` |
shiftr missing in symbol column

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +| `<=` (unsigned)      | `ule`                  | `≦` | `<=` |
signed unsigned versions?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +RzIL pure-op glyph in the Unicode exporter, so they are grounded;
First time I read grounded in that context. Wouldn't "resolved" mean the same, but is more commonly used.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +resulting RzIL would still need width reconciliation when
```suggestion
resulting RzIL would still need width casting when
```

That is meant, right?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +    1u32 << 4u32                => (0x1₃₂ ≪ 0x4₃₂ ⊥)
```suggestion
    1u32 << 4u32                => (0x1₃₂ ≪ 0x4₃₂ ⊥)
    1u222 << 4u222                => (0x1₂₂₂ ≪ 0x4₂₂₂ ⊥)
```

Just to show we are not limited by 64 bits

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +    1u32 << 4u32                => (0x1₃₂ ≪ 0x4₃₂ ⊥)
Alternatively add one small section about that.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
Would be awesome if that could be added to the rz-ax man pages.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +
This section reads overly complicated for what it says (I think how overflows are handled?).

For example:
- "`double`-precision path": What "path"? Is that an implementation detail the user doesn't know?
- "small-power case is exact but the large-power" what is small or large power? When it would overflow to 0 it is a large power? Also, later it is called big-power.
- `combining `**` with structure will embed a truncated ut64:` what does "structure" mean here.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +default); RzNum has no syntax for choosing one.
Please add a note in the issue, so we fix it also for RzNum.
Add the link to the issue also here.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +an implicit cast the user did not write:
Casts were not described yet.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +evaluator's "non-zero float is true" semantic in the lifted form:
That is confusing.
So by default it wraps the float in the condition into `is_fzero`. Then it switches branches. Fair enough.

But then:
"`is_fzero(f)` is TRUE when
the original condition was FALSE ..." - But what is the original condition? Isn't `is_fzero(f)` the condition? Does it swap branches depending how `is_fzero(f)` evaluates?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +`8` branch, matching the evaluator. The earlier-documented
```suggestion
`8` branch. The earlier-documented
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +divergence on float-conditioned ternaries is gone.
`The earlier-documented ...` seems irrelevant?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +    0.5 ? 1.5 : 2.5             => (0x3fe0000000000000.f₆₄ ≡ 0 ↠ 0x4004000000000000.f₆₄ 0x3ff8000000000000.f₆₄)
In what other float form should they generate?

Is the example off and it should be a 64 and 32bit float?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +supplied (e.g. `RzCore`'s flag / register lookup); without a callback
The thing about the callbacks need their own section.
Questions I would have.

- What is this callback mechanic about? Does every expression has one? How do I know what the current callback is and what it does? Can I change the callbacks of the expressions?
- Do users actually need to know about the callbacks? Sounds like an implementation detail.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +*and then* the surrounding operators lift structurally around it:
```suggestion
*and then* the surrounding operators lift around it:
```

Or does "structurally" has a special meaning here?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +the requested endianness), but the bare-lift fallback returns the
```suggestion
the requested endianness), otherwise it returns the
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +`RzNumFuncRegistry`. With a registry that defines `double(n) -> 2n`:
Add a link to docs how functions can be added by the user.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +supplied (e.g. `RzCore`'s flag / register lookup); without a callback
Also, add an example which uses a register and some flag to calculate something.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +`rz_il_lift_num()` (and the core wrapper `rz_core_il_lift()`) lift an
You use "grounded" and "structural" a lot below.
But to my knowledge they are not common terms in arithmetic and at least to me not obvious.
If I am not mistaken, please define them here.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +    5 + 3u8                     => (0x5₆₄ + 0x3₈)
Casting is not handled at all if I haven't overlooked it. But is crucial. 

What happens in these cases?
Does the calculation fail? (below in an unrelated context it says it won't cast implicit).

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +============================
Add a link to the main documentation.

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +`sdiv`, `smod`, `sar`) cannot be assigned.
That list differs with the reserved words above.
Better make one table with reserved words and reference it.

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +
```suggestion
share the store. The `%` shell command uses such a store, so a variable bound in one `%` invocation is visible to the
next:

```

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
Overall the sentences here read overly complicated. Relatively long sentences where short once would be easier to read.
Also a pretty excessive use of ';'.
At times reading sections is pretty confusing tbh. Hence the many comments.

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +    a = 3; b = a * a; a + b  -> 12
```suggestion
    a = 3; b = a * a; a + b;  -> 12
```

So there is an example for that case.

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +    Exponent:        x ** y    (right-assoc)
```suggestion
    Exponent:        x ** y    (right-associative)
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +  arbitrary-precision big number.
So rotation on an `u32` is like a zero extended `u64`?
And rotation on a `u128` is like a down cast to `u64`?

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +  repeated multiplication.
So they also return a double?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +Typed-address dereferences
That section is confusing because if overly complicated language. See comment below.

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +active IO layer when evaluated through `rz_core_math`; under the
```suggestion
`addr:le32` / `:be64` / `:s32` / `:f32` read from the IO layer at address `addr`.
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +suffix to one value:
So if there is no IO map at `addr` it just returns the value of `addr` itself?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +
Those examples don't make sense without context. Is there data at 0x1000 or not?

2026-06-27 13:31 UTC, Rot127 commented on doc/math-il-lift.md
> +IO callback is wired (`rz_core_math` stitches two 64-bit reads in
`when an IO callback is wired`

This means simply there is data at the given address. Right?


> `rz_core_math` stitches two 64-bit reads in

So it can't read actual 128 bit float values?
`rz_core_math` seems irrelevant for the user.

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +address is returned unchanged (parity across every width).
```suggestion
When evaluated through the bare `rz_num_math_value()` API without
IO layer, the suffix is parsed but the literal
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +address is returned unchanged (parity across every width).
Add example.

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +limited to eight bytes:
```suggestion
count is recoverable with `len`:
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +zero-width edge case and evaluates to a `ut64` `0`.
What is with UTF-8 strings?

Also add an example for that string + numerical

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +| `Σ(x)`                         | 1     | alias for `popcount` (Greek sigma)     |
Cool :D

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +        // сумма(1,2,3,4,5,6,7,8,9,10)   ->  55   (well past 8 args)
```suggestion
        // сумма(1,2,3,4,5,6,7,8,9,10)   ->  55
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +same way `plf` shows the ASCII layout that `pLf` renders in Unicode.
Too complicated, make sentences shorter.

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +subscript width. Keeping the two renderers visually consistent means
```suggestion
RzIL emits (see `il_export_string_unicode.c`). Keeping the two renderers visually consistent means
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +subscript width. Keeping the two renderers visually consistent means
```suggestion
RzIL emits (see `il_export_string_unicode.c`): a hex constant with a
subscript width. Keeping the output visually consistent means
```

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +  * **Lifting an RzNum expression to RzIL.** `rz_num_il_lift()` (and
This can be deleted. Add a reference to the `math-il-lift.md` diretly

2026-06-27 13:31 UTC, Rot127 commented on doc/math.md
> +| `RZ_NUM_ERR_RESERVED_WORD`          | bare `mod` / `log` / `le` / `be`           |
Refer to "reserved word table"

2026-06-30 19:25 UTC, Rot127 requested changes
Came until `core.c`

2026-06-30 19:25 UTC, Rot127 commented on doc/math-il-lift.md
> +
Thanks. That is a good intro.

2026-06-30 19:25 UTC, Rot127 commented on binrz/man/rz-ax.1
> +(whitespace separates independent values), or type one per line on stdin:
Is the "no spaces" a hard requirement for the grammar?
Also, what are independent values? I think it is not documented what those are.

Tbh, I was actually looking forward for `rz-ax` to finally accept them.
I always found it confusing that spaces were not ignored.
Couldn't they just be stripped from the string?
And if a sequence of values should be evaluated they use something alternative to `;`, wdyt?

If that is out of question, the "no spaces" rule should be printed in `rz-ax` I think.

2026-06-30 19:25 UTC, Rot127 commented on binrz/man/rz-ax.1
> +(whitespace separates independent values), or type one per line on stdin:
I know that is nit[icky btw. But `rz-ax` is one of the most useful tools in daily life. Way more intuitive and accessible than `bc` or the default GUI calculator.

2026-06-30 19:25 UTC, Rot127 commented on doc/math-il-lift.md
> +Operator glyphs at a glance
Please add a similar table or short reference with all supported operations to the `rz-ax -h` output (the normal output I think is best, not tugged away behind another flag).

I missed such a reference very often, because some of the supported operations are not obvious (e.g "How do I square a number? `x**2` or `x^2`, "Does this support arithmetic shift?" etc.)

2026-06-30 19:25 UTC, Rot127 commented on librz/arch/isa/arm/armass64.c
> +	return v;
Use stack allocated buffer

2026-06-30 19:25 UTC, Rot127 commented on librz/cons/grep.c
> +// not reach it as "1[1]" (either of which would wrongly evaluate to 0).
```suggestion
// stopping at any delimiter in `delims`.
//
// Some context of that function:
// The ']' (range close), ',' (next
// token) or '-' (range separator) that ends a token index, or the '[' that
// begins a column selector after a line number. The strict number parser
// rejects that trailing syntax, where the legacy reader stopped at it, so
// "[1]" must not reach rz_num_get as "1]" and a line number in ":1[1]" must
// not reach it as "1[1]" (either of which would wrongly evaluate to 0).
```

The last part in the comment doesn't describe anymore what the function does, but what bug it solves.

2026-06-30 19:25 UTC, Rot127 commented on librz/core/cmd/cmd_math.c
> +			}
Please move this and the json block to a static function.
That one is already too long

2026-06-30 19:25 UTC, Rot127 commented on librz/core/cmath.c
> +		return NULL;
Warn in case of too much memory read.

2026-06-30 19:25 UTC, Rot127 commented on librz/core/cmath.c
> +	return buf;
Warn if number of bytes is != requested number of bytes?

2026-06-30 19:25 UTC, Rot127 commented on librz/core/cmath.c
> +		}
Tha is already or should be implemented in `rz_util` (rz_mem or rz_bits likely)

2026-06-30 19:25 UTC, Rot127 commented on librz/core/cmath.c
> + * \param options   Optional options (timeout). NULL selects defaults.
```suggestion
 * \param options   Optional options. NULL selects defaults.
```

2026-06-30 19:25 UTC, Rot127 commented on librz/core/cmath.c
> +RZ_API bool rz_core_math(RZ_NONNULL RzCore *core, RZ_NONNULL const char *expr,
Maybe too late, but it would be nice if it could return a proper enum with error codes (parsing failure, memory read too large etc). Your call.

2026-06-30 19:25 UTC, Rot127 commented on librz/core/cmath.c
> + * \return The ut64 projection of the result, or 0 on error.
That would make `expr = "1-1"` an error, wouldn't it?

I assume that is a legacy API?
So please mark it as deprecated and we should possibly print a warning if the error case is hit. So at least it doesn't fail silently.

2026-07-01 14:16 UTC, notxvilka commented on binrz/man/rz-ax.1
> +(whitespace separates independent values), or type one per line on stdin:
Now it supports spaces. It wasn't about the grammar, but about how `rz-ax` handles arguments. Now it supports both ways.

2026-07-01 14:19 UTC, notxvilka commented on librz/core/cmath.c
> +RZ_API bool rz_core_math(RZ_NONNULL RzCore *core, RZ_NONNULL const char *expr,
Typed `RzNumError` is already left on `out_value->err` (PARSE, DIV_ZERO, OVERFLOW,
UNCOMPUTABLE, etc).

2026-07-04 10:18 UTC, Rot127 requested changes
Got until rz_big.h

My manual testing gave some weird behavior:

```bash
> rz-ax "1-3u3"
rz-ax: syntax error at line 1 column 5
> rz-ax "1 -   3u3"
0x1
rz-ax: empty expression
rz-ax: empty expression
rz-ax: empty expression
rz-ax: syntax error at line 1 column 3
```

Either fail clearly or give a result. But not mixed.

There are also some uncovered lines of logical important code.

2026-07-04 10:18 UTC, Rot127 commented on librz/arch/isa/arm/armass64.c
> +	char buf[32];
```suggestion
	char buf[128];
```

There are asm strings longer than 32 bytes.

2026-07-04 10:18 UTC, Rot127 commented on librz/cons/grep.c
> +	char t[32];
Is 32 suitable here?
Contrary to the AArch64 asm text case, can we make an assumption here what the maximum string length is?

2026-07-04 10:18 UTC, Rot127 commented on librz/core/cmd/cmd_math.c
> +		if (sb) {
Invert and return early.

2026-07-04 10:18 UTC, Rot127 commented on librz/core/cmath.c
> +// caller still owns `digest`.
```suggestion
// exceeds 8 bytes, otherwise a plain ut64.
```
That is obvious. The pointer is const

2026-07-04 10:18 UTC, Rot127 commented on librz/core/cmath.c
> + * \return The ut64 projection of the result, or 0 on error.
I can't go down the path currently, but does it set an error flag somewhere or not? If yes, please document it. If no, we still need to figure out what to do about it.

2026-07-04 10:18 UTC, Rot127 commented on librz/core/cprint.c
> +			size_t oxn = strcspn(ox, " \t\x1b");
Not sure about the context, but shouldn't it be able to also parse: `0x111,0x222`? A regex might be simpler because it doesn't require the assumption of how the number is post-fixed.

2026-07-04 10:18 UTC, Rot127 commented on librz/core/disasm.c
> +			*nptr = saved;
Same here, but now it tests for `IS_SEPARATOR`.

It seems a common case, so please add a function which extracts the number strings with a regex.

2026-07-04 10:18 UTC, Rot127 commented on librz/il/il_num.c
> +	memcpy(&bits, &d, sizeof(bits));
That should be in rz_util somewhere. But I think there is already one.

2026-07-04 10:18 UTC, Rot127 commented on librz/il/il_num.c
> +		return NULL;
rz_warn_if_reached()

2026-07-04 10:18 UTC, Rot127 commented on librz/il/il_num.c
> + *                  sub-expression must be grounded. May be NULL.
```suggestion
 *                  sub-expression must be grounded.
```

2026-07-04 10:18 UTC, Rot127 commented on librz/il/il_num.c
> + * \param expr      The expression to lift. Must be non-NULL.
```suggestion
 * \param expr      The expression to lift.
```

2026-07-04 10:18 UTC, Rot127 commented on librz/il/il_num.c
> + * \param expr      The expression to lift. Must be non-NULL.
Also below

2026-07-04 10:18 UTC, Rot127 commented on librz/il/il_num.c
> +		*error_msg = rz_str_dup("out of memory");
If it is out of memory but allocates a string that is weird.
Better warn or just remove the check here.

2026-07-04 10:18 UTC, Rot127 commented on librz/include/rz_il/rz_il_opcodes.h
> +struct rz_num_expression_t;
Please help me out with this. Why not just include `rz_num_expression.h`?

2026-07-04 10:18 UTC, Rot127 commented on librz/include/rz_util/rz_big.h
> +	st32 scale; ///< number of base-10 fractional digits, always >= 0
If it is always >=0, why is it signed?

2026-07-09 15:32 UTC, wargio reviewed
I'm ok with the PR, but i would remove the wall of text that has been added by the AI.

2026-07-09 18:08 UTC, notxvilka commented
> I'm ok with the PR, but i would remove the wall of text that has been added by the AI.

Which one? There are many :D

2026-07-10 11:18 UTC, Rot127 commented
@notxvilka 

> Which one? There are many :D

Same reasons I noted before. I'd say:
 
- Is it obvious in the code what happens?/If the text just describes what the code does. -> Remove, it's a duplicate.
- Is the text describing what specific problem it solves in a specific context -> Remove, should be clear by context. Also, the function can be used in all of other contexts.
- Docs are about implicitly clear things (ownership of pointers in structs)

Just read over `RzNumValue`. I writes in the struct doxygen that the pointers are owned and it writes `(owned)` in the pointer member doxygen.
But ownership is pretty obvious, because who should own them otherwise. So it makes it just hard to read. And even if it must be marked, we have `RZ_OWN`.

Comments can stay if:
- They explain an edge case not directly obvious by reading the code.
- Sum up _in an easy language_ what a complicated function does (APIs).

If a static function without calls is so complicated it needs a comment, then it is too complex and needs refactoring.

2026-07-10 14:47 UTC, Rot127 requested changes
Reviewed until `rz-ax.c`.

Also tested more manually (latest commit):

Every bit vector with less than 8 bit fails.
```bash
> rz-ax "3u3"
rz-ax: syntax error at line 1 column 3
> rz-ax "3u7"
rz-ax: syntax error at line 1 column 3
> rz-ax "3u8"
hex     0x03
binary  0b00000011
width   8 bits
```

The output doesn't seem consistent. Which will make scripting difficult:

```bash
# Decimal output
> rz-ax "0x3+0b11+3"
9
# But here it is hexadecimal
> rz-ax "(-1+1)"
0x0
```

Bitvectors ignore the `=<base>` command line option
```bash
rz-ax =10 "3u8+1"
hex     0x04
binary  0b00000100
width   8 bits
```

Invalid bases for `=` are silently interpreted as =16

```bash
rz-ax =7 "3**12"
0x81bf1
```

Arbitrary strings are silently accepted:
```bash
rz-ax "nanasd"
0
```

2026-07-10 14:47 UTC, Rot127 commented on librz/core/cmath.c
> + * \return The ut64 projection of the result, or 0 on error.
@notxvilka Ping on this one.

2026-07-10 14:47 UTC, Rot127 commented on librz/core/cmath.c
> + */
```suggestion
 * \param core      Core context.
 * \param expr      Expression to lift.
 * \param error_msg Optional out-pointer for a caller-owned diagnostic.
 * \return The lifted RzILOpPure (caller-owned), or NULL on error.
 */
```

2026-07-10 14:47 UTC, Rot127 commented on librz/core/cmath.c
> + * \param expr Expression to evaluate. Must be non-NULL.
```suggestion
 * \param core Core backing the evaluation.
 * \param expr Expression to evaluate.
```

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_il/rz_il_opcodes.h
> +RZ_API RZ_OWN RzILOpPure *rz_il_op_pure_from_num_expression(RZ_NONNULL const RzNumExpression *expr);
```suggestion
RZ_API RZ_OWN RzILOpPure *rz_il_op_pure_from_num_expression(RZ_NONNULL const RzNumExpression *expr);
```

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> + */
Move the documentation to the members.

Also, there is a lot of redundant information in there.

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> +	default:
warn if NULL

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> +		return 0;
rz_warn_if_reached

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> +		return 0.0;
rz_warn_if_reached

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> +	}
rz_warn_if_reached also for NULL cases

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> +	RZ_NULLABLE HtSP *expr_vars; ///< persistent RzNum expression variables, lazily created
```suggestion
	RZ_NULLABLE HtSP *expr_vars; ///< persistent RzNum expression variables.
```

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> +} RzNumCallbackResult;
This seems almost the same struct like `RzNumValue` (it even says "mirroring RzNumValue's union"). Why the duplicate?

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> +typedef int (*RzNumIOReadCallback)(void *user, ut64 addr, ut8 *buf, int len);
```suggestion
typedef ut64 (*RzNumIOReadCallback)(void *user, ut64 addr, ut8 *buf, size_t len);
```

And error case can be UT64_MAX

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> +	char *name; ///< owned UTF-8 name
```suggestion
	char *name; ///< UTF-8 name
```

is implied

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num.h
> + * annotation matching the RzIL Unicode export).
```suggestion
```

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num_expression.h
> + * concrete value while building and appear as a constant leaf.
These are the docs about an expression. But the struct is `RzNumExpressionKind`

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num_expression.h
> + * \brief A grounded, tree-sitter-free expression tree (lifting boundary).
What is a `tree-sitter-free expression tree`?

2026-07-10 14:47 UTC, Rot127 commented on librz/include/rz_util/rz_num_expression.h
> +	RzBitVector *bv; ///< valid for BV (owned)
```suggestion
	RzBitVector *bv; ///< valid for BV
```

2026-07-10 14:47 UTC, Rot127 commented on librz/main/rz-ax.c
> +		// error category so scripts can pattern-match.
```suggestion
```

2026-07-10 14:47 UTC, Rot127 commented on librz/main/rz-ax.c
> +		eprintf("rz-ax: %s\n", err ? err : "evaluation failed");
Should it use RZ_LOG_ERROR?

2026-07-10 14:47 UTC, Rot127 commented on librz/main/rz-ax.c
> +	// category's text.
What does this mean? Is this about how the legacy things worked? Then remove it, since no longer relevant.

2026-07-13 13:35 UTC, Rot127 commented
@notxvilka Please fix the one test. So we can see how the test coverage is.

```
[2](https://github.com/rizinorg/rizin/actions/runs/29147850040/job/86532349412?pr=4326#step:18:83)
[XX] 00h00m00s139ms db/tools/rz_ax rz-ax stdin input
RZ_COLOR=0 RZ_UTF8=0 RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -qc '!echo 0xff | rz-ax' =
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-255
+0xff
```

2026-07-18 19:47 UTC, Rot127 requested changes
Came until `evaluator.c:555`

-----

- [x] Most important bug is that invalid input is silently accepted!

- [x] Please go over the files and remove all doxygen which documents ownership.
Use the macros instead, but only if actually necessary.
Stuff like `///< ... (borrowed)` is everywhere.
Same for stuff like `<some parameter> ... NULL is accepted`.
Those parameters are almost always marked `RZ_NULLABLE` already
and just duplicate information.
There are also comments in which the LLM explains stuff to itself. Like documenting that a `const char *` is `(copied)`.

- [x] Invalid input is still not fully reported (I think).
Also, if the input is invalid rz-ax returns 0.

```
rz-ax t
rz-ax a
rz-ax: cannot resolve 'a'
rz-ax q
echo $?
0
rz-ax q21
rz-ax: cannot resolve 'q21'
echo $?
0
```

- [x] Expressions with bitvectors in between seem to fail

```
rz-ax "3-1+3u3+1"
rz-ax: syntax error at line 1 column 7
```

- [ ] Some expressions default arbitrarily to base 10, some to base 16:
```
rz-ax "3"
0x3
rz-ax "0x12121212"
303174162
rz-ax "0x3+0b11+3"
0x9
rz-ax "(-1+1)"
0x0
```

- [x] `-N` option doesn't print enough bytes for >64bit numbers, nor does it report an error.
```
rz-ax -N "0xfffffffffffffffffffffffffu128"
\xff\xff\xff\xff\xff\xff\xff\xff
```

- [x] If tenerary numbers are part of an expression, spaces are no longer ignored:
```
rz-ax "0t3 - 1+0xffff+1"
rz-ax: syntax error at line 1 column 3
rz-ax: empty expression
0x10001
```

- [x] The `-p` flag either doesn't work or I don't understand it. Shouldn't this return something like "no bits set"
```
# Should return something
rz-ax -p 0
# Should return something, fails silently (works for decimal, and hexadecimal numbers)
rz-ax -p 0t123123123123123
rz-ax -p 0x123123123123123fffffffffu1024
# Wrong output
rz-ax -p "\-0"
0x0
rz-ax -p "\-1"
0xffffffffffffffff
```

- [x] Swap endianness function returns a decimal number. Should default to hexadecimal?
```
rz-ax -e 0xffaa
2868838400
```

- [x] Something is messed up if `t` gets the prefix of a number:
```
rz-ax t11
102t
```

- [x] Bit vectors with less than 8 bits are not accepted.
```
rz-ax 8u7
rz-ax: syntax error at line 1 column 3
```

2026-07-18 19:47 UTC, Rot127 commented on librz/main/rz-ax.c
> +	bool bare_hex = str[0] == '0' && tolower((ut8)str[1]) == 'x' && str[2];
Please move all this prefix classification into its own function, then return an enum of the result.
The function should be part of RzNum.

2026-07-18 19:47 UTC, Rot127 commented on librz/util/num/evaluator.c
> +	const char *src; ///< source text (borrowed)
```suggestion
	const char *src; ///< source text
```

2026-07-18 19:47 UTC, Rot127 commented on librz/util/num/evaluator.c
> + * \param name   Function name (copied).
```suggestion
 * \param name   Function name.
```

2026-07-18 19:47 UTC, Rot127 commented on librz/util/num/evaluator.c
> +}
too much r2 vibe here, please regex

2026-07-18 19:47 UTC, Rot127 commented on librz/util/num/evaluator.c
> +}
1. Please use RZ_STR_EQ.
2. I beg you, define those numbers in macros.

2026-07-18 19:47 UTC, Rot127 commented on librz/util/num/evaluator.c
> +	return w;
Move this function int `rz_bits.h` and add a unit test.

2026-07-18 19:47 UTC, Rot127 commented on librz/util/num/evaluator.c
> +		if (p[0] == '0' && (p[1] == 'x' || p[1] == 'X')) {
Again, this should call the prefix-checking function requested above.

2026-07-18 19:47 UTC, Rot127 commented on librz/util/num/evaluator.c
> +			v = c - 'A' + 10;
Please reuse one of the other 10 implementations being around somewhere. If against all odds there isn't one, move this to an API function please.

2026-07-19 08:37 UTC, notxvilka commented on librz/main/rz-ax.c
> +		eprintf("rz-ax: %s\n", err ? err : "evaluation failed");
Usually yes, but all of rz-ax.c uses eprintf everywhere, so it's a change for another PR, definitely not here.

2026-07-20 06:30 UTC, wargio reviewed
The help message is kinda unreadable.

```
$ rz-ax -h
Usage: rz-ax [options] [expr ...]
If expr is not provided, reads from stdin.
Expressions use the RzNum language (operators, bit-vectors, big
numbers, functions); see doc/math.md for the full reference. Quote a
multi-term expression so it is one argument (spaces inside are fine);
otherwise each whitespace-separated argument converts independently.
Trailing base suffixes (101b, 35o) are deprecated; prefer 0b/0o/0t.
 int     ->  hex               ;  rz-ax 10
 hex     ->  int               ;  rz-ax 0xa
 -int    ->  hex               ;  rz-ax -77
 -hex    ->  int               ;  rz-ax 0xffffffb3
 int     ->  bin               ;  rz-ax b30
 int     ->  ternary           ;  rz-ax t42
 bin     ->  int               ;  rz-ax 1010d
 ternary ->  int               ;  rz-ax 1010dt
 float   ->  hex               ;  rz-ax 3.33f
 hex     ->  float             ;  rz-ax Fx40551ed8
 oct     ->  hex               ;  rz-ax 35o
 hex     ->  oct               ;  rz-ax Ox12 (O is a letter)
 bin     ->  hex               ;  rz-ax 1100011b
 hex     ->  bin               ;  rz-ax Bx63
 ternary ->  hex               ;  rz-ax 212t
 hex     ->  ternary           ;  rz-ax Tx23
 raw     ->  hex               ;  rz-ax -S < /binfile
 hex     ->  raw               ;  rz-ax -s 414141
 bit-vector arith              ;  rz-ax 5u8+3u8
 auto big number               ;  rz-ax 2**64
 built-in function             ;  rz-ax min(0x10,0x20)
 =base                         ;  rz-ax =10 0x46 -> output in base 10
 -l                            ;  append newline to output (for -E/-D/-r/..
 -a      show ascii table      ;  rz-ax -a
 -b      bin -> str            ;  rz-ax -b 01000101 01110110
 -B      str -> bin            ;  rz-ax -B hello
 -d      force integer         ;  rz-ax -d 3 -> 3 instead of 0x3
 -e      swap endianness       ;  rz-ax -e 0x33
 -D      base64 decode
 -E      base64 encode
 -f      floating point        ;  rz-ax -f 6.3+2.1
 -F      stdin slurp code hex  ;  rz-ax -F < shellcode.[c/py/js]
 -h      show this help        ;  rz-ax -h
 -i      dump as C byte array  ;  rz-ax -i < bytes
 -I      IP address <-> LONG   ;  rz-ax -I 3530468537
 -k      keep base             ;  rz-ax -k 33+3 -> 36
 -L      bin -> hex(bignum)    ;  rz-ax -L 111111111 # 0x1ff
 -n      int value -> hexpairs ;  rz-ax -n 0x1234 # 34120000
 -o      octalstr -> raw       ;  rz-ax -o \162 \172 # rz
 -N      binary number         ;  rz-ax -N 0x1234 # \x34\x12\x00\x00
 -r      rz style output       ;  rz-ax -r 0x1234
 -s      hexstr -> raw         ;  rz-ax -s 43 4a 50
 -S      raw -> hexstr         ;  rz-ax -S < /bin/ls > ls.hex
 -t      Unix tstamp -> str    ;  rz-ax -t 1234567890
 -m      MS-DOS tstamp -> str  ;  rz-ax -m 1234567890
 -W      Win32 tstamp -> str   ;  rz-ax -W 1234567890
 -x      hash string           ;  rz-ax -x linux osx
 -u      units                 ;  rz-ax -u 389289238 # 317.0M
 -w      signed word           ;  rz-ax -w 16 0xffff
 -v      version               ;  rz-ax -v
 -p      position of set bits  ;  rz-ax -p 0xb3

Operators (C precedence, combined into one space-free expression):
  **                power   (2**10);  note ^ is XOR, not power
  * / %             multiply, divide, modulo
  sdiv smod         signed divide / modulo
  + -               add, subtract   (unary - negates)
  << >>             logical shift left / right
  sar               arithmetic (sign-extending) shift right
  <<< >>>           rotate left / right
  & | ^ ~           and, or, xor, not
  < <= > >= == !=   comparisons (yield 0 or 1)
  ?:                ternary   (cond ? a : b)
  0x 0o 0t 0b       hex / octal / ternary / binary literals
  uN                bit-vector width suffix   (5u8, 1u32)
  fn(...)           built-ins: min max gcd sqrt log2 popcount clz ctz ...
```

2026-07-20 15:47 UTC, notxvilka commented
> help message is kinda unreadable.

Better?

```
rz-ax -h
Usage: rz-ax [options] [expression ...]

Converts numbers between bases and evaluates RzNum expressions.
Without an expression, reads one per line from stdin.

Quote an expression that contains spaces so it stays a single
argument; otherwise every argument is converted on its own.
See doc/math.md for the full expression reference.

Conversions
 int     -> hex       ;  rz-ax 10
 hex     -> int       ;  rz-ax 0xa
 -int    -> hex       ;  rz-ax -77
 -hex    -> int       ;  rz-ax 0xffffffb3
 int     -> bin       ;  rz-ax b30
 int     -> ternary   ;  rz-ax t42
 int     -> oct       ;  rz-ax Ox12
 bin     -> int       ;  rz-ax 0b1010
 oct     -> int       ;  rz-ax 0o17
 ternary -> int       ;  rz-ax 0t212
 float   -> hex       ;  rz-ax 3.33f
 hex     -> float     ;  rz-ax Fx40551ed8
 hex     -> bin       ;  rz-ax Bx63
 hex     -> ternary   ;  rz-ax Tx23
 raw     -> hex       ;  rz-ax -S < /binfile
 hex     -> raw       ;  rz-ax -s 414141
 Trailing base suffixes (101b, 35o, 212t) still work but are
 deprecated; prefer the 0b / 0o / 0t prefixes.

Expressions
 arithmetic             ;  rz-ax '3 * (10 + 2)'
 bit-vector width       ;  rz-ax 5u8+3u8
 automatic big number   ;  rz-ax 2**64
 built-in function      ;  rz-ax min(0x10,0x20)
 variable binding       ;  rz-ax 'x=10;x*4'

Options
 =N  print the result in base N   ;  rz-ax =10 0x46
 -a  show the ascii table         ;  rz-ax -a
 -b  bin -> str                   ;  rz-ax -b 01000101 01110110
 -B  str -> bin                   ;  rz-ax -B hello
 -d  print integers in base 10    ;  rz-ax -d 3           # 3, not 0x3
 -D  base64 decode                ;  rz-ax -D cml6aW4=
 -e  swap endianness              ;  rz-ax -e 0x33
 -E  base64 encode                ;  rz-ax -E rizin
 -f  keep the fractional part     ;  rz-ax -f 6.3+2.1
 -F  slurp code from stdin as hex ;  rz-ax -F < shellcode.[c/py/js]
 -h  show this help
 -i  dump as a C byte array       ;  rz-ax -i < bytes
 -I  IP address <-> LONG          ;  rz-ax -I 3530468537
 -k  keep the input base          ;  rz-ax -k 33+3       # 36
 -l  append a newline to output   ;  for -E / -D / -r / ...
 -L  bin -> hex (big number)      ;  rz-ax -L 111111111  # 0x1ff
 -m  MS-DOS timestamp -> str      ;  rz-ax -m 1234567890
 -n  int -> hex pairs             ;  rz-ax -n 0x1234     # 34120000
 -N  int -> escaped raw bytes     ;  rz-ax -N 0x1234     # \x34\x12\x00\x00
 -o  octal str -> raw             ;  rz-ax -o \162 \172   # rz
 -p  positions of the set bits    ;  rz-ax -p 0xb3
 -r  rizin command output         ;  rz-ax -r 0x1234
 -s  hex str -> raw               ;  rz-ax -s 43 4a 50
 -S  raw -> hex str               ;  rz-ax -S < /bin/ls > ls.hex
 -t  Unix timestamp -> str        ;  rz-ax -t 1234567890
 -u  human readable units         ;  rz-ax -u 389289238  # 317.0M
 -v  show the version
 -w  sign-extend a signed word    ;  rz-ax -w 16 0xffff
 -W  Win32 timestamp -> str       ;  rz-ax -W 1234567890
 -x  djb2 hash of a string        ;  rz-ax -x linux osx

Operators (C precedence)
  **                power     (2**10; note ^ is XOR, not power)
  * / %             multiply, divide, modulo
  sdiv smod         signed divide, signed modulo
  + -               add, subtract (unary - negates)
  << >>             logical shift left, right
  sar               arithmetic (sign-extending) shift right
  <<< >>>           rotate left, right
  & | ^ ~           and, or, xor, not
  < <= > >= == !=   comparisons, yielding 0 or 1
  ?:                ternary   (cond ? a : b)

Literals
  0x 0o 0t 0b       hex, octal, ternary, binary
  uN                bit-vector of N bits   (5u8, 1u32, 3u1024)
  KiB MiB GiB ...   size units             (4KiB)
  fn(...)           built-ins: min max gcd sqrt log2 popcount clz ctz ...
  ```

2026-07-20 16:38 UTC, Rot127 commented
> Better?

@notxvilka I think it would be nice to have a short `-h` help message and a long one `-H` for example.
The long one can contain all the details about conversions, supported operations etc. (how it currently looks like).
The short one only the flags.

2026-07-21 20:18 UTC, notxvilka commented
I extracted long desription to the `rz-ax -H` as suggested, also expanded `rz-ax` man page to reference the installed version rather than digging source-level `doc/math.md`.

2026-07-22 03:39 UTC, notxvilka commented
Redness is unrelated - it's same debug test I mentioned in Rizin Dev Mattermost channel.

2026-07-22 16:58 UTC, Rot127 requested changes
Should be ok afterwards.

This point ` Some expressions default arbitrarily to base 10, some to base 16:` from above is still missing

2026-07-22 16:58 UTC, Rot127 commented on librz/util/num/evaluator.c
> +	if (nc > 1) {
Invert return early

2026-07-22 16:58 UTC, Rot127 commented on librz/util/num/evaluator.c
> +	if (!ok) {
Invert and return early.

2026-07-22 16:58 UTC, Rot127 commented on librz/util/num/evaluator.c
> +}
Move such a function to rz_bits.h It probably already exists.

2026-07-23 16:41 UTC, notxvilka commented
> Should be ok afterwards.
> 
> This point ` Some expressions default arbitrarily to base 10, some to base 16:` from above is still missing

There is no way to cleanly fix it. It tries to preserve/mimic the old behavior to avoid too much breakage and could be fixed only incrementally as more and more places move to the new API.

2026-07-23 18:57 UTC, merged