Add new release procedure for Rizin with manual tagging and release creation.
rizinorg/rizin pull request #4337
Opened 2024-03-06 05:29 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Github releases doesn't seem to work reliably. So this adds the manual release process.

Still missing:

- [ ] Add a script to download the packages and source code to attach to the release.
- [ ] Add script to checklist.

**Test plan**

...

**Closing issues**

...

2024-03-06 08:31 UTC, ret2libc commented
What's the issue with GitHub releases?

2024-03-06 10:53 UTC, XVilka requested changes

2024-03-06 10:53 UTC, XVilka commented on doc/release-template.md
> +- [ ] Make public release
This should be removed or changed, since the CI makes the draft release and uploads artifacts automatically upon push to `stable`.

2024-03-06 11:06 UTC, Rot127 commented
@ret2libc It now assigned twice in a row the tag to the `dev` branch. And not to the `stable`.
Also the signing doesn't work reliably. So we can just as well sign it on our own.

2024-03-06 12:49 UTC, ret2libc commented
> @ret2libc It now assigned twice in a row the tag to the `dev` branch. And not to the `stable`. Also the signing doesn't work reliably. So we can just as well sign it on our own.

Where exactly? In the CI? Maybe we should use `target_commitish` in the `softprops/action-gh-release@v1` action. With regards to signing, there is https://sigstore.dev/ which allows automatic signatures from GH CI without any manual operation and without us having to deal with GPG keys, rotating them, updating them, etc.

2024-03-06 15:13 UTC, XVilka commented
> > @ret2libc It now assigned twice in a row the tag to the `dev` branch. And not to the `stable`. Also the signing doesn't work reliably. So we can just as well sign it on our own.
> 
> Where exactly? In the CI? Maybe we should use `target_commitish` in the `softprops/action-gh-release@v1` action. With regards to signing, there is https://sigstore.dev/ which allows automatic signatures from GH CI without any manual operation and without us having to deal with GPG keys, rotating them, updating them, etc.

Not CI - tag was created on `dev` if we create it via GitHub interface from the Draft Release.

2024-03-06 15:15 UTC, XVilka commented
Please remove instructions about signing, since we need first to decide on how exactly we do that. GitHub "standard" verification isn't enough, especially since they changed ZIP archives once. This is tracked in https://github.com/rizinorg/rizin/issues/3786

2024-03-06 15:18 UTC, ret2libc commented
> > > @ret2libc It now assigned twice in a row the tag to the `dev` branch. And not to the `stable`. Also the signing doesn't work reliably. So we can just as well sign it on our own.
> > 
> > 
> > Where exactly? In the CI? Maybe we should use `target_commitish` in the `softprops/action-gh-release@v1` action. With regards to signing, there is https://sigstore.dev/ which allows automatic signatures from GH CI without any manual operation and without us having to deal with GPG keys, rotating them, updating them, etc.
> 
> Not CI - tag was created on `dev` if we create it via GitHub interface from the Draft Release.

Yeah I understand, I'm afraid that it's caused by the wrong commit being referenced in the draft release when we create it in the CI. IIRC I "recently" changed that part of the CI as we had to switch GH action for release, so it might behave slightly different and cause this behaviour.

2024-09-20 05:38 UTC, Rot127 commented
Guess this is obsolete now.

2024-09-20 05:38 UTC, closed without merging