uplifting h8300 instructions to RzIL
rizinorg/rizin pull request #4375
Opened 2024-03-21 21:08 UTC by ashiskumarnaik

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

RzIL upliftment for H8300

...

...

for #2080

...

2024-03-22 03:02 UTC, wargio approved these changes

2024-03-22 03:03 UTC, wargio commented on librz/arch/isa/h8300/h8300_il.c
> +	return cfg;
return directly.

2024-03-22 03:05 UTC, wargio commented on librz/arch/p/analysis/analysis_h8300.c
> +static int archinfo(RzAnalysis *a, RzAnalysisInfoType query) {
rename this to `h8300_archinfo`

2024-03-22 13:40 UTC, XVilka requested changes
1. Requires a test for RzIL, see how it's done, in `test/db/asm/h8300`
2. Windows linking error (you need to update Meson files
```
  Creating library binrz/rz-run/rz-run.lib and object binrz/rz-run/rz-run.exp
rz_arch.lib(p_arch_h8300.c.obj) : error LNK2001: unresolved external symbol rz_h8300_il_config
rz_arch.lib(p_arch_h8300.c.obj) : error LNK2019: unresolved external symbol rz_h8300_il_opcode referenced in function h8300_op
binrz/rz-run/rz-run.exe : fatal error LNK1120: 2 unresolved externals
[1685/1953] Compiling C object binrz/rz-asm/rz-asm.exe.p/rz-asm.c.obj
ninja: build stopped: subcommand failed.
Command exited with code 1
```

2024-03-22 13:41 UTC, XVilka requested changes

2024-03-22 13:41 UTC, XVilka commented on librz/arch/isa/h8300/h8300_il.c
> +// Created by Ashis Kumar Naik on 21/03/24.
Should be SPDX instead

2024-03-22 13:41 UTC, XVilka commented on librz/arch/isa/h8300/h8300_il.h
> +// Created by Ashis Kumar Naik on 21/03/24.
SPDX

2024-03-23 09:00 UTC, ashiskumarnaik commented on librz/arch/isa/h8300/h8300_il.c
> +// Created by Ashis Kumar Naik on 21/03/24.
updated.

2024-03-23 09:00 UTC, ashiskumarnaik commented on librz/arch/isa/h8300/h8300_il.h
> +// Created by Ashis Kumar Naik on 21/03/24.
updated.

2024-03-24 09:55 UTC, Rot127 commented on librz/arch/p/analysis/analysis_h8300.c
> +#include "isa/h8300/h8300_il.h"
```suggestion
#include <h8300/h8300_il.h>
```

2024-03-25 03:08 UTC, wargio commented on librz/arch/meson.build
> +  'isa/h8300/h8300_il.c',
move this under line 159.

2024-03-25 11:21 UTC, XVilka commented
Don't forget to rebase when you do your next change.

2024-04-10 08:10 UTC, XVilka commented
@ashiskumarnaik have you had any chance to fix this PR?

2024-04-10 09:02 UTC, ashiskumarnaik commented
@XVilka Hi , I am still working on it.

2024-04-21 15:39 UTC, XVilka commented
Any updates?

2024-05-25 02:13 UTC, XVilka requested changes
It would require a "h8300" file with RzIL tests in this directoy as well: https://github.com/rizinorg/rizin/tree/dev/test/db/rzil

Including the "emulateme" type of test, where RzIL is used to emulate the part of the binary (see already existing tests in this directory).

For the instruction-level tests you will need to extend the https://github.com/rizinorg/rizin/blob/dev/test/db/asm/h8300 file with RzIL strings (see other files in that directory as an example)

2025-05-05 05:59 UTC, imbillow commented
#5119

2025-05-05 05:59 UTC, closed without merging