Add MSP430 to labeler
rizinorg/rizin pull request #4381
Opened 2024-03-23 06:10 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Adds MSP430 to the labeler.

**Test plan**

...

**Closing issues**

...

2024-03-23 06:12 UTC, wargio approved these changes

2024-03-24 02:24 UTC, XVilka requested changes
In fact, not only MSP430 was missing, but many architectures were missing. It makes sense to add them all at once.

2024-03-24 07:50 UTC, Rot127 commented
Labels are added now.

2024-03-25 10:41 UTC, XVilka requested changes
LGTM with a few small changes

2024-03-25 10:41 UTC, XVilka commented on .github/labeler.yml
> +GB:
Maybe better GameBoy?

2024-03-25 10:41 UTC, XVilka commented on .github/labeler.yml
> +h8300:
H8300

2024-03-25 10:41 UTC, XVilka commented on .github/labeler.yml
> +LUAC:
Just Lua is probably better, also shorter

2024-03-25 10:41 UTC, XVilka commented on .github/labeler.yml
> +v810:
V810

2024-03-25 10:41 UTC, XVilka commented on .github/labeler.yml
> +v850:
V850

2024-03-25 10:41 UTC, XVilka commented on .github/labeler.yml
> +AMDAm29000:
Just Am29k

2024-03-25 11:06 UTC, XVilka approved these changes

2024-03-25 11:07 UTC, merged