RzIL: replace float comparsion macros with functions
rizinorg/rizin pull request #4400
Opened 2024-03-29 20:16 UTC by pelijah

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

FEQ, FNEQ, FLT, FLE, FGT, FGE macros are too bulky. Their use leads to memory leaks.
I guess new functions don't really fit to `il_opcodes.c` but idk where to place them.

2024-03-30 00:51 UTC, XVilka requested changes
There is `librz/il/il_routines.c` precisely for this purpose. Maybe it could also be renamed into `il_helpers.c` to be clearer, the file Doxygen description should be updated too.

2024-03-30 01:18 UTC, XVilka commented
Note that it produces different results now:
```
[XX] db/asm/arm_32 <asm> vceq.f32 d0, d1, d2
-- <asm> vceq.f32 d0, d1, d2 <--- 020e01f2 ---> <IL>
-- IL
--- expected
+++ actual
@@ -1,1 +1,1 @@
-(seq empty (set d0 (<< (cast 64 false (ite (&& (! (|| (is_nan (float 0 (cast 32 false (>> (var d1) (bv 8 0x0) false)) )) (is_nan (float 0 (cast 32 false (>> (var d2) (bv 8 0x0) false)) )))) (! (|| (|| (is_nan (float 0 (cast 32 false (>> (var d1) (bv 8 0x0) false)) )) (is_nan (float 0 (cast 32 false (>> (var d2) (bv 8 0x0) false)) ))) (|| (<. (float 0 (cast 32 false (>> (var d1) (bv 8 0x0) false)) ) (float 0 (cast 32 false (>> (var d2) (bv 8 0x0) false)) )) (<. (float 0 (cast 32 false (>> (var d2) (bv 8 0x0) false)) ) (float 0 (cast 32 false (>> (var d1) (bv 8 0x0) false)) )))))) (~ (bv 32 0x0)) (bv 32 0x0))) (bv 8 0x0) false)) (set d0 (<< (cast 64 false (ite (&& (! (|| (is_nan (float 0 (cast 32 false (>> (var d1) (bv 8 0x20) false)) )) (is_nan (float 0 (cast 32 false (>> (var d2) (bv 8 0x20) false)) )))) (! (|| (|| (is_nan (float 0 (cast 32 false (>> (var d1) (bv 8 0x20) false)) )) (is_nan (float 0 (cast 32 false (>> (var d2) (bv 8 0x20) false)) ))) (|| (<. (float 0 (cast 32 false (>> (var d1) (bv 8 0x20) false)) ) (float 0 (cast 32 false (>> (var d2) (bv 8 0x20) false)) )) (<. (float 0 (cast 32 false (>> (var d2) (bv 8 0x20) false)) ) (float 0 (cast 32 false (>> (var d1) (bv 8 0x20) false)) )))))) (~ (bv 32 0x0)) (bv 32 0x0))) (bv 8 0x20) false)))
+(seq empty (set d0 (<< (cast 64 false (ite (&& (! (|| (is_nan (float 0 (cast 32 false (>> (var d1) (bv 8 0x0) false)) )) (is_nan (float 0 (cast 32 false (>> (var d2) (bv 8 0x0) false)) )))) (! (|| (<. (float 0 (cast 32 false (>> (var d1) (bv 8 0x0) false)) ) (float 0 (cast 32 false (>> (var d2) (bv 8 0x0) false)) )) (<. (float 0 (cast 32 false (>> (var d2) (bv 8 0x0) false)) ) (float 0 (cast 32 false (>> (var d1) (bv 8 0x0) false)) ))))) (~ (bv 32 0x0)) (bv 32 0x0))) (bv 8 0x0) false)) (set d0 (<< (cast 64 false (ite (&& (! (|| (is_nan (float 0 (cast 32 false (>> (var d1) (bv 8 0x20) false)) )) (is_nan (float 0 (cast 32 false (>> (var d2) (bv 8 0x20) false)) )))) (! (|| (<. (float 0 (cast 32 false (>> (var d1) (bv 8 0x20) false)) ) (float 0 (cast 32 false (>> (var d2) (bv 8 0x20) false)) )) (<. (float 0 (cast 32 false (>> (var d2) (bv 8 0x20) false)) ) (float 0 (cast 32 false (>> (var d1) (bv 8 0x20) false)) ))))) (~ (bv 32 0x0)) (bv 32 0x0))) (bv 8 0x20) false)))
```
And few other instructions.

2024-03-30 09:35 UTC, pelijah commented
> Note that it produces different results now:

It is expected since I have simplified expressions.

2024-03-30 14:46 UTC, Rot127 requested changes
Had just time for a shallow look. Please check with `valgrind` before merging.

2024-03-30 14:46 UTC, Rot127 commented on librz/il/il_routines.c
> +RZ_API RZ_OWN RzILOpBool *rz_il_op_new_fneq(RZ_NONNULL RzILOpFloat *x, RZ_NONNULL RzILOpFloat *y) {
```suggestion
RZ_API RZ_OWN RzILOpBool *rz_il_op_new_fneq(RZ_NONNULL RZ_OWN RzILOpFloat *x, RZ_NONNULL RZ_OWN RzILOpFloat *y) {
```

Also for all the others.

2024-03-30 14:46 UTC, Rot127 commented on librz/il/il_routines.c
> +static inline RZ_OWN RzILOpBool *_fl_is_less(RZ_NONNULL RzILOpFloat *x, RZ_NONNULL RzILOpFloat *y) {
```suggestion
static inline RZ_OWN RzILOpBool *_fl_is_less(RZ_NONNULL RZ_BORROW RzILOpFloat *x, RZ_NONNULL RZ_BORROW RzILOpFloat *y) {
```

2024-03-31 07:10 UTC, imbillow approved these changes

2024-03-31 09:12 UTC, pelijah commented
> Please check with `valgrind` before merging.

I use ASAN.

2024-04-01 09:07 UTC, Heersin approved these changes

2024-04-02 01:17 UTC, wargio approved these changes

2024-04-02 01:18 UTC, merged