Add mention of str.search.* variables in the help of iz and izz
rizinorg/rizin pull request #4433
Opened 2024-04-14 03:45 UTC by w0rm29

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Mention of variable `str.search.*` in iz and izz commands

...

**Test plan**

...

**Closing issues**

...

2024-04-14 04:40 UTC, wargio commented on librz/core/cmd_descs/cmd_info.yaml
> +    summary: List strings(str.search.*)
```suggestion
    summary: List strings (see also str.search.*)
```

2024-04-14 04:40 UTC, wargio commented on librz/core/cmd_descs/cmd_info.yaml
> +    summary: List strings(str.search.*)
same below.

2024-04-14 04:46 UTC, w0rm29 commented on librz/core/cmd_descs/cmd_info.yaml
> +    summary: List strings(str.search.*)
done

2024-04-14 06:11 UTC, XVilka requested changes
I recommend putting them into the details of the command instead.

2024-04-14 06:25 UTC, XVilka requested changes
Completely wrong change that wouldn't even compile

2024-04-14 06:29 UTC, w0rm29 commented
> Completely wrong change that wouldn't even compile

where to find the details of the command?

2024-04-14 06:31 UTC, wargio commented
you need to rebuild and commit. you cannot just push the changes on the yaml. be sure to have also pyyaml installed

2024-04-14 06:39 UTC, w0rm29 commented
> you need to rebuild and commit. you cannot just push the changes on the yaml. be sure to have also pyyaml installed

while rebuilding, I need to use the below command to rebuild

`meson setup --wipe`

2024-04-14 06:58 UTC, w0rm29 commented on librz/core/cmd_descs/cmd_info.yaml
> +    summary: List strings(str.search.*)
this is working when i am rebuilding

2024-04-14 06:59 UTC, w0rm29 commented
> I recommend putting them into the details of the command instead.

i am not able to find this, should I add a property detail?

2024-04-14 11:55 UTC, wargio commented
nono. the yaml files are automatically updated by meson if pyYAML is installed.

2024-04-14 11:56 UTC, wargio commented
https://github.com/rizinorg/rizin/blob/dev/librz/core/cmd_descs/meson.build#L37

2024-04-14 15:01 UTC, w0rm29 commented
> https://github.com/rizinorg/rizin/blob/dev/librz/core/cmd_descs/meson.build#L37

okay
so, where to add the `str.search.*` ?
earlier where i added is working
can I go ahead with it @XVilka @wargio ?

2024-04-15 01:21 UTC, wargio commented
I think what he meant is to do something like this: https://github.com/rizinorg/rizin/blob/dev/librz/core/cmd_descs/cmd_write.yaml#L92

2024-04-15 01:47 UTC, wargio commented on librz/core/cmd_descs/cmd_info.yaml
> +    description: see also str.search.*
Be a bit more descriptive: `Lists the strings found in a binary; the behavior can be modified via str.search.*`

2024-04-15 01:48 UTC, wargio commented on librz/core/cmd_descs/cmd_info.yaml
> +    description: see also str.search.*
Same here: `Lists the strings of the whole binary; the behavior can be modified via str.search.*`

2024-04-15 02:01 UTC, wargio commented on librz/core/cmd_descs/cmd_info.yaml
> +    description: Lists the strings of the whole binary; the behavior can be modified via str.search.*
check the comments. this doesn't show the strings of the whole binary

2024-04-15 04:50 UTC, wargio commented
as explained above, please install PyYAML and rebuild, then commit the new changes from the generated files.

2024-04-16 02:58 UTC, wargio approved these changes

2024-04-16 04:25 UTC, w0rm29 commented
why did the check failed
is it because of my change
I did build and it was successful

2024-04-16 06:17 UTC, wargio commented
don't worry about it. looks ready. @XVilka can i merge?

2024-04-16 06:23 UTC, merged