Remove globals and refactor to complete implementation of logging.
rizinorg/rizin pull request #4446
Opened 2024-04-18 13:34 UTC by wargio

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This PR removes almost all the globals from the logging api but also makes them `thread-safe`.
This PR also implements colored logs and more.

2024-04-18 13:59 UTC, XVilka requested changes
Nice finding. Apart from Doxygen - LGTM

2024-04-18 13:59 UTC, XVilka commented on librz/util/log.c
> +static const char *level_tags_colors[] = {
We should make this configurable in the future

2024-04-18 13:59 UTC, XVilka commented on librz/util/log.c
> +RZ_API void rz_log_set_show_sources(bool show_sources) {
Could you please add Doxygen to the API functions that miss it while you are on it?

2024-04-18 14:08 UTC, wargio commented on librz/util/log.c
> +static const char *level_tags_colors[] = {
yes, but for now, let's make it simple.

2024-04-18 14:53 UTC, Rot127 reviewed
While you are at it. Could you add a simple `getter` for the current log level? Plugins can check it, when they print log messages.

Or, even better, add a logging function which takes the message as a string (not with `vargs`). Because `vargs` cannot be used from a few languages.

2024-04-18 14:58 UTC, XVilka approved these changes

2024-04-18 16:03 UTC, Rot127 commented
Actually, if you do spent the time to add the logging API for plugins, it might be a good idea add an additional argument, where plugins can pass their name.
So the log messages can be distinguished from main Rizin.

```
[INFO] [Plugin] ...
```

2024-04-18 16:06 UTC, Rot127 approved these changes

2024-04-18 16:33 UTC, thestr4ng3r commented on librz/core/cconfig.c
> +											       " (0:VERBOSE, 1:DEBUG, 2:INFO, 3:WARN, 4:ERROR, 5:FATAL)");
VERBOSE/DEBUG swapped here?

2024-04-19 02:36 UTC, wargio commented
> Actually, if you do spent the time to add the logging API for plugins, it might be a good idea add an additional argument, where plugins can pass their name. So the log messages can be distinguished from main Rizin.
> 
> ```
> [INFO] [Plugin] ...
> ```

tbh, there is an option which tells you the function, file and line where that occurs.

2024-04-19 02:37 UTC, wargio commented on librz/core/cconfig.c
> +											       " (0:VERBOSE, 1:DEBUG, 2:INFO, 3:WARN, 4:ERROR, 5:FATAL)");
nice catch.

2024-04-19 05:02 UTC, merged