MIPS -- add fp register; support for lwl, beqz and sltiu instructions
rizinorg/rizin pull request #4513
Opened 2024-05-23 10:31 UTC by matteius

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

* In MIPS assembly language, fp stands for "frame pointer." It is a register used for stack frame management, particularly in functions that need to allocate space on the stack for local variables or save the state of other registers.  
* Add support for instructions:
* lwl - load word left, The lwl instruction loads a word (4 bytes) from memory into a register. It loads the left-most (most significant) bytes of the word from memory, starting at a specified address and continuing to the next aligned word boundary.
* beqz - branch if equal zero, The beqz instruction is a pseudo-instruction in MIPS assembly, which branches to a specified address if the value in a given register is zero. It is equivalent to beq $zero, rs, offset.
* sltiu - Set Less Than Immediate Unsigne, The sltiu instruction sets a register to 1 if the value in a source register is less than an immediate value, when both are treated as unsigned integers. Otherwise, it sets the register to 0.

Also two quality of life improvements:
* When the exported lw command (from another program) is missing the offset, we can assume offset of 0 and this lets us read that back in without manually adding a 0 offset in the assembly.
* The purpose of adding the condition || (p[0] == '$' && !strcmp(p + 1, regs[n])) in the getreg function is to handle both formats of register names that are common in assembly language. In MIPS assembly, registers can be referred to either by their name (e.g., v0, s3) or by their name prefixed with a dollar sign (e.g., $v0, $s3).

**Test plan**

I am using this code to insert instructions via cutter, and so I get console errors whenever I encounter something that cannot be assembled.    

**Closing issues**

Maybe closes #4509 assuming the tests get run by default by existing in that directory.

2024-05-23 10:50 UTC, XVilka requested changes
If you want to check both disassembly and assembly, you will need to use `da` in asm tests

2024-05-23 10:53 UTC, wargio commented on test/db/asm/mips32
> +d "nop" 00000000 0x4
please rename this file as `mips_32` because this `_32` will be used to set the bits to `32`

2024-05-23 10:55 UTC, wargio commented on librz/arch/isa/mips/mips_assembler.c
> +						if (strcmp(w0, "beqz") == 0) {
```suggestion
						if (!strcmp(w0, "beqz")) {
```

2024-05-23 11:06 UTC, matteius commented
Thanks for taking a look @wargio and @XVilka -- I didn't quite understand:
> If you want to check both disassembly and assembly, you will need to use da in asm tests

2024-05-23 11:08 UTC, XVilka commented
Lines should start not from `d instruction ` but from `da instruction`, then it will check the both ways - disassembly and assembly.

2024-05-23 11:22 UTC, wargio commented
For clarity, please check also https://github.com/rizinorg/rizin/tree/dev/test#writing-assembly-tests

2024-05-23 11:39 UTC, matteius commented
I will look into the test failures more later on when I have more time, thanks!

2024-05-23 12:06 UTC, wargio commented
looks like an endianness issue.

2024-05-25 08:30 UTC, XVilka requested changes
Many tests fail, mostly disassembly. But @wargio is working on rewriting MIPS support from scratch in capstone (see the auto-sync project https://github.com/rizinorg/rizin/issues/4007, https://github.com/rizinorg/rizin/issues/3684), I wonder if it makes sense trying to fix it in the same PR? Maybe can test only assembly for now?

```
[XX] db/asm/mips_32 <asm> mfhi t0
-- <asm> mfhi t0 <--> 10400000
-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-10400000
+10000001


[A[2K
[XX] db/asm/mips_32 <asm> mflo t0
-- <asm> mflo t0 <--> 12400000
-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-12400000
+12000001


[A[2K
[XX] db/asm/mips_32 <asm> jalr t0, t1
-- <asm> jalr t0, t1 <--> 09f82001
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-jalr t0, t1
+jalr t1

-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-09f82001
+09f8e003


[A[2K
[XX] db/asm/mips_32 <asm> jal 0x123456
-- <asm> jal 0x123456 <--> 5634120c
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-jal 0x123456
+jal 0x48d158

-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-5634120c
+158d040c


[A[2K
[XX] db/asm/mips_32 <asm> j 0x123456
-- <asm> j 0x123456 <--> 56341208
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-j 0x123456
+j 0x48d158

-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-56341208
+158d0408

[XX] db/asm/mips_32                                  26 OK         0 BR       92 XX        0 FX
```

2024-05-25 11:16 UTC, wargio commented
i'm ok for the assembly

2024-05-30 14:07 UTC, XVilka commented
@matteius could you please convert "da" to just "a", so that only assembly is checked, and we will merge if tests pass?Note though, some assembly tests also produce errors, please take a look at these failure as well.

2024-06-02 04:13 UTC, matteius commented
I expect the tests will fail again; I only changed to test just assembly, but I spent a bit of time trying to run the tests locally and couldn't.   I was able to build rizin, and then I did:
```
(base) matteius@matteius-3-0:~/rizin/test$ ../build/binrz/rz-test/rz-test db/esil/mips_32 
...
exec: Permission denied
```

I tried also as sudo, but that gets that exec is not found.

2024-06-02 14:43 UTC, XVilka requested changes
There is probably one small mistake somewhere in the assembler:
```
[XX] db/asm/mips_32 <asm> and t0, t1, t2
-- <asm> and t0, t1, t2 ---> 012b4824
-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-012b4824
+012a4024



[XX] db/asm/mips_32 <asm> xor t0, t1, t2
-- <asm> xor t0, t1, t2 ---> 012b4826
-- assembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-012b4826
+012a4026
```

2024-09-18 06:41 UTC, wargio commented
since i'm updating the mips code, i can also integrate these changes into rizin.

2025-03-28 06:06 UTC, closed without merging