[MSP430] Removed code which deletes indicator characters for certain asm syntaxes
rizinorg/rizin pull request #4522
Opened 2024-05-29 19:28 UTC by moste00

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This should fix [issue #3324](https://github.com/rizinorg/cutter/issues/3324) in Cutter's bug log. 

...

**Test plan**

I have searched in the git history and tracked the introduction of the deleted code to commit hash [c83d5f4664f222f318f8e4ae3910aeb9e5515902](https://github.com/rizinorg/rizin/commit/c83d5f4664f222f318f8e4ae3910aeb9e5515902), I have tried to find any PR or detailed message associated with this hash, explaining why the code was needed, but I found none, the commit was probably added sometimes in the project's pre-history (back when it was radare2). 

As far as I can see, the deleted code has no other effect or purpose except the undesirable effect of deleting indicator characters from the disassembly when the asm syntax isn't AT&T. Any tests breaking due to the removal of this code are wrong tests that should be removed as well.

Run `rz-asm -a msp430 -d 3f401000` on dev and then on this PR's branch. On dev, it produces `mov 0x0010, r15` as output, which is wrong, the correct output should include the character '#' before the constant, as it appears on this PR's branch.

2024-05-29 23:19 UTC, XVilka requested changes
LGTM with a small request

2024-05-29 23:19 UTC, XVilka commented on test/db/asm/msp430
Could you please add an instruction test with the `%` indicator as well?

2024-05-30 17:18 UTC, moste00 commented on test/db/asm/msp430
Hmmm, I don't think there is a `%` indicator in MSP430 assembly. If you Ctrl-F "%" in the disassembler source code (`librz\arch\isa\msp430\msp430_disas.c`), you will find only its usages as a format control character to the printing function, it's never used as an actual output of the disassembler.

2024-05-30 17:21 UTC, moste00 commented on test/db/asm/msp430
The indicators are only "#", "&", "@", and "@Rn+". The disassembler also seems to use the "$" indicator to imply a relative jump, but that usage is actually not-documented elsewhere in MSP430 resources, a relative jump is implied by just a plain address, which implicitly means the (ADDR + PC) addressing mode according the MSP430 manual.

2024-05-30 22:51 UTC, XVilka approved these changes

2024-05-30 22:52 UTC, merged