Fix #39 - Do not initialize registers on initialization
rizinorg/rizin pull request #460
Opened 2021-01-25 21:20 UTC by GustavoLCR

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

* Do not initialize registers on initialization
* Put registers in their own flagspace
* Delete register flags if necessary after aaft

**Closing issues**

Closes #39

2021-01-26 11:02 UTC, thestr4ng3r requested changes
Calling commands from the code is discouraged. Is there enough api to do it without commands? If not, this might be a good opportunity to enhance it.

2021-01-26 12:40 UTC, XVilka commented
I think that would be just `rz_debug_reg_list(core->dbg, RZ_REG_TYPE_GPR, bits, NULL, '-', 0)`.

2021-02-01 17:09 UTC, thestr4ng3r approved these changes

2021-02-02 09:12 UTC, wargio approved these changes

2021-02-02 10:31 UTC, ret2libc approved these changes

2021-02-03 09:23 UTC, merged