Update DEVELOPERS.md
rizinorg/rizin pull request #462
Opened 2021-01-25 22:17 UTC by pelijah

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2021-01-25 22:38 UTC, yossizap approved these changes

2021-01-26 08:36 UTC, kazarmy approved these changes

2021-01-26 08:40 UTC, kazarmy requested changes

2021-01-26 08:40 UTC, kazarmy commented on DEVELOPERS.md
> +	rz_return_val_if_fail(a >= 0, b >= 1, false);
```suggestion
	rz_return_val_if_fail(a >= 0 && b >= 1, false);
```

2021-01-26 08:56 UTC, ret2libc approved these changes

2021-01-26 08:56 UTC, ret2libc commented
Thanks!

2021-01-26 08:56 UTC, merged