Implement iterator for hash tables and sets
rizinorg/rizin pull request #4639
Opened 2024-09-18 09:03 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Adds iterators over (im)mutable values or immutable keys over hash tables and sets.

**Test plan**

Added

**Closing issues**

...

2024-09-18 10:11 UTC, XVilka requested changes
It probably makes sense to mention also iterators in DEVELOPERS.md, even if briefly, so that new contributors are aware of their existence

2024-09-18 10:11 UTC, XVilka commented on librz/util/ht/ht_inc.c
> +	if (state) {
Reverse these conditions

2024-09-18 13:51 UTC, imbillow commented on librz/util/ht/ht_inc.c
> +RZ_API RZ_OWN RzIterator *Ht_(as_iter_mut)(RZ_NONNULL HtName_(Ht) *ht) {
Wouldn't `RzIterator<HtName_(Ht)>` make more sense, since `Iterator` are generic containers in my understanding

2024-09-22 04:52 UTC, XVilka approved these changes
LGTM with a few nitpicks

2024-09-22 04:52 UTC, XVilka commented on librz/util/ht/ht_inc.c
> +RZ_API VALUE_TYPE *Ht_(iter_next_mut)(RzIterator *it) {
Missing return ownership

2024-09-22 04:52 UTC, XVilka commented on librz/util/ht/ht_inc.c
> +RZ_API void Ht_(free_iter_mut_state)(HT_(IterMutState) *state) {
Add `RZ_NULLABLE` to the arguments of the free functions

2024-09-22 04:52 UTC, XVilka commented on librz/util/ht/ht_inc.c
> +	rz_return_val_if_fail(state, NULL);
I am not sure an assert should be on allocation, just a simple return, IMHO. @wargio WDYT?

2024-09-24 05:43 UTC, wargio commented on librz/util/ht/ht_inc.c
> +	free(state);
this is not really needed since free accepts NULL.

2024-09-24 05:44 UTC, wargio commented on librz/util/ht/ht_inc.c
> +	free(state);
same here.

2024-09-24 05:46 UTC, wargio approved these changes
LGTM, those comments are not required.

2024-09-24 13:35 UTC, XVilka approved these changes

2024-09-24 13:36 UTC, merged