Check for jumps to preludes by default.
rizinorg/rizin pull request #4651
Opened 2024-09-26 15:09 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Remove the `tailcall` option and always check for it.
It also adds the possibility to mark instructions as `RZ_ANALYSIS_OP_TAIL`, if they are part of a tail call.

**Test plan**

All green and for Hexagon added one.

**Closing issues**

...

2024-09-26 16:25 UTC, XVilka requested changes
I like the idea but we definitely need at least a couple more tests for different architectures - ARM64 and x86_64, for example.

2024-09-26 16:25 UTC, XVilka commented on test/prj/v12-types-empty.rzdb
> -analysis.jmp.tailcall=0
Don't do that - implement migration and new bump a project version instead.

2024-09-29 11:23 UTC, XVilka approved these changes

2024-09-29 18:19 UTC, wargio approved these changes

2024-09-29 18:19 UTC, merged