Add Xtensa arch support
rizinorg/rizin pull request #4654
Opened 2024-09-28 02:35 UTC by imbillow

aaa 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2024-10-06 15:27 UTC, XVilka commented
Probably makes sense to rebase on top of the https://github.com/rizinorg/rizin/pull/4662 to avoid conflicts and double work. cc @Rot127

2024-10-07 04:51 UTC, Rot127 commented
Yes, though let's wait until the Capstone PRs are merged.

2024-11-05 14:55 UTC, XVilka requested changes
I didn't review the ESIL file since I hope we remove it soon. As long as it doesn't break anything, everything is fine in that file.

2024-11-05 14:55 UTC, XVilka commented on librz/arch/p/analysis/analysis_xtensa_cs.c
> +		//	case RZ_ANALYSIS_ARCHINFO_TEXT_ALIGN:
Either implement or remove?

2024-11-05 14:55 UTC, XVilka commented on librz/arch/p/analysis/analysis_xtensa_cs.c
> +		return true;
Return types do not match

2024-11-05 14:55 UTC, XVilka commented on test/db/analysis/xtensa
> +BROKEN=1
Please don't forget to fix it eventually

2024-11-05 14:55 UTC, XVilka commented on test/db/cmd/cmd_list
> +_dA_I 32         xtensa      LGPL3   Capstone Xtensa disassembly plugin
Add yourself as the author maybe?

2024-11-05 14:55 UTC, XVilka commented on librz/arch/isa/xtensa/xtensa.c
> +	if (!self->insn)
Missing `{}`

2024-11-05 14:55 UTC, XVilka commented on librz/arch/isa/xtensa/xtensa.h
> +#ifndef RIZIN_XTENSA_H
Could use just `RZ_XTENSA_H` maybe?

2024-11-06 08:06 UTC, XVilka requested changes
One minor thing left, apart from that - LGTM:
```
[XX] 271 ms   db/cmd/cmd_list Print the asm/analysis plugins
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -qc La =
-- stdout
--- expected
+++ actual
@@ -62,5 +62,5 @@
 a____ 16 32 64   x86.nz      LGPL3   x86 handmade assembler
 _dA__ 16         xap         PD      XAP4 RISC (CSR)
 _dA__ 32         xcore       BSD     Capstone XCore disassembler (by pancake)
-_dAeI 32         xtensa      LGPL3   Capstone Xtensa disassembly plugin (by billow)
+_dAe_ 32         xtensa      LGPL3   Capstone Xtensa disassembly plugin (by billow)
 adA__ 8          z80         GPL3    Zilog Z80 (by condret)
 ```

2024-11-06 11:23 UTC, XVilka commented
OK, LGTM now, just lets wait first for the Capstone PR to be merged first.

2024-11-06 16:10 UTC, Rot127 requested changes
Looks awesome! Just those few things and it lgtm.

2024-11-06 16:10 UTC, Rot127 commented on librz/arch/p/analysis/analysis_xtensa_cs.c
> +		"=A5	a7\n"
Add the return register as well please. `=R0 a2`?

2024-11-06 16:10 UTC, Rot127 commented on librz/arch/p/analysis/analysis_xtensa_cs.c
> +	}
Are `ReadWrite` values possible? If yes, make it two if cases please.

2024-11-06 16:10 UTC, Rot127 commented on librz/arch/p/analysis/analysis_xtensa_cs.c
> +	}
Ah, below you check for both. So please split it here.

2024-11-07 11:11 UTC, Rot127 approved these changes

2024-11-10 16:38 UTC, merged