Use pre-v5 enum names which are now supported by compatibility macros.
rizinorg/rizin pull request #4690
Opened 2024-10-25 13:13 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Requires https://github.com/capstone-engine/capstone/pull/2525

**Test plan**

...

**Closing issues**

...

2024-10-25 16:07 UTC, XVilka approved these changes

2024-10-25 16:13 UTC, XVilka requested changes
You need to update also the Capstone commit

2024-10-26 08:33 UTC, XVilka commented
@Rot127 there is one more problem with the recent Capstone update - ARM uplifting for couple instructions on big-endian systems:
```
[XX] 153 ms   db/asm/arm_64 <asm> mrs x1, NZCV

-- <asm> mrs x1, NZCV <--- 01423bd5 ---> <IL>

-- IL

--- expected

+++ actual

@@ -1,1 +1,0 @@

-(set x1 (| (ite (var nf) (bv 64 0x80000000) (bv 64 0x0)) (| (ite (var zf) (bv 64 0x40000000) (bv 64 0x0)) (| (ite (var cf) (bv 64 0x20000000) (bv 64 0x0)) (ite (var vf) (bv 64 0x10000000) (bv 64 0x0))))))

-- disasm exit status: 0

-- IL exit status: 1

-- IL stderr

Invalid instruction of lifting not implemented.

[XX] 163 ms   db/asm/arm_64 <asm> msr NZCV, x1

-- <asm> msr NZCV, x1 <--- 01421bd5 ---> <IL>

-- IL

--- expected

+++ actual

@@ -1,1 +1,0 @@

-(seq (set nf (! (is_zero (& (var x1) (bv 64 0x80000000))))) (set zf (! (is_zero (& (var x1) (bv 64 0x40000000))))) (set cf (! (is_zero (& (var x1) (bv 64 0x20000000))))) (set vf (! (is_zero (& (var x1) (bv 64 0x10000000))))))

-- disasm exit status: 0

-- IL exit status: 1

-- IL stderr

Invalid instruction of lifting not implemented.
```
https://app.travis-ci.com/github/rizinorg/rizin/jobs/627495678#L4202

2024-10-26 12:01 UTC, Rot127 commented
Closed in favor of https://github.com/rizinorg/rizin/pull/4691

2024-10-26 12:01 UTC, closed without merging