Port `ae` command to RzShell
rizinorg/rizin pull request #4732
Opened 2024-11-23 18:26 UTC by Rot127

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Port the `ae` command to RzShell

**Test plan**

All green

**Closing issues**

...

2024-11-24 02:25 UTC, XVilka requested changes

2024-11-24 02:25 UTC, XVilka commented on librz/core/cmd_descs/cmd_analysis.yaml
> +        summary: Emulate current block.
"Emulate current block using ESIL VM" or something like that. Until ESIL completely removed we should make distinction clear.

2024-11-24 02:25 UTC, XVilka commented on librz/core/cmd_descs/cmd_analysis.yaml
> +        summary: SDB queries on ESIL.info.
Unnecessary dot?

2024-11-24 02:25 UTC, XVilka commented on librz/core/cmd_descs/cmd_analysis.yaml
> +            summary: Perform sdb query on ESIL.info.
Same

2024-11-24 02:25 UTC, XVilka commented on librz/core/cmd_descs/cmd_analysis.yaml
> +            summary: Resets the ESIL.info sdb instance.
Same.

2024-11-24 02:25 UTC, XVilka commented on librz/core/cmd_descs/cmd_analysis.yaml
> +        summary: Emulate instruction encoded in the given bytes.
Same for all those emulation via ESIL instructions

2024-11-24 02:25 UTC, XVilka commented on librz/core/cmd/cmd_analysis.c
> +	// Don't ask me why this has to be done. I am just the janitor.
Lol

2024-11-24 16:12 UTC, Rot127 commented on librz/core/cmd/cmd_analysis.c
> +	// Don't ask me why this has to be done. I am just the janitor.
It very much feels this way.

2024-11-25 12:24 UTC, XVilka approved these changes

2024-11-26 13:19 UTC, wargio approved these changes

2024-11-26 13:19 UTC, merged