Improved performance of rz_bv_copy_nbits and rz_bv_set_range
rizinorg/rizin pull request #4740
Opened 2024-11-25 09:26 UTC by rajRishi22

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
This pull request optimizes the performance of the rz_bv_set_range function. The original implementation iterated through bits one at a time, leading to inefficiencies for large ranges. The updated implementation:

Processes aligned chunks of bits using system word size for faster operations.
Dynamically adjusts chunk size for different architectures (e.g., 32-bit, 64-bit).
Handles unaligned prefix and suffix bits separately while optimizing the main loop.
Adds robust boundary validation to ensure correctness.
This change reduces iteration overhead and improves performance while maintaining compatibility and correctness.

**Test plan**

1. Verify functionality for small ranges, large ranges, and edge cases (unaligned ranges).
2. Test on various architectures to confirm portability (32-bit, 64-bit).
3. Use unit tests to ensure the results match the original functionality.
4. Check for any regressions with existing test suites.

**Closing issues**
Closes #4716 
...

2024-11-25 13:15 UTC, Rot127 requested changes
Nice start!
I can imagine we can even optimize the unaligned cases. But let's do this later.

I also changed your PR message. Because it closes https://github.com/rizinorg/rizin/issues/4716 only partially (missing unaligned cases).

You can add test cases in `test/unit/test_bitvector.c`.
Once everything is implemented and passes, we can run the Travis CI to test it on big endian machines.

2024-11-25 13:15 UTC, Rot127 commented on librz/util/bitvector.c
> +    rz_return_val_if_fail(src && dst, 0);
Please run `clang-format-16` on those files. The indentation gets fixed this way.

2024-11-25 13:15 UTC, Rot127 commented on librz/util/bitvector.c
> +        ++bits_copied;
No need to increment `bits_copied`. You can simply save the original `nbit` value and return it.
As I see it there is no other return value then `nbit` or `0`.

2024-11-25 13:15 UTC, Rot127 commented on librz/util/bitvector.c
> +#include <limits.h>
```suggestion
#include <rz_types.h>
```

`limits.h` should be included already there.

2024-11-25 13:15 UTC, Rot127 commented on librz/util/bitvector.c
> +    const ut32 chunk_size = sizeof(unsigned long) * CHAR_BIT; // Word size in bits
This is fine for now. But we should eventually change it against `uint_fast8_t, uint_fast16_t, etc.`.
But these need to be added in `rz_base_types.h` as `typedef`.

2024-11-25 13:15 UTC, Rot127 commented on librz/util/bitvector.c
> +    while ((src_start_pos % chunk_size != 0 || dst_start_pos % chunk_size != 0) && nbit > 0) {
You can make `(src_start_pos % chunk_size != 0 || dst_start_pos % chunk_size != 0)` an `if` condition and then loop around `nbit > 0`.
This way you can return early within the `if` body.

2024-11-25 13:15 UTC, Rot127 commented on librz/util/bitvector.c
> +        unsigned long mask = (1UL << chunk_size) - 1;
This is equivalent to `UINT32_MAX` (or whatever type we settle on later).

2024-11-25 13:15 UTC, Rot127 commented on librz/util/bitvector.c
> +    const ut32 chunk_size = sizeof(unsigned long) * CHAR_BIT; // Word size in bits
`sizeof()` is a macro. So you can move this to a constant.

2024-11-25 13:15 UTC, Rot127 commented on librz/util/bitvector.c
> +    const ut32 chunk_size = sizeof(unsigned long) * CHAR_BIT;
Same as above. Please move it to a constant/`#define`.

2024-11-25 13:16 UTC, Rot127 commented on librz/util/bitvector.c
> +    const ut32 chunk_size = sizeof(unsigned long) * CHAR_BIT; // Word size in bits
cc @XVilka @thestr4ng3r Regarding the `fast` types.

2024-11-25 13:20 UTC, XVilka commented on librz/util/bitvector.c
> +    const ut32 chunk_size = sizeof(unsigned long) * CHAR_BIT; // Word size in bits
First we need to make sure all our supported systems have it - at least running on `dist-` branch is required.

2024-11-25 13:22 UTC, Rot127 commented on librz/util/bitvector.c
> +    const ut32 chunk_size = sizeof(unsigned long) * CHAR_BIT; // Word size in bits
It is in the `C99` standard. But for those we could just default to a normal `uint` type.

2024-11-25 17:58 UTC, rajRishi22 commented on librz/util/bitvector.c
> +    const ut32 chunk_size = sizeof(unsigned long) * CHAR_BIT; // Word size in bits
Hi @Rot127  and @XVilka  , first of all thanks a lot for such a detailed review of my code ,as a beginner  it was extremely helpful for me . I have tried to address all problems mentioned in this review.
Do i need to create rz_base_types.h for now , as i could not find that file ?

2024-11-25 18:56 UTC, Rot127 requested changes

2024-11-25 18:56 UTC, Rot127 commented on librz/util/bitvector.c
> +    const ut32 chunk_size = SIZE_OF_UNSIGNED_LONG * CHAR_BIT; // Word size in bits
You can move this whole expression into a `#define`. Macros allow some basic math

```
#define RZ_BV_CHUNK_SIZE (sizeof(unsigned long) * CHAR_BIT)
```

2024-11-25 18:56 UTC, Rot127 commented on librz/util/bitvector.c
> +        // Merge chunks using the optimized approach
Add add the link here.

2024-11-25 18:56 UTC, Rot127 commented on librz/util/bitvector.c
> +        nbit -= chunk_size;
`nbit` underflows here if `nbit < chunk_size`.

2024-11-26 02:11 UTC, wargio commented on librz/util/bitvector.c
> +			break;
```suggestion
		if (nbit < RV_BV_CHUNK_SIZE) {
			break;
		}
		nbit -= RZ_BV_CHUNK_SIZE;
```

2024-11-26 02:14 UTC, wargio commented on librz/util/bitvector.c
> +		unsigned long dst_chunk = rz_bv_get_chunk(dst, dst_start_pos / RZ_BV_CHUNK_SIZE);
maybe i'm missing something, but this function seems not in the code. also please use `ut32` as type.

2024-11-26 02:15 UTC, wargio commented on librz/util/bitvector.c
> +		unsigned long mask = UINT32_MAX;
```suggestion
		ut32 mask = UT32_MAX;
```

2024-11-26 02:16 UTC, wargio commented on librz/util/bitvector.c
> +#define SIZE_OF_UNSIGNED_LONG sizeof(unsigned long)
ut32 not unsigned long

2024-11-26 02:17 UTC, wargio requested changes
missing implementation of `rz_bv_get_chunk`

2024-11-26 08:37 UTC, wargio commented on librz/util/bitvector.c
> +		second_word &= (0xFFFFFFFF >> (32 - bit_offset)); // Clear the lower bits
```suggestion
		first_word &= ~(UT32_MAX >> bit_offset); // Clear the upper bits
		second_word &= (UT32_MAX >> (32 - bit_offset)); // Clear the lower bits
```

2024-11-26 09:19 UTC, wargio requested changes
You are touching something very critical within rizin, so please provide benchmark and C test for correctness and edge cases.

2024-12-12 21:12 UTC, Rot127 commented
Are you still interested in finishing this? If yes, please fix the build and add tests.
Otherwise, I would close it in the next days.

2024-12-13 05:15 UTC, rajRishi22 commented
Sorry , i had my college exams so i was busy , i will start working on this issue again from today.

2025-01-01 13:33 UTC, XVilka commented
This code looks like AI-generated. Closing it.

2025-01-01 13:33 UTC, closed without merging