RzSearch refactor
rizinorg/rizin pull request #4762
Opened 2024-12-10 19:06 UTC by Rot127

## WIP

 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Starting from https://github.com/rizinorg/rizin/pull/4742.

Will rewrite the commit history after it is done.
Also resent to `fuzz-dist` when all the tests pass here.

**Test plan**

...

**Closing issues**

...

2024-12-16 01:33 UTC, wargio commented on librz/core/csearch.c
> +	if (!fopts_set) {
```suggestion
	if (!(rz_search_find_opt_set_inverse_match(fopts, rz_config_get_b(core->config, "search.inverse") &&
		rz_search_find_opt_set_overlap_match(fopts, rz_config_get_b(core->config, "search.overlap") &&
		rz_search_find_opt_set_alignment(fopts, rz_config_get_i(core->config, "search.io.alignment"))) {
```

2024-12-16 01:34 UTC, wargio commented on librz/core/csearch.c
> +		if (!set_sopts) {
same change for the ifs here.

2024-12-16 01:35 UTC, wargio commented on librz/search/bytes_search.c
> + *  - `0xff0f:0xa907`: Mask and bytes with "0x" prefixes.
i forgot to implement these patterns.

2024-12-16 01:43 UTC, wargio commented on librz/search/search.c
> +		return rz_atomic_bool_get(ctx->loop);
return false.

2024-12-16 01:45 UTC, wargio commented on librz/include/rz_search.h
> +} RzSearchWindow;
This is equivalent to `RzInterval`, use that one since it has apis.

2024-12-29 21:04 UTC, Rot127 commented
@XVilka @wargio The `/x` command is done. You can review it. Continue with string search I think.

2024-12-30 02:56 UTC, wargio commented on librz/include/rz_search.h
> +RZ_API RZ_OWN RzSearchBytesPattern *rz_search_bytes_pattern_new(RZ_OWN ut8 *bytes, RZ_OWN ut8 *mask, size_t length, const char *pattern_desc);
NONNULL/NULLABLE

2024-12-30 02:57 UTC, wargio commented on librz/include/rz_search.h
> +} RzSearchBytesPattern;
i'm not 100% sure if i would expose this.

2024-12-30 03:00 UTC, wargio commented on librz/search/search.c
> +			rz_list_append(list, window);
this is the same chunked approach i did for basefind. looks very good.

2024-12-30 05:28 UTC, wargio commented
@Rot127 did you try this while debugging?

2025-01-01 16:27 UTC, Rot127 commented
> @Rot127 did you try this while debugging?

No, but good point. I add a debug test.

2025-01-01 19:06 UTC, Rot127 commented on librz/include/rz_search.h
> +} RzSearchBytesPattern;
Good point. Moved the struct definition to the internal header.
And only expose the typedef.

2025-01-03 11:07 UTC, wargio commented on librz/core/cconfig.c
> +		rz_cons_printf("%d\n", max_threads);
This should return ncores. It's under rz_th.h

2025-01-03 11:07 UTC, wargio commented on librz/core/cmd_descs/cmd_search.yaml
> +  - name: "/c"
I was thinking to change this and have one command which search for all or one specific material

2025-01-21 02:42 UTC, wargio commented on librz/search/string_search.c
> +			RzPVector *matches = rz_regex_match_all(find->regex, detected->string, detected->size, 0, RZ_REGEX_DEFAULT);
you forgot to pass the flags.

2025-01-21 19:17 UTC, Rot127 commented on librz/search/string_search.c
> +			RzPVector *matches = rz_regex_match_all(find->regex, detected->string, detected->size, 0, RZ_REGEX_DEFAULT);
Those are only flags used during compilation. Added docs for this.

2025-01-23 05:12 UTC, wargio commented on librz/util/str.c
> +		} else if (rsize == 0) {
maybe move `option->stop_at_unprintable` check within `if (rsize == 0) {`

2025-01-25 15:53 UTC, notxvilka commented
@Rot127 please rebase to solve conflicts

2025-01-29 16:35 UTC, notxvilka commented on librz/util/str_search.c
> +			} else if (rz_str_ebcdic_valid_cp(ptr[0]) && skip_ibm037 < 0) {
Be careful, since this is hot path, and the potential performance cost could be high with this particular change.

2025-01-29 16:48 UTC, Rot127 commented on librz/util/str_search.c
> +			} else if (rz_str_ebcdic_valid_cp(ptr[0]) && skip_ibm037 < 0) {
It is still ~~`O(n)`~~ `O(1)` because the `EBCDIC` check are table look ups via offset. The whole string type detection should also work well enough, that no "detect fales positive" step should be necessary (which is `O(string_len)`).
That said, I need @imbillow opinion on this anyways after New Year. The previous classification didn't seem to work. Or I didn't get it.

2025-01-30 03:03 UTC, wargio commented on librz/core/cconfig.c
> +		rz_cons_printf("%d\n", max_threads);
`max_threads = rz_th_physical_core_number();`

2025-01-30 03:04 UTC, wargio commented on librz/core/cconfig.c
> +	if (node->value[0] == '?') {
also the check needs to be done before the call.

2025-01-30 15:53 UTC, Rot127 commented
The string search is nearly done. I would propose to merge this PR after all tests are fixed and refactor the rest of the searches in another one.

This one is already huge.
And the other searches will be much less complicated (due to less refactor).

2025-01-30 16:12 UTC, wargio commented on librz/core/cconfig.c
> +		rz_cons_printf("%d\n", max_threads);
This is not resolved.

2025-01-30 16:12 UTC, wargio commented on librz/core/cconfig.c
> +	if (node->value[0] == '?') {
This neither

2025-01-30 17:00 UTC, notxvilka commented
> The string search is nearly done. I would propose to merge this PR after all tests are fixed and refactor the rest of the searches in another one.
> 
> This one is already huge. And the other searches will be much less complicated (due to less refactoring). Except you don't care to review all of it of course.

Yes, makes perfect sense.

2025-01-30 17:06 UTC, Rot127 commented
@imbillow Please pay special attention to:

https://github.com/rizinorg/rizin/pull/4762/commits/c8820283a9771ea2bff817c517a2bca55c40f240

2025-01-30 17:10 UTC, Rot127 commented on librz/core/cconfig.c
> +		rz_cons_printf("%d\n", max_threads);
Sorry, I guess I didn't get it then.
The idea is to set the number of threads. And it prints the maximum number of cores, if the user types `'?'`.

2025-01-31 02:07 UTC, wargio commented
Ok for me

2025-02-01 21:19 UTC, Rot127 commented
**Problems of the previous heuristics**

- UTF-16 and UTF-32 checks only tested for bytes with the upper bytes 0. This effectively excludes all code points > 0xff.
  But those are the ones UTF-16/32 is used in the first place. So the heuristics is off.
- The testing happened mostly sequentially and returned early. If UTF-32 matched before IBM037, it just assumed it is UTF-32, not even performing the IBM037 test. Leaving the string invisible.
- Due to this it is also hard to extend the testing. Because with every new check of a new encoding, the previous checks must somehow fail before. Forbidding the possibility of a byte sequence being valid in two encodings. (And jusdging from the code @imbillow ran into exactly this problem).
- There was no easy way to test for multiple encodings at the same offset, except running the scan again after switching encodings.

**New encoding detection**

The new solution is somewhat less performant (I think, but I didn't profile it yet and I don't think it is much worse).
But, I think it is so much more worth it, because:

- We can actually control how much of a performance hit we want.
  - Check only X bytes of the buffer? Not a big deal to implement.
  - Only check for a subset of encodings? Just some `if` conditions.
- At the same time we get way more flexibility how the detection works (via the biases).
  - If we have a binary with big endian, we can give big endian strings a strong bias.
  - We want to limit the string detection to strings of a certain length, just change the bias.
  - We need the detected strings to align with even addresses, again just change the bias.
  - In general, we can give the user a selection of choises. If they see strings of encoding X make the most sense, she can assume this is the string encoding in the file, set it and no longer get any performance penalty.
  - Most generally, we reduce the number of false negatives to 0 (within the range of the detection parameters and biases).

I think this trade is very good. Because we should always be able to provide all statically knowable information to the user.
What they do with it is their choice, but not ours.

**The algorithm**

It is rather straight forward. The detection function gets a buffer it iterates twice over the buffer (`O(2n)`) and
decodes at each index a code point for each possible encoding and checks it's printability (`O(|Encodings| * log(I)): I is number of invalid code point ranges.`).
If the decoding gives a _printable_ code point, it gets a score of the number of bytes it uses (4 if UTF-32, 2-4 for UTF-16, 1 for IBM037 etc.).
If there is no valid decoding of the bytes, the score is `0.0`.
This is done for every offset.

Now we iterate backwards over the buffer and accumulate the scores, except they have a score of `0.0`.
This means that strings of printable characters have a high score at the beginning of the string (namely the number of consecutive printable characters) and a low score at the end.

Example
Step I (calculate code points at each offset):

```
Index  | 0    | 1    | 2    | 3    | 4    | 5    |
Bytes  | 0xff | 0xff | 0x41 | 0x41 | 0xff | 0xff |
UTF-8  | 2    | 2    | 1    | 1    | 2    | 1    |
UTF-16 | 2    | 2    | 1    | 1    | 2    | 1    |
UTF-32 | 0    | 0    | 0    | 0    | 0    | 0    |
IBM037 | 0    | 0    | 1    | 1    | 0    | 0    |
...
```

Step II (accumulate backwards):

Summing up always takes the current cell score at `i` plus the score of the `i + score` cell.
So for UTF-8 we do:
```
score-5 = 1	
score-4 = 2	
score-3 = 1	+ score-4
score-2 = 1	+ score-3
score-1 = 2	+ score-3
score-0 = 2	+ score-2
```

The resulting table is:

```
Index    | 0    | 1    | 2    | 3    | 4    | 5    |
Bytes    | 0xff | 0xff | 0x41 | 0x41 | 0xff | 0xff |
UTF-8    | 6    | 5    | 4    | 3    | 2    | 1    |
UTF-16be | 6    | 5    | 4    | 3    | 2    | 1    |
UTF-32   | 0    | 0    | 0    | 0    | 0    | 0    |
IBM037   | 0    | 0    | 2    | 1    | 0    | 0    |
...
```

Now we can query this table at different offsets and get the string encoding with the highest score.
In this case it is either UTF-16 or UTF-8 everywhere. But before we query this table, we apply a bias to each score.
Let's say we know the binary is from Windows (and we suspect the strings are encoded in UTF-16).
If we query at offset 0, to get the most likely encoding, we have two possibilities (UTF-8 and UTF-16be).
But because we assume UTF-16 is more likely, we multiply the UTF-16be score with a bias (6 * 1.2) and now the UTF-16 is the most likely one.

We can apply these biases for everything.
E.g. String is too short? => If initial score is < 4.0 (uses less then 4 bytes) we add a multiplier of 0.0 (ignoring it).
But also for alignment for addresses and whatever comes to mind (e.g. code point should be < 0x7f for ASCII only).

In practice we discover a lot more possible string encodings.

The most clearest cases are in `test_str_search.c`. It did not detect a lot of the **valid** encodings.
Because the detection stopped too early. And in the tests there is the implicit assumption made, what encoding is expected (namely code points of the Latin alphabet, ASCII range).
E.g. `0xff` bytes assumed not being a valid part of UTF-16 code points, but they are.
Mostly characters with `ff` in the code point were not discovered in those test cases (e.g. `ÿ`).

Another example:
The byte sequence `0x49,0x00,0x20,0x00,0x61,0x00,0x6d,0x00` is valid for UTF-16LE and BE.
Once `I am` and once ` am`. And so forth. But only one of them was expected in the tests.

**Places for improvements (before merge?)**

- Get rid of the unrolled loops.
- Limited default search to only UTF-X. Set strong bias for endianess.
- Make `ps` list alternatives with `guess-list`.

**Later improvements**

- Different search bias profiles.
- Set sensitive selection for encodings searches based on binary information.
- Implement statistical analysis on the code points to detect language.
- Let users choose what is "printable" and what not. E.g. '\n' is part of the Unicode control plain and not printable. But for our use case (search) it is. Maybe only undefined Unicode points?

2025-02-02 04:27 UTC, wargio commented
this is worth opening an issue and handle it as a separate PR, since the string detection algo is in RzUtils.

2025-02-02 17:56 UTC, wargio commented on librz/core/cconfig.c
> +		rz_cons_printf("%d\n", max_threads);
The function gets called before the check on the question mark

2025-02-02 18:40 UTC, Rot127 commented on librz/core/cmd_descs/cmd_search.yaml
> +  - name: "/c"
Sure. But with the next PR. This is just so everything builds and in the yaml files.

2025-02-03 03:37 UTC, wargio approved these changes

2025-02-03 14:06 UTC, imbillow approved these changes

2025-02-03 17:54 UTC, notxvilka commented
Many asserts failures in the asm tests:
```
[XX]  88 ms   db/asm/gb <asm> ld [rAUD1HIGH], a
-- <asm> ld [rAUD1HIGH], a <--- e014 ---> <IL>
-- IL
--- expected
+++ actual
@@ -1,1 +1,0 @@
-(store 0 (bv 16 0xff14) (var a))

-- disasm exit status: 1
-- disasm stderr
WARNING: rz_hex_str2bin: assertion 'in && out' failed (line 573)
-- IL exit status: 1
-- IL stderr
WARNING: rz_hex_str2bin: assertion 'in && out' failed (line 573)
```

2025-02-08 16:04 UTC, Rot127 commented
All features are implemented and all the `cmd_search*` tests pass.
I'll fix the other failing tests tomorrow. Doxygen as well.

But because this is so huge, I mark it as ready for review now.

2025-02-10 16:54 UTC, notxvilka requested changes
Didn't review everything yet, will do deep sweep tomorrow.

2025-02-10 16:54 UTC, notxvilka commented on librz/core/cmd/cmd_search.c
> +	RzStrBuf *legacy_input = rz_strbuf_new(cmd);
Check if NULL

2025-02-10 16:54 UTC, notxvilka commented on librz/core/cmd/cmd_search.c
> +	rz_strbuf_free(legacy_input);
I think there is a `rz_strbuf_drain()` function that also automatically frees it.

2025-02-10 16:54 UTC, notxvilka commented on librz/core/cmd/cmd_search.c
> +	ut8 *re = RZ_NEWS0(ut8, strlen(argv[1]));
Check for NULL

2025-02-10 16:54 UTC, notxvilka commented on librz/core/cmd/cmd_search.c
> +	free(re);
Leak of `pattern`?

2025-02-10 16:54 UTC, notxvilka commented on librz/core/cmd/cmd_search.c
> +static RzRegexFlags parse_re_flag_desc(const char *re_flags_desc) {
This probably belongs in `librz/search`?

2025-02-10 16:54 UTC, notxvilka commented on librz/core/csearch.c
> +RZ_API RZ_OWN RzSearchFindOpt *rz_core_setup_default_search_find_opts(RzCore *core) {
for the API, add assert for `core`

2025-02-10 16:54 UTC, notxvilka commented on librz/include/rz_bin.h
> -	size_t max_uni_blocks; ///< Maximum number of unicode blocks
This value never changes now?

2025-02-10 16:54 UTC, notxvilka commented on librz/include/rz_util/rz_print.h
> -#define RZ_PRINT_FLAGS_ADDRMOD  0x00000002
We should refactor `RzPrint` too, not in this PR and even release, obviously

2025-02-10 16:54 UTC, notxvilka commented on librz/include/rz_util/rz_str.h
> +	RZ_STRING_ENC_SETTINGS = 'S', ///< Use str.encoding.
Not a particularly fan of this change, it leaks higher level concepts into the lower-level util.

2025-02-10 16:54 UTC, notxvilka commented on librz/search/bytes_search.c
> +	ut8 *bytes = RZ_NEWS0(ut8, strlen(byte_pattern) + 1);
Check for NULLs here

2025-02-10 16:54 UTC, notxvilka commented on librz/search/options.c
> +	if (opt) {
You can reverse the condition to simplify

2025-02-10 16:58 UTC, Rot127 commented on librz/include/rz_util/rz_str.h
> +	RZ_STRING_ENC_SETTINGS = 'S', ///< Use str.encoding.
Yeah, me neither. Didn't had an idea how to signal otherwise to use the `e str.encoding` setting. Any idea is welcome.

2025-02-10 18:33 UTC, Rot127 commented on librz/include/rz_bin.h
> -	size_t max_uni_blocks; ///< Maximum number of unicode blocks
See commit message:

```
commit b5396d56bb9aae45e3f285c69edc6bc4891dcfaa
Author: Rot127 <unisono@quyllur.org>
Date:   Fri Feb 7 11:24:23 2025 -0500

    Remove unused min_uni_blocks setting and move the number into a constant.
    
    The setting was somewhat related to false positive string detection.
    It seemed to be the value how many blocks the characters of a string
    can be in. But it is too ineffecient to scan this in this implementation.
    Also not a setting which should be exposed to the user in this way.
```

Blocks mean here: Unicode blocks. So if a string had characters of 4+ uni code blocks it was deemed a false positive.
This makes sense, but we shouldn't let the user decide this. Or give a better interface to make such decissions.
In this case it was used at one place and once place only and was always set to 4.

2025-02-10 18:34 UTC, Rot127 commented on librz/include/rz_util/rz_print.h
> -#define RZ_PRINT_FLAGS_ADDRMOD  0x00000002
Yes, But this is a TUI/UX task. Better not touch it until we have someone with actual UI experience.

2025-02-10 18:48 UTC, Rot127 commented on librz/core/cmd/cmd_search.c
> +	free(re);
Ownership goes to `rz_core_search_bytes`.

2025-02-10 18:50 UTC, Rot127 commented on librz/include/rz_util/rz_str.h
> +	RZ_STRING_ENC_SETTINGS = 'S', ///< Use str.encoding.
cc @wargio

2025-02-11 15:24 UTC, notxvilka requested changes
This test looks *definitely* wrong:
```
[XX] 434 ms   db/cmd/regexp /z at block end
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -qc 'e search.str.min_length=2
b 0x100
w bcccde @ 0xfe
w bd @ 0x1fe
e scr.color=1
/z "b.*d" r
ps ascii @ hit.string.ascii.0
ps ascii @ hit.string.ascii.1
echo ----
/z "b.*d$" r
ps ascii @ hit.string.ascii.0
' =
-- stdout
--- expected
+++ actual
@@ -1,7 +1,7 @@
 0x000000fe 5 hit.string.ascii.0
 0x000001fe 2 hit.string.ascii.1
 bcccde
-bd
+bd\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff
 ----
 0x000001fe 2 hit.string.ascii.0
-bd
+bd\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff
```

2025-02-11 21:15 UTC, Rot127 commented
There are only 3-4 tests left which are not obvious to fix. I hope can resolve them quickly tomorrow.

Added also an overview of all the changes above. For orientation.

2025-02-12 03:55 UTC, notxvilka commented
I think the old output in this test makes more sense:
```
[XX] 245 ms   db/formats/elf/strings iz (utf-32le)
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -qc 'iz~Hello
fl@F:strings
s sym.main
af
pdf~str.Hello
aar
fl@F:strings
' bins/elf/analysis/hello-utf-32le
-- stdout
--- expected
+++ actual
@@ -1,6 +1,6 @@
-  0 0x000005e8 0x004005e8  12   52 .rodata utf32le Hello World\n
+  0 0x000005e8 0x004005e8  12   52 .rodata utf32le Hello World\U00000a
 0x004005e8 52 str.Hello_World
 0x00400620 32 str.S
-|           0x0040052e      mov   qword [var_10h], str.Hello_World     ; 0x4005e8 ; U"Hello World\n"
+|           0x0040052e      mov   qword [var_10h], str.Hello_World     ; 0x4005e8 ; U"Hello World\U00000a"
 0x004005e8 52 str.Hello_World
 0x00400620 32 str.S
```

2025-02-12 04:10 UTC, notxvilka requested changes

2025-02-12 04:10 UTC, notxvilka commented on librz/arch/asm.c
> +					rz_iterator_free(iter);
I know this PR became very complex, but could you extract unrelated to the rzshearch changes into a separate PR? For example all those leak fixes?

2025-02-12 04:38 UTC, wargio commented on librz/arch/asm.c
> +					rz_iterator_free(iter);
i agree

2025-02-12 17:25 UTC, notxvilka commented
Go tests new output is better, just change the tests:
```
-| 0x00099898      auipc t2, 0x1e ; 0xb7b60 ; "foogc gp in intmapnilobjpc=ptr\u00b5s\u03bcs <== at  fp= is  lr: of  on  pc= sp: sp=) = ) m=+Inf,r2=-Inf3125: p=AhomChamDashGOGC"
+| 0x00099898      auipc t2, 0x1e ; 0xb7b60 ; "foogc gp in intmapnilobjpc=ptrµsμs <== at  fp= is  lr: of  on  pc= sp: sp=) = ) m=+Inf,r2=-Inf3125: p=AhomChamDashGOGCLEAFLisu"
```

But this one looks like a regression:
```
 [XX] 197 ms   db/cmd/cmd_pf pf z, scr.strconv and str.escbslash
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -qc 'wz \x7fabc\\123\n
(print strconv escbslash; e scr.strconv=${strconv}; e str.escbslash=${escbslash}; pf z)
.(print asciiesc false)
.(print asciiesc true)
.(print asciidot false)
.(print asciidot true)
' =
-- stdout
--- expected
+++ actual
@@ --1,6 +-1,6 @@
 0x00000000 = "\x7fabc\123\n"
-0x00000000 = "\x7fabc\\123\n"
-0x00000000 = ".abc\123\n"
-0x00000000 = ".abc\\123\n"
+0x00000000 = "\x7fabc\123\n"
+0x00000000 = ".abc\123."
+0x00000000 = ".abc\123."
```

2025-02-12 17:50 UTC, Rot127 commented
> But this one looks like a regression:

Not really, it depends on the interpretation.

The `asciidot` option is: "replace non-printable ASCII with dots". `\n`, `\t` etc are considered non-printable (part of the Unicode control plain and here in Rizin `IS_PRINTABLE()` also excludes them).
So they should be replaced with a dot.

The other one (default) is `asciiesc`. It escapes all non-printable chracters as `\xhh` or in their short form `\n` etc.

I wouldn't interpret `replace non-printable with dots` as `replace non-printable with dots except those special ones please`. It was just inconsequential before.

2025-02-12 17:50 UTC, Rot127 commented
> Go tests new output is better, just change the tests:

Mind that those will go again. Because I will add a flag to not print them if `scr.utf8` is disabled. Or should they be printed anyways?

2025-02-12 17:52 UTC, Rot127 commented on librz/arch/asm.c
> +					rz_iterator_free(iter);
https://github.com/rizinorg/rizin/pull/4895

2025-02-12 17:54 UTC, notxvilka commented
> > Go tests new output is better, just change the tests:
> 
> Mind that those will go again. Because I will add a flag to not print them if `scr.utf8` is disabled. Or should they be printed anyways?

Make these two tests then, to test both behaviors.

2025-02-12 18:56 UTC, Rot127 commented
@imbillow Please check 3cc4f243b35784ee21c186120776ea4e59e34972

2025-02-13 03:57 UTC, notxvilka requested changes

2025-02-13 03:57 UTC, notxvilka commented on librz/include/rz_io.h
> +RZ_DEPRECATE RZ_API bool rz_io_read_at(RzIO *io, ut64 addr, ut8 *buf, size_t len);
This part of the PR could be extracted into a separate one - changes in the RzIO

2025-02-13 03:57 UTC, notxvilka commented on librz/include/rz_th.h
> +typedef bool (*RzThreadIterator)(void *element, void *user);
Same with changes in thread iterator

2025-02-13 03:57 UTC, notxvilka commented on librz/include/rz_util/rz_buf.h
> +/**
As well as changes in RzBuf

2025-02-13 03:57 UTC, notxvilka commented on librz/include/rz_util/rz_strbuf.h
> +RZ_API RZ_OWN char *rz_strbuf_drain(RZ_OWN RZ_NONNULL RzStrBuf *sb);
And strbuf

2025-02-13 03:57 UTC, notxvilka commented on librz/util/vector.c
> +	if (rz_vector_empty(vec)) {
And changes in vector - also better suited for a separate PR

2025-02-13 10:58 UTC, kazarmy commented
> > But this one looks like a regression:

> Not really, it depends on the interpretation.

The backslashes should default to being escaped (`\\`). It was pancake that didn't want them escaped, possibly because they clutter up Windows/UNC paths.

> The asciidot option is: "replace non-printable ASCII with dots". `\n`, `\t` etc are considered non-printable ...

The above is true, but in my experience, `\n` and `\t` are common enough in program code to be considered special and highlightable (Rizin code itself has significant numbers of them), and `\r` is a Windows (and HTTP) line termination character so it should also qualify as deserving special treatment. And who knows, somebody might decide to use `\b` for nefarious deeds.

2025-02-13 11:48 UTC, Rot127 commented
@kazarmy

> The backslashes should default to being escaped (\\). It was pancake that didn't want them escaped, possibly because it clutters up Windows/UNC paths.

Every single backslash? Also for escaped bytes and code points? So `\xhh` becomes `\\xhh` and the same for `\U00hhhhhh`? Both is fine, as long as we are consistent.

> And who knows, somebody might decide to use \b for nefarious deeds.

I don't care too much about the `ASCII as dot` setting tbh. I would even remove it and only use it internally for the hex view. Because there it is easy to see `x1b` and the `.`.

2025-02-13 12:24 UTC, kazarmy commented
> Every single backslash?

Only for code point U+005C in memory, I guess.

> ... ASCII as dot setting tbh. I would even remove it ...

It would be interesting to remove it, and see whether anyone screams, and then put it back in if so, but I think you need to ask @notxvilka on that.

2025-02-13 13:15 UTC, Rot127 commented
> Only for code point U+005C in binary memory, I guess.

This should already be the case. Did you see it not somewhere?

2025-02-13 13:26 UTC, kazarmy commented
> This should already be the case. Did you see it not somewhere?

I didn't see it in https://github.com/rizinorg/rizin/pull/4762#issuecomment-2654392564 but now I've noticed that you've fixed that (I think ... pr is really big). Apologies for not noticing before.

2025-02-13 13:36 UTC, Rot127 commented
> I didn't see it in https://github.com/rizinorg/rizin/pull/4762#issuecomment-2654392564 but now I've noticed that you've fixed that (I think ... pr is really big). Apologies for not noticing before.

Nah, no worries. I try to reduce it. NI am sorry it got so enormous.

2025-02-13 19:31 UTC, notxvilka commented
@Rot127 all extracted PRs were merged, please rebase.

2025-02-13 21:21 UTC, Rot127 commented
Last failing tests is because I failed to add the execute permission. See https://github.com/rizinorg/rizin/pull/4762

2025-02-14 03:45 UTC, notxvilka requested changes
See the bindgen-linter output:
```
Type comment at <rizin/librz/search/search.c:619:33> lacks pointer
```

Another problem is the MSVC compilation error:
```
FAILED: test/unit/test_encodings.exe.p/test_encodings.c.obj 
"cl" "-Itest\unit\test_encodings.exe.p" "-I." "-I.." "-Ilibrz" "-I..\librz" "-Ilibrz\include" "-I..\librz\include" "-Itest\unit" "-I..\test\unit" "-Ilibrz\util\sdb\src" "-I..\librz\util\sdb\src" "-I..\librz\arch\isa" "-I..\librz\arch\isa_gnu" "-Ilibrz\arch" "-I..\librz\arch" "-I..\librz\bin\format\elf" "-I..\librz\bin\format\dmp" "-I..\librz\bin\format\mdmp" "-I..\librz\bin\format\pe" "-I..\librz\bin\format" "-Ilibrz\core\cmd_descs" "-I..\librz\core\cmd_descs" "-I..\librz\type\parser" "/MT" "/nologo" "/showIncludes" "/utf-8" "/W2" "/O2" "/Gw" "-DPSAPI_VERSION=1" "-DRZ_PLUGIN_INCORE=1" "-DSUPPORTS_PCRE2_JIT" "/Fdtest\unit\test_encodings.exe.p\test_encodings.c.pdb" /Fotest/unit/test_encodings.exe.p/test_encodings.c.obj "/c" ../test/unit/test_encodings.c
../test/unit/test_encodings.c(223): error C2059: syntax error: '}'
[2126/2302] Compiling C object test/unit/test_event.exe.p/test_event.c.obj
../test/unit/test_event.c(42): warning C4312: 'type cast': conversion from 'unsigned int' to 'void *' of greater size
../test/unit/test_event.c(46): warning C4312: 'type cast': conversion from 'unsigned int' to 'void *' of greater size
../test/unit/test_event.c(53): warning C4312: 'type cast': conversion from 'unsigned int' to 'void *' of greater size
[2127/2302] Linking target test/unit/test_endian.exe
ninja: build stopped: subcommand failed.
```

2025-02-15 02:55 UTC, kazarmy commented
> Only for code point U+005C in binary memory, I guess.

... except for memory (hex)dumps if space is limited.

2025-02-15 07:24 UTC, notxvilka commented
MSVC compilation error still happens

2025-02-16 13:37 UTC, notxvilka requested changes
```
 [XX] 298 ms   db/cmd/cmd_pd pd bin.str.filter
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -qc 'e asm.bytes=false
e asm.cmt.off=false
s 0x004028e0
e bin.str.filter=
pd 1
e bin.str.filter=U
pd 1
' bins/elf/analysis/ls2
-- stdout
--- expected
+++ actual
@@ -0,3 +0,9 @@
             0x004028e0      mov   esi, str.usr_share_locale            ; "/usr/share/locale"
             0x004028e0      mov   esi, str.usr_share_locale
+
+
+
+FAILED AT FILTER;
+
+


```

2025-02-16 13:41 UTC, Rot127 commented
I know. Try to limit why the GCC tests fail. Can't reproduce it locally. So I do educated guessing now (before I have to use act)

2025-02-17 15:27 UTC, notxvilka commented
This new output looks better:
```
 [XX] 280 ms   db/cmd/cmd_i iz ibm037 on zos binary
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -esearch.show_progress=false -eflirt.sigdb.load.home=false -N -qc 'iz~SRSGENER
iz~SRSPRHEX
iz~SRSTASK
' bins/zos/linklib.xmt
-- stdout
--- expected
+++ actual
@@ -12,6 +12,6 @@
 125 0x0000323f 0x0000323f   9   10         ibm037  3SRSPRHEX
 191 0x00004c0f 0x00004c0f  27   28         ibm037  SRSPRHEX_03/06/08_14.17°Ö}\f
  18 0x000003ba 0x000003ba   8    9         ibm037  SRSTASK 
- 91 0x00002540 0x00002540  17   18         ibm037  ­bå0­«SRSTASK  \-
+ 91 0x00002545 0x00002545  12   13         ibm037  «SRSTASK  \-
 124 0x00003230 0x00003230   8    9         ibm037  SRSTASK 
 130 0x000033e4 0x000033e4 103  104         ibm037  SRSTASK_12/31/08_20.31 SRS Version 1.3.0_A13001  COPYRIGHT 1998-2008 DAVID W DANNER ALL RIGHTS RESERVED
```

2025-02-17 15:29 UTC, Rot127 commented
Some yes. But this is unrealted to the main problem. The gcc-12 builds don't work for whatever reason. They write some wrong bytes. Just setup a gcc-12 VM now, to finally fix it.

2025-02-18 12:40 UTC, wargio commented
`rz_config_set: variable 'str.search.encoding' not found`. i guess there is a typo somewhere?

2025-02-18 12:42 UTC, wargio approved these changes

2025-02-19 18:03 UTC, notxvilka commented
Still a timeout. Maybe some slight performance optimization is still needed.

2025-02-20 04:39 UTC, wargio commented on librz/arch/data.c
> +	RzStrEnc encoding = analysis->coreb.cfggeti(analysis->core, "str.encoding");
```suggestion
	RzStrEnc encoding = analysis->core ? analysis->coreb.cfggeti(analysis->core, "str.encoding") : RZ_STRING_ENC_GUESS;
```

2025-02-20 04:39 UTC, wargio commented on librz/arch/data.c
> +	RzStrEnc encoding = analysis->coreb.cfggeti(analysis->core, "str.encoding");
don't assume that pointer is valid.

2025-02-20 04:41 UTC, wargio commented on librz/util/ebcdic.c
> +	return invalid_ebcdic_decode(src, *dst) ? 0 : 1;
is this now boolean?

2025-02-20 04:52 UTC, wargio requested changes
Please add a check somewhere when we search for golang strings to enforce `utf8` because they are compiled as utf8 for constant strings. everything else that is not a constant string is not necessary as utf8

https://go.dev/blog/strings

2025-02-20 13:43 UTC, wargio commented on librz/util/str_search.c
> +	}
no need to have an if. just `free(heap_alloc)`

2025-02-20 14:11 UTC, wargio approved these changes

2025-02-20 14:16 UTC, Rot127 commented on librz/util/ebcdic.c
> +	return invalid_ebcdic_decode(src, *dst) ? 0 : 1;
No, it returns the number of bytes consumed. In case it couldn't decode a character, it returns `0`, because it consumed nothing. For UTF-8 it can return 0-4, for example.

I refactored all the other "code point" decoding functions like this as well. Because before it was kinda random. Should document it though.

2025-02-20 15:17 UTC, Rot127 commented
Going to squash commits into reasonable parts and push to `dist-fuzz`.

2025-02-20 15:19 UTC, notxvilka commented
> Going to squash commits into reasonable parts and push to `dist-fuzz`.

@Rot127 please open a new PR with that.

2025-02-20 15:37 UTC, notxvilka approved these changes
An immense amount of work and way better test coverage. While there are still things that could be improved, I believe they could go in separate PRs to not block this PR anymore.
Thus, LGTM. Let's merge it once green and has better history! Kudos!

2025-02-20 15:37 UTC, notxvilka commented on .github/workflows/ci.yml
> -            cflags: "-DASAN=1 -DRZ_ASSERT_STDOUT=1 -ftrivial-auto-var-init=pattern -funsigned-char"
Open an issue about it also

2025-02-20 15:37 UTC, notxvilka commented on librz/arch/p/analysis/analysis_arm_cs.c
> +			val->mul = (ut64)armop.mem.scale << armop.shift.value;
I think this one is already in `dev`, maybe rebase?

2025-02-20 15:37 UTC, notxvilka commented on librz/core/cconfig.c
> +		rz_config_set(core->config, "str.encoding", "utf8");
Not necessarily, for example, it could be linked with C or C++ library that has UTF-16 strings. But that's out of the scope of this PR. Should be handled separately.

2025-02-20 15:37 UTC, notxvilka commented on librz/include/rz_util/rz_str.h
> +	RZ_STRING_ENC_SETTINGS = 'S', ///< Use str.encoding.
@wargio you never answered this one. It's okay for now, but would be nice to separate.

2025-02-20 15:37 UTC, notxvilka commented on librz/search/search_internal.h
> +#define RZ_SEARCH_AES_LENGTH         40
Should be in a separate file, I think, but is fine for this PR, could be done afterwards.

2025-02-20 15:37 UTC, notxvilka commented on librz/util/hex.c
> + * Example:
I think examples have their own Doxygen syntax

2025-02-20 15:44 UTC, Rot127 commented on librz/search/search_internal.h
> +#define RZ_SEARCH_AES_LENGTH         40
Yes, will be. With the AES search refactored. @wargio already moved it into a separted file before.

2025-02-20 15:46 UTC, wargio commented on librz/search/search_internal.h
> +#define RZ_SEARCH_AES_LENGTH         40
keep this internal. no real need to move this, and since i want to refactor more that type of search with new features, i think it can be ok to be there for now.

2025-02-20 15:47 UTC, wargio commented on librz/core/cconfig.c
> +		rz_config_set(core->config, "str.encoding", "utf8");
if we want to simplify this, then we can enforce it where we search for golang strings directly

2025-02-20 15:50 UTC, wargio commented on librz/core/cmd_descs/cmd_search.yaml
> +  - name: "/c"
I will do this. i think what will be done for this is just `/c <type>` where by default is going to be `all` or if specified, whatever the user will choose.

2025-02-20 15:52 UTC, Rot127 commented on librz/util/hex.c
> + * Example:
Could only find https://www.doxygen.nl/manual/commands.html#cmdexample

But this is about including a file. But I'll highlight the code.

2025-02-20 15:53 UTC, wargio commented on librz/include/rz_util/rz_str.h
> +	RZ_STRING_ENC_SETTINGS = 'S', ///< Use str.encoding.
sorry, i missed it. i don't like this, i think it would be better to just pass an argument for the encoding and then pass this to the lower level..
since normally the calls are core > analysis, we can do the same by just passing the correct encoding when core calls the search api

2025-02-20 15:54 UTC, wargio commented on librz/include/rz_util/rz_str.h
> +#define ASCII_LAST_CODE_POINT 0x7F
be sure this is the correct place. i remember there was a header with some constants, maybe it could go there, also since this is exposed it should have `RZ_` prefix

2025-02-20 15:54 UTC, wargio commented on librz/include/rz_util/rz_unicode.h
> +#define UNICODE_LAST_CODE_POINT        0x10ffff
`RZ_` prefix

2025-02-20 16:16 UTC, Rot127 commented on librz/include/rz_util/rz_str.h
> +#define ASCII_LAST_CODE_POINT 0x7F
Yeah, I left it there because it not really is Unicode, and there is not ASCII header. But putting it to `rz_unicode.h` is indeed better.

2025-02-20 17:13 UTC, Rot127 commented on librz/core/cconfig.c
> +		rz_config_set(core->config, "str.encoding", "utf8");
Makes sense, set it now only in `rz_recover_all_golang_functions_strings_handler()`

2025-02-20 17:13 UTC, Rot127 commented
Close for PR with cleaned up history.

2025-02-20 17:13 UTC, closed without merging