add rzil 'fexcept'|'FEXCEPT'
rizinorg/rizin pull request #4771
Opened 2024-12-16 17:12 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Add a new rzil op for getting floating point exceptions

**Test plan**

...

**Closing issues**

...

2024-12-16 17:16 UTC, wargio approved these changes
this makes sense, but i think those should be handled like for div0

2024-12-16 17:32 UTC, XVilka approved these changes

2024-12-16 17:35 UTC, XVilka requested changes

2024-12-16 17:35 UTC, XVilka commented on librz/il/il_opcodes.c
> +RZ_API RZ_OWN RzILOpBool * rz_il_op_new_fexcept(RzFloatException e, RZ_NONNULL RzILOpFloat *x) {
```
librz/include/rz_il/rz_il_opcodes.h:769:27: error: code should be clang-formatted [-Wclang-format-violations]
RZ_API RZ_OWN RzILOpBool * rz_il_op_new_fexcept(RzFloatException e, RZ_NONNULL RzILOpFloat *x);
                          ^
```

2024-12-17 03:45 UTC, XVilka approved these changes

2024-12-17 04:40 UTC, wargio commented on librz/il/theory_fbasic.c
> +		break;
This should also generate an exception event like here: https://github.com/rizinorg/rizin/blob/e7b919f001c5894ee66aeae49567e6cf8dfc429a/librz/il/theory_bitv.c#L233

2024-12-17 04:41 UTC, wargio requested changes
see previous comment

2024-12-17 06:35 UTC, XVilka requested changes
1. Please add a test also
2. Please rebase to fix the CI

2024-12-17 08:41 UTC, XVilka approved these changes

2024-12-17 09:29 UTC, wargio approved these changes

2024-12-17 16:14 UTC, XVilka commented
@thestr4ng3r could you please give a quick look?

2024-12-18 05:39 UTC, merged