Feature/filtering la
rizinorg/rizin pull request #4786
Opened 2024-12-21 16:51 UTC by well-mannered-goat

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

I updated the `rz_core_asm_plugins_print` function to handle the input of features argument and also removed the arch argument from `rz_core_asm_plugin_print` while also adding argument to handle the features

- the strings feat and feat2 in `rz_core_asm_plugin_print` were being made and then I concatenate them into feat, my filter is passed as flags argument in the function and if any character of flags is not present in feat the function returns `RZ_CMD_STATUS_OK` rather than printing the output for that `RzAsmPlugin`
- updated the `rz_plugins_asm_print_handler` to handle the `rz_core_plugins_asm_print` accordingly with the number of arguments
- also updated the call of function `rz_core_asm_plugins_print` at other places by passing NULL as flags
- updated `plugins_asm_print_args` to have an optional argument name 'features'
- updated the `cmd_plugins.yaml` to handle an argument for La command

**Test plan**

- Normal working of La
![image](https://github.com/user-attachments/assets/284d5094-0733-4098-a609-7d03f8cd5d42)
- Output for only assemblers
![image](https://github.com/user-attachments/assets/482684b3-95e5-463b-a6ad-1d80f478f8a7)
- Output for only Analysis with RzIL
![image](https://github.com/user-attachments/assets/46a6a1fa-cfb1-4816-b7c6-f3927d73cc16)

**Closing issues**

closes #4756

2024-12-22 07:58 UTC, wargio requested changes
Add a test under test/db/cmd/

2024-12-22 07:58 UTC, wargio commented on librz/core/casm.c
> +	for (int i = 0;flags && flags[i] != '\0'; i++) {
I like how you solved it, but this is not clang formatted. Run sys/clang-format.py (requires clang format) and submit the changes.

2024-12-24 05:43 UTC, well-mannered-goat commented
So I have been working on the testing of this command and found out that `Laj` command expected wrong output with only `a` and `d` features in output as initially only those were printed in JSON output.
I updated it to have others too.

Also since I have applied filtering on Laq and Laj commands too, should I do extensive testing for each filtering and their combinations with La command output types?

2024-12-24 09:35 UTC, wargio commented
Just add a test for each j and q variant.

2024-12-24 11:57 UTC, wargio requested changes
Looks like you did not use the correct clang-format version. Google clang format static and use clang format 16

2024-12-24 11:59 UTC, wargio commented
Also for the tests, just merge them into one test.
So it would run multiple commands in one rizin session

2024-12-24 12:06 UTC, well-mannered-goat commented
Sorry, would apply the changes as soon as possible

2024-12-24 15:34 UTC, wargio commented
take your time. no rush

2024-12-24 15:44 UTC, wargio commented
Ps: check the options of sys/clang-format.py to pass the correct version of clang format

2024-12-24 15:55 UTC, well-mannered-goat commented
I cant pass the version in the script it seems

I have installed 16.0.0 on my machine

![image](https://github.com/user-attachments/assets/c0457bd0-cb7c-45a0-9d33-0812d3e866b7)

![image](https://github.com/user-attachments/assets/b07ad0c4-bf57-4374-9c16-aa3b74c84110)

is this the correct version needed?

2024-12-24 17:24 UTC, wargio commented
No, i meant the binary location of clang-format16
-C should allow this

2024-12-25 03:58 UTC, well-mannered-goat commented
I passed the path to binary location of clang-format in -c argument and there was no change in any file
Also i did not push the output_file in test directory, do I need to push it too?

2024-12-25 12:13 UTC, wargio commented
this is how i run it `./sys/clang-format.py -C /opt/clang-format-static/clang-format-16`

2024-12-25 13:24 UTC, well-mannered-goat commented
So this is my binary location
![image](https://github.com/user-attachments/assets/5eda680a-60d6-4028-9271-426e0b1220fd)

this is what i run `./sys/clang-format.py -C /opt/clang-16.0.0/bin/clang-format`

2024-12-26 06:20 UTC, wargio requested changes
Ok, just manually revert the changes of
- `librz/arch/isa/rx/rx_opcode_detail.c`
- `librz/bin/format/elf/glibc_elf.h`
- `librz/hash/algorithms/ssdeep/fnv_hash.h`
- `librz/include/rz_magic.h`

Then squash and we can merge.

2024-12-26 07:50 UTC, well-mannered-goat commented
squashed the commits
sorry didnt know had to keep less number of commits, would keep in mind about it.

2024-12-26 08:37 UTC, wargio commented
> squashed the commits sorry didnt know had to keep less number of commits, would keep in mind about it.

Not really, we normally always squash, but is just to have a clean history here (for readability)

2024-12-26 11:14 UTC, well-mannered-goat commented
Seems like RzIL support for xtensa is added

would update the tests

2024-12-26 15:14 UTC, wargio approved these changes

2024-12-26 15:17 UTC, XVilka approved these changes

2024-12-26 15:45 UTC, merged