Refactor rizin graph in rz_util
rizinorg/rizin pull request #4788
Opened 2024-12-22 16:41 UTC by Heersin

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

working on implement functions
Add more graph representation for rizin, see https://github.com/rizinorg/rizin/issues/4231

1. support identifier for nodes
2. matrix based graph

**Test plan**

1. unit test
2. replace old graph api and test

**Closing issues**

...

2024-12-22 16:46 UTC, XVilka submitted a review, later dismissed

2024-12-22 16:46 UTC, XVilka commented on librz/include/rz_util/rz_graph_new.h
> + * @brief Represents a node in a graph, node should be hashable.
Rizin uses `\brief` syntax, here and everywhere please use this one.

2024-12-29 17:10 UTC, Rot127 reviewed
Looks already way way better then before! Thanks a lot.

Some questions you might have already considered.

1. Should the graph's API mostly work on Node pointers or the node ids? Having both would be nice. If the node content doesn't matter to the user. But working on pointers is fine for me as well for now.
2. Runtime complexity for getting neighbors. Please let's not clone the nodes every time the neighbor list is requested. This doesn't scale well. Instead a read only `RzIterator` over the lists/matrix is a better fit I think.
3. Could the elements in the List based graph implementation contain edges? It would maybe reduce internal complexity getting the neighbors. Especially for directed graphs.

2024-12-29 17:10 UTC, Rot127 commented on librz/include/rz_util/rz_graph_new.h
> +	bool (*del_node)(RzGraphNew *graph, RzGraphNodeNew *node);
I wonder if it is useful to have the same callbacks, but taking the node ids, instead of the node pointers.
This way users can decide they don't want to mess with the pointers at all.

2024-12-29 17:10 UTC, Rot127 commented on librz/include/rz_util/rz_graph_new.h
> +	unsigned int n_edges;
```suggestion
	ut64 n_nodes;
	ut64 n_edges;
```

Just in case :)

2024-12-29 17:10 UTC, Rot127 commented on librz/include/rz_util/rz_graph_new.h
> +	HtUP *nodes; /* <hash_id, RzGraphNode> */
I think you can add a `typedef RzGraphHashId;`

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	unsigned int n_nodes;
```suggestion
	ut64 n_nodes;
```

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	}
Why not a simple rz_return_val_if`?

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +		RZ_LOG_WARN("Node not found in the graph")
```suggestion
		RZ_LOG_WARN("Node not found in the graph.\n");
```

The new lines are missing.

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	return new_neighbours;
I think we can just return the actual list as constant pointer. No need to clone the list internally. These "get_neighbors" functions get called a lot in algorithms and it would cost us a lot of runtime.

Instead, we could add a function to the API like `clone_neighbor_list` or similar. Once we need it. Not here.

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +
Same as above. In this case I would vote to have two lists for each node. One for `in` and one for `outgoing` edges. If the graph is undirected, just one is used.
Not sure if it is the best solution. A list of edges instead of nodes could be nice as well.

But cloning the list on every `get_neighbor()` doesn't scale well. Exchanging runtime complexity against memory complexity is better IMHO.

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> + * @return true if the graph is initialized successfully, false otherwise.
```suggestion
 * @return true if the edge is initialized successfully, false otherwise.
```

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	st64 **adj_matrix;
```suggestion
	ut8 **adj_matrix;
```

Any reason to make the cells so big? With `ut8` we could already encode 255 edge types.

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	impl->adj_matrix[from->hash_id][to->hash_id] = 1;
Move the magic values like `1` and `0` into macros. `EDGE_SET`, `EDGE_UNSET` or similar.
It might be even useful to add some small `inline` functions to test this property.

E.g.:

```c
static inline bool edge_set(impl, from, to) { return impl->adj_matrix[from->hash_id][to->hash_id] & 1; }
```

This way we can extend the graph easier with special edges. By using the upper bits.

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	st64 **adj_matrix;
Or `bit0` is set or unset. And the upper bits are some other properties. Edge color for example.

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	for (unsigned int i = 0; i < impl->n_nodes; i++) {
```suggestion
	for (ut64 i = 0; i < impl->n_nodes; i++) {
```

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	}
Same as above. Let's not clone all the nodes just because the neighbors are requested. The pointers to the neighbors are enough.

It could instead return a `RzIterator` for example.

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	}
This would largely prevent the graph to be accessed by multiple threads. Because the pointers returned by the iterator might live longer then the nodes in the graph.

But we would need to add another implementation for this use case anyways.

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +RZ_API RzGraphNew *rz_graph_new_new(RzGraphIdentifierHash user_hash, RzGraphUserdataFree user_free, RzGraphImpl impl) {
```suggestion
RZ_API RZ_OWN RzGraphNew *rz_graph_new_new(RzGraphIdentifierHash user_hash, RzGraphUserdataFree user_free, RzGraphImpl impl) {
```

2024-12-29 17:10 UTC, Rot127 commented on librz/util/graph.c
> +	return g->edge_set->ops->get_out_neighbours(g, node);
These callbacks might are a performance problem (see: https://github.com/rizinorg/rizin/issues/4769). We would need to test this and maybe replace them with a switch.

2025-01-09 11:28 UTC, Heersin commented on librz/util/graph.c
> +	}
i guess just auto-complete and choose one of them

2025-01-09 11:30 UTC, Heersin commented on librz/util/graph.c
> +	return new_neighbours;
yeah, it's the heaviest operation for get neighbours, at that time, i didn't know if a better way rizin util could support for User get a reference of Node set

2025-01-09 11:32 UTC, Heersin commented on librz/util/graph.c
> +	impl->adj_matrix[from->hash_id][to->hash_id] = 1;
nice, I would fix this dirty and quick implementation

2025-01-09 11:39 UTC, Heersin commented on librz/include/rz_util/rz_graph_new.h
> +	bool (*del_node)(RzGraphNew *graph, RzGraphNodeNew *node);
in the design, these pointers should all be internal to the graph API, with external access only through a unified set of functions.

2025-01-09 11:51 UTC, Heersin commented
> Looks already way way better then before! Thanks a lot.
> 
> Some questions you might have already considered.
> 
>     1. Should the graph's API mostly work on Node pointers or the node ids? Having both would be nice. If the node content doesn't matter to the user. But working on pointers is fine for me as well for now.
> 
>     2. Runtime complexity for getting neighbors. Please let's not clone the nodes every time the neighbor list is requested. This doesn't scale well. Instead a read only `RzIterator` over the lists/matrix is a better fit I think.
> 
>     3. Could the elements in the List based graph implementation contain edges? It would maybe reduce internal complexity getting the neighbors. Especially for directed graphs.

1. yes, this is also something I have been contemplating. don't know if it would be confused to provide both way to access. so I defined them mostly work on Node pointer, and they could turn `id` into pointer through hash_find
2. exactly, it did bring crazy workload for runtime. I'm looking for a better way to return neighbors, do u know which file provide a best practice sample for returning `RzIterator`?
3. no they don't contain explicit edges, initially I implemented it as edge and nodes, but later remove edges to abstract the RzGraph and implement PoC. You r right It's good to have edge in impl for list-based graph, and to reduce the complexity, thanks for point out that

2025-01-09 13:11 UTC, Rot127 commented
>  do u know which file provide a best practice sample for returning RzIterator

You can checkout `ht_inc.c`. The functions `Ht_(as_iter_keys)`, `Ht_(as_iter_mut)` and the corresponding (`iter_next` etc.) return an iterator over a hash map. Your usecase is even simpler I think.

> no they don't contain explicit edges, initially I implemented it as edge and nodes, but later remove edges to abstract the RzGraph and implement PoC. You r right It's good to have edge in impl for list-based graph, and to reduce the complexity, thanks for point out that

You make a good point there. Considering code complexity (meaning: many lines of code) vs. low runtime complexity.

If you don't want to add an edge list for now (because too much work/ too many things to consider), it is fine.
We can still extend it.

cc @wargio

2025-01-09 13:42 UTC, wargio commented
agreed with @Rot127

I think it is ok to have first an implementation that works, then we can improve the execution time.

2025-11-14 16:52 UTC, notxvilka commented
@Heersin have you had any updates since?

2026-01-18 11:07 UTC, notxvilka commented
@Heersin ping

2026-02-12 16:06 UTC, Heersin commented
> @Heersin ping

Waiting to implement DFS. A question is I reserved edge_data in RzGraphEdgeNew, not sure if we need such a data for analysis inside rizin @XVilka  @Rot127

2026-02-12 16:47 UTC, Rot127 commented
@Heersin 
> A question is I reserved edge_data in RzGraphEdgeNew, not sure if we need such a data for analysis inside rizin

Please, yes!
I am currently missing exactly this feature:

My use case is a control flow graph. Each node is a basic block (a sequence of instructions with the last instruction being a branch (jump or call)).

Now, the edges of the CFG are the jumps. Obvious.
But there is no edge between the call and its next instruction (the instruction where the callee would return to). But it would be nice to have some different kind of edge between call and return point (can eases analysis).

Then I would have edges of type I for normal branches, and edges of type II for "follows call".

2026-02-12 16:49 UTC, notxvilka commented
i agree, it makes sense to support generic graphs with whatever data provided.

2026-02-15 09:51 UTC, notxvilka requested changes
It probably makes sense to split graph into two files: implementation and algorithms.

2026-02-15 09:53 UTC, notxvilka requested changes

2026-02-15 09:53 UTC, notxvilka commented on librz/util/graph.c
> +/* Matrix Impl */
I think it makes sense to write "adjacency matrix" instead of just "matrix" so it's clear exactly what does it mean.

2026-02-15 14:24 UTC, Heersin commented on librz/util/graph.c
> +/* Matrix Impl */
ok, will split to two files after unit test

2026-02-15 17:34 UTC, Rot127 requested changes

2026-02-15 17:34 UTC, Rot127 commented on librz/util/graph.c
> +RZ_API void rz_graph_free_new(RZ_NULLABLE RZ_OWN RzGraphNew *g) {
```suggestion
RZ_API void rz_graph_free(RZ_NULLABLE RZ_OWN RzGraphNew *g) {
```

2026-02-15 17:34 UTC, Rot127 commented on librz/util/graph.c
> +RZ_API void rz_graph_free_new(RZ_NULLABLE RZ_OWN RzGraphNew *g) {
Just so we don't forget about it :)

2026-02-16 06:26 UTC, Heersin commented
> It probably makes sense to split graph into two files: implementation and algorithms.

DONE
should we replace the old API in another PR? or just replace them in the same one ? @notxvilka @Rot127

2026-02-16 12:48 UTC, Rot127 commented
@Heersin Please replace it here, so the test coverage is higher.

2026-02-16 13:42 UTC, wargio commented
Replace it

2026-02-20 20:17 UTC, notxvilka requested changes
Don't forget to rebase it as well, please.

See also this: https://github.com/rizinorg/rizin/issues/992 (could be done separately but gives you an idea of the possible APIs needed)

2026-02-25 16:37 UTC, notxvilka requested changes
Many compilation errors

2026-02-25 16:57 UTC, Rot127 requested changes
There is a use case I still miss in the tests and API.
It is also very very common, so I think it should be implemented and be an example in the README or similar.

The case is:
How to I check for nodes and edges in a graph, if I don't know the `RzGraphNode` pointers?
I think this is the default scenario for Graph APIs. Because the internal node pointers shouldn't be managed by the API users. Hence, we cannot expect users to know them.

I would rename `rz_graph_has_edge()` to something like `rz_graph_has_edge_by_nptr` or similar.
And change `rz_graph_has_edge(RzGraph *g, RzGraphNode *from, RzGraphNode *to)` to `rz_graph_has_edge(RzGraph *g, void *id_node_a, void *id_node_b)`.

This makes it way more intuitive to use IMO.
Because tbh, I have yet to run into a situation where I identify a node by its node pointer, instead by its identifier.
And the requirement by the old graph to always use the node pointer was a huge annoyance.

Same logic applies to the `has_node` and `del_node`, `del_edge` etc.

I think this should also ease the refactoring in all the other code.

cc @notxvilka Because it is the Graph API topic.

Edit:

To be clear though, I think we should keep the `_by_nptr` variants in the API. It maybe is helpful for some use cases.

2026-03-04 05:49 UTC, notxvilka commented
> I would rename `rz_graph_has_edge()` to something like `rz_graph_has_edge_by_nptr` or similar. And change `rz_graph_has_edge(RzGraph *g, RzGraphNode *from, RzGraphNode *to)` to `rz_graph_has_edge(RzGraph *g, void *id_node_a, void *id_node_b)`.
> 
> This makes it way more intuitive to use IMO. Because tbh, I have yet to run into a situation where I identify a node by its node pointer, instead by its identifier. And the requirement by the old graph to always use the node pointer was a huge annoyance.
> 
> Same logic applies to the `has_node` and `del_node`, `del_edge` etc.

Good call, yes, I agree it's a good suggestion.

2026-03-08 16:36 UTC, Heersin commented
> There is a use case I still miss in the tests and API. It is also very very common, so I think it should be implemented and be an example in the README or similar.
> 
> The case is: How to I check for nodes and edges in a graph, if I don't know the `RzGraphNode` pointers? I think this is the default scenario for Graph APIs. Because the internal node pointers shouldn't be managed by the API users. Hence, we cannot expect users to know them.
> 
> I would rename `rz_graph_has_edge()` to something like `rz_graph_has_edge_by_nptr` or similar. And change `rz_graph_has_edge(RzGraph *g, RzGraphNode *from, RzGraphNode *to)` to `rz_graph_has_edge(RzGraph *g, void *id_node_a, void *id_node_b)`.
> 
> This makes it way more intuitive to use IMO. Because tbh, I have yet to run into a situation where I identify a node by its node pointer, instead by its identifier. And the requirement by the old graph to always use the node pointer was a huge annoyance.
> 
> Same logic applies to the `has_node` and `del_node`, `del_edge` etc.
> 
> I think this should also ease the refactoring in all the other code.
> 
> cc @notxvilka Because it is the Graph API topic.
> 
> Edit:
> 
> To be clear though, I think we should keep the `_by_nptr` variants in the API. It maybe is helpful for some use cases.

OK, would check them this week. Yes, node pointer is expected to be fetched by calculating hash(identifier), I would add wrapper for this in this phase. @Rot127 is it work in your case ?

2026-03-08 16:38 UTC, Heersin commented
> Many compilation errors

Yep, found it's a huge change to replace those graph API (many old graph API relying on accessing inside data). haven't replace them in rz_test/* yet 😭 it keeps reporting error @notxvilka

2026-03-10 12:47 UTC, Rot127 commented
> add wrapper for this in this phase.

Yes, this would be totally fine. Keep it simple. We optimize later. It is a convenience thing.

> Yep, found it's a huge change to replace those graph API (many old graph API relying on accessing inside data). haven't replace them in rz_test/* yet 😭 it keeps reporting error

I feel you :)
It shows how much needed this refactor was, and how much it will make everything better.

2026-03-10 13:59 UTC, notxvilka commented
I also sent a few recommendations on some easy optimizations that can be done in the Mattermost private message. Take a look when you have time.

2026-03-20 17:08 UTC, Heersin commented
Still Some DB fixing WIP

2026-03-20 19:04 UTC, notxvilka requested changes
A few small nitpicks

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_algorithm.c
> +enum {
Add a note/doxygen about meaning of these colors, otherwise it might mislead people who read it.

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_algorithm.c
> +	// assert g, from, to, edge_color, visitor NON NULL
You could just use `rz_return_if_fail()`

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_algorithm.c
> +	// assert g, node, stack NON NULL
Same, `return_if_fail()`

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_algorithm.c
> +		// CORLOR changes
A typo in COLOR

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_algorithm.c
> + * @param g graph
Please use `\param` syntax

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_algorithm.c
> + * @param g graph
Same

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_algorithm.c
> + * @param g graph
Same

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_impl.c
> +	if (!e) {
It could be actually omitted and free() called directly since `free()` handles NULL well. Mark it also as inline then, or as a macro

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_impl.c
> +static RZ_OWN RzPVector *edge_vec_new(RzGraphEdgeDataFree edge_data_free) {
Add `inline` here

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_impl.c
> +static RZ_OWN bool rz_graph_list_impl_add_node(RzGraph *g, RzGraphNode *node) {
Add `inline`

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_impl.c
> +	if (vec) {
You can omit the check, `rz_pvector_free()` handles the NULL check well

2026-03-20 19:04 UTC, notxvilka commented on librz/util/graph_impl.c
> +	if (state) {
You could flip this condition and return early instead

2026-04-03 16:39 UTC, notxvilka requested changes
```
Missing type comment at <rizin/librz/util/graph_impl.c:1547:59> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1564:46> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1573:46> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1583:46> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1593:46> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1603:77> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1613:61> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1622:60> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1631:65> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1640:64> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1649:54> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1658:53> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_impl.c:1667:87> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:54:38> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:89:42> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:120:37> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:184:31> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:239:35> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:254:43> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:270:45> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:286:53> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:296:43> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:348:77> (token is not a comment)
Missing type comment at <rizin/librz/util/graph_algorithm.c:462:87> (token is not a comment)
...
```

2026-04-03 16:39 UTC, notxvilka commented on librz/util/graph_algorithm.c
> +		// CORLOR changes
@Heersin you forgot also this one

2026-04-03 19:02 UTC, notxvilka commented
Also compilation on Windows should be fixed:
```
aph_new.c.obj "/c" ../test/unit/test_graph_new.c
../test/unit/test_graph_new.c(40): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(45): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(49): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(53): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(56): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(59): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(70): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(71): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(72): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(105): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(106): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(107): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(133): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(134): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(135): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(136): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(181): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(182): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(183): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(227): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(228): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(229): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(261): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(262): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(263): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(281): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(282): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(283): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(284): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(312): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(313): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(314): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(315): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(316): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(349): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(350): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(351): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(373): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(374): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(375): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(448): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(453): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(457): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(461): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(464): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(467): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(478): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(479): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(480): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(513): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(514): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(515): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(541): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(542): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(543): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(544): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(589): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(590): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(591): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(632): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(633): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(634): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(666): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(667): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(668): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(686): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(687): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(688): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(689): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(716): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(717): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(718): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(719): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(720): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(753): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(754): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(755): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(777): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(778): error C2036: 'void *': unknown size
../test/unit/test_graph_new.c(779): error C2036: 'void *': unknown size
```

2026-04-04 12:47 UTC, Rot127 commented
@Heersin I continue working on it here: https://github.com/rizinorg/rizin/pull/6152
Can you push to the repo branches as well? Otherwise I can cherry-pick your changes you do here into the `dist-` branch

2026-04-06 12:40 UTC, Heersin commented
> @Heersin I continue working on it here: #6152 Can you push to the repo branches as well? Otherwise I can cherry-pick your changes you do here into the `dist-` branch

ok

2026-04-08 19:35 UTC, closed without merging

2026-04-08 19:35 UTC, notxvilka commented
Superseded by https://github.com/rizinorg/rizin/pull/6152