Add text descriptions for asm.cpu values in ARM architecture plugin
rizinorg/rizin pull request #4809
Opened 2024-12-31 07:01 UTC by kavin-t28

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

2024-12-31 09:42 UTC, XVilka requested changes
What is this? Have you even tried? It will not work.

2025-01-01 04:45 UTC, kavin-t28 commented
I tried to do it from my understanding , please guide me if i have done something wrong

2025-01-01 08:21 UTC, wargio requested changes
I'm sorry, but explain us how this should work (by your logic)? it's like you thrown random text in a file

2025-01-10 13:26 UTC, Rot127 commented
I close this for now. Because you ticked all the boxes in the PR description, but didn't added test cases nor added a PR in the book. Suggesting you didn't read the requirements. Also your PR description of the changes doesn't match the actual code changes.

Of course, you are welcome to open a new PR fixing the issue more thoroughly.

2025-01-10 13:26 UTC, closed without merging