Rewrite some documentation
rizinorg/rizin pull request #49
Opened 2020-10-23 08:00 UTC by ret2libc

2020-10-23 09:05 UTC, wargio approved these changes

2020-10-23 09:40 UTC, XVilka requested changes

2020-10-23 19:28 UTC, xarkes approved these changes

2020-10-26 09:23 UTC, XVilka requested changes

2020-10-26 09:41 UTC, XVilka approved these changes

2020-10-26 10:13 UTC, ITAYC0HEN requested changes
As discussed, use "Rizin" and not "rizin" when referring to the name of the project (and not to the program which is `rizin`)

2020-10-26 12:10 UTC, wargio approved these changes

2020-10-26 15:29 UTC, thestr4ng3r approved these changes

2020-10-26 16:12 UTC, merged