Refactor some parts of vmenus to use more API ##refactor
rizinorg/rizin pull request #503
Opened 2021-02-01 02:22 UTC by officialcjunior

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This commit replaces all instances where `ecn` and `ecp`
were called using `rz_core_cmd0 `, with their corresponding APIs.

Also created a new API `rz_core_eval_variables_print` to handle
the command `?$`

**Test plan**

- [ ]  Make sure that `rz_core_eval_variables_print()` works and is put in the right place.

**Closing issues**

Related to #491

2021-02-01 04:59 UTC, XVilka requested changes
I wonder if it makes sense to rename the `rz_core_get_help_vars()` too. Into something like `rz_core_eval_vars_get()` or similar to be more consistent. @ret2libc what do you think?

2021-02-01 10:02 UTC, ret2libc commented
> I wonder if it makes sense to rename the `rz_core_get_help_vars()` too. Into something like `rz_core_eval_vars_get()` or similar to be more consistent. @ret2libc what do you think?

Actually I'm not sure `eval` is the right name, because I think `eval` usually refers to `e` config variables. These are different... Not sure what should be their names though :( Right now they are called "help_variables" so maybe `rz_core_eval_variables_print` should be called `rz_core_help_vars_print` and `rz_core_get_help_vars` should be `rz_core_help_vars_get`...WDYT?

2021-02-03 08:42 UTC, ret2libc commented
@officialcjunior please see https://github.com/rizinorg/rizin/pull/503#issuecomment-770734100 for the names. Otherwise, the PR is ok!

2021-02-03 10:35 UTC, officialcjunior commented
> @officialcjunior please see [#503 (comment)](https://github.com/rizinorg/rizin/pull/503#issuecomment-770734100) for the names. Otherwise, the PR is ok!

Oh, I thought you had asked @XVilka about his opinion and I was waiting for that 😄

So, I can go with renaming `rz_core_eval_variables_print` to `rz_core_help_vars_print`?

2021-02-03 11:31 UTC, XVilka approved these changes
Ok, lets rename the function, apart from that LGTM.

2021-02-03 12:58 UTC, ret2libc commented
Alslo r`z_core_get_help_vars -> rz_core_help_vars_get`

2021-02-03 15:15 UTC, ret2libc approved these changes

2021-02-03 15:20 UTC, merged