core/cmd_analysis: use API instead of calling rz_core_cmd
rizinorg/rizin pull request #603
Opened 2021-02-12 13:29 UTC by ret2libc

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Use API instead of calling rz_core_cmd0

**Test plan**

...

**Closing issues**

...

2021-02-12 15:58 UTC, XVilka requested changes

2021-02-12 15:58 UTC, XVilka commented on librz/core/cmd_analysis.c
> +RZ_IPI void rz_core_agraph_print_custom(RzCore *core) {
I suggest putting those into the separate file, e.g. `librz/core/cagraph.c` or something like that.

2021-02-12 17:42 UTC, XVilka commented
Uh, currently `librz/core/agraph.c` is the visual ASCII graph interface. So the IPI is a bit out of the place here. What about this:
- Rename current `librz/core/agraph.c` into `librz/core/vgraph.c`
- Move these IPI `rz_core_agraph_*` functions into the newly created `librz/core/agraph.c`?

2021-02-12 17:56 UTC, wargio approved these changes

2021-02-12 18:43 UTC, ret2libc commented
> Uh, currently `librz/core/agraph.c` is the visual ASCII graph interface. So the IPI is a bit out of the place here. What about this:
> 
> * Rename current `librz/core/agraph.c` into `librz/core/vgraph.c`
> * Move these IPI `rz_core_agraph_*` functions into the newly created `librz/core/agraph.c`?
> 
> P.S. Please also fix the build.

I can create `cagraph.c` actually. I  think renaming agraph to vgraph might be confusing, because agraph.c contains all the agraph functions AFAIR.

2021-02-13 03:21 UTC, XVilka commented
Clang complains with:
```
Check failure on line 19 in librz/core/cagraph.c

Code scanning

Potential leak of memory pointed to by 'b'
```

2021-02-13 12:10 UTC, XVilka approved these changes

2021-02-15 03:26 UTC, XVilka approved these changes

2021-02-15 03:27 UTC, merged