Extract common API to generate different types of graphs/outputs ##breaking
rizinorg/rizin pull request #637
Opened 2021-02-16 15:37 UTC by ret2libc

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Extract a common API to print graphs (`ag` commands) as needed. Few things to consider about this:
- unfortunately existing code did slightly different things for different types of graph/output so when possible i tried to refactor these differences and just use one single code to output a graph in different modes. What this means is that some commands now might output slightly different output. For example, `agc`/`agC` in json mode printed:
```
[
  {
    "name": "entry0",
    "size": 46,
    "imports": [
      "reloc.__libc_start_main"
    ]
  }
]
```
while now it prints:
```
{
  "nodes": [
    {
      "id": 0,
      "title": "entry0",
      "body": "",
      "out_nodes": [
        1
      ]
    },
    {
      "id": 1,
      "title": "reloc.__libc_start_main",
      "body": "",
      "out_nodes": [
        
      ]
    }
  ]
}
```
which is the common format.
- Only `agf` commands/subcommands was not refactored for now, because it involves a lot of changes, so right now `agf` is kinda of a special case, because it uses completely different code to print a graph and to write it in different formats.

Probably Cutter needs to be fixed for the `agc`/`agC` (and maybe other) cases, while `agf` would still work.

**Test plan**

...

**Closing issues**

...

2021-02-16 16:05 UTC, ret2libc commented
The refactoring is not perfect IMO, but probably a better one would require a much bigger investment in time which I do not think would pay off right now. I believe the `rz_core_agraph_print_type` API is more or less what we want and we can probably improve the inner details within it.

2021-02-16 16:21 UTC, XVilka requested changes

2021-02-16 16:21 UTC, XVilka commented on librz/core/cagraph.c
> +	bool refgraph = rz_config_get_i(core->config, "graph.refs");
`rz_config_get_b()`

2021-02-16 16:21 UTC, XVilka commented on librz/core/cagraph.c
> +		if (fcnr->type == 'C' && rz_list_find(calls, fcnr, (RzListComparator)funccall_analysis_ref_cmp) == NULL) {
We should convert `fcnr->type` to enums as well.

2021-02-16 16:21 UTC, XVilka commented on librz/core/cagraph.c
> +	rz_config_set_i(core->config, "scr.utf8", 0);
Some of those are boolean, please use `rz_config_set_b()` where appropriate.

2021-02-16 16:22 UTC, ret2libc commented on librz/core/cagraph.c
> +	rz_config_set_i(core->config, "scr.utf8", 0);
Yep, I actually didn't touch that code but mostly copied-pasted from other locations and forgot about the new set_b ;)

2021-02-16 16:59 UTC, karliss commented
As someone who started refactoring this in different direction  (so take my opinion with grain of salt) with `rz_graph_drawable` i think this PR are making some things worse. Things I don't like in this PR:
* functions converting graph from each respective rizin representation shouldn't be storing the result in single global(core->graph) variable, it makes the API worse and introduces problems with it getting overwritten
* converting from the common graph to selected output format should be separate function from getting the graph
* in some cases information about addresses is lost

2021-02-16 18:39 UTC, ret2libc commented
> As someone who started refactoring this in different direction (so take my opinion with grain of salt) with `rz_graph_drawable` i think this PR are making some things worse. Things I don't like in this PR:
> 
> * functions converting graph from each respective rizin representation shouldn't be storing the result in single global(core->graph) variable, it makes the API worse and introduces problems with it getting overwritten

I absolutely agree about this point, but  most of the existing codes related to graph was already using the global graph and I didn't mean to change too many "concepts" in one shot. In particular, most code was doing things like `rz_core_cmd(".agi*;agg")`. That's the main thing I intended to "fix".

> * converting from the common graph to selected output format should be separate function from getting the graph

That's why you have all the `rz_core_agraph_data_create`, `rz_core_agraph_imports_create`, etc. and then you have the `rz_core_agraph_print_json`, `rz_core_agraph_print_ascii`, etc. The `rz_core_agraph_print_type` API puts those things together as many times you want to create the graph and print it immediately. Does it make sense?

> * in some cases information about addresses is lost

This is probably true... I do wonder, however, if having those info in a "drawable graph" is really what you want, instead of having those info available somewhere else.

2021-02-17 09:02 UTC, closed without merging

2021-02-17 09:02 UTC, ret2libc commented
Let's close this for now. I'm going to do smaller refactorings for the commands part and then we can think to something better for the graph mess.