Fix Ctrl-J issue (#612)
rizinorg/rizin pull request #826
Opened 2021-03-15 17:07 UTC by valdaarhun

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`Ctrl-J` now performs the same function as `Ctrl-M` and `enter`. It adds a new line after the command.

**Test plan**

...

**Closing issues**

Closes #612

2021-03-15 18:01 UTC, ret2libc requested changes
If the code is exactly the same as the `enter` case, why not just adding `case 10` on top of `case 13` in the switch?

2021-03-15 18:38 UTC, valdaarhun commented
@ret2libc Gosh, why didn't I think of that. That will make the code less redundant as well. I'll do it right away.

2021-03-15 19:32 UTC, ret2libc approved these changes

2021-03-15 21:20 UTC, Maijin approved these changes

2021-03-16 01:30 UTC, XVilka approved these changes

2021-03-16 01:30 UTC, merged