Fix a bug that causes normal function recognized as constructor
rizinorg/rizin pull request #898
Opened 2021-03-24 09:31 UTC by Basstorm

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
before
```
[Polygon]
  (vtable at 0x3d20)
nth name          addr vt_offset type
-------------------------------------
1   Polygon     0x11ea -1        CONSTRUCTOR
2   Polygon1    0x121e -1        CONSTRUCTOR
3   ~Polygon    0x122e -1        DESTRUCTOR
4   set_values  0x14a6 -1        DEFAULT
5   area        0x14d0 0x0       VIRTUAL
6   sides       0x14e4 0x8       VIRTUAL
```
after
```
[Polygon]
  (vtable at 0x3d20)
nth name          addr vt_offset type
-------------------------------------
1   Polygon     0x11ea -1        CONSTRUCTOR
2   Polygon1    0x121e -1        DEFAULT
3   Poly        0x122e -1        DEFAULT
4   ~Polygon    0x123e -1        DESTRUCTOR
5   set_values  0x14b6 -1        DEFAULT
6   area        0x14e0 0x0       VIRTUAL
7   sides       0x14f4 0x8       VIRTUAL
```

...

**Test plan**

...

**Closing issues**

...

2021-03-24 11:29 UTC, XVilka commented
Do you have a test for this? Or maybe do the change or extend the existing one?

2021-03-24 11:41 UTC, Basstorm commented
> Do you have a test for this? Or maybe do the change or extend the existing one?

This bug is due to the fact that during the constructor detection process, when the function name is longer than the class name, only the length of the class name is detected, and the part after that is ignored. So, to add tests, I need to add a testbin like `Polygon`, `Polygonxxxx`. I will add one later.

2021-03-24 18:23 UTC, wargio requested changes
Add a test, please.

2021-03-25 04:42 UTC, XVilka approved these changes

2021-03-25 07:34 UTC, wargio approved these changes

2021-03-25 07:34 UTC, merged